Section "Device"
    Identifier "dummy"
    Driver "dummy"
    VideoRam 256000
EndSection
Section "Monitor"
    Identifier "mon"
    HorizSync 5.0-200.0
    VertRefresh 10.0-250.0
    Modeline "1280x720_60" 74.25 1280 1390 1430 1650 720 725 730 750 +hsync +vsync
EndSection
Section "Screen"
    Identifier "scr"
    Device "dummy"
    Monitor "mon"
    DefaultDepth 24
    SubSection "Display"
        Depth 24
        Modes "1280x720_60"
        Virtual 4096 2160
    EndSubSection
EndSection
Section "ServerFlags"
    Option "AutoAddDevices" "false"
EndSection
