"project_identifier": "retroarch"
"api_key": "_secret_"
"preserve_hierarchy": true

"files":
  [
    {
      "source": "/msg_hash_us.json",
      "translation": "/msg_hash_%two_letters_code%.json",
    },
    {
      "source": "/steam_us.json",
      "translation": "/steam_%two_letters_code%.json",
    },
    {
      "source": "/googleplay_us.json",
      "translation": "/googleplay_%two_letters_code%.json",
    },
  ]
