#if defined(_MSC_VER) && !defined(_XBOX) && (_MSC_VER >= 1500 && _MSC_VER < 1900)
#if (_MSC_VER >= 1700)
/* https://support.microsoft.com/en-us/kb/980263 */
#pragma execution_character_set("utf-8")
#endif
#pragma warning(disable:4566)
#endif

MSG_HASH(
      MSG_COMPILER,
      "編譯器"
      )
MSG_HASH(
      MSG_UNKNOWN_COMPILER,
      "未知的編譯器"
      )
MSG_HASH(
      MSG_DEVICE_DISCONNECTED_FROM_PORT,
      "設備已從連接口上移開"
      )
MSG_HASH(
      MSG_UNKNOWN_NETPLAY_COMMAND_RECEIVED,
      "接收到未知的連線遊戲指令"
      )
MSG_HASH(
      MSG_FILE_ALREADY_EXISTS_SAVING_TO_BACKUP_BUFFER,
      "文件已存在。儲存到備份至緩衝區"
      )
MSG_HASH(
      MSG_GOT_CONNECTION_FROM,
      "連接來自： \"%s\""
      )
MSG_HASH(
      MSG_GOT_CONNECTION_FROM_NAME,
      "連接來自： \"%s (%s)\""
      )
MSG_HASH(
      MSG_PUBLIC_ADDRESS,
      "公開地址"
      )
MSG_HASH(
      MSG_NO_ARGUMENTS_SUPPLIED_AND_NO_MENU_BUILTIN,
      "未提供參數也沒有內建選單，顯示幫助..."
      )
MSG_HASH(
      MSG_SETTING_DISK_IN_TRAY,
      "設定光碟機裡光碟"
      )
MSG_HASH(
      MSG_WAITING_FOR_CLIENT,
      "等待客戶端 ..."
      )
MSG_HASH(
      MSG_NETPLAY_YOU_HAVE_LEFT_THE_GAME,
      "你已離開遊戲"
      )
MSG_HASH(
      MSG_NETPLAY_YOU_HAVE_JOINED_AS_PLAYER_N,
      "你已作為玩家 %d 加入"
      )
MSG_HASH(
      MSG_NETPLAY_ENDIAN_DEPENDENT,
      "這個核心模擬器不支援不同系統的網路連線對打"
      )
MSG_HASH(
      MSG_NETPLAY_PLATFORM_DEPENDENT,
      "此模擬器且不支援此兩種架構下的連線遊戲模式"
      )
MSG_HASH(
      MSG_NETPLAY_ENTER_PASSWORD,
      "輸入連線遊戲服務器的密碼："
      )
MSG_HASH(
      MSG_NETPLAY_INCORRECT_PASSWORD,
      "密碼錯誤"
      )
MSG_HASH(
      MSG_NETPLAY_SERVER_NAMED_HANGUP,
      "\"%s\" 已斷開連線"
      )
MSG_HASH(
      MSG_NETPLAY_SERVER_HANGUP,
      "連線遊戲客戶端已離開"
      )
MSG_HASH(
      MSG_NETPLAY_CLIENT_HANGUP,
      "已離開連線遊戲模式"
      )
MSG_HASH(
      MSG_NETPLAY_CANNOT_PLAY_UNPRIVILEGED,
      "你沒有遊戲權限"
      )
MSG_HASH(
      MSG_NETPLAY_CANNOT_PLAY_NO_SLOTS,
      "連線遊戲人數已滿" /*FIXME:"There are no free player slots"*/
      )
MSG_HASH(
      MSG_NETPLAY_CANNOT_PLAY,
      "無法切換到遊戲模式"
      )
MSG_HASH(
      MSG_NETPLAY_PEER_PAUSED,
      "連線遊戲對方 \"%s\" 已暫停"
      )
MSG_HASH(
      MSG_NETPLAY_CHANGED_NICK,
      "你的暱稱已修改為 \"%s\""
      )
MSG_HASH(
      MENU_ENUM_SUBLABEL_VIDEO_SHARED_CONTEXT,
      "使用模擬器硬體渲染私人內容時可避免硬體在各frames時的狀態改變."
      )
MSG_HASH(
      MENU_ENUM_SUBLABEL_MENU_HORIZONTAL_ANIMATION,
      "Enable horizontal animation for the menu. This will have a performance hit."
      )
MSG_HASH(
      MENU_ENUM_SUBLABEL_MENU_SETTINGS,
      "調整選單顯示的相關設定。"
      )
MSG_HASH(
      MENU_ENUM_SUBLABEL_VIDEO_HARD_SYNC,
      "強制同步CPU和GPU，以性能為代價換取低延遲。"
      )
MSG_HASH(
      MENU_ENUM_SUBLABEL_VIDEO_THREADED,
      "以延遲和視訊撕裂為代價換取高性能，當且僅當能\n"
      "達到全速模擬時使用。"
      )
MSG_HASH(
      MSG_AUDIO_VOLUME,
      "聲音音量"
      )
MSG_HASH(
      MSG_AUTODETECT,
      "自動偵測"
      )
MSG_HASH(
      MSG_AUTOLOADING_SAVESTATE_FROM,
      "自動載入存檔從"
      )
MSG_HASH(
      MSG_CAPABILITIES,
      "容量"
      )
MSG_HASH(
      MSG_CONNECTING_TO_NETPLAY_HOST,
      "連線到連線遊戲主機"
      )
MSG_HASH(
      MSG_CONNECTING_TO_PORT,
      "連接到連接口"
      )
MSG_HASH(
      MSG_CONNECTION_SLOT,
      "連接到插槽"
      )
MSG_HASH(
      MSG_SORRY_UNIMPLEMENTED_CORES_DONT_DEMAND_CONTENT_NETPLAY,
      "對不起，錯誤發生：模擬器核心未請求內容，無法加入連線遊戲。"
      )
MSG_HASH(
MSG_FAILED_TO_SET_DISK,
      "設定磁盤失敗")
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_ACCOUNTS_CHEEVOS_PASSWORD,
     "密碼"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_ACCOUNTS_CHEEVOS_SETTINGS,
      "Cheevos帳戶" /*FIXME:"Accounts Cheevos"*/
      )
MSG_HASH(
       MENU_ENUM_LABEL_VALUE_ACCOUNTS_CHEEVOS_USERNAME,
       "用戶名"
       )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_ACCOUNTS_LIST,
      "帳戶"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_ACCOUNTS_LIST_END,
      "帳戶列表終端"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_ACCOUNTS_RETRO_ACHIEVEMENTS,
      "Retro 成就"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_ACHIEVEMENT_LIST,
      "成就列表"
      )

MSG_HASH(
      MENU_ENUM_LABEL_VALUE_ACHIEVEMENT_LIST_HARDCORE,
      "成就列表（專家模式）" /*FIXME:"Achievement List (Hardcore)"*/
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_ADD_CONTENT_LIST,
      "添加遊戲內容"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CONFIGURATIONS_LIST,
      "設定"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_ADD_TAB,
      "導入遊戲內容"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_NETPLAY_TAB,
      "連線遊戲房間"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_ASK_ARCHIVE,
      "詢問"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_ASSETS_DIRECTORY,
       "資源目錄"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUDIO_BLOCK_FRAMES,
      "塊幀" /*FIXME:"Block Frames"*/
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUDIO_DEVICE,
       "聲音設備"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUDIO_DRIVER,
       "聲音驅動程式"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUDIO_DSP_PLUGIN,
       "聲音DSP插件"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUDIO_ENABLE,
      "啟用聲音"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUDIO_FILTER_DIR,
      "聲音過濾器目錄"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_TURBO_DEADZONE_LIST,
      "渦輪/盲區"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUDIO_LATENCY,
      "聲音時延(ms)"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUDIO_MAX_TIMING_SKEW,
      "聲音最大採樣間隔"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUDIO_MUTE,
      "聲音靜音"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUDIO_OUTPUT_RATE,
      "聲音輸出碼率(Hz)"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUDIO_RATE_CONTROL_DELTA,
      "動態聲音碼率控制間隔"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUDIO_RESAMPLER_DRIVER,
      "聲音重採樣驅動程式"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUDIO_SETTINGS,
      "聲音"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUDIO_SYNC,
      "啟用聲音同步"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUDIO_VOLUME,
      "聲音音量級別(dB)"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUTOSAVE_INTERVAL,
      "SaveRAM自動儲存間隔"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUTO_OVERRIDES_ENABLE,
      "自動載入覆寫文件"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUTO_REMAPS_ENABLE,
      "自動戴入重映射文件"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUTO_SHADERS_ENABLE,
      "自動戴入Shader預設"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BASIC_MENU_CONTROLS_BACK,
      "返回"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BASIC_MENU_CONTROLS_CONFIRM,
      "確認"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BASIC_MENU_CONTROLS_INFO,
      "訊息"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BASIC_MENU_CONTROLS_QUIT,
      "退出"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BASIC_MENU_CONTROLS_SCROLL_DOWN,
      "向下滾動"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BASIC_MENU_CONTROLS_SCROLL_UP,
      "向上滾動"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BASIC_MENU_CONTROLS_START,
      "開始"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BASIC_MENU_CONTROLS_TOGGLE_KEYBOARD,
      "切換鍵盤"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BASIC_MENU_CONTROLS_TOGGLE_MENU,
      "切換選單"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BASIC_MENU_ENUM_CONTROLS,
      "基本選單控制"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BASIC_MENU_ENUM_CONTROLS_CONFIRM,
      "確認"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BASIC_MENU_ENUM_CONTROLS_INFO,
      "訊息"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BASIC_MENU_ENUM_CONTROLS_QUIT,
      "退出"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BASIC_MENU_ENUM_CONTROLS_SCROLL_UP,
      "向上滾動"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BASIC_MENU_ENUM_CONTROLS_START,
      "默認值"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BASIC_MENU_ENUM_CONTROLS_TOGGLE_KEYBOARD,
      "切換鍵盤"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BASIC_MENU_ENUM_CONTROLS_TOGGLE_MENU,
      "切換選單"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BLOCK_SRAM_OVERWRITE,
      "載入儲存狀態時不覆蓋SaveRAM"
      )
#ifdef HAVE_LAKKA
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BLUETOOTH_ENABLE,
      "啟用藍牙服務"
      )
#endif
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BUILDBOT_ASSETS_URL,
      "構建機器人資源URL"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CACHE_DIRECTORY,
      "緩沖目錄"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CAMERA_ALLOW,
      "允許使用相機"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CAMERA_DRIVER,
      "相機驅動程式"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CHEAT,
      "金手指"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CHEAT_APPLY_CHANGES,
      "執行金手指修改"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CHEAT_DATABASE_PATH,
      "金手指文件目錄"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CHEAT_FILE,
      "金手指文件"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CHEAT_FILE_LOAD,
      "載入金手指文件"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CHEAT_FILE_SAVE_AS,
      "另存金手指文件"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CHEAT_NUM_PASSES,
      "金手指通過" /*FIXME: "Cheat Passes"*/
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CHEEVOS_DESCRIPTION,
      "描述"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CHEEVOS_HARDCORE_MODE_ENABLE,
/* FIXME? Translate 'Hardcore Mode' */
      "成就-專家模式"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CHEEVOS_LOCKED_ENTRY,
      "鎖定"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CHEEVOS_SETTINGS,
      "Retro 成就"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CHEEVOS_TEST_UNOFFICIAL,
/* FIXME? Translate 'Test Unofficial Achievements' */
      "非官方測試成就"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CHEEVOS_UNLOCKED_ENTRY,
      "未鎖定"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CLOSE_CONTENT,
      "關閉"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CONFIG,
      "設定"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CONFIGURATIONS,
      "載入設定"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CONFIGURATION_SETTINGS,
      "設定"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CONFIG_SAVE_ON_EXIT,
      "退出時儲存設定"
      )
MSG_HASH(
MENU_ENUM_LABEL_VALUE_CONFIRM_ON_EXIT,
      "退出時進行詢問"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CONTENT_DATABASE_DIRECTORY,
      "遊戲內容數據庫目錄"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CONTENT_DIR,
      "遊戲內容目錄"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CONTENT_HISTORY_SIZE,
      "歷史記錄數量")
MSG_HASH(MENU_ENUM_LABEL_VALUE_PLAYLIST_ENTRY_REMOVE,
      "允許移除記錄")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CONTENT_SETTINGS,
      "快捷選單")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_ASSETS_DIR,
      "下載目錄")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_ASSETS_DIRECTORY,
      "下載目錄")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_CHEAT_OPTIONS,
      "金手指")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_COUNTERS,
      "核心計數器")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_ENABLE,
      "顯示核心名稱")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_INFORMATION,
      "核心訊息")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_INFO_AUTHORS,
      "作者")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_INFO_CATEGORIES,
      "分類")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_INFO_CORE_LABEL,
      "核心標籤")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_INFO_CORE_NAME,
      "核心名稱")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_INFO_FIRMWARE,
      "韌體")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_INFO_LICENSES,
      "許可證")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_INFO_PERMISSIONS,
      "許可")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_INFO_SUPPORTED_EXTENSIONS,
      "支持的擴展")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_INFO_SYSTEM_MANUFACTURER,
      "系統製造商")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_INFO_SYSTEM_NAME,
      "系統名稱")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_INPUT_REMAPPING_OPTIONS,
      "控制")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_LIST,
      "戴入核心")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_OPTIONS,
      "選項")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_SETTINGS,
      "核心")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_SET_SUPPORTS_NO_CONTENT_ENABLE,
      "自動啟動一個核心")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_UPDATER_AUTO_EXTRACT_ARCHIVE,
      "自動解壓下載的檔案")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_UPDATER_BUILDBOT_URL,
      "構建機器人核心URL")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_UPDATER_LIST,
      "核心更新程序")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_UPDATER_SETTINGS,
      "更新程序")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CPU_ARCHITECTURE,
      "CPU架構:")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CPU_CORES,
      "CPU核心:")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CURSOR_DIRECTORY,
      "指針目錄")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CURSOR_MANAGER,
      "光標管理器")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CUSTOM_RATIO,
      "自定義比率")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DATABASE_MANAGER,
      "數據庫管理器")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DATABASE_SELECTION,
      "選擇數據庫")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DELETE_ENTRY,
      "移除")
MSG_HASH(MENU_ENUM_LABEL_VALUE_FAVORITES,
      "選擇文件並探測核心") /* TODO/FIXME - update */
MSG_HASH(MENU_ENUM_LABEL_VALUE_DIRECTORY_CONTENT,
      "<遊戲內容目錄>")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DIRECTORY_DEFAULT,
      "<默認>")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DIRECTORY_NONE,
      "<無>")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DIRECTORY_NOT_FOUND,
      "沒有找到文件夾。")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DIRECTORY_SETTINGS,
      "目錄")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DISK_INDEX,
      "光碟索引")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DISK_OPTIONS,
      "光碟控制")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DONT_CARE,
      "不關心")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DOWNLOADED_FILE_DETECT_CORE_LIST,
      "下載目錄")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DOWNLOAD_CORE,
      "下載核心……")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DOWNLOAD_CORE_CONTENT,
      "下載遊戲內容")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DRIVER_SETTINGS,
      "驅動")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DUMMY_ON_CORE_SHUTDOWN,
/* FIXME? Translate 'Load Dummy on Core Shutdown' */
      "核心關閉時戴入虛擬程序")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CHECK_FOR_MISSING_FIRMWARE,
      "載入前檢查韌體/BIOS是否存在") /*FIXME: "Check for Missing Firmware Before Loading"*/
MSG_HASH(MENU_ENUM_LABEL_VALUE_DYNAMIC_WALLPAPER,
      "動態壁紙")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DYNAMIC_WALLPAPERS_DIRECTORY,
      "動態壁紙目錄")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CHEEVOS_ENABLE,
/* FIXME? Translate 'Enable Achievements' */
      "啟用成就系統")
MSG_HASH(MENU_ENUM_LABEL_VALUE_FALSE,
      "取消")
MSG_HASH(MENU_ENUM_LABEL_VALUE_FASTFORWARD_RATIO,
      "最大運行速度")
MSG_HASH(MENU_ENUM_LABEL_VALUE_FPS_SHOW,
      "顯示幀率")
MSG_HASH(MENU_ENUM_LABEL_VALUE_FRAME_THROTTLE_ENABLE,
      "限制最大運行速度")
MSG_HASH(MENU_ENUM_LABEL_VALUE_FRAME_THROTTLE_SETTINGS,
      "幀率限制")
MSG_HASH(MENU_ENUM_LABEL_VALUE_FRONTEND_COUNTERS,
      "前端計數器")
MSG_HASH(MENU_ENUM_LABEL_VALUE_GAME_SPECIFIC_OPTIONS,
      "自動戴入遊戲內容特定的核心選項")
MSG_HASH(MENU_ENUM_LABEL_VALUE_GAME_SPECIFIC_OPTIONS_CREATE,
      "創建遊戲選項文件")
MSG_HASH(MENU_ENUM_LABEL_VALUE_GAME_SPECIFIC_OPTIONS_IN_USE,
      "遊戲選項文件")
MSG_HASH(MENU_ENUM_LABEL_VALUE_HELP,
      "幫助")
MSG_HASH(MENU_ENUM_LABEL_VALUE_HELP_AUDIO_VIDEO_TROUBLESHOOTING,
      "聲音/視訊故障排除")
MSG_HASH(MENU_ENUM_LABEL_VALUE_HELP_CHANGE_VIRTUAL_GAMEPAD,
      "變更虛擬遊戲控制器覆層")
MSG_HASH(MENU_ENUM_LABEL_VALUE_HELP_CONTROLS,
      "基本選單控制")
MSG_HASH(MENU_ENUM_LABEL_VALUE_HELP_LIST,
      "幫助")
MSG_HASH(MENU_ENUM_LABEL_VALUE_HELP_LOADING_CONTENT,
      "戴入遊戲內容")
MSG_HASH(MENU_ENUM_LABEL_VALUE_HELP_SCANNING_CONTENT,
      "掃瞄遊戲內容")
MSG_HASH(MENU_ENUM_LABEL_VALUE_HELP_WHAT_IS_A_CORE,
      "什麼是「核心」？")
MSG_HASH(MENU_ENUM_LABEL_VALUE_HISTORY_LIST_ENABLE,
      "啟用歷史記錄")
MSG_HASH(MENU_ENUM_LABEL_VALUE_HISTORY_TAB,
      "歷史")
MSG_HASH(MENU_ENUM_LABEL_VALUE_HORIZONTAL_MENU,
      "水平化選單")
MSG_HASH(MENU_ENUM_LABEL_VALUE_IMAGES_TAB,
      "圖像")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INFORMATION,
      "訊息")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INFORMATION_LIST,
      "訊息")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_ADC_TYPE,
      "手柄輸入轉數字選項")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_ALL_USERS_CONTROL_MENU,
      "所有用戶都能控制選單")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_LEFT_X,
      "左搖桿X")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_LEFT_X_MINUS,
      "左搖桿X- (左)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_LEFT_X_PLUS,
      "左搖桿X+ (右)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_LEFT_Y,
      "左搖桿Y")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_LEFT_Y_MINUS,
      "左搖桿Y- (上)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_LEFT_Y_PLUS,
      "左搖桿Y+ (下)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_RIGHT_X,
      "右搖桿X")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_RIGHT_X_MINUS,
      "右搖桿X- (左)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_RIGHT_X_PLUS,
      "右搖桿X+ (右)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_RIGHT_Y,
      "右搖桿Y")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_RIGHT_Y_MINUS,
      "右搖桿Y- (上)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_RIGHT_Y_PLUS,
      "右搖桿Y+ (下)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_AUTODETECT_ENABLE,
      "啟用自動設定")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MENU_INPUT_SWAP_OK_CANCEL,
      "選單切換 確定/取消 按鈕") /*FIXME:"Menu Swap OK & Cancel Buttons"*/
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_BIND_ALL,
      "綁定全部")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_BIND_DEFAULT_ALL,
      "綁定全部至默認值")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_BIND_TIMEOUT,
      "綁定超時時間")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_DESCRIPTOR_HIDE_UNBOUND,
      "隱藏未綁定的核心輸入描述")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_DESCRIPTOR_LABEL_SHOW,
      "顯示輸入描述標籤")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_DEVICE_INDEX,
      "設備索引")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_DEVICE_TYPE,
      "設備類型")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_DRIVER,
      "輸入驅動")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_DUTY_CYCLE,
      "Turbo占空比")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_HOTKEY_BINDS,
      "輸入熱鍵綁定")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_ICADE_ENABLE,
      "鍵盤控制器映射啟用")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_A,
      "A鍵(右側)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_B,
      "B鍵(下方)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_DOWN,
      "下十字鍵")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_L2,
      "L2鍵(觸發)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_L3,
      "L3鍵(拇指)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_L,
      "L鍵(手柄肩部)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_LEFT,
      "左十字鍵")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_R2,
      "R2鍵(觸發)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_R3,
      "R3鍵(拇指)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_R,
      "R鍵(手柄肩部)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_RIGHT,
      "右十字鍵")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_SELECT,
      "選擇鍵")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_START,
      "開始鍵")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_UP,
      "上十字鍵")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_X,
      "X鍵(上方)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_Y,
      "Y鍵(左側)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_KEY,
      "(鍵: %s)") /*FIXME:"(Key: %s)"*/
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_MOUSE_LEFT,
      "Mouse 1")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_MOUSE_RIGHT,
      "Mouse 2")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_MOUSE_MIDDLE,
      "Mouse 3")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_MOUSE_BUTTON4,
      "Mouse 4")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_MOUSE_BUTTON5,
      "Mouse 5")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_MOUSE_WHEEL_UP,
      "Wheel Up")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_MOUSE_WHEEL_DOWN,
      "Wheel Down")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_MOUSE_HORIZ_WHEEL_UP,
      "Wheel Left")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_MOUSE_HORIZ_WHEEL_DOWN,
      "Wheel Right")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_KEYBOARD_GAMEPAD_MAPPING_TYPE,
      "鍵盤控制器映射類型")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_MAX_USERS,
      "最大用戶數")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_MENU_ENUM_TOGGLE_GAMEPAD_COMBO,
      "遊戲控制器選單切出組合鍵")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_CHEAT_INDEX_MINUS,
      "金手指索引 -")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_CHEAT_INDEX_PLUS,
      "金手指索引 +")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_CHEAT_TOGGLE,
      "金手指開關")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_DISK_EJECT_TOGGLE,
      "光驅出倉切換")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_DISK_NEXT,
      "下一張光碟")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_DISK_PREV,
      "上一張光碟")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_ENABLE_HOTKEY,
      "啟用熱鍵")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_FAST_FORWARD_HOLD_KEY,
      "快進保持")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_FAST_FORWARD_KEY,
      "快進切換")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_FRAMEADVANCE,
      "幀提前量")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_FULLSCREEN_TOGGLE_KEY,
      "切換全營幕")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_GRAB_MOUSE_TOGGLE,
      "鼠標捕獲開關")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_GAME_FOCUS_TOGGLE,
      "切換遊戲焦距")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_LOAD_STATE_KEY,
      "戴入狀態")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_MENU_TOGGLE,
      "切換選單")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_BSV_RECORD_TOGGLE,
      "視訊錄製開關")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_MUTE,
      "靜音開關")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_NETPLAY_GAME_WATCH,
      "連線遊戲切換 遊戲/圍觀 模式")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_OSK,
      "切換營幕鍵盤")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_OVERLAY_NEXT,
      "下一個覆層")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_PAUSE_TOGGLE,
      "切換暫停")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_QUIT_KEY,
      "退出 RetroArch")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_RESET,
      "重置遊戲")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_REWIND,
      "回溯")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_SAVE_STATE_KEY,
      "儲存狀態")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_SCREENSHOT,
      "營幕截圖")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_SHADER_NEXT,
      "下一個Shader")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_SHADER_PREV,
      "上一個Shader")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_SLOWMOTION_HOLD_KEY,
      "慢動作")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_STATE_SLOT_MINUS,
      "存檔槽 -")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_STATE_SLOT_PLUS,
      "存檔槽 +")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_VOLUME_DOWN,
      "音量 -")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_VOLUME_UP,
      "音量 +")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_OSK_OVERLAY_ENABLE,
      "顯示鍵盤覆層")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_OVERLAY_ENABLE,
      "顯示覆層")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_OVERLAY_HIDE_IN_MENU,
      "在選單中隱藏覆層")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_POLL_TYPE_BEHAVIOR,
      "輪詢類型行為")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_POLL_TYPE_BEHAVIOR_EARLY,
      "較早")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_POLL_TYPE_BEHAVIOR_LATE,
      "稍晚")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_POLL_TYPE_BEHAVIOR_NORMAL,
      "正常")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_PREFER_FRONT_TOUCH,
      "優先前置觸摸")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_REMAPPING_DIRECTORY,
      "輸入重映射目錄")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_REMAP_BINDS_ENABLE,
      "啟用綁定重映射")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_SAVE_AUTOCONFIG,
      "儲存自動設定")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_SETTINGS,
      "輸入")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_SMALL_KEYBOARD_ENABLE,
      "啟用小鍵盤")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_TOUCH_ENABLE,
      "啟用觸摸")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_TURBO_ENABLE,
      "TURBO開關")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_TURBO_PERIOD,
      "Turbo區間")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_USER_BINDS, /* TODO/FIXME - change User to Port */
      "輸入用戶 %u 的綁定")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INTERNAL_STORAGE_STATUS,
      "內部存儲狀態")
MSG_HASH(MENU_ENUM_LABEL_VALUE_JOYPAD_AUTOCONFIG_DIR,
      "輸入設備自動設定目錄")
MSG_HASH(MENU_ENUM_LABEL_VALUE_JOYPAD_DRIVER,
      "手柄驅動")
#ifdef HAVE_LAKKA
MSG_HASH(MENU_ENUM_LABEL_VALUE_LAKKA_SERVICES,
      "Lakka 服務")
#endif
MSG_HASH(MENU_ENUM_LABEL_VALUE_LANG_CHINESE_SIMPLIFIED,
      "簡體中文")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LANG_CHINESE_TRADITIONAL,
      "繁體中文")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LANG_DUTCH,
      "荷蘭語")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LANG_ENGLISH,
      "英語")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LANG_ESPERANTO,
      "世界語")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LANG_FRENCH,
      "法語")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LANG_GERMAN,
      "德語")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LANG_ITALIAN,
      "意大利語")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LANG_JAPANESE,
      "日語")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LANG_KOREAN,
      "韓語")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LANG_POLISH,
      "波蘭語")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LANG_PORTUGUESE_BRAZIL,
      "葡萄牙語")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LANG_PORTUGUESE_PORTUGAL,
      "葡萄牙語")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LANG_RUSSIAN,
      "俄語")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LANG_SPANISH,
      "西班牙語")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LANG_VIETNAMESE,
      "越南語")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LANG_ARABIC,
      "阿拉伯")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LANG_GREEK,
      "希腊语")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LANG_TURKISH,
      "土耳其")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LEFT_ANALOG,
      "左側搖桿")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LIBRETRO_DIR_PATH,
      "核心目錄")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LIBRETRO_INFO_PATH,
      "核心訊息目錄")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LIBRETRO_LOG_LEVEL,
      "核心日誌級別")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LINEAR,
      "線性")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LOAD_ARCHIVE,
      "使用核心戴入壓縮包")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LOAD_CONTENT_HISTORY,
      "戴入最近的遊戲內容")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LOAD_CONTENT_LIST,
      "載入遊戲內容")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LOAD_DISC,
      "Load Disc")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DUMP_DISC,
      "Dump Disc")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LOAD_STATE,
      "戴入狀態")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LOCATION_ALLOW,
      "允許使用位置")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LOCATION_DRIVER,
      "定位驅動")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LOGGING_SETTINGS,
      "日誌")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LOG_VERBOSITY,
      "完整日誌記錄")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MAIN_MENU,
      "主選單")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MANAGEMENT,
      "數據庫設定")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MATERIALUI_MENU_COLOR_THEME,
      "選單顏色主題")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MATERIALUI_MENU_COLOR_THEME_BLUE,
      "藍色")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MATERIALUI_MENU_COLOR_THEME_BLUE_GREY,
      "藍灰色")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MATERIALUI_MENU_COLOR_THEME_DARK_BLUE,
      "深藍色")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MATERIALUI_MENU_COLOR_THEME_GREEN,
      "綠色")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MATERIALUI_MENU_COLOR_THEME_NVIDIA_SHIELD,
      "NV SHIELD")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MATERIALUI_MENU_COLOR_THEME_RED,
      "紅色")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MATERIALUI_MENU_COLOR_THEME_YELLOW,
      "黃色")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MATERIALUI_MENU_FOOTER_OPACITY,
      "底部不透明度")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MATERIALUI_MENU_HEADER_OPACITY,
      "頂部不透明度")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MENU_DRIVER,
      "選單驅動")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MENU_ENUM_THROTTLE_FRAMERATE,
      "限制選單幀率")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MENU_FILE_BROWSER_SETTINGS, /* TODO/FIXME - update */
      "File Browser")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MENU_LINEAR_FILTER,
      "選單線性過濾")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MENU_HORIZONTAL_ANIMATION,
      "Horizontal Animation")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MENU_SETTINGS,
      "選單")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MENU_WALLPAPER,
      "選單壁紙")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MENU_WALLPAPER_OPACITY,
      "壁紙不透明度")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MISSING,
      "丟失")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MORE,
      "...")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MOUSE_ENABLE,
      "鼠標支持")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MULTIMEDIA_SETTINGS,
      "多媒體")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MUSIC_TAB,
      "音樂")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NAVIGATION_BROWSER_FILTER_SUPPORTED_EXTENSIONS_ENABLE,
      "過濾未知擴展名")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NAVIGATION_WRAPAROUND,
      "環繞式導航")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NEAREST,
      "最近")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY,
      "連線遊戲")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY_CHECK_FRAMES,
      "連線遊戲檢查幀數")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY_DELAY_FRAMES,
      "連線遊戲延遲幀數")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY_DISCONNECT,
      "斷開連接")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY_ENABLE,
      "啟用連線遊戲")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY_ENABLE_CLIENT,
      "連接到遊戲主機")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY_ENABLE_HOST,
      "作為遊戲主機")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY_DISABLE_HOST,
      "停止連線主機")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY_IP_ADDRESS,
      "服務器地址")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY_LAN_SCAN_SETTINGS,
      "掃瞄本地網路")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY_MODE,
      "啟用連線遊戲客戶端")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY_NICKNAME,
      "用戶名")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY_PASSWORD,
      "服務器密碼")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY_SETTINGS,
      "連線遊戲設定")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY_STATELESS_MODE,
      "連線遊戲無狀態模式")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY_SPECTATE_PASSWORD,
      "服務器圍觀的密碼")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY_SPECTATOR_MODE_ENABLE,
      "啟用連線遊戲旁觀者")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY_TCP_UDP_PORT,
      "連線遊戲TCP/UDP端口")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY_NAT_TRAVERSAL,
      "連線遊戲使用NAT穿透技術")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETWORK_CMD_ENABLE,
      "網路命令")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETWORK_CMD_PORT,
      "網路命令端口")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETWORK_INFORMATION,
      "網路訊息")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETWORK_REMOTE_ENABLE,
      "網路遊戲控制器")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETWORK_REMOTE_PORT,
      "網路遠端基本端口")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETWORK_SETTINGS,
      "網路")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NO,
      "否")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NONE,
      "無")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NOT_AVAILABLE,
      "N/A")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NO_ACHIEVEMENTS_TO_DISPLAY,
      "沒有可顯示的成就。")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NO_CORE,
      "沒有核心")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NO_CORES_AVAILABLE,
      "沒有可用的核心。")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NO_CORE_INFORMATION_AVAILABLE,
      "沒有可用的核心訊息。")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NO_CORE_OPTIONS_AVAILABLE,
      "沒有可用的核心選項。")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NO_ENTRIES_TO_DISPLAY,
      "沒有可顯示的條目。")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NO_HISTORY_AVAILABLE,
      "沒有可用的歷史記錄。")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NO_INFORMATION_AVAILABLE,
      "沒有可用的訊息。")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NO_ITEMS,
      "沒有條目。")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NO_NETPLAY_HOSTS_FOUND,
      "未發現連線遊戲主機。")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NO_NETWORKS_FOUND,
      "未發現網路。")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NO_PERFORMANCE_COUNTERS,
      "沒有性能計數器。")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NO_PLAYLISTS,
      "沒有遊戲列表。")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NO_PLAYLIST_ENTRIES_AVAILABLE,
      "沒有可用的遊戲列表項目。")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NO_SETTINGS_FOUND,
      "沒有找到設定。")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NO_SHADER_PARAMETERS,
      "沒有Shader參數.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_OFF,
      "關")
MSG_HASH(MENU_ENUM_LABEL_VALUE_ON,
      "開")
MSG_HASH(MENU_ENUM_LABEL_VALUE_ONLINE_UPDATER,
      "連線更新器")
MSG_HASH(MENU_ENUM_LABEL_VALUE_ONSCREEN_DISPLAY_SETTINGS,
      "營幕顯示")
MSG_HASH(MENU_ENUM_LABEL_VALUE_ONSCREEN_OVERLAY_SETTINGS,
      "營幕覆層")
MSG_HASH(MENU_ENUM_LABEL_VALUE_OPEN_ARCHIVE,
      "以文件夾形式打開壓縮包")
MSG_HASH(MENU_ENUM_LABEL_VALUE_ONSCREEN_NOTIFICATIONS_SETTINGS,
      "營幕通知")
MSG_HASH(MENU_ENUM_LABEL_VALUE_OPTIONAL,
      "任意")
MSG_HASH(MENU_ENUM_LABEL_VALUE_OSK_OVERLAY_DIRECTORY,
      "OSK覆層目錄")
MSG_HASH(MENU_ENUM_LABEL_VALUE_OVERLAY,
      "覆層")
MSG_HASH(MENU_ENUM_LABEL_VALUE_OVERLAY_AUTOLOAD_PREFERRED,
      "自動戴入最佳的覆層")
MSG_HASH(MENU_ENUM_LABEL_VALUE_OVERLAY_DIRECTORY,
      "覆層目錄")
MSG_HASH(MENU_ENUM_LABEL_VALUE_OVERLAY_OPACITY,
      "覆層不透明度")
MSG_HASH(MENU_ENUM_LABEL_VALUE_OVERLAY_PRESET,
      "覆層預設")
MSG_HASH(MENU_ENUM_LABEL_VALUE_OVERLAY_SCALE,
      "覆層縮放比例")
MSG_HASH(MENU_ENUM_LABEL_VALUE_OVERLAY_SETTINGS,
      "營幕覆層")
MSG_HASH(MENU_ENUM_LABEL_VALUE_PAL60_ENABLE,
      "使用PAL60模式")
MSG_HASH(MENU_ENUM_LABEL_VALUE_PARENT_DIRECTORY,
      "上一級目錄")
MSG_HASH(MENU_ENUM_LABEL_VALUE_PAUSE_LIBRETRO,
      "當選單激活時暫停")
MSG_HASH(MENU_ENUM_LABEL_VALUE_PAUSE_NONACTIVE,
      "禁止後台運行")
MSG_HASH(MENU_ENUM_LABEL_VALUE_PERFCNT_ENABLE,
      "性能計數器")
MSG_HASH(MENU_ENUM_LABEL_VALUE_PLAYLISTS_TAB,
      "遊戲列表")
MSG_HASH(MENU_ENUM_LABEL_VALUE_PLAYLIST_DIRECTORY,
      "遊戲列表目錄")
MSG_HASH(MENU_ENUM_LABEL_VALUE_PLAYLIST_SETTINGS,
      "遊戲列表")
MSG_HASH(MENU_ENUM_LABEL_VALUE_POINTER_ENABLE,
      "觸控支援")
MSG_HASH(MENU_ENUM_LABEL_VALUE_PORT,
      "端口")
MSG_HASH(MENU_ENUM_LABEL_VALUE_PRESENT,
      "現在")
MSG_HASH(MENU_ENUM_LABEL_VALUE_PRIVACY_SETTINGS,
      "隱私")
MSG_HASH(MENU_ENUM_LABEL_VALUE_QUIT_RETROARCH,
      "退出 RetroArch")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_ANALOG,
      "支持搖桿輸入")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_BBFC_RATING,
      "BBFC 分級")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_CERO_RATING,
      "CERO 分級")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_COOP,
      "多人遊戲支持")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_CRC32,
      "CRC32")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_DESCRIPTION,
      "描述")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_DEVELOPER,
      "開發者")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_EDGE_MAGAZINE_ISSUE,
      "Edge雜誌發行")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_EDGE_MAGAZINE_RATING,
      "Edge雜誌評分")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_EDGE_MAGAZINE_REVIEW,
      "Edge雜誌評論")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_ELSPA_RATING,
      "ELSPA 分級")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_ENHANCEMENT_HW,
      "增強硬件")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_ESRB_RATING,
      "ESRB 分級")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_FAMITSU_MAGAZINE_RATING,
      "次世代(Famitsu)雜誌評分")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_FRANCHISE,
      "經銷商")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_GENRE,
      "類型")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_MD5,
      "MD5")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_NAME,
      "名稱")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_ORIGIN,
      "起源")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_PEGI_RATING,
      "PEGI 分級")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_PUBLISHER,
      "出版方")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_RELEASE_MONTH,
      "發售月份")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_RELEASE_YEAR,
      "發售年份")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_RUMBLE,
      "震動支持")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_SERIAL,
      "系列")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_SHA1,
      "SHA1")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_START_CONTENT,
      "啟動遊戲內容")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_TGDB_RATING,
      "TGDB 評分")
#ifdef HAVE_LAKKA_SWITCH
MSG_HASH(MENU_ENUM_LABEL_VALUE_REBOOT,
      "重啟 (RCM)")
#else
MSG_HASH(MENU_ENUM_LABEL_VALUE_REBOOT,
      "重啟")
#endif
MSG_HASH(MENU_ENUM_LABEL_VALUE_RECORDING_CONFIG_DIRECTORY,
      "錄影設定目錄")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RECORDING_OUTPUT_DIRECTORY,
      "錄影輸出目錄")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RECORDING_SETTINGS,
      "錄影")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RECORD_CONFIG,
      "錄影設定")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RECORD_DRIVER,
      "錄影驅動")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RECORD_ENABLE,
      "啟用錄影")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RECORD_PATH,
      "輸出文件")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RECORD_USE_OUTPUT_DIRECTORY,
      "使用輸出目錄")
MSG_HASH(MENU_ENUM_LABEL_VALUE_REMAP_FILE,
      "重映射文件")
MSG_HASH(MENU_ENUM_LABEL_VALUE_REMAP_FILE_LOAD,
      "戴入重映射文件")
MSG_HASH(MENU_ENUM_LABEL_VALUE_REMAP_FILE_SAVE_CORE,
      "儲存核心重映射文件")
MSG_HASH(MENU_ENUM_LABEL_VALUE_REMAP_FILE_SAVE_GAME,
      "儲存遊戲重映射文件")
MSG_HASH(MENU_ENUM_LABEL_VALUE_REQUIRED,
      "必須")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RESTART_CONTENT,
      "重啟")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RESTART_RETROARCH,
      "重啟 RetroArch")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RESUME,
      "繼續")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RESUME_CONTENT,
      "繼續")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RETROKEYBOARD,
      "Retro鍵盤")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RETROPAD,
      "Retro觸控板")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RETROPAD_WITH_ANALOG,
      "RetroPad w/ Analog")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RETRO_ACHIEVEMENTS_SETTINGS,
      "Retro 成就")
MSG_HASH(MENU_ENUM_LABEL_VALUE_REWIND_ENABLE,
      "啟用回溯")
MSG_HASH(MENU_ENUM_LABEL_VALUE_REWIND_GRANULARITY,
      "回溯粒度")
MSG_HASH(MENU_ENUM_LABEL_VALUE_REWIND_SETTINGS,
      "回溯")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RGUI_BROWSER_DIRECTORY,
      "文件瀏覽器目錄")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RGUI_CONFIG_DIRECTORY,
      "設定目錄")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RGUI_SHOW_START_SCREEN,
      "顯示開始營幕")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RIGHT_ANALOG,
      "右側搖桿")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RUN,
      "運行")
#ifdef HAVE_LAKKA
MSG_HASH(MENU_ENUM_LABEL_VALUE_SAMBA_ENABLE,
      "啟用SAMBA文件共享服務")
#endif
MSG_HASH(MENU_ENUM_LABEL_VALUE_SAVEFILE_DIRECTORY,
      "存檔文件目錄")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SAVESTATE_AUTO_INDEX,
      "自動索引儲存狀態")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SAVESTATE_AUTO_LOAD,
      "自動戴入狀態")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SAVESTATE_AUTO_SAVE,
      "自動儲存狀態")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SAVESTATE_DIRECTORY,
      "狀態存儲目錄")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SAVESTATE_THUMBNAIL_ENABLE,
      "既時存檔縮圖")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SAVE_CURRENT_CONFIG,
      "儲存當前設定")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SAVE_CURRENT_CONFIG_OVERRIDE_CORE,
      "儲存核心覆寫")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SAVE_CURRENT_CONFIG_OVERRIDE_GAME,
      "儲存遊戲覆寫")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SAVE_NEW_CONFIG,
      "儲存新設定")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SAVE_STATE,
      "儲存狀態")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SAVING_SETTINGS,
      "存檔")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SCAN_DIRECTORY,
      "掃瞄文件夾")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SCAN_FILE,
      "掃瞄文件")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SCAN_THIS_DIRECTORY,
      "<掃瞄當前目錄>")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SCREENSHOT_DIRECTORY,
      "營幕截圖目錄")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SCREEN_RESOLUTION,
      "營幕分辨率")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SEARCH,
      "搜索：")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SECONDS,
      "秒")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SETTINGS,
      "設定")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SETTINGS_TAB,
      "設定")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SHADER,
      "Shader")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SHADER_APPLY_CHANGES,
      "應用Shader修改")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SHADER_OPTIONS,
      "Shader效果")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SHADER_PIPELINE_RIBBON,
      "Ribbon")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SHADER_PIPELINE_RIBBON_SIMPLIFIED,
      "Ribbon (簡化)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SHADER_PIPELINE_SIMPLE_SNOW,
      "Simple Snow")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SHADER_PIPELINE_SNOW,
      "Snow")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SHOW_ADVANCED_SETTINGS,
      "顯示高級設定")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SHOW_HIDDEN_FILES,
      "顯示隱藏的文件和文件夾")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SHUTDOWN,
      "關機")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SLOWMOTION_RATIO,
      "慢動作倍率")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SORT_SAVEFILES_ENABLE,
      "排序文件夾中的存檔")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SORT_SAVESTATES_ENABLE,
      "排序文件夾中的狀態存儲")
#ifdef HAVE_LAKKA
MSG_HASH(MENU_ENUM_LABEL_VALUE_SSH_ENABLE,
      "啟用SSH遠程終端服務")
#endif
MSG_HASH(MENU_ENUM_LABEL_VALUE_START_CORE,
      "啟動核心")
MSG_HASH(MENU_ENUM_LABEL_VALUE_START_NET_RETROPAD,
      "啟動遠程的RetroPad")
MSG_HASH(MENU_ENUM_LABEL_VALUE_START_VIDEO_PROCESSOR,
      "啟動視訊處理")
MSG_HASH(MENU_ENUM_LABEL_VALUE_STATE_SLOT,
      "狀態存儲槽")
MSG_HASH(MENU_ENUM_LABEL_VALUE_STATUS,
      "狀態")
MSG_HASH(MENU_ENUM_LABEL_VALUE_STDIN_CMD_ENABLE,
      "標準輸入流命令")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SUPPORTED_CORES,
      "支持的核心")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SUSPEND_SCREENSAVER_ENABLE,
      "暫停屏保程序")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_BGM_ENABLE,
      "啟用系統背景音樂")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_DIRECTORY,
      "系統/BIOS目錄")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFORMATION,
      "系統訊息")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_7ZIP_SUPPORT,
      "7zip 支持")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_ALSA_SUPPORT,
      "ALSA 支持")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_BUILD_DATE,
      "編譯日期")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_CG_SUPPORT,
      "Cg 支持")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_COCOA_SUPPORT,
      "Cocoa 支持")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_COMMAND_IFACE_SUPPORT,
      "控制台支持")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_CORETEXT_SUPPORT,
      "CoreText 支持")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_CPU_FEATURES,
      "CPU特性")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_DISPLAY_METRIC_DPI,
      "顯示器度量DPI")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_DISPLAY_METRIC_MM_HEIGHT,
      "顯示器度量高度(mm)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_DISPLAY_METRIC_MM_WIDTH,
      "顯示器度量寬度(mm)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_DSOUND_SUPPORT,
      "DirectSound 支持")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_WASAPI_SUPPORT,
      "WASAPI 支持")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_DYLIB_SUPPORT,
      "動態鏈接庫支持")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_DYNAMIC_SUPPORT,
      "運行時動態戴入libretro庫")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_EGL_SUPPORT,
      "EGL 支持")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_FBO_SUPPORT,
      "OpenGL/Direct3D 渲染至紋理 (多渲染批次Shader) 支持")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_FFMPEG_SUPPORT,
      "FFmpeg 支持")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_FREETYPE_SUPPORT,
      "FreeType 支持")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_STB_TRUETYPE_SUPPORT,
      "STB TrueType 支持")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_FRONTEND_IDENTIFIER,
      "前端標識")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_FRONTEND_NAME,
      "前端名稱")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_FRONTEND_OS,
      "前端操作系統")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_GIT_VERSION,
      "Git版本")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_GLSL_SUPPORT,
      "GLSL 支持")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_HLSL_SUPPORT,
      "HLSL 支持")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_JACK_SUPPORT,
      "JACK 支持")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_KMS_SUPPORT,
      "KMS/EGL 支持")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_LIBRETRODB_SUPPORT,
      "LibretroDB 支持")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_LIBUSB_SUPPORT,
      "Libusb 支持")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_NETPLAY_SUPPORT,
      "Netplay (點對點) 支持")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_NETWORK_COMMAND_IFACE_SUPPORT,
      "網路控制台支持")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_NETWORK_REMOTE_SUPPORT,
      "網路控制器支持")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_OPENAL_SUPPORT,
      "OpenAL 支持")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_OPENGLES_SUPPORT,
      "OpenGL ES 支持")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_OPENGL_SUPPORT,
      "OpenGL 支持")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_OPENSL_SUPPORT,
      "OpenSL 支持")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_OPENVG_SUPPORT,
      "OpenVG 支持")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_OSS_SUPPORT,
      "OSS 支持")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_OVERLAY_SUPPORT,
      "覆層支持")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_POWER_SOURCE,
      "電源")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_POWER_SOURCE_CHARGED,
      "已充滿電")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_POWER_SOURCE_CHARGING,
      "充電中")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_POWER_SOURCE_DISCHARGING,
      "放電中")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_POWER_SOURCE_NO_SOURCE,
      "沒有電源")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_PULSEAUDIO_SUPPORT,
      "PulseAudio 支持")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_PYTHON_SUPPORT,
      "Python (Shader中腳本支持) 支持")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_RBMP_SUPPORT,
      "BMP 支持 (RBMP)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_RETRORATING_LEVEL,
      "RetroRating 等級")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_RJPEG_SUPPORT,
      "JPEG 支持 (RJPEG)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_ROARAUDIO_SUPPORT,
      "RoarAudio 支持")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_RPNG_SUPPORT,
      "PNG 支持 (RPNG)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_RSOUND_SUPPORT,
      "RSound 支持")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_RTGA_SUPPORT,
      "TGA 支持 (RTGA)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_SDL2_SUPPORT,
      "SDL2 支持")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_SDL_IMAGE_SUPPORT,
      "SDL 圖像支持")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_SDL_SUPPORT,
      "SDL1.2 支持")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_SLANG_SUPPORT,
      "Slang 支持")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_THREADING_SUPPORT,
      "多線程支持")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_UDEV_SUPPORT,
      "Udev 支持")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_V4L2_SUPPORT,
      "Video4Linux2 支持")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_VIDEO_CONTEXT_DRIVER,
      "視訊上下文驅動")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_VULKAN_SUPPORT,
      "Vulkan 支持")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_WAYLAND_SUPPORT,
      "Wayland 支持")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_X11_SUPPORT,
      "X11 支持")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_XAUDIO2_SUPPORT,
      "XAudio2 支持")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_XVIDEO_SUPPORT,
      "XVideo 支持")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_ZLIB_SUPPORT,
      "Zlib 支持")
MSG_HASH(MENU_ENUM_LABEL_VALUE_TAKE_SCREENSHOT,
      "截取營幕")
MSG_HASH(MENU_ENUM_LABEL_VALUE_THREADED_DATA_RUNLOOP_ENABLE, /* TODO/FIXME - update */
      "啟用多線程數據執行循環")
MSG_HASH(MENU_ENUM_LABEL_VALUE_THUMBNAILS,
      "縮略圖")
MSG_HASH(MENU_ENUM_LABEL_VALUE_THUMBNAILS_DIRECTORY,
      "縮略圖目錄")
MSG_HASH(MENU_ENUM_LABEL_VALUE_THUMBNAILS_UPDATER_LIST,
      "縮略圖更新程序")
MSG_HASH(MENU_ENUM_LABEL_VALUE_THUMBNAIL_MODE_BOXARTS,
      "Boxarts")
MSG_HASH(MENU_ENUM_LABEL_VALUE_THUMBNAIL_MODE_SCREENSHOTS,
      "截屏")
MSG_HASH(MENU_ENUM_LABEL_VALUE_THUMBNAIL_MODE_TITLE_SCREENS,
      "標題畫面")
MSG_HASH(MENU_ENUM_LABEL_VALUE_TIMEDATE_ENABLE,
      "顯示時間日期")
MSG_HASH(MENU_ENUM_LABEL_VALUE_TRUE,
      "真")
MSG_HASH(MENU_ENUM_LABEL_VALUE_UI_COMPANION_ENABLE,
      "UI Companion Enable")
MSG_HASH(MENU_ENUM_LABEL_VALUE_UI_COMPANION_START_ON_BOOT,
      "UI Companion Start On Boot")
MSG_HASH(MENU_ENUM_LABEL_VALUE_UI_MENUBAR_ENABLE,
      "Menubar")
MSG_HASH(MENU_ENUM_LABEL_VALUE_UNABLE_TO_READ_COMPRESSED_FILE,
      "無法讀取壓縮的文件。")
MSG_HASH(MENU_ENUM_LABEL_VALUE_UNDO_LOAD_STATE,
      "撤銷戴入狀態")
MSG_HASH(MENU_ENUM_LABEL_VALUE_UNDO_SAVE_STATE,
      "撤銷儲存狀態")
MSG_HASH(MENU_ENUM_LABEL_VALUE_UNKNOWN,
      "未知")
MSG_HASH(MENU_ENUM_LABEL_VALUE_UPDATER_SETTINGS,
      "更新程序")
MSG_HASH(MENU_ENUM_LABEL_VALUE_UPDATE_ASSETS,
      "更新資源")
MSG_HASH(MENU_ENUM_LABEL_VALUE_UPDATE_AUTOCONFIG_PROFILES,
      "更新自動設定檔案")
MSG_HASH(MENU_ENUM_LABEL_VALUE_UPDATE_CG_SHADERS,
      "更新CG Shader效果文件")
MSG_HASH(MENU_ENUM_LABEL_VALUE_UPDATE_CHEATS,
      "更新金手指")
MSG_HASH(MENU_ENUM_LABEL_VALUE_UPDATE_CORE_INFO_FILES,
      "更新核心訊息文件")
MSG_HASH(MENU_ENUM_LABEL_VALUE_UPDATE_DATABASES,
      "更新數據庫")
MSG_HASH(MENU_ENUM_LABEL_VALUE_UPDATE_GLSL_SHADERS,
      "更新GLSL Shader效果文件")
MSG_HASH(MENU_ENUM_LABEL_VALUE_UPDATE_LAKKA,
      "更新 Lakka")
MSG_HASH(MENU_ENUM_LABEL_VALUE_UPDATE_OVERLAYS,
      "更新覆層")
MSG_HASH(MENU_ENUM_LABEL_VALUE_UPDATE_SLANG_SHADERS,
      "更新Slang Shader效果文件")
MSG_HASH(MENU_ENUM_LABEL_VALUE_USER,
      "用戶")
MSG_HASH(MENU_ENUM_LABEL_VALUE_USER_INTERFACE_SETTINGS,
      "用戶界面")
MSG_HASH(MENU_ENUM_LABEL_VALUE_USER_LANGUAGE,
      "語言")
MSG_HASH(MENU_ENUM_LABEL_VALUE_USER_SETTINGS,
      "用戶")
MSG_HASH(MENU_ENUM_LABEL_VALUE_USE_BUILTIN_IMAGE_VIEWER,
      "使用內建的圖像瀏覽器")
MSG_HASH(MENU_ENUM_LABEL_VALUE_USE_BUILTIN_PLAYER,
      "使用內建媒體播放器")
MSG_HASH(MENU_ENUM_LABEL_VALUE_USE_THIS_DIRECTORY,
      "<使用當前目錄>")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_ALLOW_ROTATE,
      "允許旋轉")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_ASPECT_RATIO_AUTO,
      "自動選擇畫面比例")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_ASPECT_RATIO_INDEX,
      "畫面比例選項")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_BLACK_FRAME_INSERTION,
      "黑色幀補間")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_DISABLE_COMPOSITION,
      "禁用桌面元素")
#if defined(_3DS)
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_3DS_LCD_BOTTOM,
      "3DS底部屏幕")
#endif
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_DRIVER,
      "視訊驅動")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_FILTER,
      "視訊濾鏡")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_FILTER_DIR,
      "視訊濾鏡目錄")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_FILTER_FLICKER,
      "閃爍過濾器")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_FONT_ENABLE,
      "顯示屏顯消息(OSD)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_FONT_PATH,
      "屏顯消息(OSD)字體")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_FONT_SIZE,
      "屏顯消息(OSD)大小")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_FORCE_ASPECT,
      "強制畫面比例")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_FORCE_SRGB_DISABLE,
      "強制禁止sRGB幀緩衝")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_FRAME_DELAY,
      "幀延時")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_FULLSCREEN,
      "使用全屏模式")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_GAMMA,
      "視訊Gamma")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_GPU_RECORD,
      "啟用GPU錄影")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_GPU_SCREENSHOT,
      "啟用GPU截屏")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_HARD_SYNC,
      "強制GPU同步")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_HARD_SYNC_FRAMES,
      "強制GPU同步幀數")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_MAX_SWAPCHAIN_IMAGES,
      "最大交換鏈圖像數")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_MESSAGE_POS_X,
      "屏顯消息(OSD)X軸位置")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_MESSAGE_POS_Y,
      "屏顯消息(OSD)Y軸位置")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_MONITOR_INDEX,
      "顯示器索引")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_POST_FILTER_RECORD,
      "啟用錄影後期濾鏡")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_REFRESH_RATE,
      "刷新率")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_REFRESH_RATE_AUTO,
      "估算的顯示器幀率")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_REFRESH_RATE_POLLED,
      "Set Display-Reported Refresh Rate")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_ROTATION,
      "旋轉")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_SCALE,
      "窗口縮放量")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_SCALE_INTEGER,
      "整數化縮放量")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_SETTINGS,
      "視訊")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_SHADER_DIR,
      "視訊Shader目錄")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_SHADER_NUM_PASSES,
      "Shader渲染遍數")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_SHADER_PARAMETERS,
      "預覽Shader參數")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_SHADER_PRESET,
      "戴入Shader預設")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_SHADER_PRESET_SAVE_AS,
      "儲存Shader預設為")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_SHADER_PRESET_SAVE_CORE,
      "儲存核心預設")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_SHADER_PRESET_SAVE_GAME,
      "儲存遊戲預設")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_SHARED_CONTEXT,
      "啟用硬件共享上下文")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_SMOOTH,
      "硬件雙線性過濾")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_SOFT_FILTER,
      "啟用軟件過濾器")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_SWAP_INTERVAL,
      "垂直同步交換間隔")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_TAB,
      "視訊")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_THREADED,
      "多線程渲染")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_VFILTER,
      "降低閃爍")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_VIEWPORT_CUSTOM_HEIGHT,
      "自定義畫面高度")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_VIEWPORT_CUSTOM_WIDTH,
      "自定義畫面寬度")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_VIEWPORT_CUSTOM_X,
      "自定義畫面X")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_VIEWPORT_CUSTOM_Y,
      "自定義畫面Y")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_VI_WIDTH,
      "設定 VI 營幕寬度")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_VSYNC,
      "垂直同步")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_WINDOWED_FULLSCREEN,
      "無邊框窗口全屏模式")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_WINDOW_WIDTH,
      "窗口寬度")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_WINDOW_HEIGHT,
      "窗口高度")
MSG_HASH(MENU_ENUM_LABEL_VALUE_WIFI_DRIVER,
      "Wi-Fi驅動")
MSG_HASH(MENU_ENUM_LABEL_VALUE_WIFI_SETTINGS,
      "Wi-Fi")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_ALPHA_FACTOR,
      "選單透明度因子")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_FONT,
      "選單字體")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_ICON_THEME_CUSTOM,
      "自定義")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_MENU_COLOR_THEME,
      "選單顏色主題")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_MENU_COLOR_THEME_APPLE_GREEN,
      "蘋果綠")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_MENU_COLOR_THEME_DARK,
      "深色")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_MENU_COLOR_THEME_DARK_PURPLE,
      "深紫色")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_MENU_COLOR_THEME_ELECTRIC_BLUE,
      "鐵藍色")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_MENU_COLOR_THEME_GOLDEN,
      "金色")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_MENU_COLOR_THEME_LEGACY_RED,
      "傳統紅")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_MENU_COLOR_THEME_MIDNIGHT_BLUE,
      "藍黑色")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_MENU_COLOR_THEME_PLAIN,
      "樸素")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_MENU_COLOR_THEME_UNDERSEA,
      "海底")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_MENU_COLOR_THEME_VOLCANIC_RED,
      "火山紅")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_RIBBON_ENABLE,
      "選單Shader管線")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MENU_SCALE_FACTOR,
      "選單縮放因子")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_SHADOWS_ENABLE,
      "啟用圖標陰影")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CONTENT_SHOW_HISTORY,
      "顯示歷史頁")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CONTENT_SHOW_ADD,
      "顯示導入內容頁")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CONTENT_SHOW_IMAGES,
      "顯示圖像頁")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CONTENT_SHOW_MUSIC,
      "顯示音樂頁")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CONTENT_SHOW_SETTINGS,
      "顯示設定頁")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CONTENT_SHOW_VIDEO,
      "顯示視訊頁")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_LAYOUT,
      "Menu Layout")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_THEME,
      "選單圖標主題")
MSG_HASH(MENU_ENUM_LABEL_VALUE_YES,
      "是")
MSG_HASH(MENU_ENUM_LABEL_VIDEO_SHADER_PRESET_TWO,
      "Shader預設")
MSG_HASH(MENU_ENUM_SUBLABEL_CHEEVOS_ENABLE,
      "打開或關閉成就。更多內容請訪問 http://retroachievements.org")
MSG_HASH(MENU_ENUM_SUBLABEL_CHEEVOS_TEST_UNOFFICIAL,
      "為測試目的而打開或關閉非官方成就和/或測試版特性。")
MSG_HASH(MENU_ENUM_SUBLABEL_CHEEVOS_HARDCORE_MODE_ENABLE,
      "為所有遊戲打開或關閉存檔、金手指、回退、快進、暫停和慢動作。")
MSG_HASH(MENU_ENUM_SUBLABEL_DRIVER_SETTINGS,
      "修改驅動設定。")
MSG_HASH(MENU_ENUM_SUBLABEL_RETRO_ACHIEVEMENTS_SETTINGS,
      "修改成就設定。")
MSG_HASH(MENU_ENUM_SUBLABEL_CORE_SETTINGS,
      "修改核心設定。")
MSG_HASH(MENU_ENUM_SUBLABEL_RECORDING_SETTINGS,
      "修改錄製的設定。")
MSG_HASH(MENU_ENUM_SUBLABEL_ONSCREEN_DISPLAY_SETTINGS,
      "修改顯示覆蓋、鍵盤覆蓋和營幕通知的設定。")
MSG_HASH(MENU_ENUM_SUBLABEL_FRAME_THROTTLE_SETTINGS,
      "修改回滾、快進和慢動作的設定。")
MSG_HASH(MENU_ENUM_SUBLABEL_SAVING_SETTINGS,
      "修改存檔設定。")
MSG_HASH(MENU_ENUM_SUBLABEL_LOGGING_SETTINGS,
      "修改日誌設定。")
MSG_HASH(MENU_ENUM_SUBLABEL_USER_INTERFACE_SETTINGS,
      "修改用戶界面設定。")
MSG_HASH(MENU_ENUM_SUBLABEL_USER_SETTINGS,
      "修改帳號、用戶名和語言。")
MSG_HASH(MENU_ENUM_SUBLABEL_PRIVACY_SETTINGS,
      "修改你的隱私設定。")
MSG_HASH(MENU_ENUM_SUBLABEL_DIRECTORY_SETTINGS,
      "修改此系統的默認目錄。")
MSG_HASH(MENU_ENUM_SUBLABEL_PLAYLIST_SETTINGS,
      "修改遊戲列表設定。")
MSG_HASH(MENU_ENUM_SUBLABEL_NETWORK_SETTINGS,
      "修改網路設定。")
MSG_HASH(MENU_ENUM_SUBLABEL_ADD_CONTENT_LIST,
      "下載且/或者掃瞄遊戲內容，並將其加入你的收藏中。")
MSG_HASH(MENU_ENUM_SUBLABEL_AUDIO_SETTINGS,
      "調整聲音輸出的選項。")
#ifdef HAVE_LAKKA
MSG_HASH(MENU_ENUM_SUBLABEL_BLUETOOTH_ENABLE,
      "啟用或者禁止藍牙。")
#endif
MSG_HASH(MENU_ENUM_SUBLABEL_CONFIG_SAVE_ON_EXIT,
      "程序將在退出時儲存修改到設定文件。")
MSG_HASH(MENU_ENUM_SUBLABEL_CONFIGURATION_SETTINGS,
      "修改設定文件的默認設定。")
MSG_HASH(MENU_ENUM_SUBLABEL_CONFIGURATIONS_LIST,
      "管理和創建設定文件。")
MSG_HASH(MENU_ENUM_SUBLABEL_CPU_CORES,
      "CPU擁有的核心總數。")
MSG_HASH(MENU_ENUM_SUBLABEL_FPS_SHOW,
      "在營幕上顯示當前每秒的幀率。")
MSG_HASH(MENU_ENUM_SUBLABEL_INPUT_HOTKEY_BINDS,
      "設定熱鍵選項。")
MSG_HASH(MENU_ENUM_SUBLABEL_INPUT_MENU_ENUM_TOGGLE_GAMEPAD_COMBO,
      "控制器用來切出選單的組合鍵。")
MSG_HASH(MENU_ENUM_SUBLABEL_INPUT_SETTINGS,
      "調整遊戲控制器、鍵盤和鼠標的設定。")
MSG_HASH(MENU_ENUM_SUBLABEL_INPUT_USER_BINDS, /* TODO/FIXME - change user to port */
      "設定該用戶的控制選項。")
MSG_HASH(MENU_ENUM_SUBLABEL_LOG_VERBOSITY,
      "啟用或禁止向控制台打印日誌。")
MSG_HASH(MENU_ENUM_SUBLABEL_NETPLAY,
      "加入或者開啟一個連線多人遊戲的會話。")
MSG_HASH(MENU_ENUM_SUBLABEL_NETPLAY_LAN_SCAN_SETTINGS,
      "在局域網內搜索並連接聯網遊戲的主機。")
MSG_HASH(MENU_ENUM_SUBLABEL_INFORMATION_LIST_LIST,
      "顯示核心、網路和系統的訊息。顯示數據庫和光標的管理器。")
MSG_HASH(MENU_ENUM_SUBLABEL_ONLINE_UPDATER,
      "下載並更新RetroArch的附加插件和組件。")
#ifdef HAVE_LAKKA
MSG_HASH(MENU_ENUM_SUBLABEL_SAMBA_ENABLE,
      "啟用或者禁止網路文件夾共享(SAMBA)。")
MSG_HASH(MENU_ENUM_SUBLABEL_SERVICES_SETTINGS,
      "管理操作系統層級的服務。")
#endif
MSG_HASH(MENU_ENUM_SUBLABEL_SHOW_HIDDEN_FILES,
      "在文件瀏覽器中顯示隱藏的文件或文件夾。")
#ifdef HAVE_LAKKA
MSG_HASH(MENU_ENUM_SUBLABEL_SSH_ENABLE,
      "啟用或者禁止遠程終端訪問(SSH)。")
#endif
MSG_HASH(MENU_ENUM_SUBLABEL_SUSPEND_SCREENSAVER_ENABLE,
      "阻止系統激活營幕保護程序。")
MSG_HASH(MENU_ENUM_SUBLABEL_USER_LANGUAGE,
      "設定用戶界面的語言。")
MSG_HASH(MENU_ENUM_SUBLABEL_VIDEO_BLACK_FRAME_INSERTION,
      "在幀與幀之間插入黑色的中間幀，通常用於消除在\n"
      "120Hz刷新率的顯示器上運行60Hz的遊戲內容帶來\n"
      "的鬼影。")
MSG_HASH(MENU_ENUM_SUBLABEL_VIDEO_FRAME_DELAY,
      "以增加畫面卡頓的風險換取低延時，在垂直同步後增加\n"
      "時延(毫秒)。")
MSG_HASH(MENU_ENUM_SUBLABEL_VIDEO_HARD_SYNC_FRAMES,
      "設定當開啟「強制GPU同步」時CPU可以預先GPU多少幀。")
MSG_HASH(MENU_ENUM_SUBLABEL_VIDEO_MAX_SWAPCHAIN_IMAGES,
      "強制顯示驅動程序使用特定的緩衝模式。")
MSG_HASH(MENU_ENUM_SUBLABEL_VIDEO_MONITOR_INDEX,
      "選擇將要使用哪一個顯示器。")
MSG_HASH(MENU_ENUM_SUBLABEL_VIDEO_REFRESH_RATE_AUTO,
      "估算的顯示器刷新率(Hz)。")
MSG_HASH(MENU_ENUM_SUBLABEL_VIDEO_REFRESH_RATE_POLLED,
      "The refresh rate as reported by the display driver.")
MSG_HASH(MENU_ENUM_SUBLABEL_VIDEO_SETTINGS,
      "調整視訊輸出的選項。")
MSG_HASH(MENU_ENUM_SUBLABEL_WIFI_SETTINGS,
      "掃瞄無線網路並且建立連接。")
MSG_HASH(MENU_ENUM_SUBLABEL_HELP_LIST,
      "學習更多關於其是如何工作的。")
MSG_HASH(MSG_APPENDED_DISK,
      "磁碟已加入")
MSG_HASH(MSG_APPLICATION_DIR,
      "應用程序目錄")
MSG_HASH(MSG_APPLYING_SHADER,
      "載入 shader")
MSG_HASH(MSG_AUDIO_MUTED,
      "靜音。")
MSG_HASH(MSG_AUDIO_UNMUTED,
      "取消靜音。")
MSG_HASH(MSG_AUTOCONFIG_FILE_ERROR_SAVING,
      "儲存 autoconf 文件錯誤。")
MSG_HASH(MSG_AUTOCONFIG_FILE_SAVED_SUCCESSFULLY,
      "自動設定文件儲存成功。")
MSG_HASH(MSG_AUTOSAVE_FAILED,
      "無法初始化自動儲存。")
MSG_HASH(MSG_AUTO_SAVE_STATE_TO,
      "自動儲存狀態至")
MSG_HASH(MSG_BLOCKING_SRAM_OVERWRITE,
      "阻止 SRAM 覆蓋")
MSG_HASH(MSG_BRINGING_UP_COMMAND_INTERFACE_ON_PORT,
      "啟用通訊埠上的指令介面")
MSG_HASH(MSG_BYTES,
      "字節")
MSG_HASH(MSG_CANNOT_INFER_NEW_CONFIG_PATH,
      "無法推斷新的設定路徑，使用當前時間。")
MSG_HASH(MSG_CHEEVOS_HARDCORE_MODE_ENABLE,
      "硬核模式開啟：及時存檔和回放被禁用.")
MSG_HASH(MSG_COMPARING_WITH_KNOWN_MAGIC_NUMBERS,
      "與已知的magic numbers比較...")
MSG_HASH(MSG_COMPILED_AGAINST_API,
      "Compiled against API")
MSG_HASH(MSG_CONFIG_DIRECTORY_NOT_SET,
      "未設定設定目錄，無法儲存新的設定。")
MSG_HASH(MSG_CONNECTED_TO,
      "連接至")
MSG_HASH(MSG_CONTENT_CRC32S_DIFFER,
      "內容的CRC32s不同。無法使用不同的遊戲。")
MSG_HASH(MSG_CONTENT_LOADING_SKIPPED_IMPLEMENTATION_WILL_DO_IT,
      "跳過內容戴入。實現將自行戴入。")
MSG_HASH(MSG_CORE_DOES_NOT_SUPPORT_SAVESTATES,
      "核心不支持儲存狀態。")
MSG_HASH(MSG_CORE_OPTIONS_FILE_CREATED_SUCCESSFULLY,
      "模擬器核心設定檔建立成功.")
MSG_HASH(MSG_COULD_NOT_FIND_ANY_NEXT_DRIVER,
      "無法找到磁碟")
MSG_HASH(MSG_COULD_NOT_FIND_COMPATIBLE_SYSTEM,
      "無法找到相容系統.")
MSG_HASH(MSG_COULD_NOT_FIND_VALID_DATA_TRACK,
      "無法找到有效的數據軌")
MSG_HASH(MSG_COULD_NOT_OPEN_DATA_TRACK,
      "無法打開數據軌")
MSG_HASH(MSG_COULD_NOT_READ_CONTENT_FILE,
      "無法讀取內容文件")
MSG_HASH(MSG_COULD_NOT_READ_MOVIE_HEADER,
      "無法讀取視訊頭部訊息.")
MSG_HASH(MSG_COULD_NOT_READ_STATE_FROM_MOVIE,
      "無法讀取視訊狀態.")
MSG_HASH(MSG_DECOMPRESSION_ALREADY_IN_PROGRESS,
      "解壓縮已在進行中。")
MSG_HASH(MSG_DECOMPRESSION_FAILED,
      "解壓縮失敗。")
MSG_HASH(MSG_DETECTED_VIEWPORT_OF,
      "Detected viewport of")
MSG_HASH(MSG_DID_NOT_FIND_A_VALID_CONTENT_PATCH,
      "無法找到任何有效的內容位置.")
MSG_HASH(MSG_DISCONNECT_DEVICE_FROM_A_VALID_PORT,
      "從連接埠離開.")
MSG_HASH(MSG_DISK_CLOSED,
      "已關閉")
MSG_HASH(MSG_DISK_EJECTED,
      "已彈出")
MSG_HASH(MSG_DOWNLOADING,
      "正在下載")
MSG_HASH(MSG_DOWNLOAD_FAILED,
      "下載失敗")
MSG_HASH(MSG_ERROR,
      "錯誤")
MSG_HASH(MSG_ERROR_LIBRETRO_CORE_REQUIRES_CONTENT,
      "Libretro core 需載入相關遊戲內容, 但程式未找到可載入內容.")
MSG_HASH(MSG_ERROR_LIBRETRO_CORE_REQUIRES_SPECIAL_CONTENT,
      "Libretro core 需載入相關特定遊戲內容, 但程式未找到可載入內容.")
MSG_HASH(MSG_ERROR_PARSING_ARGUMENTS,
      "處理參數時發生錯誤.")
MSG_HASH(MSG_ERROR_SAVING_CORE_OPTIONS_FILE,
      "無法儲存 core options 檔案.")
MSG_HASH(MSG_ERROR_SAVING_REMAP_FILE,
      "無法儲存 remap 檔案.")
MSG_HASH(MSG_ERROR_SAVING_SHADER_PRESET,
      "無法儲存預置 shader.")
MSG_HASH(MSG_EXTERNAL_APPLICATION_DIR,
      "外部應用程序目錄")
MSG_HASH(MSG_EXTRACTING,
      "正在解壓")
MSG_HASH(MSG_EXTRACTING_FILE,
      "解壓文件")
MSG_HASH(MSG_FAILED_SAVING_CONFIG_TO,
      "無法儲存設定到")
MSG_HASH(MSG_FAILED_TO,
      "執行失敗")
MSG_HASH(MSG_FAILED_TO_ACCEPT_INCOMING_SPECTATOR,
      "無法讓觀眾加入.")
MSG_HASH(MSG_FAILED_TO_ALLOCATE_MEMORY_FOR_PATCHED_CONTENT,
      "無法配置記憶體給已俢改的遊戲")
MSG_HASH(MSG_FAILED_TO_APPLY_SHADER,
      "無法載入 shader.")
MSG_HASH(MSG_FAILED_TO_BIND_SOCKET,
      "無法連接通訊埠.")
MSG_HASH(MSG_FAILED_TO_CREATE_THE_DIRECTORY,
      "創建目錄失敗。")
MSG_HASH(MSG_FAILED_TO_EXTRACT_CONTENT_FROM_COMPRESSED_FILE,
      "從壓縮文件中提取內容失敗")
MSG_HASH(MSG_FAILED_TO_GET_NICKNAME_FROM_CLIENT,
      "從客戶端獲取暱稱失敗.")
MSG_HASH(MSG_FAILED_TO_LOAD,
      "無法戴入")
MSG_HASH(MSG_FAILED_TO_LOAD_CONTENT,
      "載入內容失敗")
MSG_HASH(MSG_FAILED_TO_LOAD_MOVIE_FILE,
      "載入視訊文件失敗")
MSG_HASH(MSG_FAILED_TO_LOAD_OVERLAY,
      "無法戴入 overlay.")
MSG_HASH(MSG_FAILED_TO_LOAD_STATE,
      "無法戴入 state ")
MSG_HASH(MSG_FAILED_TO_OPEN_LIBRETRO_CORE,
      "打開libretro核心失敗")
MSG_HASH(MSG_FAILED_TO_PATCH,
      "補丁應用失敗")
MSG_HASH(MSG_FAILED_TO_RECEIVE_HEADER_FROM_CLIENT,
      "無法接收連線端的資訊")
MSG_HASH(MSG_FAILED_TO_RECEIVE_NICKNAME,
      "無法接收暱稱.")
MSG_HASH(MSG_FAILED_TO_RECEIVE_NICKNAME_FROM_HOST,
      "無法接收主控端的暱稱.")
MSG_HASH(MSG_FAILED_TO_RECEIVE_NICKNAME_SIZE_FROM_HOST,
      "無法接收主控端的暱稱大小.")
MSG_HASH(MSG_FAILED_TO_RECEIVE_SRAM_DATA_FROM_HOST,
      "無法接收主控端 SRAM 資料.")
MSG_HASH(MSG_FAILED_TO_REMOVE_DISK_FROM_TRAY,
      "移除光碟失敗.")
MSG_HASH(MSG_FAILED_TO_REMOVE_TEMPORARY_FILE,
      "移除臨時文件失敗")
MSG_HASH(MSG_FAILED_TO_SAVE_SRAM,
      "SRAM 存檔失敗")
MSG_HASH(MSG_FAILED_TO_SAVE_STATE_TO,
      "即時存檔儲存失敗")
MSG_HASH(MSG_FAILED_TO_SEND_NICKNAME,
      "發送暱稱失敗.")
MSG_HASH(MSG_FAILED_TO_SEND_NICKNAME_SIZE,
      "發送暱稱尺寸失敗.")
MSG_HASH(MSG_FAILED_TO_SEND_NICKNAME_TO_CLIENT,
      "發送暱稱至客戶端失敗.")
MSG_HASH(MSG_FAILED_TO_SEND_NICKNAME_TO_HOST,
      "發送暱稱至主控端失敗.")
MSG_HASH(MSG_FAILED_TO_SEND_SRAM_DATA_TO_CLIENT,
      "發送SRAM數據至客戶端失敗.")
MSG_HASH(MSG_FAILED_TO_START_AUDIO_DRIVER,
      "聲音驅動啟動失敗，將在無聲音模式下繼續啟動。")
MSG_HASH(MSG_FAILED_TO_START_MOVIE_RECORD,
      "啟動視訊錄製失敗.")
MSG_HASH(MSG_FAILED_TO_START_RECORDING,
      "建用錄製視訊失敗.")
MSG_HASH(MSG_FAILED_TO_TAKE_SCREENSHOT,
      "營幕快照失敗.")
MSG_HASH(MSG_FAILED_TO_UNDO_LOAD_STATE,
      "還原載入即時存檔失敗")
MSG_HASH(MSG_FAILED_TO_UNDO_SAVE_STATE,
      "還原即時存檔失敗")
MSG_HASH(MSG_FAILED_TO_UNMUTE_AUDIO,
      "還原取消靜音失敗")
MSG_HASH(MSG_FATAL_ERROR_RECEIVED_IN,
      "接收資料時發生錯誤")
MSG_HASH(MSG_FILE_NOT_FOUND,
      "未找到文件")
MSG_HASH(MSG_FOUND_AUTO_SAVESTATE_IN,
      "找到自動存檔")
MSG_HASH(MSG_FOUND_DISK_LABEL,
      "找到磁碟標籤")
MSG_HASH(MSG_FOUND_FIRST_DATA_TRACK_ON_FILE,
      "在文件中找到第一個資料軌道")
MSG_HASH(MSG_FOUND_LAST_STATE_SLOT,
      "找到最後一個狀態槽")
MSG_HASH(MSG_FOUND_SHADER,
      "找到 shader")
MSG_HASH(MSG_FRAMES,
      "幀")
MSG_HASH(MSG_GAME_SPECIFIC_CORE_OPTIONS_FOUND_AT,
      "Per-Game Options: 找到特定遊戲的設定檔案")
MSG_HASH(MSG_GOT_INVALID_DISK_INDEX,
      "錯誤的磁碟索引")
MSG_HASH(MSG_GRAB_MOUSE_STATE,
      "抓取鼠標狀態")
MSG_HASH(MSG_GAME_FOCUS_ON,
      "打開遊戲焦點")
MSG_HASH(MSG_GAME_FOCUS_OFF,
      "取消遊戲焦點")
MSG_HASH(MSG_INFLATED_CHECKSUM_DID_NOT_MATCH_CRC32,
      "比較檔案 CRC32 錯誤.")
MSG_HASH(MSG_INPUT_CHEAT,
      "輸入金手指")
MSG_HASH(MSG_INPUT_CHEAT_FILENAME,
      "金手指檔案")
MSG_HASH(MSG_INPUT_PRESET_FILENAME,
      "目前檔案")
MSG_HASH(MSG_INPUT_RENAME_ENTRY,
      "變更 Title 名稱")
MSG_HASH(MSG_INTERFACE,
      "接口")
MSG_HASH(MSG_INTERNAL_STORAGE,
      "內部存儲")
MSG_HASH(MSG_REMOVABLE_STORAGE,
      "可移除的儲存空間")
MSG_HASH(MSG_INVALID_NICKNAME_SIZE,
      "不合法暱稱大小.")
MSG_HASH(MSG_IN_BYTES,
      "(字節)")
MSG_HASH(MSG_IN_GIGABYTES,
      "(吉字節)")
MSG_HASH(MSG_IN_MEGABYTES,
      "(兆字節)")
MSG_HASH(MSG_LIBRETRO_ABI_BREAK,
      "libretro 版本錯誤.")
MSG_HASH(MSG_LIBRETRO_FRONTEND,
      "為libretro而設計的前端")
MSG_HASH(MSG_LOADED_STATE_FROM_SLOT,
      "戴入狀態從槽 #%d.")
MSG_HASH(MSG_LOADED_STATE_FROM_SLOT_AUTO,
      "戴入狀態從槽 #-1 (auto).")
MSG_HASH(MSG_LOADING,
      "正在戴入")
MSG_HASH(MSG_FIRMWARE,
      "一個或多個固件文件丟失")
MSG_HASH(MSG_LOADING_CONTENT_FILE,
      "正在戴入內容文件")
MSG_HASH(MSG_LOADING_HISTORY_FILE,
      "正在讀取歷史文件")
MSG_HASH(MSG_LOADING_STATE,
      "正在讀取存檔")
MSG_HASH(MSG_MEMORY,
      "內存")
MSG_HASH(MSG_MOVIE_FILE_IS_NOT_A_VALID_BSV1_FILE,
      "視訊不是有效的BSV1文件。")
MSG_HASH(MSG_MOVIE_FORMAT_DIFFERENT_SERIALIZER_VERSION,
      "視訊格式看起來使用了不同的序列化版本。很有可能失敗。")
MSG_HASH(MSG_MOVIE_PLAYBACK_ENDED,
      "視訊回放結束.")
MSG_HASH(MSG_MOVIE_RECORD_STOPPED,
      "停止視訊錄製。")
MSG_HASH(MSG_NETPLAY_FAILED,
      "初始化連線遊戲失敗。")
MSG_HASH(MSG_NO_CONTENT_STARTING_DUMMY_CORE,
      "沒有內容，啟動虛擬核心。")
MSG_HASH(MSG_NO_SAVE_STATE_HAS_BEEN_OVERWRITTEN_YET,
      "未覆蓋任何存檔。")
MSG_HASH(MSG_NO_STATE_HAS_BEEN_LOADED_YET,
      "沒有戴入任何存檔。")
MSG_HASH(MSG_OVERRIDES_ERROR_SAVING,
      "儲存覆蓋錯誤。")
MSG_HASH(MSG_OVERRIDES_SAVED_SUCCESSFULLY,
      "覆蓋儲存成功。")
MSG_HASH(MSG_PAUSED,
      "暫停。")
MSG_HASH(MSG_PROGRAM,
      "RetroArch")
MSG_HASH(MSG_READING_FIRST_DATA_TRACK,
      "讀取第一條數據軌...")
MSG_HASH(MSG_RECEIVED,
      "接收完畢")
MSG_HASH(MSG_RECORDING_TERMINATED_DUE_TO_RESIZE,
      "錄製因改變大小而停止。")
MSG_HASH(MSG_RECORDING_TO,
      "錄製到")
MSG_HASH(MSG_REDIRECTING_CHEATFILE_TO,
      "重定向金手指文件至")
MSG_HASH(MSG_REDIRECTING_SAVEFILE_TO,
      "重新轉向 save file to")
MSG_HASH(MSG_REDIRECTING_SAVESTATE_TO,
      "重新轉向 savestate to")
MSG_HASH(MSG_REMAP_FILE_SAVED_SUCCESSFULLY,
      "Remap file 儲存成功.")
MSG_HASH(MSG_REMOVED_DISK_FROM_TRAY,
      "從托盤中取出光磁.")
MSG_HASH(MSG_REMOVING_TEMPORARY_CONTENT_FILE,
      "移除臨時內容文件")
MSG_HASH(MSG_RESET,
      "重置")
MSG_HASH(MSG_RESTARTING_RECORDING_DUE_TO_DRIVER_REINIT,
      "重啟錄製由於驅動器重新初始化。")
MSG_HASH(MSG_RESTORED_OLD_SAVE_STATE,
      "重載舊的存檔。")
MSG_HASH(MSG_RESTORING_DEFAULT_SHADER_PRESET_TO,
      "Shaders: 重設預設 shader ")
MSG_HASH(MSG_REWINDING,
      "正在回溯。")
MSG_HASH(MSG_REWIND_INIT,
      "初始化 rewind 緩衝")
MSG_HASH(MSG_REWIND_INIT_FAILED,
      "初始化回放緩存失敗. 回放功能關閉.")
MSG_HASH(MSG_REWIND_INIT_FAILED_THREADED_AUDIO,
      "無法使用 rewind 功能。因為當前正使用 threaded audio.")
MSG_HASH(MSG_REWIND_REACHED_END,
      "到達回放緩存末端.")
MSG_HASH(MSG_SAVED_NEW_CONFIG_TO,
      "已儲存新設定到")
MSG_HASH(MSG_SAVED_STATE_TO_SLOT,
      "儲存狀態至槽 #%d.")
MSG_HASH(MSG_SAVED_STATE_TO_SLOT_AUTO,
      "儲存狀態至槽 #-1 (auto).")
MSG_HASH(MSG_SAVED_SUCCESSFULLY_TO,
      "成功儲存至")
MSG_HASH(MSG_SAVING_RAM_TYPE,
      "儲存 RAM 類型")
MSG_HASH(MSG_SAVING_STATE,
      "存檔中")
MSG_HASH(MSG_SCANNING,
      "掃瞄中")
MSG_HASH(MSG_SCANNING_OF_DIRECTORY_FINISHED,
      "已完成對文件夾的掃瞄")
MSG_HASH(MSG_SENDING_COMMAND,
      "發送指令")
MSG_HASH(MSG_SKIPPING_SRAM_LOAD,
      "跳過 SRAM 戴入。")
MSG_HASH(MSG_SLOW_MOTION,
      "慢動作。")
MSG_HASH(MSG_FAST_FORWARD,
      "快進。")
MSG_HASH(MSG_SLOW_MOTION_REWIND,
      "慢動作回溯。")
MSG_HASH(MSG_SRAM_WILL_NOT_BE_SAVED,
      "SRAM 將不會被儲存.")
MSG_HASH(MSG_STARTING_MOVIE_PLAYBACK,
      "視訊回放.")
MSG_HASH(MSG_STARTING_MOVIE_RECORD_TO,
      "Starting movie record to")
MSG_HASH(MSG_STATE_SIZE,
      "即時存檔大小")
MSG_HASH(MSG_STATE_SLOT,
      "狀態存檔槽")
MSG_HASH(MSG_TAKING_SCREENSHOT,
      "截屏。")
MSG_HASH(MSG_TO,
      "到")
MSG_HASH(MSG_UNDID_LOAD_STATE,
      "已撤銷戴入狀態。")
MSG_HASH(MSG_UNDOING_SAVE_STATE,
      "撤銷即時存檔")
MSG_HASH(MSG_UNKNOWN,
      "未知")
MSG_HASH(MSG_UNPAUSED,
      "取消暫停。")
MSG_HASH(MSG_UNRECOGNIZED_COMMAND,
      "無法識別的指令")
MSG_HASH(MSG_USING_CORE_NAME_FOR_NEW_CONFIG,
      "使用核心模擬器名稱當新的設定檔名稱")
MSG_HASH(MSG_USING_LIBRETRO_DUMMY_CORE_RECORDING_SKIPPED,
      "使用libretro虛擬核心。跳過錄製。")
MSG_HASH(MSG_VALUE_DISCONNECTING_DEVICE_FROM_PORT,
      "從端口斷開設備")
MSG_HASH(MSG_VALUE_REBOOTING,
      "正在重啟……")
MSG_HASH(MSG_VALUE_SHUTTING_DOWN,
      "正在關機……")
MSG_HASH(MSG_VERSION_OF_LIBRETRO_API,
      "libretro API 版本")
MSG_HASH(MSG_VIEWPORT_SIZE_CALCULATION_FAILED,
      "Viewport size calculation failed! Will continue using raw data. This will probably not work right ...")
MSG_HASH(MSG_VIRTUAL_DISK_TRAY,
      "virtual disk tray.")
MSG_HASH(MENU_ENUM_SUBLABEL_AUDIO_LATENCY,
      "設定您想要的聲音延遲(毫秒). 假設預設的裝置無法支援設定值時該值可能無法成功套用.")
MSG_HASH(MENU_ENUM_SUBLABEL_AUDIO_MUTE,
      "禁音/取消禁音。")
MSG_HASH(
      MENU_ENUM_SUBLABEL_CAMERA_ALLOW,
      "允許或禁止核心使用攝像頭。"
      )
MSG_HASH(
      MENU_ENUM_SUBLABEL_LOCATION_ALLOW,
      "開啟或取消定位服務"
      )
MSG_HASH(
      MENU_ENUM_SUBLABEL_INPUT_MAX_USERS,
      "RetroArch 最大遊戲支援人數"
      )
MSG_HASH(
      MENU_ENUM_SUBLABEL_INPUT_ALL_USERS_CONTROL_MENU,
      "允許任何使用者去控制選單，如果取消，將只會有1個人可以控制選單."
      )
MSG_HASH(
      MENU_ENUM_SUBLABEL_AUDIO_VOLUME,
      "音量大小 (in dB). 0 dB 是標準大小."
      )
MSG_HASH(
   MENU_ENUM_SUBLABEL_AUDIO_SYNC,
   "同步聲音。推薦。"
   )
MSG_HASH(
   MENU_ENUM_SUBLABEL_VIDEO_VSYNC,
   "同步顯卡的視訊輸出到營幕刷新率。推薦。"
   )
MSG_HASH(
   MENU_ENUM_SUBLABEL_CHECK_FOR_MISSING_FIRMWARE,
   "載入遊戲前檢查必要的韌體/BIOS是否存在."
   )
MSG_HASH(
   MENU_ENUM_SUBLABEL_AUDIO_ENABLE,
   "啟用聲音輸出。"
   )
MSG_HASH(
   MSG_FAILED,
   "已失敗"
   )
MSG_HASH(
   MSG_SUCCEEDED,
   "已成功"
   )
MSG_HASH(
   MSG_DEVICE_NOT_CONFIGURED,
   "未設定"
   )
MSG_HASH(
   MSG_DEVICE_NOT_CONFIGURED_FALLBACK,
   "未設定，將使用內定值"
   )
MSG_HASH(
   MENU_ENUM_LABEL_VALUE_DATABASE_CURSOR_LIST,
   "數據庫 Cursor List"
   )
MSG_HASH(
   MENU_ENUM_LABEL_VALUE_DATABASE_CURSOR_LIST_ENTRY_DEVELOPER,
   "數據庫 - 過濾器 : 開發者"
   )
MSG_HASH(
   MENU_ENUM_LABEL_VALUE_DATABASE_CURSOR_LIST_ENTRY_PUBLISHER,
   "數據庫 - 過濾器 : 發佈者"
   )
MSG_HASH(
   MENU_ENUM_LABEL_VALUE_DISABLED,
   "禁用"
   )
MSG_HASH(
   MENU_ENUM_LABEL_VALUE_ENABLED,
   "啟用"
   )
MSG_HASH(
   MENU_ENUM_LABEL_VALUE_CONTENT_HISTORY_PATH,
   "內容歷史路徑"
   )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_DATABASE_CURSOR_LIST_ENTRY_ORIGIN,
      "數據庫 - 過濾器 : Origin")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DATABASE_CURSOR_LIST_ENTRY_FRANCHISE,
      "數據庫 - 過濾器 : Franchise")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DATABASE_CURSOR_LIST_ENTRY_ESRB_RATING,
      "數據庫 - 過濾器 : ESRB Rating")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DATABASE_CURSOR_LIST_ENTRY_ELSPA_RATING,
      "數據庫 - 過濾器 : ELSPA Rating")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DATABASE_CURSOR_LIST_ENTRY_PEGI_RATING,
      "數據庫 - 過濾器 : PEGI Rating")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DATABASE_CURSOR_LIST_ENTRY_CERO_RATING,
      "數據庫 - 過濾器 : CERO Rating")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DATABASE_CURSOR_LIST_ENTRY_BBFC_RATING,
      "數據庫 - 過濾器 : BBFC Rating")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DATABASE_CURSOR_LIST_ENTRY_MAX_USERS,
      "數據庫 - 過濾器 : 最大用戶數")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DATABASE_CURSOR_LIST_ENTRY_RELEASEDATE_BY_MONTH,
      "數據庫 - 過濾器 : 發行月份")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DATABASE_CURSOR_LIST_ENTRY_RELEASEDATE_BY_YEAR,
      "數據庫 - 過濾器 : 發行年代")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DATABASE_CURSOR_LIST_ENTRY_EDGE_MAGAZINE_ISSUE,
      "數據庫 - 過濾器 : Edge Magazine Issue")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DATABASE_CURSOR_LIST_ENTRY_EDGE_MAGAZINE_RATING,
      "數據庫 - 過濾器 : Edge Magazine Rating")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DATABASE_CURSOR_LIST_ENTRY_DATABASE_INFO,
      "數據庫訊息")
MSG_HASH(MSG_WIFI_SCAN_COMPLETE,
      "Wi-Fi 掃瞄完成。")
MSG_HASH(MSG_SCANNING_WIRELESS_NETWORKS,
      "掃瞄無線網路...")
MSG_HASH(MSG_NETPLAY_LAN_SCAN_COMPLETE,
      "連線遊戲主機掃瞄完成。")
MSG_HASH(MSG_NETPLAY_LAN_SCANNING,
      "掃瞄連線遊戲主機...")
MSG_HASH(MENU_ENUM_SUBLABEL_PAUSE_NONACTIVE,
      "當窗口失去焦點時暫停遊戲。")
MSG_HASH(MENU_ENUM_SUBLABEL_VIDEO_DISABLE_COMPOSITION,
      "Enable or disable composition.")
MSG_HASH(MENU_ENUM_SUBLABEL_HISTORY_LIST_ENABLE,
      "為遊戲、圖片、音樂和視訊啟用/禁用歷史記錄。")
MSG_HASH(MENU_ENUM_SUBLABEL_CONTENT_HISTORY_SIZE,
      "遊戲、圖片、音樂和視訊歷史記錄的數量限制。")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_UNIFIED_MENU_CONTROLS,
      "統一選單控制")
MSG_HASH(MENU_ENUM_SUBLABEL_VIDEO_FONT_ENABLE,
      "顯示營幕消息。")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETWORK_USER_REMOTE_ENABLE,
      "用戶 %d 遠程允許")
MSG_HASH(MENU_ENUM_LABEL_VALUE_BATTERY_LEVEL_ENABLE,
      "顯示電池電量")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SELECT_FILE,
      "選擇文件")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SELECT_FROM_PLAYLIST,
      "從播放列表中選擇")
MSG_HASH(MENU_ENUM_LABEL_VALUE_FILTER,
      "過濾器")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SCALE,
      "刻度")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY_START_WHEN_LOADED,
      "連線遊戲將在內容戴入後開始。")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY_LOAD_CONTENT_MANUALLY,
      "無法找到合適的核心或內容文件，手動戴入。")
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BROWSE_URL_LIST,
      "瀏覽URL"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BROWSE_URL,
      "URL路徑"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BROWSE_START,
      "開始"
      )
MSG_HASH(MENU_ENUM_LABEL_VALUE_SHADER_PIPELINE_BOKEH,
      "Bokeh")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY_REFRESH_ROOMS,
      "更新 Room 列表")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY_ROOM_NICKNAME,
      "暱稱: %s")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY_ROOM_NICKNAME_LAN,
      "暱稱 (lan): %s")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY_COMPAT_CONTENT_FOUND,
      "找到相容遊戲")
MSG_HASH(MENU_ENUM_SUBLABEL_CHEEVOS_USERNAME,
      "輸入Retro Achievements 的帳號.")
MSG_HASH(MENU_ENUM_SUBLABEL_CHEEVOS_PASSWORD,
      "輸入Retro Achievements 的密碼.")
MSG_HASH(MENU_ENUM_SUBLABEL_QUIT_RETROARCH,
      "離開程式.")
MSG_HASH(MENU_ENUM_SUBLABEL_CHEAT_APPLY_CHANGES,
      "金手指一但變更會立該生效.")
MSG_HASH(
      MENU_ENUM_SUBLABEL_CHEAT_FILE_LOAD,
      "載入一個金手指檔案."
      )
MSG_HASH(
      MENU_ENUM_SUBLABEL_CHEAT_FILE_SAVE_AS,
      "儲存目前的金手指."
      )
MSG_HASH(
      MSG_AUDIO_MIXER_VOLUME,
      "全區域混音器聲音大小"
      )
MSG_HASH(
      MENU_ENUM_SUBLABEL_AUDIO_MIXER_VOLUME,
      "全區域混音器聲音大小 (dB). 0 dB 為原始聲音大小。未經過調整."
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUDIO_MIXER_VOLUME,
      "混音器聲音大小(dB)"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUDIO_MIXER_MUTE,
      "混音器 靜音"
      )
MSG_HASH(MENU_ENUM_SUBLABEL_AUDIO_MIXER_MUTE,
      "靜音/取消靜音 混音器.")
MSG_HASH(MENU_ENUM_LABEL_MENU_SHOW_ONLINE_UPDATER,
      "顯示 Online Updater")
MSG_HASH(MENU_ENUM_SUBLABEL_MENU_SHOW_ONLINE_UPDATER,
      "顯示/隱藏 the 'Online Updater' option.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MENU_SHOW_CORE_UPDATER,
      "顯示 Core Updater")
MSG_HASH(MENU_ENUM_SUBLABEL_MENU_SHOW_CORE_UPDATER,
      "顯示/隱藏 the ability to update cores (and core info files).")
MSG_HASH(MSG_PREPARING_FOR_CONTENT_SCAN,
      "正準備掃描內容...")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_DELETE,
      "刪除模擬程式(core)")
MSG_HASH(MENU_ENUM_SUBLABEL_CORE_DELETE,
      "從磁碟搬移模擬程式(core).")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RENAME_ENTRY,
      "變更此筆資料的名稱.")
MSG_HASH(MENU_ENUM_LABEL_RENAME_ENTRY,
      "更名")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MENU_FRAMEBUFFER_OPACITY,
      "Framebuffer 透明度")
MSG_HASH(MENU_ENUM_SUBLABEL_MENU_FRAMEBUFFER_OPACITY,
      "修改framebuffer 透明度.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_GOTO_FAVORITES,
      "我的最愛")
MSG_HASH(MENU_ENUM_SUBLABEL_GOTO_FAVORITES,
      "先前加入至『我的最愛』的遊戲內容將會出現在這裡.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_GOTO_MUSIC,
      "音樂")
MSG_HASH(MENU_ENUM_SUBLABEL_GOTO_MUSIC,
      "先前播放的音樂將會出現在這裡.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_GOTO_IMAGES,
      "圖片")
MSG_HASH(MENU_ENUM_SUBLABEL_GOTO_IMAGES,
      "先前觀看的圖片將會出現在這裡.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_GOTO_VIDEO,
      "視訊")
MSG_HASH(MENU_ENUM_SUBLABEL_GOTO_VIDEO,
      "先前遊玩的影像將會出現在這裡.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MATERIALUI_ICONS_ENABLE,
      "Menu Icons")
MSG_HASH(MENU_ENUM_SUBLABEL_MATERIALUI_ICONS_ENABLE,
      "開啟/取消 the menu icons shown at the lefthand side of the menu entries.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_MAIN_MENU_ENABLE_SETTINGS,
      "開啟 Settings Tab")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CONTENT_SHOW_SETTINGS_PASSWORD,
      "設定開啟 Settings Tab 的密碼")
MSG_HASH(MSG_INPUT_ENABLE_SETTINGS_PASSWORD,
      "請輸入密碼")
MSG_HASH(MSG_INPUT_ENABLE_SETTINGS_PASSWORD_OK,
      "密碼正確")
MSG_HASH(MSG_INPUT_ENABLE_SETTINGS_PASSWORD_NOK,
      "密碼錯誤")
MSG_HASH(MENU_ENUM_SUBLABEL_XMB_MAIN_MENU_ENABLE_SETTINGS,
      "開啟 Settings tab. 必需重開機")
MSG_HASH(MENU_ENUM_SUBLABEL_CONTENT_SHOW_SETTINGS_PASSWORD,
      "請輸入隱藏 settings tab 的密碼。事後可在選項中取消")
MSG_HASH(MENU_ENUM_SUBLABEL_PLAYLIST_ENTRY_RENAME,
      "Allow the user to rename entries in playlists.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_PLAYLIST_ENTRY_RENAME,
      "Allow to rename entries")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MENU_SHOW_LOAD_CORE,
      "顯示 Load Core")
MSG_HASH(MENU_ENUM_SUBLABEL_MENU_SHOW_LOAD_CORE,
      "顯示/隱藏 the 'Load Core' option.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MENU_SHOW_LOAD_CONTENT,
      "顯示 Load Content")
MSG_HASH(MENU_ENUM_SUBLABEL_MENU_SHOW_LOAD_CONTENT,
      "顯示/隱藏 the 'Load Content' option.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MENU_SHOW_INFORMATION,
      "顯示 Information")
MSG_HASH(MENU_ENUM_SUBLABEL_MENU_SHOW_INFORMATION,
      "顯示/隱藏 the 'Information' option.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MENU_SHOW_CONFIGURATIONS,
      "顯示 Configurations")
MSG_HASH(MENU_ENUM_SUBLABEL_MENU_SHOW_CONFIGURATIONS,
      "顯示/隱藏 the 'Configurations' option.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MENU_SHOW_HELP,
      "顯示 Help")
MSG_HASH(MENU_ENUM_SUBLABEL_MENU_SHOW_HELP,
      "顯示/隱藏 the 'Help' option.")
#ifdef HAVE_LAKKA
MSG_HASH(MENU_ENUM_LABEL_VALUE_MENU_SHOW_QUIT_RETROARCH,
      "顯示 Restart RetroArch")
MSG_HASH(MENU_ENUM_SUBLABEL_MENU_SHOW_QUIT_RETROARCH,
      "顯示/隱藏 the 'Restart RetroArch' option.")
#else
MSG_HASH(MENU_ENUM_LABEL_VALUE_MENU_SHOW_QUIT_RETROARCH,
      "顯示 Quit RetroArch")
MSG_HASH(MENU_ENUM_SUBLABEL_MENU_SHOW_QUIT_RETROARCH,
      "顯示/隱藏 the 'Quit RetroArch' option.")
#endif
MSG_HASH(MENU_ENUM_LABEL_VALUE_MENU_SHOW_REBOOT,
      "顯示 Reboot")
MSG_HASH(MENU_ENUM_SUBLABEL_MENU_SHOW_REBOOT,
      "顯示/隱藏 the 'Reboot' option.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MENU_SHOW_SHUTDOWN,
      "顯示 Shutdown")
MSG_HASH(MENU_ENUM_SUBLABEL_MENU_SHOW_SHUTDOWN,
      "顯示/隱藏 the 'Shutdown' option.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_QUICK_MENU_VIEWS_SETTINGS,
      "Quick Menu")
MSG_HASH(MENU_ENUM_SUBLABEL_QUICK_MENU_VIEWS_SETTINGS,
      "顯示 or 隱藏 elements on the Quick Menu screen.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_QUICK_MENU_SHOW_TAKE_SCREENSHOT,
      "顯示 Take Screenshot")
MSG_HASH(MENU_ENUM_SUBLABEL_QUICK_MENU_SHOW_TAKE_SCREENSHOT,
      "顯示/隱藏 the 'Take Screenshot' option.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_QUICK_MENU_SHOW_SAVE_LOAD_STATE,
      "顯示 Save/Load State")
MSG_HASH(MENU_ENUM_SUBLABEL_QUICK_MENU_SHOW_SAVE_LOAD_STATE,
      "顯示/隱藏 the options for saving/loading state.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_QUICK_MENU_SHOW_UNDO_SAVE_LOAD_STATE,
      "顯示 Undo Save/Load State")
MSG_HASH(MENU_ENUM_SUBLABEL_QUICK_MENU_SHOW_UNDO_SAVE_LOAD_STATE,
      "顯示/隱藏 the options for undoing save/load state.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_QUICK_MENU_SHOW_ADD_TO_FAVORITES,
      "顯示 Add to Favorites")
MSG_HASH(MENU_ENUM_SUBLABEL_QUICK_MENU_SHOW_ADD_TO_FAVORITES,
      "顯示/隱藏 the 'Add to Favorites' option.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_QUICK_MENU_SHOW_START_RECORDING,
      "Show Start Recording")
MSG_HASH(MENU_ENUM_SUBLABEL_QUICK_MENU_SHOW_START_RECORDING,
      "Show/hide the 'Start Recording' option.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_QUICK_MENU_SHOW_START_STREAMING,
      "Show Start Streaming")
MSG_HASH(MENU_ENUM_SUBLABEL_QUICK_MENU_SHOW_START_STREAMING,
      "Show/hide the 'Start Streaming' option.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_QUICK_MENU_SHOW_RESET_CORE_ASSOCIATION,
      "Show Reset Core Association")
MSG_HASH(MENU_ENUM_SUBLABEL_QUICK_MENU_SHOW_RESET_CORE_ASSOCIATION,
      "Show/hide the 'Reset Core Association' option.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_QUICK_MENU_SHOW_OPTIONS,
      "顯示 Options")
MSG_HASH(MENU_ENUM_SUBLABEL_QUICK_MENU_SHOW_OPTIONS,
      "顯示/隱藏 the 'Options' option.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_QUICK_MENU_SHOW_CONTROLS,
      "顯示 Controls")
MSG_HASH(MENU_ENUM_SUBLABEL_QUICK_MENU_SHOW_CONTROLS,
      "顯示/隱藏 the 'Controls' option.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_QUICK_MENU_SHOW_CHEATS,
      "顯示 Cheats")
MSG_HASH(MENU_ENUM_SUBLABEL_QUICK_MENU_SHOW_CHEATS,
      "顯示/隱藏 the 'Cheats' option.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_QUICK_MENU_SHOW_SHADERS,
      "顯示 Shaders")
MSG_HASH(MENU_ENUM_SUBLABEL_QUICK_MENU_SHOW_SHADERS,
      "顯示/隱藏 the 'Shaders' option.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_QUICK_MENU_SHOW_SAVE_CORE_OVERRIDES,
      "顯示 Save Core Overrides")
MSG_HASH(MENU_ENUM_SUBLABEL_QUICK_MENU_SHOW_SAVE_CORE_OVERRIDES,
      "顯示/隱藏 the 'Save Core Overrides' option.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_QUICK_MENU_SHOW_SAVE_GAME_OVERRIDES,
      "顯示 Save Game Overrides")
MSG_HASH(MENU_ENUM_SUBLABEL_QUICK_MENU_SHOW_SAVE_GAME_OVERRIDES,
      "顯示/隱藏 the 'Save Game Overrides' option.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_QUICK_MENU_SHOW_INFORMATION,
      "顯示 Information")
MSG_HASH(MENU_ENUM_SUBLABEL_QUICK_MENU_SHOW_INFORMATION,
      "顯示/隱藏 the 'Information' option.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MENU_DISABLE_KIOSK_MODE,
      "取消 Kiosk 模式")
MSG_HASH(MENU_ENUM_SUBLABEL_MENU_DISABLE_KIOSK_MODE,
      "取消 kiosk 模式. 需重機器.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MENU_ENABLE_KIOSK_MODE,
      "開啟 Kiosk 模式")
MSG_HASH(MENU_ENUM_SUBLABEL_MENU_ENABLE_KIOSK_MODE,
      "隱藏相關設定")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MENU_KIOSK_MODE_PASSWORD,
      "設定取消 Kiosk 模式的密碼")
MSG_HASH(MENU_ENUM_SUBLABEL_MENU_KIOSK_MODE_PASSWORD,
      "設定開啟 Kiosk 模式的密碼.事後可在選項中取消.")
MSG_HASH(MSG_INPUT_KIOSK_MODE_PASSWORD,
      "Enter Password")
MSG_HASH(MSG_INPUT_KIOSK_MODE_PASSWORD_OK,
      "密碼正確")
MSG_HASH(MSG_INPUT_KIOSK_MODE_PASSWORD_NOK,
      "密碼錯誤")
MSG_HASH(MENU_ENUM_LABEL_VALUE_AUTOMATICALLY_ADD_CONTENT_TO_PLAYLIST,
      "自動增加遊戲內容至 playlist")
MSG_HASH(MENU_ENUM_SUBLABEL_AUTOMATICALLY_ADD_CONTENT_TO_PLAYLIST,
      "Automatically scans loaded content so they appear inside playlists.")
MSG_HASH(MSG_SCANNING_OF_FILE_FINISHED,
      "掃瞄檔案結束")
MSG_HASH(MENU_ENUM_LABEL_VALUE_AUDIO_RESAMPLER_QUALITY,
      "聲音重採樣器品質")
MSG_HASH(MENU_ENUM_LABEL_VALUE_STATISTICS_SHOW,
      "顯示統計數字")
MSG_HASH(MENU_ENUM_SUBLABEL_STATISTICS_SHOW,
      "在畫面中顯示技術資訊.")
MSG_HASH(
    MENU_ENUM_LABEL_VALUE_CRT_SWITCH_X_AXIS_CENTERING,
    "X-Axis 校正中"
    )
MSG_HASH(
      MENU_ENUM_SUBLABEL_CRT_SWITCH_RESOLUTION_USE_CUSTOM_REFRESH_RATE,
      "必要時使用設定檔中的自定更新頻率")
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CRT_SWITCH_RESOLUTION_USE_CUSTOM_REFRESH_RATE,
      "使用自定更新頻率")
MSG_HASH(
    MENU_ENUM_LABEL_VALUE_QUICK_MENU_START_RECORDING,
    "開始錄製"
    )
MSG_HASH(
    MENU_ENUM_SUBLABEL_QUICK_MENU_START_RECORDING,
    "開始錄製"
    )
MSG_HASH(
    MENU_ENUM_LABEL_VALUE_QUICK_MENU_STOP_RECORDING,
    "停止錄製"
    )
MSG_HASH(
    MENU_ENUM_SUBLABEL_QUICK_MENU_STOP_RECORDING,
    "停止錄製"
    )
MSG_HASH(
    MENU_ENUM_LABEL_VALUE_QUICK_MENU_START_STREAMING,
    "開始串流"
    )
MSG_HASH(
    MENU_ENUM_SUBLABEL_QUICK_MENU_START_STREAMING,
    "開始串流"
    )
MSG_HASH(
    MENU_ENUM_LABEL_VALUE_QUICK_MENU_STOP_STREAMING,
    "停止串流"
    )
MSG_HASH(
    MENU_ENUM_SUBLABEL_QUICK_MENU_STOP_STREAMING,
    "停止串流"
    )
MSG_HASH(
    MENU_ENUM_LABEL_VALUE_INPUT_META_RECORDING_TOGGLE,
    "錄製開關"
    )
MSG_HASH(
    MENU_ENUM_LABEL_VALUE_INPUT_META_STREAMING_TOGGLE,
    "串流開關"
    )
MSG_HASH(
    MENU_ENUM_LABEL_VALUE_VIDEO_RECORD_QUALITY,
    "錄製品質"
    )
MSG_HASH(
    MENU_ENUM_LABEL_VALUE_VIDEO_STREAM_QUALITY,
    "串流品質"
    )
MSG_HASH(
    MENU_ENUM_LABEL_VALUE_STREAMING_URL,
    "串流 URL"
    )
MSG_HASH(
    MENU_ENUM_LABEL_VALUE_UDP_STREAM_PORT,
    "UDP 串流 Port"
    )
MSG_HASH(MENU_ENUM_LABEL_VALUE_TWITCH_STREAM_KEY,
      "Twitch 串流 Key")
MSG_HASH(MENU_ENUM_LABEL_VALUE_YOUTUBE_STREAM_KEY,
      "YouTube 串流 Key")
MSG_HASH(MENU_ENUM_LABEL_VALUE_STREAMING_MODE,
      "串流模式")
MSG_HASH(MENU_ENUM_LABEL_VALUE_STREAMING_TITLE,
      "串流名稱")
MSG_HASH(MENU_ENUM_LABEL_VALUE_OZONE_MENU_COLOR_THEME,
      "選單顏色主題")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DELETE_PLAYLIST,
      "刪除播放清單")
