/* THIS FILE IS GENERATED by intl/json2h.py - do not edit.
 * Packed message table; source of truth is the Crowdin
 * project (see intl/crowdin_sync.py). */
#if defined(_MSC_VER) && !defined(_XBOX) && (_MSC_VER >= 1500 && _MSC_VER < 1900)
#if (_MSC_VER >= 1700)
/* https://support.microsoft.com/en-us/kb/980263 */
#pragma execution_character_set("utf-8")
#endif
#pragma warning(disable:4566)
#endif

static const struct
{
   char s0[22];
   char s1[34];
   char s2[22];
   char s3[19];
   char s4[22];
   char s5[56];
   char s6[44];
   char s7[56];
   char s8[22];
   char s9[64];
   char s10[19];
   char s11[41];
   char s12[13];
   char s13[34];
   char s14[19];
   char s15[22];
   char s16[22];
   char s17[22];
   char s18[19];
   char s19[22];
   char s20[19];
   char s21[22];
   char s22[13];
#ifdef HAVE_LAKKA
#ifdef HAVE_RETROFLAG
   char s23[77];
   char s24[125];
#endif
#endif
} msg_hash_si_blob =
{
   "සැකසුම්",
   "ප්‍රියතමයන්",
   "ඉතිහාසය",
   "සංගීතය",
   "දෘශ්‍යක",
   "අන්තර්ගතය ආයාතකරන්න",
   "අන්තර්ගතය පූරණය",
   "අන්තර්ගතය ආයාතකරන්න",
   "සැකසුම්",
   "වැඩසටහන වින්‍යාස කරන්න.",
   "තොරතුර",
   "වින්‍යාස ගොනුව",
   "උදව්",
   "ප්‍රියතමයන්",
   "සංගීතය",
   "දෘශ්‍යක",
   "සැකසුම්",
   "ඉතිහාසය",
   "තොරතුර",
   "සැකසුම්",
   "තොරතුර",
   "ඉතිහාසය",
   "උදව්",
#ifdef HAVE_LAKKA
#ifdef HAVE_RETROFLAG
   "Retroflag Safe Shutdown\"\n#else\n   \"Retroflag Safe Shutdown (Reboot required)",
   "For use with compatible Retroflag case.\"\n#else\n   \"For use with compatible Retroflag case. Reboot is required when changing.",
#endif
#endif
};

/* Contiguity check: char members have alignment 1, so any
 * compiler that pads this struct fails here instead of
 * misindexing at runtime. */
typedef char msg_hash_si_blob_check[
      (sizeof(msg_hash_si_blob) == (648u
#ifdef HAVE_LAKKA
#ifdef HAVE_RETROFLAG
       + 77u
       + 125u
#endif
#endif
      )) ? 1 : -1];

static const uint32_t msg_hash_si_ids[] =
{
   (uint32_t)MENU_ENUM_LABEL_VALUE_SETTINGS_TAB,
   (uint32_t)MENU_ENUM_LABEL_VALUE_FAVORITES_TAB,
   (uint32_t)MENU_ENUM_LABEL_VALUE_HISTORY_TAB,
   (uint32_t)MENU_ENUM_LABEL_VALUE_MUSIC_TAB,
   (uint32_t)MENU_ENUM_LABEL_VALUE_VIDEO_TAB,
   (uint32_t)MENU_ENUM_LABEL_VALUE_ADD_TAB,
   (uint32_t)MENU_ENUM_LABEL_VALUE_LOAD_CONTENT_LIST,
   (uint32_t)MENU_ENUM_LABEL_VALUE_ADD_CONTENT_LIST,
   (uint32_t)MENU_ENUM_LABEL_VALUE_SETTINGS,
   (uint32_t)MENU_ENUM_SUBLABEL_SETTINGS,
   (uint32_t)MENU_ENUM_LABEL_VALUE_INFORMATION_LIST,
   (uint32_t)MENU_ENUM_LABEL_VALUE_CONFIGURATIONS_LIST,
   (uint32_t)MENU_ENUM_LABEL_VALUE_HELP_LIST,
   (uint32_t)MENU_ENUM_LABEL_VALUE_GOTO_FAVORITES,
   (uint32_t)MENU_ENUM_LABEL_VALUE_GOTO_MUSIC,
   (uint32_t)MENU_ENUM_LABEL_VALUE_GOTO_VIDEO,
   (uint32_t)MENU_ENUM_LABEL_VALUE_SETTINGS_VIEWS_SETTINGS,
   (uint32_t)MENU_ENUM_LABEL_VALUE_HISTORY_LIST_ENABLE,
   (uint32_t)MENU_ENUM_LABEL_VALUE_INFORMATION,
   (uint32_t)MENU_ENUM_LABEL_VALUE_QT_MENU_VIEW_OPTIONS_TITLE,
   (uint32_t)MENU_ENUM_LABEL_VALUE_QT_INFORMATION,
   (uint32_t)MENU_ENUM_LABEL_VALUE_LOAD_CONTENT_HISTORY,
   (uint32_t)MENU_ENUM_LABEL_VALUE_HELP,
#ifdef HAVE_LAKKA
#ifdef HAVE_RETROFLAG
   (uint32_t)MENU_ENUM_LABEL_VALUE_SAFESHUTDOWN_ENABLE,
   (uint32_t)MENU_ENUM_SUBLABEL_SAFESHUTDOWN_ENABLE,
#endif
#endif
};
