MSG_HASH(
      MSG_COMPILER,
      "Compilateur"
      )
MSG_HASH(
      MSG_UNKNOWN_COMPILER,
      "Compilateur inconnu"
      )
MSG_HASH(
      MSG_DEVICE_DISCONNECTED_FROM_PORT,
      "Périphérique déconnecté (du port si 'port X')"
      )
MSG_HASH(
      MSG_UNKNOWN_NETPLAY_COMMAND_RECEIVED,
      "Unknown netplay command received"
      )
MSG_HASH(
      MSG_FILE_ALREADY_EXISTS_SAVING_TO_BACKUP_BUFFER,
      "File already exists. Saving to backup buffer"
      )
MSG_HASH(
      MSG_GOT_CONNECTION_FROM,
      "Got connection from: \"%s\""
      )
MSG_HASH(
      MSG_GOT_CONNECTION_FROM_NAME,
      "Got connection from: \"%s (%s)\""
      )
MSG_HASH(
      MSG_NO_ARGUMENTS_SUPPLIED_AND_NO_MENU_BUILTIN,
      "No arguments supplied and no menu builtin, displaying help..."
      )
MSG_HASH(
      MSG_NETPLAY_USERS_HAS_FLIPPED,
      "Netplay users has flipped"
      )
MSG_HASH(
      MSG_SETTING_DISK_IN_TRAY,
      "Setting disk in tray"
      )
MSG_HASH(
      MSG_WAITING_FOR_CLIENT,
      "En attente du client..."
      )
MSG_HASH(
      MENU_ENUM_SUBLABEL_VIDEO_SHARED_CONTEXT,
      "Give hardware-rendered cores their own private context. Avoids having to assume hardware state changes inbetween frames."
      )
MSG_HASH(
      MENU_ENUM_SUBLABEL_MENU_SETTINGS,
      "Ajuste les réglages liés à l'apparence de l'écran de menu."
      )
MSG_HASH(
      MENU_ENUM_SUBLABEL_VIDEO_HARD_SYNC,
      "Synchronisation 'hard' du CPU et du GPU. Réduit la latence au prix de la performance."
      )
MSG_HASH(
      MENU_ENUM_SUBLABEL_VIDEO_THREADED,
      "Améliore les performances au prix d'une certaine latence et d'à-coups visuels accrus. À n'utiliser que si vous ne pouvez pas faire autrement."
      )
MSG_HASH(
      MSG_AUDIO_VOLUME,
      "Volume sonore"
      )
MSG_HASH(
      MSG_AUTODETECT,
      "Détection automatique"
      )
MSG_HASH(
      MSG_AUTOLOADING_SAVESTATE_FROM,
      "Chargement auto d'une savestate depuis"
      )
MSG_HASH(
      MSG_CAPABILITIES,
      "Capacités"
      )
MSG_HASH(
      MSG_CONNECTING_TO_NETPLAY_HOST,
      "Connexion à l'hôte"
      )
MSG_HASH(
      MSG_CONNECTING_TO_PORT,
      "Connexion au port"
      )
MSG_HASH(
      MSG_CONNECTION_SLOT,
      "Slot de connexion"
      )
MSG_HASH(
      MSG_SORRY_UNIMPLEMENTED_CORES_DONT_DEMAND_CONTENT_NETPLAY,
      "Sorry, unimplemented: cores that don't demand content cannot participate in netplay."
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_ACCOUNTS_CHEEVOS_PASSWORD,
      "Mot de passe"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_ACCOUNTS_CHEEVOS_SETTINGS,
      "Accounts Cheevos"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_ACCOUNTS_CHEEVOS_USERNAME,
      "Nom d'utilisateur"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_ACCOUNTS_LIST,
      "Comptes en ligne"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_ACCOUNTS_LIST_END,
      "Accounts List Endpoint"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_ACCOUNTS_RETRO_ACHIEVEMENTS,
      "Succès Retro"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_ACHIEVEMENT_LIST,
      "Liste des Succès"
      )

MSG_HASH(
      MENU_ENUM_LABEL_VALUE_ACHIEVEMENT_LIST_HARDCORE,
      "Liste des Succès (hardcore)"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_ADD_CONTENT_LIST,
      "Ajouter du contenu"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CONFIGURATIONS_LIST,
      "Charger une configuration"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_ADD_TAB,
      "Scanner"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_ASK_ARCHIVE,
      "Demander"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_ASSETS_DIRECTORY,
      "Dossier des assets"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUDIO_BLOCK_FRAMES,
      "Block Frames"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUDIO_DEVICE,
      "Carte son"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUDIO_DRIVER,
      "Pilote audio"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUDIO_DSP_PLUGIN,
      "Module DSP"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUDIO_ENABLE,
      "Activer le son"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUDIO_FILTER_DIR,
      "Dossier des filtres audio"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_TURBO_DEADZONE_LIST,
      "Turbo/Deadzone"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUDIO_LATENCY,
      "Latence audio (ms)"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUDIO_MAX_TIMING_SKEW,
      "Limite max de l'ajustement"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUDIO_MUTE,
      "Muet"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUDIO_OUTPUT_RATE,
      "Fréquence de sortie (Hz)"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUDIO_RATE_CONTROL_DELTA,
      "Delta du taux de contrôle"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUDIO_RESAMPLER_DRIVER,
      "Pilote de ré-échantillonage audio"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUDIO_SETTINGS,
      "Audio"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUDIO_SYNC,
      "Synchroniser le son"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUDIO_VOLUME,
      "Volume sonore (dB)"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUTOSAVE_INTERVAL,
      "Intervalle de sauvegarde SaveRAM"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUTO_OVERRIDES_ENABLE,
      "Charger les fichiers d'override automatiquement"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUTO_REMAPS_ENABLE,
      "Charger les fichiers remaps automatiquement"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUTO_SHADERS_ENABLE,
      "Charger les pré-réglages de shaders automatiquement"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BASIC_MENU_CONTROLS_BACK,
      "Retour"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BASIC_MENU_CONTROLS_CONFIRM,
      "Confirmer"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BASIC_MENU_CONTROLS_INFO,
      "Information"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BASIC_MENU_CONTROLS_QUIT,
      "Quitter"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BASIC_MENU_CONTROLS_SCROLL_DOWN,
      "Défilement vers le bas"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BASIC_MENU_CONTROLS_SCROLL_UP,
      "Défilement vers le haut"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BASIC_MENU_CONTROLS_START,
      "Démarrer"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BASIC_MENU_CONTROLS_TOGGLE_KEYBOARD,
      "Basculer sur le Clavier"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BASIC_MENU_CONTROLS_TOGGLE_MENU,
      "Basculer sur le Menu"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BASIC_MENU_ENUM_CONTROLS,
      "Contrôles du menu basiques"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BASIC_MENU_ENUM_CONTROLS_CONFIRM,
      "Confirmer / OK"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BASIC_MENU_ENUM_CONTROLS_INFO,
      "Information"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BASIC_MENU_ENUM_CONTROLS_QUIT,
      "Quitter"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BASIC_MENU_ENUM_CONTROLS_SCROLL_UP,
      "Défilement vers le haut"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BASIC_MENU_ENUM_CONTROLS_START,
      "Defaults"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BASIC_MENU_ENUM_CONTROLS_TOGGLE_KEYBOARD,
      "Basculer sur le Klavier"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BASIC_MENU_ENUM_CONTROLS_TOGGLE_MENU,
      "Basculer sur le Menu"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BLOCK_SRAM_OVERWRITE,
      "Ne pas écraser la SaveRAM en chargeant la savestate"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BLUETOOTH_ENABLE,
      "Activer le Bluetooth"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BUILDBOT_ASSETS_URL,
      "URL du buildbot des assets"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CACHE_DIRECTORY,
      "Dossier d'extraction"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CAMERA_ALLOW,
      "Autoriser la caméra"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CAMERA_DRIVER,
      "Pilote de caméra"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CHEAT,
      "Triche"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CHEAT_APPLY_CHANGES,
      "Appliquer les changements"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CHEAT_DATABASE_PATH,
      "Dossier des fichiers de triche"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CHEAT_FILE,
      "Fichier de Triche"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CHEAT_FILE_LOAD,
      "Charger un fichier de Triche"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CHEAT_FILE_SAVE_AS,
      "Enregistrer le fichier de Triche sous"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CHEAT_NUM_PASSES,
      "Nombre de passages"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CHEEVOS_DESCRIPTION,
      "Description"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CHEEVOS_HARDCORE_MODE_ENABLE,
      "Mode Hardcore des Succès"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CHEEVOS_LOCKED_ACHIEVEMENTS,
      "Succès verrouillés:"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CHEEVOS_LOCKED_ENTRY,
      "Verrouillé"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CHEEVOS_SETTINGS,
      "Succès Retro"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CHEEVOS_TEST_UNOFFICIAL,
      "Test Unofficial Achievements"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CHEEVOS_UNLOCKED_ACHIEVEMENTS,
      "Succès déverrouillés:"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CHEEVOS_UNLOCKED_ENTRY,
      "Déverrouillé"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CLOSE_CONTENT,
      "Quitter"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CONFIG,
      "Configuration"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CONFIGURATIONS,
      "Charger la configuration"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CONFIGURATION_SETTINGS,
      "Configurations"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CONFIG_SAVE_ON_EXIT,
      "Sauver la config en quittant"
      )
MSG_HASH(MENU_ENUM_LABEL_VALUE_CONTENT_COLLECTION_LIST,
      "Collections")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CONTENT_DATABASE_DIRECTORY,
      "Dossier des bases de données de contenus")
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CONTENT_DIR,
      "Contenu"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CONTENT_HISTORY_SIZE,
      "Taille de l'historique")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CONTENT_SETTINGS,
      "Menu rapide")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_ASSETS_DIR,
      "Assets de Coeur")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_ASSETS_DIRECTORY,
      "Dossier des téléchargements")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_CHEAT_OPTIONS,
      "Triche")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_COUNTERS,
      "Compteurs de Cores")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_ENABLE,
      "Afficher le coeur actuel")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_INFORMATION,
      "Informations sur le coeur")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_INFO_AUTHORS,
      "Auteurs")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_INFO_CATEGORIES,
      "Catégories")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_INFO_CORE_LABEL,
      "Label")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_INFO_CORE_NAME,
      "Nom")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_INFO_FIRMWARE,
      "Firmware(s)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_INFO_LICENSES,
      "Licence(s)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_INFO_PERMISSIONS,
      "Permissions")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_INFO_SUPPORTED_EXTENSIONS,
      "Extensions supportées")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_INFO_SYSTEM_MANUFACTURER,
      "Fabricant du système")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_INFO_SYSTEM_NAME,
      "Système")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_INPUT_REMAPPING_OPTIONS,
      "Remap d'entrées")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_LIST,
      "Charger un coeur")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_OPTIONS,
      "Options")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_SETTINGS,
      "Coeurs")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_SET_SUPPORTS_NO_CONTENT_ENABLE,
      "Ne pas démarrer de coeur automatiquement")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_UPDATER_AUTO_EXTRACT_ARCHIVE,
      "Extraire automatiquement")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_UPDATER_BUILDBOT_URL,
      "URL du buildbot des coeurs")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_UPDATER_LIST,
      "Mise à jour des coeurs")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_UPDATER_SETTINGS,
      "Mises à jour")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CPU_ARCHITECTURE,
      "CPU Architecture:")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CPU_CORES,
      "CPU Cores:")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CURSOR_DIRECTORY,
      "Dossier des curseurs")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CURSOR_MANAGER,
      "Gestion des curseurs")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CUSTOM_RATIO,
      "Forcer une résolution")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DATABASE_MANAGER,
      "Gestion de la base de données")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DATABASE_SELECTION,
      "Sélection de la base de données")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DELETE_ENTRY,
      "Supprimer")
MSG_HASH(MENU_ENUM_LABEL_VALUE_FAVORITES,
      "Via les fichiers") /* TODO/FIXME - update */
MSG_HASH(MENU_ENUM_LABEL_VALUE_DIRECTORY_CONTENT,
      "<Dossier de contenu>")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DIRECTORY_DEFAULT,
      "<Par défaut>")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DIRECTORY_NONE,
      "<Aucun>")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DIRECTORY_NOT_FOUND,
      "Dossier non trouvé.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DIRECTORY_SETTINGS,
      "Dossiers")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DISK_CYCLE_TRAY_STATUS,
      "État du lecteur de disque")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DISK_IMAGE_APPEND,
      "Ajouter une image de disque")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DISK_INDEX,
      "Numéro du disque")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DISK_OPTIONS,
      "Disques")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DONT_CARE,
      "Peu importe")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DOWNLOADED_FILE_DETECT_CORE_LIST,
      "Via les téléchargements (détecter le coeur)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DOWNLOAD_CORE,
      "Download Core...")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DOWNLOAD_CORE_CONTENT,
      "Télécharger du contenu")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DPI_OVERRIDE_ENABLE,
      "Personnaliser le DPI")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DPI_OVERRIDE_VALUE,
      "Valeur du DPI personnalisé")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DRIVER_SETTINGS,
      "Pilotes")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DUMMY_ON_CORE_SHUTDOWN,
      "Utiliser un faux coeur lorsqu'il n'y en a pas")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DYNAMIC_WALLPAPER,
      "Fond d'écran dynamique")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DYNAMIC_WALLPAPERS_DIRECTORY,
      "Dossier des fonds d'écran dynamiques")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CHEEVOS_ENABLE,
      "Activer les Succès")
MSG_HASH(MENU_ENUM_LABEL_VALUE_ENTRY_HOVER_COLOR,
      "Couleur de l'entrée active")
MSG_HASH(MENU_ENUM_LABEL_VALUE_ENTRY_NORMAL_COLOR,
      "Couleur des entrées du menu")
MSG_HASH(MENU_ENUM_LABEL_VALUE_FALSE,
      "Faux")
MSG_HASH(MENU_ENUM_LABEL_VALUE_FASTFORWARD_RATIO,
      "Vitesse de l'avance rapide")
MSG_HASH(MENU_ENUM_LABEL_VALUE_FPS_SHOW,
      "Afficher les i/s")
MSG_HASH(MENU_ENUM_LABEL_VALUE_FRAME_THROTTLE_ENABLE,
      "Limiter la vitesse d'exécution")
MSG_HASH(MENU_ENUM_LABEL_VALUE_FRAME_THROTTLE_SETTINGS,
      "Vitesse d'affichage")
MSG_HASH(MENU_ENUM_LABEL_VALUE_FRONTEND_COUNTERS,
      "Compteurs du Frontend")
MSG_HASH(MENU_ENUM_LABEL_VALUE_GAME_SPECIFIC_OPTIONS,
      "Options du coeur par jeu")
MSG_HASH(MENU_ENUM_LABEL_VALUE_GAME_SPECIFIC_OPTIONS_CREATE,
      "Créer un fichier d'options par jeu")
MSG_HASH(MENU_ENUM_LABEL_VALUE_GAME_SPECIFIC_OPTIONS_IN_USE,
      "Fichier d'option par jeu")
MSG_HASH(MENU_ENUM_LABEL_VALUE_HELP,
      "Aide")
MSG_HASH(MENU_ENUM_LABEL_VALUE_HELP_AUDIO_VIDEO_TROUBLESHOOTING,
      "Dépannage audio / vidéo")
MSG_HASH(MENU_ENUM_LABEL_VALUE_HELP_CHANGE_VIRTUAL_GAMEPAD,
      "Modifier l'overlay de la manette virtuelle")
MSG_HASH(MENU_ENUM_LABEL_VALUE_HELP_CONTROLS,
      "Contrôles du menu basiques")
MSG_HASH(MENU_ENUM_LABEL_VALUE_HELP_LIST,
      "Aide")
MSG_HASH(MENU_ENUM_LABEL_VALUE_HELP_LOADING_CONTENT,
      "Chargement du contenu")
MSG_HASH(MENU_ENUM_LABEL_VALUE_HELP_SCANNING_CONTENT,
      "Recherche de Contenu")
MSG_HASH(MENU_ENUM_LABEL_VALUE_HELP_WHAT_IS_A_CORE,
      "Qu'est-ce qu'un Core ?")
MSG_HASH(MENU_ENUM_LABEL_VALUE_HISTORY_LIST_ENABLE,
      "Afficher l'historique")
MSG_HASH(MENU_ENUM_LABEL_VALUE_HISTORY_TAB,
      "Historique")
MSG_HASH(MENU_ENUM_LABEL_VALUE_HORIZONTAL_MENU,
      "Menu Horizontal")
MSG_HASH(MENU_ENUM_LABEL_VALUE_IMAGES_TAB,
      "Image")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INFORMATION,
      "Information")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INFORMATION_LIST,
      "Informations")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_ADC_TYPE,
      "Type Analogique vers Numérique")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_ALL_USERS_CONTROL_MENU,
      "Tous les utilisateurs contrôlent le menu")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_LEFT_X,
      "Analogique Gauche X")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_LEFT_X_MINUS,
      "Analogique Gauche X- (gauche)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_LEFT_X_PLUS,
      "Analogique Gauche X+ (droite)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_LEFT_Y,
      "Analogique Gauche Y")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_LEFT_Y_MINUS,
      "Analogique Gauche Y- (haut)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_LEFT_Y_PLUS,
      "Analogique Gauche Y+ (bas)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_RIGHT_X,
      "Analogique Droit X")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_RIGHT_X_MINUS,
      "Analogique Droit X- (gauche)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_RIGHT_X_PLUS,
      "Analogique Droit X+ (droite)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_RIGHT_Y,
      "Analogique Droit Y")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_RIGHT_Y_MINUS,
      "Analogique Droit Y- (haut)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_RIGHT_Y_PLUS,
      "Analogique Droit Y+ (bas)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_AUTODETECT_ENABLE,
      "Activer l'autoconfiguration")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_AXIS_THRESHOLD,
      "Seuil des axes")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MENU_INPUT_SWAP_OK_CANCEL,
      "Inverser les boutons OK et Annuler dans le Menu")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_BIND_ALL,
      "Tout Assigner")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_BIND_DEFAULT_ALL,
      "Tout Assigner par Défaut")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_BIND_TIMEOUT,
      "Expiration de l'assignation")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_DESCRIPTOR_HIDE_UNBOUND,
      "Cacher les remaps non mappés des coeurs")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_DESCRIPTOR_LABEL_SHOW,
      "Afficher les remaps du coeur")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_DEVICE_INDEX,
      "Index du Périphérique")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_DEVICE_TYPE,
      "Type de Périphérique")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_DRIVER,
      "Pilote des entrées")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_DUTY_CYCLE,
      "Rapport de cycle")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_HOTKEY_BINDS,
      "Racourcis d'entrées")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_ICADE_ENABLE,
      "Activer le mapping de la manette sur le clavier")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_A,
      "Bouton A (droite)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_B,
      "Bouton B (bas)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_DOWN,
      "Croix Bas")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_L2,
      "Bouton L2 (gachette)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_L3,
      "Bouton L3 (pouce)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_L,
      "Bouton L (shoulder)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_LEFT,
      "Croix Gauche")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_R2,
      "Bouton R2 (gachette)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_R3,
      "Bouton R3 (pouce)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_R,
      "Bouton R (shoulder)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_RIGHT,
      "Croix Droite")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_SELECT,
      "Bouton Select")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_START,
      "Bouton Start")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_UP,
      "Croix Haut")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_X,
      "Bouton X (haut)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_Y,
      "Bouton Y (gauche)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_KEY,
      "(Touche: %s)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_KEYBOARD_GAMEPAD_MAPPING_TYPE,
      "Type de Mapping Manette sur Clavier")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_MAX_USERS,
      "Nombre d'utilisateurs")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_MENU_ENUM_TOGGLE_GAMEPAD_COMBO,
      "Combinaison pour afficher le menu")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_CHEAT_INDEX_MINUS,
      "Index de triche -")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_CHEAT_INDEX_PLUS,
      "Index de triche +")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_CHEAT_TOGGLE,
      "Activer / désactiver la triche")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_DISK_EJECT_TOGGLE,
      "Insérer / retirer un disque")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_DISK_NEXT,
      "Disque suivant")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_DISK_PREV,
      "Disque précédent")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_ENABLE_HOTKEY,
      "Activer les raccourcis clavier")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_FAST_FORWARD_HOLD_KEY,
      "Touche d'avance rapide")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_FAST_FORWARD_KEY,
      "Bascule d'avance rapide")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_FRAMEADVANCE,
      "Saut d'image")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_FULLSCREEN_TOGGLE_KEY,
      "Plein écran")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_GRAB_MOUSE_TOGGLE,
      "Touche de capture de la souris")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_LOAD_STATE_KEY,
      "Charger un état")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_MENU_TOGGLE,
      "Afficher le menu")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_MOVIE_RECORD_TOGGLE,
      "Activer l'enregistrement")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_MUTE,
      "Sourdine")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_NETPLAY_FLIP,
      "Inverser les joueurs en réseau")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_OSK,
      "Afficher le clavier virtuel")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_OVERLAY_NEXT,
      "Overlay suivante")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_PAUSE_TOGGLE,
      "Pause")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_QUIT_KEY,
      "Quitter RetroArch")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_RESET,
      "Redémarrer le jeu")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_REWIND,
      "Rembobinage")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_SAVE_STATE_KEY,
      "Sauvegarder un état")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_SCREENSHOT,
      "Prendre une capture d'écran")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_SHADER_NEXT,
      "Shader suivant")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_SHADER_PREV,
      "Shader précédent")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_SLOWMOTION,
      "Ralenti")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_STATE_SLOT_MINUS,
      "Emplacement de savestate -")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_STATE_SLOT_PLUS,
      "Emplacement de savestate +")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_VOLUME_DOWN,
      "Volume -")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_VOLUME_UP,
      "Volume +")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_OVERLAY_ENABLE,
      "Activer les overlays")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_OVERLAY_HIDE_IN_MENU,
      "Cacher l'overlay dans le menu")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_POLL_TYPE_BEHAVIOR,
      "Comportement du type de Poll")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_POLL_TYPE_BEHAVIOR_EARLY,
      "Tôt")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_POLL_TYPE_BEHAVIOR_LATE,
      "Tard")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_POLL_TYPE_BEHAVIOR_NORMAL,
      "Normal")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_PREFER_FRONT_TOUCH,
      "Prefer Front Touch")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_REMAPPING_DIRECTORY,
      "Dossier de remaps d'entrées")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_REMAP_BINDS_ENABLE,
      "Autoriser le remapping des entrées")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_SAVE_AUTOCONFIG,
      "Sauvegarder l'autoconfiguration")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_SETTINGS,
      "Entrées")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_SMALL_KEYBOARD_ENABLE,
      "Petit Clavier Activer")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_TOUCH_ENABLE,
      "Touch Activer")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_TURBO_ENABLE,
      "Activer le turbo")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_TURBO_PERIOD,
      "Délai du turbo")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_USER_BINDS,
      "Entrées utilisateur %u")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INTERNAL_STORAGE_STATUS,
      "État du stockage interne")
MSG_HASH(MENU_ENUM_LABEL_VALUE_JOYPAD_AUTOCONFIG_DIR,
      "Dossier des autoconfigs d'entrées")
MSG_HASH(MENU_ENUM_LABEL_VALUE_JOYPAD_DRIVER,
      "Pilote des manettes")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LAKKA_SERVICES,
      "Services")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LANG_CHINESE_SIMPLIFIED,
      "Chinois (Simplifié)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LANG_CHINESE_TRADITIONAL,
      "Chinois (Traditionnel)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LANG_DUTCH,
      "Néerlandais")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LANG_ENGLISH,
      "Anglais")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LANG_ESPERANTO,
      "Esperanto")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LANG_FRENCH,
      "Français")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LANG_GERMAN,
      "Allemand")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LANG_ITALIAN,
      "Italien")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LANG_JAPANESE,
      "Japonais")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LANG_KOREAN,
      "Coréen")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LANG_PORTUGUESE_BRAZIL,
      "Portuguais (Brazil)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LANG_PORTUGUESE_PORTUGAL,
      "Portuguais (Portugal)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LANG_RUSSIAN,
      "Russe")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LANG_SPANISH,
      "Espagnol")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LANG_VIETNAMESE,
      "Vietnamien")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LEFT_ANALOG,
      "Stick analogique gauche")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LIBRETRO_DIR_PATH,
      "Dossier des coeurs")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LIBRETRO_INFO_PATH,
      "Dossier des informations des coeurs")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LIBRETRO_LOG_LEVEL,
      "Verbosité des journaux des coeurs")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LINEAR,
      "Linéaire")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LOAD_ARCHIVE,
      "Charger l'archive") /* TODO/FIXME */
MSG_HASH(MENU_ENUM_LABEL_VALUE_LOAD_CONTENT_HISTORY,
      "Récemment ouvert")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LOAD_CONTENT_LIST,
      "Charger du contenu")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LOAD_STATE,
      "Charger une savestate")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LOCATION_ALLOW,
      "Autoriser la localisation")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LOCATION_DRIVER,
      "Pilote de localisation")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LOGGING_SETTINGS,
      "Journaux")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LOG_VERBOSITY,
      "Verbosité des journaux")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MAIN_MENU,
      "Menu principal")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MANAGEMENT,
      "Gestion avancée")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MATERIALUI_MENU_COLOR_THEME,
      "Dégradé de font d'écran")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MATERIALUI_MENU_COLOR_THEME_BLUE,
      "Bleu")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MATERIALUI_MENU_COLOR_THEME_BLUE_GREY,
      "Gris bleu")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MATERIALUI_MENU_COLOR_THEME_DARK_BLUE,
      "Bleu foncé")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MATERIALUI_MENU_COLOR_THEME_GREEN,
      "Vert")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MATERIALUI_MENU_COLOR_THEME_NVIDIA_SHIELD,
      "Shield")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MATERIALUI_MENU_COLOR_THEME_RED,
      "Rouge")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MATERIALUI_MENU_COLOR_THEME_YELLOW,
      "Jaune")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MATERIALUI_MENU_FOOTER_OPACITY,
      "Opacité du pied de page")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MATERIALUI_MENU_HEADER_OPACITY,
      "Opacité de l'en-tête")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MENU_DRIVER,
      "Pilote de menu")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MENU_ENUM_THROTTLE_FRAMERATE,
      "Contrôler le framerate du menu")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MENU_FILE_BROWSER_SETTINGS, /* TODO/FIXME - update */
      "Navigateur de fichiers")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MENU_LINEAR_FILTER,
      "Filtre linéaire")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MENU_SETTINGS,
      "Menu")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MENU_WALLPAPER,
      "Fond d'écran")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MENU_WALLPAPER_OPACITY,
      "Opacité de l'arrière-plan")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MISSING,
      "Manquant")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MORE,
      "...")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MOUSE_ENABLE,
      "Support de la souris")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MULTIMEDIA_SETTINGS,
      "Multimédia")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MUSIC_TAB,
      "Musique")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NAVIGATION_BROWSER_FILTER_SUPPORTED_EXTENSIONS_ENABLE,
      "Filtrer par extentions supportées")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NAVIGATION_WRAPAROUND,
      "Saut-retour")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NEAREST,
      "Au plus proche")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY,
      "Jeu en réseau")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY_CHECK_FRAMES,
      "Netplay Check Frames")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY_CLIENT_SWAP_INPUT,
      "Inverser les entrées du jeu en réseau")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY_DELAY_FRAMES,
      "Netplay Delay Frames")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY_DISCONNECT,
      "Déconnexion")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY_ENABLE,
      "Autoriser le jeu en réseau")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY_ENABLE_CLIENT,
      "Connexion à l'hôte distant")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY_ENABLE_HOST,
      "Commencer l'hébergement")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY_DISABLE_HOST,
      "Stop netplay host")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY_IP_ADDRESS,
      "Adresse IP")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY_MODE,
      "Activer le mode client")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY_NICKNAME,
      "Nom d'utilisateur")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY_SETTINGS,
      "Réglages du jeu en réseau")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY_SPECTATOR_MODE_ENABLE,
      "Activer le mode spectateur")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY_TCP_UDP_PORT,
      "Port TCP/UDP du jeu en réseau")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETWORK_CMD_ENABLE,
      "Commandes réseau")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETWORK_CMD_PORT,
      "Port des commandes réseau")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETWORK_INFORMATION,
      "Informations du réseau")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETWORK_REMOTE_ENABLE,
      "Manette réseau")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETWORK_REMOTE_PORT,
      "Network Remote Base Port")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETWORK_SETTINGS,
      "Réseau")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NO,
      "Non")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NONE,
      "Aucun")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NOT_AVAILABLE,
      "Indisponible")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NO_ACHIEVEMENTS_TO_DISPLAY,
      "Aucun Succès à afficher.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NO_CORE,
      "Aucun coeur")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NO_CORES_AVAILABLE,
      "Aucun coeur disponible.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NO_CORE_INFORMATION_AVAILABLE,
      "Pas d'informations disponibles.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NO_CORE_OPTIONS_AVAILABLE,
      "Pas d'options disponibles.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NO_ENTRIES_TO_DISPLAY,
      "Aucune entrée à afficher.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NO_HISTORY_AVAILABLE,
      "Aucun historique disponible.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NO_INFORMATION_AVAILABLE,
      "Pas d'informations disponibles.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NO_ITEMS,
      "Vide.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NO_PERFORMANCE_COUNTERS,
      "Pas de compteurs de performance.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NO_PLAYLIST_ENTRIES_AVAILABLE,
      "Playlist vide.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NO_SETTINGS_FOUND,
      "Pas de réglages trouvés.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NO_SHADER_PARAMETERS,
      "Aucun paramètre.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_OFF,
      "OFF")
MSG_HASH(MENU_ENUM_LABEL_VALUE_ON,
      "ON")
MSG_HASH(MENU_ENUM_LABEL_VALUE_ONLINE,
      "En ligne")
MSG_HASH(MENU_ENUM_LABEL_VALUE_ONLINE_UPDATER,
      "Mises à jour")
MSG_HASH(MENU_ENUM_LABEL_VALUE_ONSCREEN_DISPLAY_SETTINGS,
      "Messages d'info")
MSG_HASH(MENU_ENUM_LABEL_VALUE_ONSCREEN_OVERLAY_SETTINGS,
      "Overlay à l'écran")
MSG_HASH(MENU_ENUM_LABEL_VALUE_ONSCREEN_NOTIFICATIONS_SETTINGS,
      "Notifications à l'écran")
MSG_HASH(MENU_ENUM_LABEL_VALUE_OPEN_ARCHIVE,
      "Ouvrir l'archive") /* TODO/FIXME */
MSG_HASH(MENU_ENUM_LABEL_VALUE_OPTIONAL,
      "Optionnel")
MSG_HASH(MENU_ENUM_LABEL_VALUE_OVERLAY_AUTOLOAD_PREFERRED,
      "Charger l'overlay préféré automatiquement")
MSG_HASH(MENU_ENUM_LABEL_VALUE_OVERLAY_DIRECTORY,
      "Dossier des overlays")
MSG_HASH(MENU_ENUM_LABEL_VALUE_OVERLAY_OPACITY,
      "Transparence de l'overlay")
MSG_HASH(MENU_ENUM_LABEL_VALUE_OVERLAY_PRESET,
      "Préréglages de l'overlay")
MSG_HASH(MENU_ENUM_LABEL_VALUE_OVERLAY_SCALE,
      "Zoom de l'overlay")
MSG_HASH(MENU_ENUM_LABEL_VALUE_OVERLAY_SETTINGS,
      "Overlays")
MSG_HASH(MENU_ENUM_LABEL_VALUE_PAL60_ENABLE,
      "Utiliser le mode PAL60")
MSG_HASH(MENU_ENUM_LABEL_VALUE_PARENT_DIRECTORY,
      "Dossier parent")
MSG_HASH(MENU_ENUM_LABEL_VALUE_PAUSE_LIBRETRO,
      "Pauser le contenu quand le menu est activé")
MSG_HASH(MENU_ENUM_LABEL_VALUE_PAUSE_NONACTIVE,
      "Ne pas fonctionner en arrière-plan")
MSG_HASH(MENU_ENUM_LABEL_VALUE_PERFCNT_ENABLE,
      "Compteurs de performance")
MSG_HASH(MENU_ENUM_LABEL_VALUE_PLAYLISTS_TAB,
      "Playlists")
MSG_HASH(MENU_ENUM_LABEL_VALUE_PLAYLIST_DIRECTORY,
      "Dossier des playlists")
MSG_HASH(MENU_ENUM_LABEL_VALUE_PLAYLIST_SETTINGS,
      "Playlists")
MSG_HASH(MENU_ENUM_LABEL_VALUE_POINTER_ENABLE,
      "Support du tactile")
MSG_HASH(MENU_ENUM_LABEL_VALUE_PORT,
      "Port")
MSG_HASH(MENU_ENUM_LABEL_VALUE_PRESENT,
      "Présent")
MSG_HASH(MENU_ENUM_LABEL_VALUE_PRIVACY_SETTINGS,
      "Confidentialité")
MSG_HASH(MENU_ENUM_LABEL_VALUE_QUIT_RETROARCH,
      "Quitter RetroArch")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_ANALOG,
      "Support de l'analogique")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_BBFC_RATING,
      "BBFC Rating")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_CERO_RATING,
      "CERO Rating")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_COOP,
      "Support du co-op")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_CRC32,
      "CRC32")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_DESCRIPTION,
      "Description")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_DEVELOPER,
      "Développeur")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_EDGE_MAGAZINE_ISSUE,
      "Numéro du magazine Edge")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_EDGE_MAGAZINE_RATING,
      "Note du magazine Edge")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_EDGE_MAGAZINE_REVIEW,
      "Test du magazine Edge")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_ELSPA_RATING,
      "Classification ELSPA")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_ENHANCEMENT_HW,
      "Matériel d'amélioration")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_ESRB_RATING,
      "Classification ESRB")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_FAMITSU_MAGAZINE_RATING,
      "Note du magazine Famitsu")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_FRANCHISE,
      "Franchise")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_GENRE,
      "Genre")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_MD5,
      "MD5")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_NAME,
      "Nom")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_ORIGIN,
      "Origine")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_PEGI_RATING,
      "Classification PEGI")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_PUBLISHER,
      "Éditeur")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_RELEASE_MONTH,
      "Mois de sortie")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_RELEASE_YEAR,
      "Année de sortie")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_RUMBLE,
      "Support des vibrations")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_SERIAL,
      "Numéro de série")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_SHA1,
      "SHA1")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_START_CONTENT,
      "Exécuter le contenu")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_TGDB_RATING,
      "Classification TGDB")
MSG_HASH(MENU_ENUM_LABEL_VALUE_REBOOT,
      "Redémarrer")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RECORDING_CONFIG_DIRECTORY,
      "Dossier des réglages de capture vidéo")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RECORDING_OUTPUT_DIRECTORY,
      "Dossier d'enregistrement des vidéos")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RECORDING_SETTINGS,
      "Capture video")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RECORD_CONFIG,
      "Configuration de capture")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RECORD_DRIVER,
      "Pilote de capture vidéo")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RECORD_ENABLE,
      "Autoriser les captures vidéo")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RECORD_PATH,
      "Chemin de l'enregistrement")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RECORD_USE_OUTPUT_DIRECTORY,
      "Utiliser le dossier d'enregistrement")
MSG_HASH(MENU_ENUM_LABEL_VALUE_REMAP_FILE_LOAD,
      "Charger un fichier de remap")
MSG_HASH(MENU_ENUM_LABEL_VALUE_REMAP_FILE_SAVE_CORE,
      "Sauvegarder un fichier remaps de coeur")
MSG_HASH(MENU_ENUM_LABEL_VALUE_REMAP_FILE_SAVE_GAME,
      "Sauvegarder un fichier de remap de contenu")
MSG_HASH(MENU_ENUM_LABEL_VALUE_REQUIRED,
      "Requis")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RESTART_CONTENT,
      "Redémarrer le contenu")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RESTART_RETROARCH,
      "Redémarrer RetroArch")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RESUME,
      "Reprendre")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RESUME_CONTENT,
      "Reprendre")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RETROKEYBOARD,
      "RetroKeyboard")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RETROPAD,
      "RetroPad")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RETROPAD_WITH_ANALOG,
      "Retropad avec analogique")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RETRO_ACHIEVEMENTS_SETTINGS,
      "Succès")
MSG_HASH(MENU_ENUM_LABEL_VALUE_REWIND_ENABLE,
      "Activer le rembobinage")
MSG_HASH(MENU_ENUM_LABEL_VALUE_REWIND_GRANULARITY,
      "Précision du rembobinage")
MSG_HASH(MENU_ENUM_LABEL_VALUE_REWIND_SETTINGS,
      "Rembobinage")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RGUI_BROWSER_DIRECTORY,
      "Dossier racine de navigation")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RGUI_CONFIG_DIRECTORY,
      "Dossier des fichiers de configuration")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RGUI_SHOW_START_SCREEN,
      "Afficher l'écran de d'aide")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RIGHT_ANALOG,
      "Stick analogique droit")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RUN,
      "Lancer")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SAMBA_ENABLE,
      "Activer SAMBA")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SAVEFILE_DIRECTORY,
      "Dossier des sauvegardes")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SAVESTATE_AUTO_INDEX,
      "Indexer automatiquement les savestates")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SAVESTATE_AUTO_LOAD,
      "Charger automatiquement les savestates")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SAVESTATE_AUTO_SAVE,
      "Sauvegarde automatique")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SAVESTATE_DIRECTORY,
      "Dossier des sauvegardes rapides")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SAVE_CURRENT_CONFIG,
      "Sauvegarder la configuration actuelle")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SAVE_CURRENT_CONFIG_OVERRIDE_CORE,
      "Sauvegarder les overrides de cœur")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SAVE_CURRENT_CONFIG_OVERRIDE_GAME,
      "Sauvegarder les overrides de jeu")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SAVE_NEW_CONFIG,
      "Sauvegarder la configuration")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SAVE_STATE,
      "Sauvegarder une savestate")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SAVING_SETTINGS,
      "Sauvegardes")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SCAN_DIRECTORY,
      "Scanner un dossier")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SCAN_FILE,
      "Scanner un fichier")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SCAN_THIS_DIRECTORY,
      "<Scanner ce dossier>")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SCREENSHOT_DIRECTORY,
      "Dossier des captures d'écran")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SCREEN_RESOLUTION,
      "Résolution d'écran")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SEARCH,
      "Recherche :")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SECONDS,
      "secondes")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SETTINGS,
      "Réglages")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SETTINGS_TAB,
      "Réglages")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SHADER,
      "Shader")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SHADER_APPLY_CHANGES,
      "Appliquer les changements")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SHADER_OPTIONS,
      "Shaders")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SHADER_PIPELINE_RIBBON,
      "Ruban")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SHADER_PIPELINE_RIBBON_SIMPLIFIED,
      "Ruban (simplifié)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SHADER_PIPELINE_SIMPLE_SNOW,
      "Neige simple")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SHADER_PIPELINE_SNOW,
      "Neige")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SHOW_ADVANCED_SETTINGS,
      "Afficher les réglages avancés")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SHOW_HIDDEN_FILES,
      "Afficher les fichiers et dossiers cachés")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SHUTDOWN,
      "Éteindre")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SLOWMOTION_RATIO,
      "Taux de ralentissement")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SORT_SAVEFILES_ENABLE,
      "Classer les sauvegardes par dossier")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SORT_SAVESTATES_ENABLE,
      "Classer les savestates par dossier")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SSH_ENABLE,
      "Activer SSH")
MSG_HASH(MENU_ENUM_LABEL_VALUE_START_CORE,
      "Démarrer le coeur")
MSG_HASH(MENU_ENUM_LABEL_VALUE_START_NET_RETROPAD,
      "Mode manette à distance")
MSG_HASH(MENU_ENUM_LABEL_VALUE_START_VIDEO_PROCESSOR,
      "Démarrer le processeur vidéo")
MSG_HASH(MENU_ENUM_LABEL_VALUE_STATE_SLOT,
      "Emplacement de savestate")
MSG_HASH(MENU_ENUM_LABEL_VALUE_STATUS,
      "Statut")
MSG_HASH(MENU_ENUM_LABEL_VALUE_STDIN_CMD_ENABLE,
      "Commandes stdin")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SUPPORTED_CORES,
      "Cores suggérés")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SUSPEND_SCREENSAVER_ENABLE,
      "Désactiver l'économiseur d'écran")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_BGM_ENABLE,
      "Musique du système activée")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_DIRECTORY,
      "Dossier système/BIOS")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFORMATION,
      "Informations du système")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_7ZIP_SUPPORT,
      "Support de 7zip")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_ALSA_SUPPORT,
      "Support d'ALSA")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_BUILD_DATE,
      "Date de build")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_CG_SUPPORT,
      "Support de CG")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_COCOA_SUPPORT,
      "Support de Cocoa")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_COMMAND_IFACE_SUPPORT,
      "Support de l'interface de commandes")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_CORETEXT_SUPPORT,
      "Support de CoreText")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_CPU_FEATURES,
      "Fonctionnalités du CPU")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_DISPLAY_METRIC_DPI,
      "DPI de l'écran")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_DISPLAY_METRIC_MM_HEIGHT,
      "Hauteur d'écran (mm)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_DISPLAY_METRIC_MM_WIDTH,
      "Largeur d'écran (mm)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_DSOUND_SUPPORT,
      "Support de DirectSoundt")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_WASAPI_SUPPORT,
      "Support de WASAPI")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_DYLIB_SUPPORT,
      "Support des bibliothèques dynamiques")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_EGL_SUPPORT,
      "Support d'EGL")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_FBO_SUPPORT,
      "Support d'OpenGL/Direct3D render-to-texture (shaders multi-passages)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_FFMPEG_SUPPORT,
      "Support de FFmpeg")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_FREETYPE_SUPPORT,
      "Support de FreeType")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_FRONTEND_IDENTIFIER,
      "Identifiant frontend")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_FRONTEND_NAME,
      "Nom du frontend")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_FRONTEND_OS,
      "OS du frontend")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_GIT_VERSION,
      "Version git")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_GLSL_SUPPORT,
      "Support de GLSL")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_HLSL_SUPPORT,
      "Support de HLSL")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_JACK_SUPPORT,
      "Support de JACK")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_KMS_SUPPORT,
      "Support de KMS/EGL")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_LIBRETRODB_SUPPORT,
      "Support de libretroDB")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_LIBUSB_SUPPORT,
      "Support de libusb")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_LIBXML2_SUPPORT,
      "Support du parser XML libxml2")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_NETPLAY_SUPPORT,
      "Support du jeu en réseau")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_NETWORK_COMMAND_IFACE_SUPPORT,
      "Support des commandes réseau")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_OPENAL_SUPPORT,
      "Support d'OpenAL")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_OPENGLES_SUPPORT,
      "Support d'OpenGL ES")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_OPENGL_SUPPORT,
      "Support d'OpenGL")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_OPENSL_SUPPORT,
      "Support d'OpenSL")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_OPENVG_SUPPORT,
      "Support d'OpenVG")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_OSS_SUPPORT,
      "Support d'OSS")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_OVERLAY_SUPPORT,
      "Support des overlays")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_POWER_SOURCE,
      "Alimentation")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_POWER_SOURCE_CHARGED,
      "Chargé")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_POWER_SOURCE_CHARGING,
      "En chargement")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_POWER_SOURCE_DISCHARGING,
      "Déchargé")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_POWER_SOURCE_NO_SOURCE,
      "Non alimenté")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_PULSEAUDIO_SUPPORT,
      "Support de PulseAudio")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_PYTHON_SUPPORT,
      "Support de Python (scripting des shaders)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_RETRORATING_LEVEL,
      "Niveau RetroRating")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_ROARAUDIO_SUPPORT,
      "Support de RoarAudio")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_RPNG_SUPPORT,
      "Support des PNGs (RPNG)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_RSOUND_SUPPORT,
      "Support de RSound")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_SDL2_SUPPORT,
      "Support de SDL2")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_SDL_IMAGE_SUPPORT,
      "Support de SDL_Image")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_SDL_SUPPORT,
      "Support de SDL1.2")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_THREADING_SUPPORT,
      "Support du threading")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_UDEV_SUPPORT,
      "Support de udev")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_V4L2_SUPPORT,
      "Support de Video4Linux2")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_VIDEO_CONTEXT_DRIVER,
      "Pilote du contexte vidéo")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_WAYLAND_SUPPORT,
      "Support de Wayland")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_X11_SUPPORT,
      "Support de X11")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_XAUDIO2_SUPPORT,
      "Support de XAudio2")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_XVIDEO_SUPPORT,
      "Support de XVideo")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_ZLIB_SUPPORT,
      "Support de Zlib")
MSG_HASH(MENU_ENUM_LABEL_VALUE_TAKE_SCREENSHOT,
      "Capturer l écran")
MSG_HASH(MENU_ENUM_LABEL_VALUE_THREADED_DATA_RUNLOOP_ENABLE, /* TODO/FIXME - update */
      "Boucle de données threadée")
MSG_HASH(MENU_ENUM_LABEL_VALUE_THUMBNAILS,
      "Vignettes")
MSG_HASH(MENU_ENUM_LABEL_VALUE_THUMBNAILS_DIRECTORY,
      "Dossier des vignettes")
MSG_HASH(MENU_ENUM_LABEL_VALUE_THUMBNAILS_UPDATER_LIST,
      "Mise à jour des vignettes")
MSG_HASH(MENU_ENUM_LABEL_VALUE_THUMBNAIL_MODE_BOXARTS,
      "Jaquettes")
MSG_HASH(MENU_ENUM_LABEL_VALUE_THUMBNAIL_MODE_SCREENSHOTS,
      "Captures d'écrans")
MSG_HASH(MENU_ENUM_LABEL_VALUE_THUMBNAIL_MODE_TITLE_SCREENS,
      "Écrans titres")
MSG_HASH(MENU_ENUM_LABEL_VALUE_TIMEDATE_ENABLE,
      "Afficher la date et l'heure")
MSG_HASH(MENU_ENUM_LABEL_VALUE_TITLE_COLOR,
      "Couleur du titre du menu")
MSG_HASH(MENU_ENUM_LABEL_VALUE_TRUE,
      "Vrai")
MSG_HASH(MENU_ENUM_LABEL_VALUE_UI_COMPANION_START_ON_BOOT,
      "Lancer le compagnon d'interface au démarrage")
MSG_HASH(MENU_ENUM_LABEL_VALUE_UI_MENUBAR_ENABLE,
      "Barre de menu")
MSG_HASH(MENU_ENUM_LABEL_VALUE_UNABLE_TO_READ_COMPRESSED_FILE,
      "Impossible de lire l'archive.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_UNDO_LOAD_STATE,
      "Annuler charger une savestate")
MSG_HASH(MENU_ENUM_LABEL_VALUE_UNDO_SAVE_STATE,
      "Annuler sauvegarder une savestate")
MSG_HASH(MENU_ENUM_LABEL_VALUE_UNKNOWN,
      "Inconnu")
MSG_HASH(MENU_ENUM_LABEL_VALUE_UPDATER_SETTINGS,
      "Paramètres de mises à jour")
MSG_HASH(MENU_ENUM_LABEL_VALUE_UPDATE_ASSETS,
      "Mettre à jour les assets")
MSG_HASH(MENU_ENUM_LABEL_VALUE_UPDATE_AUTOCONFIG_PROFILES,
      "Mettre à jour les profils d'autoconfiguration")
MSG_HASH(MENU_ENUM_LABEL_VALUE_UPDATE_CG_SHADERS,
      "Mettre à jour les shaders CG")
MSG_HASH(MENU_ENUM_LABEL_VALUE_UPDATE_CHEATS,
      "Mettre à jour les codes de triche")
MSG_HASH(MENU_ENUM_LABEL_VALUE_UPDATE_CORE_INFO_FILES,
      "Mettre à jour les informations des coeurs")
MSG_HASH(MENU_ENUM_LABEL_VALUE_UPDATE_DATABASES,
      "Mettre à jour les bases de données")
MSG_HASH(MENU_ENUM_LABEL_VALUE_UPDATE_GLSL_SHADERS,
      "Mettre à jour les shaders GLSL")
MSG_HASH(MENU_ENUM_LABEL_VALUE_UPDATE_LAKKA,
      "Mettre à jour Lakka")
MSG_HASH(MENU_ENUM_LABEL_VALUE_UPDATE_OVERLAYS,
      "Mettre à jour les overlays")
MSG_HASH(MENU_ENUM_LABEL_VALUE_UPDATE_SLANG_SHADERS,
      "Mettre à jour les shaders Slang")
MSG_HASH(MENU_ENUM_LABEL_VALUE_USER,
      "Utilisateur")
MSG_HASH(MENU_ENUM_LABEL_VALUE_USER_INTERFACE_SETTINGS,
      "Interface graphique")
MSG_HASH(MENU_ENUM_LABEL_VALUE_USER_LANGUAGE,
      "Langue")
MSG_HASH(MENU_ENUM_LABEL_VALUE_USER_SETTINGS,
      "Utilisateur")
MSG_HASH(MENU_ENUM_LABEL_VALUE_USE_BUILTIN_IMAGE_VIEWER,
      "Utiliser le lecteur d'image embarqué")
MSG_HASH(MENU_ENUM_LABEL_VALUE_USE_BUILTIN_PLAYER,
      "Utiliser le lecteur vidéo embarqué")
MSG_HASH(MENU_ENUM_LABEL_VALUE_USE_THIS_DIRECTORY,
      "<Choisir ce dossier>")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_ALLOW_ROTATE,
      "Autoriser la rotation")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_ASPECT_RATIO_AUTO,
      "Format d'image automatique")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_ASPECT_RATIO_INDEX,
      "Rapport d'aspect")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_BLACK_FRAME_INSERTION,
      "Insérer des frames noires")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_CROP_OVERSCAN,
      "Tronquer l'overscan (Reload)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_DISABLE_COMPOSITION,
      "Désactiver le compositeur du bureau")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_DRIVER,
      "Pilote vidéo")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_FILTER,
      "Filtre vidéo")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_FILTER_DIR,
      "Dossier des filtres vidéo")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_FILTER_FLICKER,
      "Filtre anti-scintillement")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_FONT_ENABLE,
      "Afficher les messages d'info")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_FONT_PATH,
      "Police des messages d'info")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_FONT_SIZE,
      "Taille du texte des messages")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_FORCE_ASPECT,
      "Forcer le format d'image")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_FORCE_SRGB_DISABLE,
      "Désactiver sRGB FBO")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_FRAME_DELAY,
      "Délayer les frames")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_FULLSCREEN,
      "Plein écran")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_GAMMA,
      "Gamma")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_GPU_RECORD,
      "Captures vidéo via le GPU")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_GPU_SCREENSHOT,
      "Activer les captures d'écran GPU")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_HARD_SYNC,
      "Synchroniser le GPU au CPU")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_HARD_SYNC_FRAMES,
      "Trames de synchro GPU")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_MAX_SWAPCHAIN_IMAGES,
      "Max swapchain images")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_MESSAGE_POS_X,
      "Position X")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_MESSAGE_POS_Y,
      "Position Y")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_MONITOR_INDEX,
      "Écran")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_POST_FILTER_RECORD,
      "Activer les filtres de traitement")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_REFRESH_RATE,
      "Fréquence de rafraichissement")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_REFRESH_RATE_AUTO,
      "Fréquence estimée de l'écran")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_ROTATION,
      "Rotation")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_SCALE,
      "Zoom (en fenêtre)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_SCALE_INTEGER,
      "Aligner aux pixels de l'écran")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_SETTINGS,
      "Vidéo")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_SHADER_DIR,
      "Dossier des shaders vidéo")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_SHADER_NUM_PASSES,
      "Nombre de passages")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_SHADER_PARAMETERS,
      "Preview Shader Parameters")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_SHADER_PRESET,
      "Charger un preset de shader")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_SHADER_PRESET_PARAMETERS,
      "Charger un preset de shader")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_SHADER_PRESET_SAVE_AS,
      "Enregistrer le preset sous")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_SHADER_PRESET_SAVE_CORE,
      "Sauvegarder le preset de core")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_SHADER_PRESET_SAVE_GAME,
      "Sauvegarder le preset de jeu")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_SHARED_CONTEXT,
      "Partager le contexte matériel")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_SMOOTH,
      "Filtre bilinéaire (HW)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_SOFT_FILTER,
      "Filtre doux activé")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_SWAP_INTERVAL,
      "Intervale de synchronisation verticale")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_TAB,
      "Vidéo")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_THREADED,
      "Threader l'affichage")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_VFILTER,
      "Deflicker")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_VIEWPORT_CUSTOM_HEIGHT,
      "Hauteur personnalisée de la fenêtre")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_VIEWPORT_CUSTOM_WIDTH,
      "Largeur personnalisée de la fenêtre")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_VIEWPORT_CUSTOM_X,
      "Position horizontale personnalisée")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_VIEWPORT_CUSTOM_Y,
      "Position verticale personnalisée")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_VI_WIDTH,
      "Set VI Screen Width")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_VSYNC,
      "Synchronisation verticale")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_WINDOWED_FULLSCREEN,
      "Mode plein écran fenêtré")
MSG_HASH(MENU_ENUM_LABEL_VALUE_WIFI_DRIVER,
      "Pilote du Wi-Fi")
MSG_HASH(MENU_ENUM_LABEL_VALUE_WIFI_SETTINGS,
      "Wi-Fi")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_ALPHA_FACTOR,
      "XMB : Transparence")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_FONT,
      "XMB : Police")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_ICON_THEME_CUSTOM,
      "Perso")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_ICON_THEME_FLATUI,
      "FlatUI")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_ICON_THEME_MONOCHROME,
      "Monochrome")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_ICON_THEME_SYSTEMATIC,
      "Systematic")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_ICON_THEME_NEOACTIVE,
      "NeoActive")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_ICON_THEME_PIXEL,
      "Pixel")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_ICON_THEME_RETROACTIVE,
      "RetroActive")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_ICON_THEME_DOTART,
      "Dot-Art")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_MENU_COLOR_THEME,
      "Dégradé de fond d'écran")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_MENU_COLOR_THEME_APPLE_GREEN,
      "Vert Pomme")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_MENU_COLOR_THEME_DARK,
      "Sombre")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_MENU_COLOR_THEME_DARK_PURPLE,
      "Violet Foncé")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_MENU_COLOR_THEME_ELECTRIC_BLUE,
      "Bleu Électrique")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_MENU_COLOR_THEME_GOLDEN,
      "Doré")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_MENU_COLOR_THEME_LEGACY_RED,
      "Rouge (Legacy)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_MENU_COLOR_THEME_MIDNIGHT_BLUE,
      "Bleu Nuit")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_MENU_COLOR_THEME_PLAIN,
      "uni")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_MENU_COLOR_THEME_UNDERSEA,
      "Sous-Marin")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_MENU_COLOR_THEME_VOLCANIC_RED,
      "Rouge Volcanique")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_RIBBON_ENABLE,
      "Fond d'écran animé")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_SCALE_FACTOR,
      "XMB : Zoom")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_SHADOWS_ENABLE,
      "Ombres pour les icones")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_SHOW_HISTORY,
      "Afficher l'onglet Historique")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_SHOW_IMAGES,
      "Afficher l'onglet Images")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_SHOW_MUSIC,
      "Afficher l'onglet Musique")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_SHOW_SETTINGS,
      "Afficher l'onglet Paramètres")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_SHOW_VIDEO,
      "Afficher l'onglet Vidéo")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_THEME,
      "XMB : Thème")
MSG_HASH(MENU_ENUM_LABEL_VALUE_YES,
      "Oui")
MSG_HASH(MENU_ENUM_LABEL_VIDEO_SHADER_PRESET_TWO,
      "Preset de shader")
MSG_HASH(MENU_ENUM_SUBLABEL_CHEEVOS_ENABLE,
      "Activer ou désactiver les Succès. Pour plus d'information, visiter http://retroachievements.org")
MSG_HASH(MENU_ENUM_SUBLABEL_CHEEVOS_TEST_UNOFFICIAL,
      "Activer ou désactiver les Succès non-officiels et / ou les fonctionnalités en beta à des fins de test.")
MSG_HASH(MENU_ENUM_SUBLABEL_CHEEVOS_HARDCORE_MODE_ENABLE,
      "Activer ou désactiver les savestates, la triche, le rembobinage, la pause et le ralenti pour tous les jeux.")
MSG_HASH(MENU_ENUM_SUBLABEL_DRIVER_SETTINGS,
      "Modifier les pilotes pour ce système.")
MSG_HASH(MENU_ENUM_SUBLABEL_RETRO_ACHIEVEMENTS_SETTINGS,
      "Modifier les paramètres des Succès.")
MSG_HASH(MENU_ENUM_SUBLABEL_CORE_SETTINGS,
      "Modifier les paramètres des cœurs.")
MSG_HASH(MENU_ENUM_SUBLABEL_RECORDING_SETTINGS,
      "Modifier les paramètres d'enregistrement.")
MSG_HASH(MENU_ENUM_SUBLABEL_ONSCREEN_DISPLAY_SETTINGS,
      "Modifier les paramètres d'overlay à l'écran, d'overlay clavier et de notifications à l'écran.")
MSG_HASH(MENU_ENUM_SUBLABEL_FRAME_THROTTLE_SETTINGS,
      "Modifier les paramètres de rembobinage, d'avance rapide et de ralenti.")
MSG_HASH(MENU_ENUM_SUBLABEL_SAVING_SETTINGS,
      "Modifier les paramètres de sauvegarde.")
MSG_HASH(MENU_ENUM_SUBLABEL_LOGGING_SETTINGS,
      "Modifier les paramètres de journalisation.")
MSG_HASH(MENU_ENUM_SUBLABEL_USER_INTERFACE_SETTINGS,
      "Modifier les paramètres d'interface utilisateur.")
MSG_HASH(MENU_ENUM_SUBLABEL_USER_SETTINGS,
      "Modifier les comptes, pseudos, et langues.")
MSG_HASH(MENU_ENUM_SUBLABEL_PRIVACY_SETTINGS,
      "Modifier les paramètres de vie privée.")
MSG_HASH(MENU_ENUM_SUBLABEL_DIRECTORY_SETTINGS,
      "Modifier les répertoires par défaut pour ce système.")
MSG_HASH(MENU_ENUM_SUBLABEL_PLAYLIST_SETTINGS,
      "Modifier les paramètres des playlists.")
MSG_HASH(MENU_ENUM_SUBLABEL_NETWORK_SETTINGS,
      "Configurer les paramètres de serveurs et de réseau.")
MSG_HASH(MENU_ENUM_SUBLABEL_ADD_CONTENT_LIST,
      "Scanner les contenus et les ajouter à la base de données.")
MSG_HASH(MENU_ENUM_SUBLABEL_AUDIO_SETTINGS,
      "Ajuster les paramètres de sortie audio.")
MSG_HASH(MENU_ENUM_SUBLABEL_BLUETOOTH_ENABLE,
      "Activer ou désactiver le Bluetooth.")
MSG_HASH(MENU_ENUM_SUBLABEL_CONFIG_SAVE_ON_EXIT,
      "Sauvegarder les modifications dans le fichier de configuration en quittant.")
MSG_HASH(MENU_ENUM_SUBLABEL_CONFIGURATION_SETTINGS,
      "Modifier les paramètres par défaut pour les fichiers de configuration.")
MSG_HASH(MENU_ENUM_SUBLABEL_CONFIGURATIONS_LIST,
      "Créer et gérer les fichiers de configuration.")
MSG_HASH(MENU_ENUM_SUBLABEL_CPU_CORES,
      "Nombre de cœurs du CPU.")
MSG_HASH(MENU_ENUM_SUBLABEL_FPS_SHOW,
      "Affiche le nombre d'images par seconde à l'écran.")
MSG_HASH(MENU_ENUM_SUBLABEL_INPUT_HOTKEY_BINDS,
      "Configurer les paramètres des raccourcis clavier.")
MSG_HASH(MENU_ENUM_SUBLABEL_INPUT_MENU_ENUM_TOGGLE_GAMEPAD_COMBO,
      "Combinaison de boutons manette pour afficher le menu.")
MSG_HASH(MENU_ENUM_SUBLABEL_INPUT_SETTINGS,
      "Ajuster les paramètres des manettes, du clavier et de la souris.")
MSG_HASH(MENU_ENUM_SUBLABEL_INPUT_USER_BINDS,
      "Configurer les contrôles pour cet utilisateur.")
MSG_HASH(MENU_ENUM_SUBLABEL_LOG_VERBOSITY,
      "Activer ou désactiver la journalisation dans le terminal.")
MSG_HASH(MENU_ENUM_SUBLABEL_NETPLAY,
      "Rejoindre ou héberger une session réseau.")
MSG_HASH(MENU_ENUM_SUBLABEL_INFORMATION_LIST_LIST,
      "Afficher les informations de cœurs, de réseau et du système.")
MSG_HASH(MENU_ENUM_SUBLABEL_ONLINE_UPDATER,
      "Télécharger des add-ons, des composants et du contenu pour RetroArch.")
MSG_HASH(MENU_ENUM_SUBLABEL_SAMBA_ENABLE,
      "Activer ou désactiver le partage réseau des dossiers.")
MSG_HASH(MENU_ENUM_SUBLABEL_SERVICES_SETTINGS,
      "Gérer les services système.")
MSG_HASH(MENU_ENUM_SUBLABEL_SHOW_HIDDEN_FILES,
      "Afficher les dossiers et fichiers cachés dans l'explorateur.")
MSG_HASH(MENU_ENUM_SUBLABEL_SSH_ENABLE,
      "Activer ou désactiver l'accès distant via la ligne de commande.")
MSG_HASH(MENU_ENUM_SUBLABEL_SUSPEND_SCREENSAVER_ENABLE,
      "Empêche l'activation de l'économiseur d'écran.")
MSG_HASH(MENU_ENUM_SUBLABEL_USER_LANGUAGE,
      "Définit la langue de l'interface.")
MSG_HASH(MENU_ENUM_SUBLABEL_VIDEO_BLACK_FRAME_INSERTION,
      "Insère une image noire entre chaque image. Utile pour les utilisateurs de moniteurs 120 Hz qui veulent pouvoir jouer à du contenu à 60 Hz sans ghosting.")
MSG_HASH(MENU_ENUM_SUBLABEL_VIDEO_FRAME_DELAY,
      "Réduit la latence au risque d'augmenter les saccades. Ajoute un délai après la synchronisation verticale (en ms).")
MSG_HASH(MENU_ENUM_SUBLABEL_VIDEO_HARD_SYNC_FRAMES,
      "Définit le nombre d'images que le CPU peut calculer avant le GPU lorsque la synchronisation GPU est active.")
MSG_HASH(MENU_ENUM_SUBLABEL_VIDEO_MAX_SWAPCHAIN_IMAGES,
      "Indique au pilote graphique d'utiliser un mode de tampon spécifique.")
MSG_HASH(MENU_ENUM_SUBLABEL_VIDEO_MONITOR_INDEX,
      "Sélectionne l'écran à utiliser.")
MSG_HASH(MENU_ENUM_SUBLABEL_VIDEO_REFRESH_RATE_AUTO,
      "Taux de rafraîchissement estimé de l'écran en Hz.")
MSG_HASH(MENU_ENUM_SUBLABEL_VIDEO_SETTINGS,
      "Ajuster les paramètres de sortie vidéo.")
MSG_HASH(MENU_ENUM_SUBLABEL_WIFI_SETTINGS,
      "Scanner les réseaux Wi-Fi et établir une connexion.")
MSG_HASH(MENU_ENUM_SUBLABEL_HELP_LIST,
      "Mieux comprendre comment ça marche.")
MSG_HASH(MSG_APPENDED_DISK,
      "Disque fusionné")
MSG_HASH(MSG_APPLICATION_DIR,
      "Répertoire de l'application.")
MSG_HASH(MSG_APPLYING_CHEAT,
      "Appliquer les changements de triche.")
MSG_HASH(MSG_APPLYING_SHADER,
      "Application du shader")
MSG_HASH(MSG_AUDIO_MUTED,
      "Son coupé.")
MSG_HASH(MSG_AUDIO_UNMUTED,
      "Remise du son.")
MSG_HASH(MSG_AUTOCONFIG_FILE_ERROR_SAVING,
      "Erreur lors de l'enregistrement du fichier d'autoconfiguration.")
MSG_HASH(MSG_AUTOCONFIG_FILE_SAVED_SUCCESSFULLY,
      "Enregistrement réussi du fichier d'autoconfiguration.")
MSG_HASH(MSG_AUTOSAVE_FAILED,
      "Impossible d'activer l'enregistrement automatique.")
MSG_HASH(MSG_AUTO_SAVE_STATE_TO,
      "Savestate automatique vers")
MSG_HASH(MSG_BLOCKING_SRAM_OVERWRITE,
      "Bloque l'écrasement de la SRAM")
MSG_HASH(MSG_BRINGING_UP_COMMAND_INTERFACE_ON_PORT,
      "Amener l'interface de commande sur le port")
MSG_HASH(MSG_BYTES,
      "octets")
MSG_HASH(MSG_CANNOT_INFER_NEW_CONFIG_PATH,
      "Impossiblede déduire le nouveau chemin de configuration. Utilisation de l'heure actuelle.")
MSG_HASH(MSG_CHEEVOS_HARDCORE_MODE_ENABLE,
      "Mode matériel activé , savestate et rembobinage sont désactivés.")
MSG_HASH(MSG_COMPARING_WITH_KNOWN_MAGIC_NUMBERS,
      "Comparaison avec les numéros magiques connus...")
MSG_HASH(MSG_COMPILED_AGAINST_API,
      "Compilé depuis l'API")
MSG_HASH(MSG_CONFIG_DIRECTORY_NOT_SET,
      "Répertoire de configuration non défini. Impossible de sauvegarder le nouveau fichier.")
MSG_HASH(MSG_CONNECTED_TO,
      "Connecté à")
MSG_HASH(MSG_CONTENT_CRC32S_DIFFER,
      "Le contenu du CRC32 est différent. Impossible d'utiliser des jeux non-identiques.")
MSG_HASH(MSG_CONTENT_LOADING_SKIPPED_IMPLEMENTATION_WILL_DO_IT,
      "Chargement du contenu ignoré. L'implémentation va le charger d'elle-même.")
MSG_HASH(MSG_CORE_DOES_NOT_SUPPORT_SAVESTATES,
      "Le core ne supporte pas les savestates.")
MSG_HASH(MSG_CORE_OPTIONS_FILE_CREATED_SUCCESSFULLY,
      "Le fichier d'options du cœur a été créé.")
MSG_HASH(MSG_COULD_NOT_FIND_ANY_NEXT_DRIVER,
      "Impossible de trouver d'autre pilote.")
MSG_HASH(MSG_COULD_NOT_FIND_COMPATIBLE_SYSTEM,
      "Impossible de trouver un système compatible.")
MSG_HASH(MSG_COULD_NOT_FIND_VALID_DATA_TRACK,
      "Impossible de trouver de données valides.")
MSG_HASH(MSG_COULD_NOT_OPEN_DATA_TRACK,
      "could not open data track")
MSG_HASH(MSG_COULD_NOT_READ_CONTENT_FILE,
      "Impossible de lire le contenu du fichier")
MSG_HASH(MSG_COULD_NOT_READ_MOVIE_HEADER,
      "Impossible de lire l'entête du film.")
MSG_HASH(MSG_COULD_NOT_READ_STATE_FROM_MOVIE,
      "Impossible de lire l'état du film.")
MSG_HASH(MSG_CRC32_CHECKSUM_MISMATCH,
      "Le checksum du CRC32 est différrent entre le contenu du fichier et celui des données sauvegardées dans l'entête du fichier de replay. le replay a de grandes chances de se désynchroniser à la lecture.")
MSG_HASH(MSG_CUSTOM_TIMING_GIVEN,
      "Temps personnalisé attribué")
MSG_HASH(MSG_DECOMPRESSION_ALREADY_IN_PROGRESS,
      "Décompression en cours.")
MSG_HASH(MSG_DECOMPRESSION_FAILED,
      "Échec de la décompression.")
MSG_HASH(MSG_DETECTED_VIEWPORT_OF,
      "Détection du visuel")
MSG_HASH(MSG_DID_NOT_FIND_A_VALID_CONTENT_PATCH,
      "Impossible de trouver un patch de contenu valide.")
MSG_HASH(MSG_DISCONNECT_DEVICE_FROM_A_VALID_PORT,
      "Déconnexion du périphérique depuis un port valide.")
MSG_HASH(MSG_DISK_CLOSED,
      "Fermé")
MSG_HASH(MSG_DISK_EJECTED,
      "Éjecté")
MSG_HASH(MSG_DOWNLOADING,
      "Téléchargement")
MSG_HASH(MSG_DOWNLOAD_FAILED,
      "Échec du téléchargement")
MSG_HASH(MSG_ERROR,
      "Erreur")
MSG_HASH(MSG_ERROR_LIBRETRO_CORE_REQUIRES_CONTENT,
      "Le cœur Libretro nécessite un contenu, or aucun n'a été fourni.")
MSG_HASH(MSG_ERROR_LIBRETRO_CORE_REQUIRES_SPECIAL_CONTENT,
      "Le cœur Libretro nécessite un contenu spécial, or aucun n'a été fourni.")
MSG_HASH(MSG_ERROR_PARSING_ARGUMENTS,
      "Erreur lors de l'analyse des arguments.")
MSG_HASH(MSG_ERROR_SAVING_CORE_OPTIONS_FILE,
      "Erreur lors de l'enregistrement du fichier d'option du cœur.")
MSG_HASH(MSG_ERROR_SAVING_REMAP_FILE,
      "Erreur lors de l'enregistrement du fichier de remap.")
MSG_HASH(MSG_ERROR_SAVING_SHADER_PRESET,
      "Erreur lors de l'enregistrement du preset de shader.")
MSG_HASH(MSG_EXTERNAL_APPLICATION_DIR,
      "Répertoire d'application externe.")
MSG_HASH(MSG_EXTRACTING,
      "Extraction")
MSG_HASH(MSG_EXTRACTING_FILE,
      "Fichier en cours d'extraction")
MSG_HASH(MSG_FAILED_SAVING_CONFIG_TO,
      "Erreur lors de la sauvegarde de la configuration vers")
MSG_HASH(MSG_FAILED_TO,
      "Échec de")
MSG_HASH(MSG_FAILED_TO_ACCEPT_INCOMING_SPECTATOR,
      "Échec de l'accueil du spectateur entrant.")
MSG_HASH(MSG_FAILED_TO_ALLOCATE_MEMORY_FOR_PATCHED_CONTENT,
      "Échec d'allocation mémoire pour le contenu patché...")
MSG_HASH(MSG_FAILED_TO_APPLY_SHADER,
      "Impossible d'appliquer le shader.")
MSG_HASH(MSG_FAILED_TO_BIND_SOCKET,
      "Échec d'attribution du socket.")
MSG_HASH(MSG_FAILED_TO_CREATE_THE_DIRECTORY,
      "Échec de création du répertoire.")
MSG_HASH(MSG_FAILED_TO_EXTRACT_CONTENT_FROM_COMPRESSED_FILE,
      "Échec de l'extraction du contenu depuis le fichier compressé.")
MSG_HASH(MSG_FAILED_TO_GET_NICKNAME_FROM_CLIENT,
      "Échec d'obtention du pseudo depuis le client.")
MSG_HASH(MSG_FAILED_TO_LOAD,
      "Échec du chargement")
MSG_HASH(MSG_FAILED_TO_LOAD_CONTENT,
      "Échec du chargement du fichier")
MSG_HASH(MSG_FAILED_TO_LOAD_MOVIE_FILE,
      "Échec du chargement du fichier vidéo")
MSG_HASH(MSG_FAILED_TO_LOAD_OVERLAY,
      "Impossible de charger l'overlay.")
MSG_HASH(MSG_FAILED_TO_LOAD_STATE,
      "Impossible de charger la savestate à partir de")
MSG_HASH(MSG_FAILED_TO_OPEN_LIBRETRO_CORE,
      "Échec de l'ouverture du cœur Libretro")
MSG_HASH(MSG_FAILED_TO_PATCH,
      "Échec du patch")
MSG_HASH(MSG_FAILED_TO_RECEIVE_HEADER_FROM_CLIENT,
      "Échec de l'obtention de l'entête depuis le client.")
MSG_HASH(MSG_FAILED_TO_RECEIVE_NICKNAME,
      "Échec de l'obtention du pseudo.")
MSG_HASH(MSG_FAILED_TO_RECEIVE_NICKNAME_FROM_HOST,
      "Échec de l'obtention du pseudo depuis l'hôte.")
MSG_HASH(MSG_FAILED_TO_RECEIVE_NICKNAME_SIZE_FROM_HOST,
      "Échec de l'obtention de la taille du pseudo depuis l'hôte.")
MSG_HASH(MSG_FAILED_TO_RECEIVE_SRAM_DATA_FROM_HOST,
      "Échec de l'obtention des données SRAM depuis l'hôte.")
MSG_HASH(MSG_FAILED_TO_REMOVE_DISK_FROM_TRAY,
      "Impossible d'éjecter le disque du lecteur.")
MSG_HASH(MSG_FAILED_TO_REMOVE_TEMPORARY_FILE,
      "Impossible de supprimer le fichier temporaire")
MSG_HASH(MSG_FAILED_TO_SAVE_SRAM,
      "Impossible de sauvegarder la SRAM")
MSG_HASH(MSG_FAILED_TO_SAVE_STATE_TO,
      "Impossible de sauvegarder la savestate vers")
MSG_HASH(MSG_FAILED_TO_SEND_NICKNAME,
      "Échec de l'envoi du pseudo.")
MSG_HASH(MSG_FAILED_TO_SEND_NICKNAME_SIZE,
      "Échec de l'envoi de la taille du pseudo.")
MSG_HASH(MSG_FAILED_TO_SEND_NICKNAME_TO_CLIENT,
      "Échec de l'envoi du pseudo vers le client.")
MSG_HASH(MSG_FAILED_TO_SEND_NICKNAME_TO_HOST,
      "Échec de l'envoi du pseudo vers l'hôte.")
MSG_HASH(MSG_FAILED_TO_SEND_SRAM_DATA_TO_CLIENT,
      "Échec de l'envoi des données SRAM au client.")
MSG_HASH(MSG_FAILED_TO_START_AUDIO_DRIVER,
      "Échec du démarrage du pilote audio. Pas de son.")
MSG_HASH(MSG_FAILED_TO_START_MOVIE_RECORD,
      "Impossible de démarrer l'enregistrement vidéo.")
MSG_HASH(MSG_FAILED_TO_START_RECORDING,
      "Échec de l'activation de l'enregistrement.")
MSG_HASH(MSG_FAILED_TO_TAKE_SCREENSHOT,
      "Échec de la copie d'écran.")
MSG_HASH(MSG_FAILED_TO_UNDO_LOAD_STATE,
      "Aucun savestate de retour arrière trouvé")
MSG_HASH(MSG_FAILED_TO_UNDO_SAVE_STATE,
      "Impossible de sauvegarder les informations de savestate de retour arrière")
MSG_HASH(MSG_FAILED_TO_UNMUTE_AUDIO,
      "Impossible de remettre le son.")
MSG_HASH(MSG_FATAL_ERROR_RECEIVED_IN,
      "Erreur fatale dans")
MSG_HASH(MSG_FILE_NOT_FOUND,
      "Fichier non trouvé.")
MSG_HASH(MSG_FOUND_AUTO_SAVESTATE_IN,
      "Savestate automatique trouvée dans")
MSG_HASH(MSG_FOUND_DISK_LABEL,
      "Étiquette du disque trouvée")
MSG_HASH(MSG_FOUND_FIRST_DATA_TRACK_ON_FILE,
      "Première piste de données trouvée sur le fichier")
MSG_HASH(MSG_FOUND_LAST_STATE_SLOT,
      "Dernier emplacement d'état trouvé")
MSG_HASH(MSG_FOUND_SHADER,
      "Shader trouvé")
MSG_HASH(MSG_FRAMES,
      "Images")
MSG_HASH(MSG_GAME_SPECIFIC_CORE_OPTIONS_FOUND_AT,
      "Options par jeu : options de cœur pour le jeu trouvées dans")
MSG_HASH(MSG_GOT_INVALID_DISK_INDEX,
      "Index du disque invalide.")
MSG_HASH(MSG_GRAB_MOUSE_STATE,
      "Capture la souris")
MSG_HASH(MSG_HW_RENDERED_MUST_USE_POSTSHADED_RECORDING,
      "Le core Libretro utilise le rendu matériel. Obligation d'utiliser également l'enregistrement post-shaded.")
MSG_HASH(MSG_INFLATED_CHECKSUM_DID_NOT_MATCH_CRC32,
      "Le checksum gonflé ne correspond pas au CRC32.")
MSG_HASH(MSG_INPUT_CHEAT,
      "Saisir le code de triche")
MSG_HASH(MSG_INPUT_CHEAT_FILENAME,
      "Nom du fichier de triche")
MSG_HASH(MSG_INPUT_PRESET_FILENAME,
      "Nom du fichier preset")
MSG_HASH(MSG_INTERFACE,
      "Interface")
MSG_HASH(MSG_INTERNAL_STORAGE,
      "Stockage interne")
MSG_HASH(MSG_REMOVABLE_STORAGE,
      "Stockage amovible")
MSG_HASH(MSG_INVALID_NICKNAME_SIZE,
      "Taille du pseudo non-valide.")
MSG_HASH(MSG_IN_BYTES,
      "en octets")
MSG_HASH(MSG_IN_GIGABYTES,
      "en gigaoctets")
MSG_HASH(MSG_IN_MEGABYTES,
      "en mégaoctets")
MSG_HASH(MSG_LIBRETRO_ABI_BREAK,
      "est compilé avec une version différente de la bibliothèque libretro actuelle.")
MSG_HASH(MSG_LIBRETRO_FRONTEND,
      "Frontend pour libretro")
MSG_HASH(MSG_LOADED_STATE_FROM_SLOT,
      "Chargement du savestate à partir du slot #%d.")
MSG_HASH(MSG_LOADED_STATE_FROM_SLOT_AUTO,
      "Chargement du savestate à partir du slot #-1 (auto).")
MSG_HASH(MSG_LOADING,
      "Chargement")
MSG_HASH(MSG_FIRMWARE,
      "Un ou plusieurs firmware sont manquants")
MSG_HASH(MSG_LOADING_CONTENT_FILE,
      "Chargement du contenu")
MSG_HASH(MSG_LOADING_HISTORY_FILE,
      "Chargement du fichier d'historique")
MSG_HASH(MSG_LOADING_STATE,
      "Chargement savestate")
MSG_HASH(MSG_MEMORY,
      "Mémoire")
MSG_HASH(MSG_MOVIE_FILE_IS_NOT_A_VALID_BSV1_FILE,
      "Le fichier vidéo n'est pas un fichier BSV1 valide.")
MSG_HASH(MSG_MOVIE_FORMAT_DIFFERENT_SERIALIZER_VERSION,
      "Le format du film semble avoir une version de sérialisateur différent. Échec très probable.")
MSG_HASH(MSG_MOVIE_PLAYBACK_ENDED,
      "Fin de la lecture vidéo")
MSG_HASH(MSG_MOVIE_RECORD_STOPPED,
      "Arrêt de l'enregistrement vidéo.")
MSG_HASH(MSG_NETPLAY_FAILED,
      "Échec de l'initialisation du jeu en réseau")
MSG_HASH(MSG_NO_CONTENT_STARTING_DUMMY_CORE,
      "Aucun contenu, chargement d'un cœur factice.")
MSG_HASH(MSG_NO_SAVE_STATE_HAS_BEEN_OVERWRITTEN_YET,
      "Aucun état de sauvegarde n'a été écrasé pour l'instant.")
MSG_HASH(MSG_NO_STATE_HAS_BEEN_LOADED_YET,
      "Aucun état n'a été chargé pour l'instant.")
MSG_HASH(MSG_OVERRIDES_ERROR_SAVING,
      "Erreur lors de l'enregistrement des overrides.")
MSG_HASH(MSG_OVERRIDES_SAVED_SUCCESSFULLY,
      "Les overrides ont été sauvegardés.")
MSG_HASH(MSG_PAUSED,
      "Pause.")
MSG_HASH(MSG_PROGRAM,
      "RetroArch")
MSG_HASH(MSG_READING_FIRST_DATA_TRACK,
      "lecture de la première piste de données...")
MSG_HASH(MSG_RECEIVED,
      "Reçu")
MSG_HASH(MSG_RECORDING_TERMINATED_DUE_TO_RESIZE,
      "Enregistrement interrompu à cause du redimensionnement.")
MSG_HASH(MSG_RECORDING_TO,
      "Enregistrement vers")
MSG_HASH(MSG_REDIRECTING_CHEATFILE_TO,
      "Redirection du fichier triche vers")
MSG_HASH(MSG_REDIRECTING_SAVEFILE_TO,
      "Redirection de la sauvegarde vers")
MSG_HASH(MSG_REDIRECTING_SAVESTATE_TO,
      "Redirection de la savestate vers")
MSG_HASH(MSG_REMAP_FILE_SAVED_SUCCESSFULLY,
      "Fichier de remap sauvegardé.")
MSG_HASH(MSG_REMOVED_DISK_FROM_TRAY,
      "Éjection du disque du lecteur.")
MSG_HASH(MSG_REMOVING_TEMPORARY_CONTENT_FILE,
      "Suppression du fichier temporaire")
MSG_HASH(MSG_RESET,
      "Réinitialisation")
MSG_HASH(MSG_RESTARTING_RECORDING_DUE_TO_DRIVER_REINIT,
      "Redémarrage de l'enregistrement à cause de la réinitialisation du pilote.")
MSG_HASH(MSG_RESTORED_OLD_SAVE_STATE,
      "Ancienne save state restaurée.")
MSG_HASH(MSG_RESTORING_DEFAULT_SHADER_PRESET_TO,
      "Shaders : restauration du preset de shader par défaut vers")
MSG_HASH(MSG_REVERTING_SAVEFILE_DIRECTORY_TO,
      "Annulation des changements du répertoire de sauvegarde vers")
MSG_HASH(MSG_REVERTING_SAVESTATE_DIRECTORY_TO,
      "Annulation des changements du répertoire de savestate vers")
MSG_HASH(MSG_REWINDING,
      "Rembobinage.")
MSG_HASH(MSG_REWIND_INIT,
      "Initialisation du tampon pour le retour rapide avec une taille")
MSG_HASH(MSG_REWIND_INIT_FAILED,
      "Échec de l'initialisation du tampon pour le retour rapide. Cette fonctionnalité sera désactivée.")
MSG_HASH(MSG_REWIND_INIT_FAILED_THREADED_AUDIO,
      "L'implémentation utilise audio thread. Impossible d'activer le retour rapide.")
MSG_HASH(MSG_REWIND_REACHED_END,
      "Atteinte de la fin du tampon de rembobinage.")
MSG_HASH(MSG_SAVED_NEW_CONFIG_TO,
      "Nouvelle configuration sauvegardée vers")
MSG_HASH(MSG_SAVED_STATE_TO_SLOT,
      "Savestate vers slot #%d.")
MSG_HASH(MSG_SAVED_STATE_TO_SLOT_AUTO,
      "Savestate vers slot #-1 (auto).")
MSG_HASH(MSG_SAVED_SUCCESSFULLY_TO,
      "Sauvegarde réussie vers")
MSG_HASH(MSG_SAVING_RAM_TYPE,
      "Sauvegarde du type de RAM")
MSG_HASH(MSG_SAVING_STATE,
      "Sauvegarde savestate")
MSG_HASH(MSG_SCANNING,
      "Analyse")
MSG_HASH(MSG_SCANNING_OF_DIRECTORY_FINISHED,
      "Analyse des dossiers terminée")
MSG_HASH(MSG_SENDING_COMMAND,
      "Envoi commande")
MSG_HASH(MSG_SEVERAL_PATCHES_ARE_EXPLICITLY_DEFINED,
      "Plusieurs patches sont définis explicitement, ignore tout...")
MSG_HASH(MSG_SHADER,
      "Shader")
MSG_HASH(MSG_SHADER_PRESET_SAVED_SUCCESSFULLY,
      "Preset de shader sauvegardé.")
MSG_HASH(MSG_SKIPPING_SRAM_LOAD,
      "Ignore le chargement de la SRAM.")
MSG_HASH(MSG_SLOW_MOTION,
      "Ralenti.")
MSG_HASH(MSG_SLOW_MOTION_REWIND,
      "Rembobinage ralenti.")
MSG_HASH(MSG_SRAM_WILL_NOT_BE_SAVED,
      "SRAM ne sera pas sauvegardée.")
MSG_HASH(MSG_STARTING_MOVIE_PLAYBACK,
      "Démarrage de la lecture vidéo.")
MSG_HASH(MSG_STARTING_MOVIE_RECORD_TO,
      "Démarrage de l'enregistrement vidéo vers")
MSG_HASH(MSG_STATE_SIZE,
      "Taille savestate")
MSG_HASH(MSG_STATE_SLOT,
      "Emplacement d'état")
MSG_HASH(MSG_TAKING_SCREENSHOT,
      "Réalisation d'une copie d'écran.")
MSG_HASH(MSG_TO,
      "de")
MSG_HASH(MSG_UNDID_LOAD_STATE,
      "Chargement d'état annulé.")
MSG_HASH(MSG_UNDOING_SAVE_STATE,
      "Annulation de la savestate")
MSG_HASH(MSG_UNKNOWN,
      "Inconnu")
MSG_HASH(MSG_UNPAUSED,
      "Relancé.")
MSG_HASH(MSG_UNRECOGNIZED_COMMAND,
      "Commande non reconnue")
MSG_HASH(MSG_USING_CORE_NAME_FOR_NEW_CONFIG,
      "Utilisation du nom du cœur pour la nouvelle configuration.")
MSG_HASH(MSG_USING_LIBRETRO_DUMMY_CORE_RECORDING_SKIPPED,
      "Utilisation d'un core libretro simple. Ignore l'enregistrement.")
MSG_HASH(MSG_VALUE_CONNECT_DEVICE_FROM_A_VALID_PORT,
      "Connecter le périphérique depuis un port valide.")
MSG_HASH(MSG_VALUE_DISCONNECTING_DEVICE_FROM_PORT,
      "Déconnexion du périphérique du port")
MSG_HASH(MSG_VALUE_REBOOTING,
      "Redémarrage...")
MSG_HASH(MSG_VALUE_SHUTTING_DOWN,
      "Extinction en cours...")
MSG_HASH(MSG_VERSION_OF_LIBRETRO_API,
      "Version de l'API libretro")
MSG_HASH(MSG_VIEWPORT_SIZE_CALCULATION_FAILED,
      "Échec du calcul de la taille du visuel ! Utilisation des données brutes. Cela ne fonctionnera probablement pas bien ...")
MSG_HASH(MSG_VIRTUAL_DISK_TRAY,
      "Lecteur de disque virtuel.")
MSG_HASH(MENU_ENUM_SUBLABEL_AUDIO_LATENCY,
      "Latence audio désirée en millisecondes. Peut être ignorée si le pilote audio ne peut fournir une telle valeur.")
MSG_HASH(MENU_ENUM_SUBLABEL_AUDIO_MUTE,
      "Sourdine activée / désactivée.")
MSG_HASH(
      MENU_ENUM_SUBLABEL_AUDIO_RATE_CONTROL_DELTA,
      "Aide à lisser les imperfections de timing lors de la synchronisation audio et vidéo. Attention, si désactivé, une synchronisation correcte est quasiment impossible."
      )
MSG_HASH(
      MENU_ENUM_SUBLABEL_CAMERA_ALLOW,
      "Autorise ou empêche l'accès à la caméra par les cœurs."
      )
MSG_HASH(
      MENU_ENUM_SUBLABEL_LOCATION_ALLOW,
      "Autorise ou empêche l'accès aux services de localication par les cœurs."
      )
MSG_HASH(
      MENU_ENUM_SUBLABEL_INPUT_MAX_USERS,
      "Nombre maximum d'utilisateurs supportés par RetroArch."
      )
MSG_HASH(
      MENU_ENUM_SUBLABEL_INPUT_POLL_TYPE_BEHAVIOR,
      "Influence la façon dont le polling des entrées est fait au sein de RetroArch. Le mettre sur 'Tôt' ou 'Tard' peut diminuer la latence, selon la configuration de la machine."
      )
MSG_HASH(
      MENU_ENUM_SUBLABEL_INPUT_ALL_USERS_CONTROL_MENU,
      "Autorise n'importe quel utilisateur à contrôler le menu. Si désactivé, seul l'utilisateur n°1 peut contrôler le menu."
      )
MSG_HASH(
      MENU_ENUM_SUBLABEL_AUDIO_VOLUME,
      "Volume sonore (en dB). 0 dB correspond au volume normal, aucun gain n'est appliqué."
      )
MSG_HASH(
   MENU_ENUM_SUBLABEL_AUDIO_SYNC,
   "Synchronise l'audio. Recommandé."
   )
MSG_HASH(
   MENU_ENUM_SUBLABEL_INPUT_AXIS_THRESHOLD,
   "Indique à quel point un axe doit être poussé avant d'obtenir une pression sur un bouton."
   )
MSG_HASH(
   MENU_ENUM_SUBLABEL_INPUT_BIND_TIMEOUT,
   "Nombre de secondes à attendre avant de passer à l'assignation suivante."
   )
MSG_HASH(
   MENU_ENUM_SUBLABEL_INPUT_TURBO_PERIOD,
   "Décrit la période après laquelle les boutons turbos s'activent. Les nombres sont décrits en frames."
   )
MSG_HASH(
   MENU_ENUM_SUBLABEL_INPUT_DUTY_CYCLE,
   "Décrit la durée pendant laquelle un bouton turbo est activé. Les nombres sont décrits en frames."
   )
MSG_HASH(
   MENU_ENUM_SUBLABEL_VIDEO_VSYNC,
   "Synchronise la sortie vidéo de la carte graphique au taux de rafraîchissement de l'écran. Recommandé."
   )
MSG_HASH(
   MENU_ENUM_SUBLABEL_VIDEO_ALLOW_ROTATE,
   "Autorise les cœurs à définir la rotation. Lorsque cette option est désactivée, les requêtes de rotation sont ignorées. Utile pour les configurations où il faut tourner l'écran à la main."
   )
MSG_HASH(
   MENU_ENUM_SUBLABEL_DUMMY_ON_CORE_SHUTDOWN,
   "Certains cœurs ont une fonctionnalité d'extinction. Si activée, cette option empêchera le cœur d'éteindre RetroArch. À la place, il lancera un cœur factice."
   )
MSG_HASH(
   MENU_ENUM_SUBLABEL_CHECK_FOR_MISSING_FIRMWARE,
   "Vérifie que tous les firmwares requis sont présents avant de tenter de charger le contenu."
   )
MSG_HASH(
   MENU_ENUM_SUBLABEL_VIDEO_REFRESH_RATE,
   "rafraîchissement vertical de l'écran. Utilisé pour calculer un taux adapté pour l'entrée audio. NOTE : cette option est ignorée lorsque 'vidéo threadée' est activée."
   )
MSG_HASH(
   MENU_ENUM_SUBLABEL_AUDIO_ENABLE,
   "Active la sortie audio."
   )
MSG_HASH(
   MENU_ENUM_SUBLABEL_AUDIO_MAX_TIMING_SKEW,
   "Changement maximal possible du taux de l'entrée audio. Cette valeur peut être augmentée pour autoriser de très grands changements de timing, par exemple pour exécuter un cœur PAL sur un écran NTSC, au prix d'un pitch audio imprécis."
   )
MSG_HASH(
   MSG_FAILED,
   "échec"
   )
MSG_HASH(
   MSG_SUCCEEDED,
   "succès"
   )
MSG_HASH(
   MSG_DEVICE_NOT_CONFIGURED,
   "non configuré"
   )
MSG_HASH(
   MSG_DEVICE_NOT_CONFIGURED_FALLBACK,
   "non configuré, utilisation du fallback"
   )
MSG_HASH(
   MENU_ENUM_LABEL_VALUE_DATABASE_CURSOR_LIST,
   "Liste de curseurs de la base de données"
   )
MSG_HASH(
   MENU_ENUM_LABEL_VALUE_DATABASE_CURSOR_LIST_ENTRY_DEVELOPER,
   "Base de données - Filtre : Développeur"
   )
MSG_HASH(
   MENU_ENUM_LABEL_VALUE_DATABASE_CURSOR_LIST_ENTRY_PUBLISHER,
   "Base de données - Filtre : Éditeur"
   )
MSG_HASH(
   MENU_ENUM_LABEL_VALUE_DISABLED,
   "Désactivé"
   )
MSG_HASH(
   MENU_ENUM_LABEL_VALUE_ENABLED,
   "Activé"
   )
MSG_HASH(
   MENU_ENUM_LABEL_VALUE_CONTENT_HISTORY_PATH,
   "Patch de l'historique du contenu"
   )
MSG_HASH(
      MENU_ENUM_LABEL_DATABASE_CURSOR_LIST_ENTRY_ORIGIN,
      "Base de données - Filtre : Origine")
MSG_HASH(MENU_ENUM_LABEL_DATABASE_CURSOR_LIST_ENTRY_FRANCHISE,
      "Base de données - Filtre : Franchise")
MSG_HASH(MENU_ENUM_LABEL_DATABASE_CURSOR_LIST_ENTRY_ESRB_RATING,
      "Base de données - Filtre : Classification ESRB")
MSG_HASH(MENU_ENUM_LABEL_DATABASE_CURSOR_LIST_ENTRY_ELSPA_RATING,
      "Base de données - Filtre : Classification ALSPA")
MSG_HASH(MENU_ENUM_LABEL_DATABASE_CURSOR_LIST_ENTRY_PEGI_RATING,
      "Base de données - Filtre : Classification PEGI")
MSG_HASH(MENU_ENUM_LABEL_DATABASE_CURSOR_LIST_ENTRY_CERO_RATING,
      "Base de données - Filtre : Classification CERO")
MSG_HASH(MENU_ENUM_LABEL_DATABASE_CURSOR_LIST_ENTRY_BBFC_RATING,
      "Base de données - Filtre : Classification BBFC")
MSG_HASH(MENU_ENUM_LABEL_DATABASE_CURSOR_LIST_ENTRY_MAX_USERS,
      "Base de données - Filtre : Utilisateurs Max")
MSG_HASH(MENU_ENUM_LABEL_DATABASE_CURSOR_LIST_ENTRY_RELEASEDATE_BY_MONTH,
      "Base de données - Filtre : Datedesortie Par Mois")
MSG_HASH(MENU_ENUM_LABEL_DATABASE_CURSOR_LIST_ENTRY_RELEASEDATE_BY_YEAR,
      "Base de données - Filtre : Datedesortie Par Année")
MSG_HASH(MENU_ENUM_LABEL_DATABASE_CURSOR_LIST_ENTRY_EDGE_MAGAZINE_ISSUE,
      "Base de données - Filtre : Numéro du Magazine Edge")
MSG_HASH(MENU_ENUM_LABEL_DATABASE_CURSOR_LIST_ENTRY_EDGE_MAGAZINE_RATING,
      "Base de données - Filtre : Note du Magazine Edge")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DATABASE_CURSOR_LIST_ENTRY_DATABASE_INFO,
      "info Base de données")
MSG_HASH(MENU_ENUM_SUBLABEL_PAUSE_NONACTIVE,
      "Mettre en pause le jeu lorsque le focus de la fenêtre est perdu.")
MSG_HASH(MENU_ENUM_SUBLABEL_VIDEO_DISABLE_COMPOSITION,
      "Activer ou désactiver le compositeur (Windows seulement).")
MSG_HASH(MENU_ENUM_SUBLABEL_HISTORY_LIST_ENABLE,
      "Activer ou désactiver l'historique pour les jeux, les images, la musique et les vidéos.")
MSG_HASH(MENU_ENUM_SUBLABEL_CONTENT_HISTORY_SIZE,
      "Limiter le nombre d'entrées dans l'historique pour les jeux, les images, la musique et les vidéos.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_UNIFIED_MENU_CONTROLS,
      "Contrôles du menu unifiés")
MSG_HASH(MENU_ENUM_SUBLABEL_INPUT_UNIFIED_MENU_CONTROLS,
      "Utiliser les mêmes contrôles à la fois pour le menu et pour le jeu. S'applique au clavier.")
MSG_HASH(MENU_ENUM_SUBLABEL_VIDEO_FONT_ENABLE,
      "Afficher les messages à l'écran.")
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BROWSE_URL_LIST,
      "Parcourir l'URL"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BROWSE_URL,
      "Chemin de l'URL"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BROWSE_START,
      "Démarrer"
      )
MSG_HASH(MENU_ENUM_LABEL_VALUE_SHADER_PIPELINE_BOKEH,
      "Bokeh")
