#if defined(_MSC_VER) && !defined(_XBOX)
/* https://support.microsoft.com/en-us/kb/980263 */
#pragma execution_character_set("utf-8")
#endif

MSG_HASH(
      MSG_COMPILER,
      "Компилятор"
      )
MSG_HASH(
      MSG_UNKNOWN_COMPILER,
      "Неизвестный компилятор"
      )
MSG_HASH(
      MSG_DEVICE_DISCONNECTED_FROM_PORT,
      "Устройство отключено от порта"
      )
MSG_HASH(
      MSG_UNKNOWN_NETPLAY_COMMAND_RECEIVED,
      "Неизвестная команда netplay"
      )
MSG_HASH(
      MSG_FILE_ALREADY_EXISTS_SAVING_TO_BACKUP_BUFFER,
      "Файл уже существует. Сохранение в резервном буфере"
      )
MSG_HASH(
      MSG_GOT_CONNECTION_FROM,
      "Установленно  соединение с: \"%s\""
      )
MSG_HASH(
      MSG_GOT_CONNECTION_FROM_NAME,
      "Установленно  соединение с: \"%s (%s)\""
      )
MSG_HASH(
      MSG_NO_ARGUMENTS_SUPPLIED_AND_NO_MENU_BUILTIN,
      "Нет аргументов и встроенного меню,отображается справка..."
      )
MSG_HASH(
      MSG_NETPLAY_USERS_HAS_FLIPPED,
      "Netplay users has flipped"
      )
MSG_HASH(
      MSG_SETTING_DISK_IN_TRAY,
      "Установка диска в привод"
      )
MSG_HASH(
      MSG_WAITING_FOR_CLIENT,
      "Ожидание клиента ..."
      )
MSG_HASH(
      MENU_ENUM_SUBLABEL_VIDEO_SHARED_CONTEXT,
      "Предоставьте аппаратно-рендерированным ядрам собственный контекст.Избегайте принятия изменений состояния оборудования между кадрами."
      )
MSG_HASH(
      MENU_ENUM_SUBLABEL_MENU_SETTINGS,
      "Настройка параметров, относящихся к внешнему виду экрана меню."
      )
MSG_HASH(
      MENU_ENUM_SUBLABEL_VIDEO_HARD_SYNC,
      "Синхронизируйте CPU и GPU.Это улучшит производительность."
      )
MSG_HASH(
      MENU_ENUM_SUBLABEL_VIDEO_THREADED,
      "Повышает производительность за счёт понижения количества кадров в секунду. Использовать только когда другие способы не сработали."
      )
MSG_HASH(
      MSG_AUDIO_VOLUME,
      "Громкость звука"
      )
MSG_HASH(
      MSG_AUTODETECT,
      "Определять автоматически"
      )
MSG_HASH(
      MSG_AUTOLOADING_SAVESTATE_FROM,
      "Автозагрузка из"
      )
MSG_HASH(
      MSG_CAPABILITIES,
      "Возможности"
      )
MSG_HASH(
      MSG_CONNECTING_TO_NETPLAY_HOST,
      "Подключение к netplay"
      )
MSG_HASH(
      MSG_CONNECTING_TO_PORT,
      "Подключение к порту"
      )
MSG_HASH(
      MSG_CONNECTION_SLOT,
      "Слот подключения"
      )
MSG_HASH(
      MSG_SORRY_UNIMPLEMENTED_CORES_DONT_DEMAND_CONTENT_NETPLAY,
      "Sorry, unimplemented: cores that don't demand content cannot participate in netplay."
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_ACCOUNTS_CHEEVOS_PASSWORD,
      "Пароль"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_ACCOUNTS_CHEEVOS_SETTINGS,
      "Аккаунт Cheevos"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_ACCOUNTS_CHEEVOS_USERNAME,
      "Имя пользователя"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_ACCOUNTS_LIST,
      "Аккаунты"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_ACCOUNTS_LIST_END,
      "Аккаунт лист Endpoint"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_ACCOUNTS_RETRO_ACHIEVEMENTS,
      "Достижения"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_ACHIEVEMENT_LIST,
      "Список достижений"
      )


MSG_HASH(
      MENU_ENUM_LABEL_VALUE_ACHIEVEMENT_LIST_HARDCORE,
      "Список достижений (Hardcore)"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_ADD_CONTENT_LIST,
      "Результат сканирования"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CONFIGURATIONS_LIST,
      "Конфигурации"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_ADD_TAB,
      "Импорт содержимого"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_ASK_ARCHIVE,
      "Спрашивать"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_ASSETS_DIRECTORY,
      "Активы"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUDIO_BLOCK_FRAMES,
      "Блокировка фреймов"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUDIO_DEVICE,
      "Аудио-устройство"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUDIO_DRIVER,
      "Аудио драйвер"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUDIO_DSP_PLUGIN,
      "Аудио DSP Plugin"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUDIO_ENABLE,
      "Включить звук"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUDIO_FILTER_DIR,
      "Аудио фильтр"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_TURBO_DEADZONE_LIST,
      "Turbo/Deadzone"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUDIO_LATENCY,
      "Задержка звука (ms)"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUDIO_MAX_TIMING_SKEW,
      "Максимальный тайминг синхронизации аудио-сигнала"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUDIO_MUTE,
      "Выключить звук"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUDIO_OUTPUT_RATE,
      "Частота аудиовыхода (KHz)"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUDIO_RATE_CONTROL_DELTA,
      "Динамический контроль скорости звука"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUDIO_RESAMPLER_DRIVER,
      "Драйвер аудиоразъема"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUDIO_SETTINGS,
      "Аудио"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUDIO_SYNC,
      "Синхронизация звука"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUDIO_VOLUME,
      "Уровень громкости звука (dB)"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUTOSAVE_INTERVAL,
      "Интервал авто-сохранений"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUTO_OVERRIDES_ENABLE,
      "Переопределить файлы загрузки"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUTO_REMAPS_ENABLE,
      "Load Remap Files Automatically"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_AUTO_SHADERS_ENABLE,
      "Автоматическая загрузка преднастройки шейдеров"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BASIC_MENU_CONTROLS_BACK,
      "Назад"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BASIC_MENU_CONTROLS_CONFIRM,
      "Подтвердить"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BASIC_MENU_CONTROLS_INFO,
      "Инфо"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BASIC_MENU_CONTROLS_QUIT,
      "Выйти"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BASIC_MENU_CONTROLS_SCROLL_DOWN,
      "Прокрутить вниз"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BASIC_MENU_CONTROLS_SCROLL_UP,
      "Прокрутить вверх"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BASIC_MENU_CONTROLS_START,
      "Старт"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BASIC_MENU_CONTROLS_TOGGLE_KEYBOARD,
      "Переключить клавиатуру"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BASIC_MENU_CONTROLS_TOGGLE_MENU,
      "Переключить меню"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BASIC_MENU_ENUM_CONTROLS,
      "Базовые элементы управления меню"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BASIC_MENU_ENUM_CONTROLS_CONFIRM,
      "Подтвердить"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BASIC_MENU_ENUM_CONTROLS_INFO,
      "Инфо"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BASIC_MENU_ENUM_CONTROLS_QUIT,
      "Выйти"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BASIC_MENU_ENUM_CONTROLS_SCROLL_UP,
      "Прокрутить вверх"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BASIC_MENU_ENUM_CONTROLS_START,
      "По умолчанию"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BASIC_MENU_ENUM_CONTROLS_TOGGLE_KEYBOARD,
      "Переключить клавиатуру"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BASIC_MENU_ENUM_CONTROLS_TOGGLE_MENU,
      "Переключить меню"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BLOCK_SRAM_OVERWRITE,
      "Не перезаписывать SaveRAM при загрузке сохранений"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BLUETOOTH_ENABLE,
      "Bluetooth Включить"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BUILDBOT_ASSETS_URL,
      "Создание ботов URL"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CACHE_DIRECTORY,
      "Кэш"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CAMERA_ALLOW,
      "Разрешить использовать камеру"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CAMERA_DRIVER,
      "Драйвер камеры"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CHEAT,
      "Чит"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CHEAT_APPLY_CHANGES,
      "Применить изменения чита"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CHEAT_DATABASE_PATH,
      "Чит-файл"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CHEAT_FILE,
      "Чит-файл"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CHEAT_FILE_LOAD,
      "Загрузить чит-файл"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CHEAT_FILE_SAVE_AS,
      "Сохранить чит файл как:"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CHEAT_NUM_PASSES,
      "Пропуск чита"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CHEEVOS_DESCRIPTION,
      "Описание"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CHEEVOS_HARDCORE_MODE_ENABLE,
      "Достижения в Hardcore Mode"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CHEEVOS_LOCKED_ACHIEVEMENTS,
      "Заблокированные Достижения:"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CHEEVOS_LOCKED_ENTRY,
      "Заблокировано"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CHEEVOS_SETTINGS,
      "Достижения"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CHEEVOS_TEST_UNOFFICIAL,
      "Тестовые Неофициальные Достижения"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CHEEVOS_UNLOCKED_ACHIEVEMENTS,
      "Разблокированные достижения:"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CHEEVOS_UNLOCKED_ENTRY,
      "Разблокирован"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CLOSE_CONTENT,
      "Закрыть"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CONFIG,
      "Конфигурация"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CONFIGURATIONS,
      "Загрузить конфигурацию"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CONFIGURATION_SETTINGS,
      "Конфигурация"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CONFIG_SAVE_ON_EXIT,
      "Сохранить конфигурацию и выйти"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CONTENT_COLLECTION_LIST,
      "Коллекции"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CONTENT_DATABASE_DIRECTORY,
      "База Данных контента"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CONTENT_DIR,
      "Контент"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_CONTENT_HISTORY_SIZE,
      "Размер списка истории")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CONTENT_SETTINGS,
      "Выйти из меню")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_ASSETS_DIR,
      "Основные средства")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_ASSETS_DIRECTORY,
      "Загрузки")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_CHEAT_OPTIONS,
      "Читы")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_COUNTERS,
      "Основной счётчик")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_ENABLE,
      "Отобразить имя основного средства")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_INFORMATION,
      "Основная информация")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_INFO_AUTHORS,
      "Авторы")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_INFO_CATEGORIES,
      "Категории")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_INFO_CORE_LABEL,
      "Символ ядра")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_INFO_CORE_NAME,
      "Имя ядра")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_INFO_FIRMWARE,
      "Микропрограммы")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_INFO_LICENSES,
      "Лицензии")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_INFO_PERMISSIONS,
      "Разрешения")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_INFO_SUPPORTED_EXTENSIONS,
      "Поддерживаемые расширения")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_INFO_SYSTEM_MANUFACTURER,
      "Разработчик системы")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_INFO_SYSTEM_NAME,
      "Имя системы")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_INPUT_REMAPPING_OPTIONS,
      "Элементы управления")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_LIST,
      "Загрузка ядра")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_OPTIONS,
      "Опции")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_SETTINGS,
      "Ядро")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_SET_SUPPORTS_NO_CONTENT_ENABLE,
      "Автоматически запускать ядро")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_UPDATER_AUTO_EXTRACT_ARCHIVE,
      "Автоматически извлечь загруженный архив")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_UPDATER_BUILDBOT_URL,
      "Создание ботов URL")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_UPDATER_LIST,
      "Обновление ядра")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CORE_UPDATER_SETTINGS,
      "Обновление")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CPU_ARCHITECTURE,
      "Архитектура CPU:")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CPU_CORES,
      "Ядра CPU:")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CURSOR_DIRECTORY,
      "Курсор")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CURSOR_MANAGER,
      "Курсор менеджер")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CUSTOM_RATIO,
      "Дополнительное значение")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DATABASE_MANAGER,
      "Менеджер баз данных")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DATABASE_SELECTION,
      "Выбор баз данных")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DELETE_ENTRY,
      "Удаление")
MSG_HASH(MENU_ENUM_LABEL_VALUE_FAVORITES,
      "Избранное")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DIRECTORY_CONTENT,
      "<Каталог содержимого>")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DIRECTORY_DEFAULT,
      "<По умолчанию>")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DIRECTORY_NONE,
      "<Нет>")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DIRECTORY_NOT_FOUND,
      "Каталог не найден.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DIRECTORY_SETTINGS,
      "Каталог")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DISK_CYCLE_TRAY_STATUS,
      "Статус диска в приводе")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DISK_IMAGE_APPEND,
      "Добавить образ диска")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DISK_INDEX,
      "Индекс диска")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DISK_OPTIONS,
      "Управление диском")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DONT_CARE,
      "Не важно")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DOWNLOADED_FILE_DETECT_CORE_LIST,
      "Загрузки")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DOWNLOAD_CORE,
      "Загрузка ядра...")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DOWNLOAD_CORE_CONTENT,
      "Загрузка содержимого")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DPI_OVERRIDE_ENABLE,
      "Разрешить переопределение DPI")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DPI_OVERRIDE_VALUE,
      "DPI Переопределение")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DRIVER_SETTINGS,
      "Драйвер")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DUMMY_ON_CORE_SHUTDOWN,
      "Загрузка макета при выключении ядра")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DYNAMIC_WALLPAPER,
      "Динамические обои")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DYNAMIC_WALLPAPERS_DIRECTORY,
      "Динамические обои")
MSG_HASH(MENU_ENUM_LABEL_VALUE_CHEEVOS_ENABLE,
      "Включить достижения")
MSG_HASH(MENU_ENUM_LABEL_VALUE_ENTRY_HOVER_COLOR,
      "Цвет наведения указателя меню")
MSG_HASH(MENU_ENUM_LABEL_VALUE_ENTRY_NORMAL_COLOR,
      "Нормальный цвет ввода в меню")
MSG_HASH(MENU_ENUM_LABEL_VALUE_FALSE,
      "Выключено")
MSG_HASH(MENU_ENUM_LABEL_VALUE_FASTFORWARD_RATIO,
      "Максимальная рабочая скорость")
MSG_HASH(MENU_ENUM_LABEL_VALUE_FPS_SHOW,
      "Вывести значение FPS на экран")
MSG_HASH(MENU_ENUM_LABEL_VALUE_FRAME_THROTTLE_ENABLE,
      "Ограничить максимальную скорость работы")
MSG_HASH(MENU_ENUM_LABEL_VALUE_FRAME_THROTTLE_SETTINGS,
      "Настройка частоты кадров")
MSG_HASH(MENU_ENUM_LABEL_VALUE_FRONTEND_COUNTERS,
      "Внешние счетчики")
MSG_HASH(MENU_ENUM_LABEL_VALUE_GAME_SPECIFIC_OPTIONS,
      "Автоматически загружать основные параметры")
MSG_HASH(MENU_ENUM_LABEL_VALUE_GAME_SPECIFIC_OPTIONS_CREATE,
      "Создать файл параметров игры")
MSG_HASH(MENU_ENUM_LABEL_VALUE_GAME_SPECIFIC_OPTIONS_IN_USE,
      "Файл параметров игры")
MSG_HASH(MENU_ENUM_LABEL_VALUE_HELP,
      "Помощь")
MSG_HASH(MENU_ENUM_LABEL_VALUE_HELP_AUDIO_VIDEO_TROUBLESHOOTING,
      "Устранение проблем с аудио / видео")
MSG_HASH(MENU_ENUM_LABEL_VALUE_HELP_CHANGE_VIRTUAL_GAMEPAD,
      "Изменение обложки виртуального геймпада")
MSG_HASH(MENU_ENUM_LABEL_VALUE_HELP_CONTROLS,
      "Основные элементы управления меню")
MSG_HASH(MENU_ENUM_LABEL_VALUE_HELP_LIST,
      "Помощь")
MSG_HASH(MENU_ENUM_LABEL_VALUE_HELP_LOADING_CONTENT,
      "Загрузка содержимого")
MSG_HASH(MENU_ENUM_LABEL_VALUE_HELP_SCANNING_CONTENT,
      "Сканирование содержимого")
MSG_HASH(MENU_ENUM_LABEL_VALUE_HELP_WHAT_IS_A_CORE,
      "Что такое ядро?")
MSG_HASH(MENU_ENUM_LABEL_VALUE_HISTORY_LIST_ENABLE,
      "Список истории включен")
MSG_HASH(MENU_ENUM_LABEL_VALUE_HISTORY_TAB,
      "История")
MSG_HASH(MENU_ENUM_LABEL_VALUE_HORIZONTAL_MENU,
      "Горизонтальное меню")
MSG_HASH(MENU_ENUM_LABEL_VALUE_IMAGES_TAB,
      "Образ")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INFORMATION,
      "информация")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INFORMATION_LIST,
      "Информация")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_ADC_TYPE,
      "Аналого-цифровой тип")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_ALL_USERS_CONTROL_MENU,
      "Все пользователи управляющие меню")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_LEFT_X,
      "Левый аналог ось - X")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_LEFT_X_MINUS,
      "Левый аналог ось - X (влево)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_LEFT_X_PLUS,
      "Левый аналог ось - X+ (вправо)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_LEFT_Y,
      "Левый аналог ось - Y")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_LEFT_Y_MINUS,
      "Левый аналог ось - Y- (вверх)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_LEFT_Y_PLUS,
      "Левый аналог ось - Y+ (вниз)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_RIGHT_X,
      "Правый аналог ось - X")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_RIGHT_X_MINUS,
      "Правый аналог ось - X- (влево)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_RIGHT_X_PLUS,
      "Правый аналог ось - X + (вправо)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_RIGHT_Y,
      "Правый аналог ось - Y")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_RIGHT_Y_MINUS,
      "Правый аналог ось - Y- (вверх)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_RIGHT_Y_PLUS,
      "Правый аналог ось - Y+ (вниз)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_AUTODETECT_ENABLE,
      "Авто-конфигурация включена")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_AXIS_THRESHOLD,
      "Мертвая зона у стиков")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MENU_INPUT_SWAP_OK_CANCEL,
      "Сменить функции кнопок")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_BIND_ALL,
      "Скрепить всё")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_BIND_DEFAULT_ALL,
      "Скрепить все по умолчанию")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_BIND_TIMEOUT,
      "Тайм-аут привязки")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_DESCRIPTOR_HIDE_UNBOUND,
      "Скрыть несвязанные входные дескрипторы ядра")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_DESCRIPTOR_LABEL_SHOW,
      "Отображать ярлыки дескрипторов ввода")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_DEVICE_INDEX,
      "Индекс устройства")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_DEVICE_TYPE,
      "Тип устройства")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_DRIVER,
      "Ввод драйвера")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_DUTY_CYCLE,
      "Рабочий цикл")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_HOTKEY_BINDS,
      "Связывание горячих клавиш ввода")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_ICADE_ENABLE,
      "Клавиатура и геймпад включены")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_A,
      "Кнопка A ")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_B,
      "Кнопка B ")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_DOWN,
      "Крестовина ВНИЗ")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_L2,
      "Кнопка L2 ")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_L3,
      "Кнопка L3")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_L,
      "Кнопка L ")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_LEFT,
      "Крестовина ВЛЕВО")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_R2,
      "Кнопка R2")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_R3,
      "Кнопка R3")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_R,
      "Кнопка R")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_RIGHT,
      "Крестовина ВПРАВО")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_SELECT,
      "Кнопка SELECT")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_START,
      "Кнопка START")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_UP,
      "Крестовина ВВЕРХ")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_X,
      "Кнопка X")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_Y,
      "Кнопка Y")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_KEY,
      "(Ключ: %s)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_KEYBOARD_GAMEPAD_MAPPING_TYPE,
      "Тип отображения клавиатуры для геймпада")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_MAX_USERS,
      "Максимум пользователей")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_MENU_ENUM_TOGGLE_GAMEPAD_COMBO,
      "Переключать меню геймпадом")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_CHEAT_INDEX_MINUS,
      "Cheat index -")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_CHEAT_INDEX_PLUS,
      "Cheat index +")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_CHEAT_TOGGLE,
      "Переключить чит")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_DISK_EJECT_TOGGLE,
      "Извлечь диск")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_DISK_NEXT,
      "Следующий диск")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_DISK_PREV,
      "Предыдущий диск")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_ENABLE_HOTKEY,
      "EВключить горячие клавиши")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_FAST_FORWARD_HOLD_KEY,
      "Ускоренная перемотка вперед")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_FAST_FORWARD_KEY,
      "Быстрая перемотка вперед")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_FRAMEADVANCE,
      "Дополнительные фреймы")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_FULLSCREEN_TOGGLE_KEY,
      "На весь экран")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_GRAB_MOUSE_TOGGLE,
      "Переключатель мыши")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_LOAD_STATE_KEY,
      "Состояние загрузки")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_MENU_TOGGLE,
      "Переключение меню")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_MOVIE_RECORD_TOGGLE,
      "Переключатель записи видео")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_MUTE,
      "Отключения звука")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_NETPLAY_FLIP,
      "Netplay отразить пользователей")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_OSK,
      "Переключение экранной клавиатуры")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_OVERLAY_NEXT,
      "Наложение поверх")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_PAUSE_TOGGLE,
      "Приостановить переключение")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_QUIT_KEY,
      "Выход из RetroArch")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_RESET,
      "Сбросить игру")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_REWIND,
      "Перемотка назад")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_SAVE_STATE_KEY,
      "Сохранить состояние")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_SCREENSHOT,
      "Сделать скриншот")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_SHADER_NEXT,
      "Следующий шейдер")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_SHADER_PREV,
      "Предыдущий шейдер")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_SLOWMOTION,
      "Замедленная съемка")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_STATE_SLOT_MINUS,
      "Сохранять слот -")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_STATE_SLOT_PLUS,
      "Сохранять слот +")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_VOLUME_DOWN,
      "Громкость -")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_META_VOLUME_UP,
      "Громкость +")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_OVERLAY_ENABLE,
      "Отобразить наложение")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_OVERLAY_HIDE_IN_MENU,
      "Скрыть наложение в меню")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_POLL_TYPE_BEHAVIOR,
      "Тип поведения")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_POLL_TYPE_BEHAVIOR_EARLY,
      "Раньше")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_POLL_TYPE_BEHAVIOR_LATE,
      "Позже")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_POLL_TYPE_BEHAVIOR_NORMAL,
      "Нормально")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_PREFER_FRONT_TOUCH,
      "Предпочительно переднее касание")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_REMAPPING_DIRECTORY,
      "Переопределение ввода")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_REMAP_BINDS_ENABLE,
      "Включить замену привязок")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_SAVE_AUTOCONFIG,
      "Сохранить авто-конфигурацию")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_SETTINGS,
      "Ввод")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_SMALL_KEYBOARD_ENABLE,
      "Включить малую клавиатуру")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_TOUCH_ENABLE,
      "Включить касание")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_TURBO_ENABLE,
      "Турбо-режим включить")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_TURBO_PERIOD,
      "Турбо-период")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_USER_BINDS,
      "Вход пользователя% u Binds")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INTERNAL_STORAGE_STATUS,
      "Состояние внутренней памяти")
MSG_HASH(MENU_ENUM_LABEL_VALUE_JOYPAD_AUTOCONFIG_DIR,
      "Ввод авто-конфига")
MSG_HASH(MENU_ENUM_LABEL_VALUE_JOYPAD_DRIVER,
      "Драйвер геймпада")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LAKKA_SERVICES,
      "Сервисы")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LANG_CHINESE_SIMPLIFIED,
      "Chinese (Simplified)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LANG_CHINESE_TRADITIONAL,
      "Chinese (Traditional)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LANG_DUTCH,
      "Dutch")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LANG_ENGLISH,
      "English")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LANG_ESPERANTO,
      "Esperanto")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LANG_FRENCH,
      "French")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LANG_GERMAN,
      "German")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LANG_ITALIAN,
      "Italian")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LANG_JAPANESE,
      "Japanese")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LANG_KOREAN,
      "Korean")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LANG_POLISH,
      "Polish")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LANG_PORTUGUESE_BRAZIL,
      "Portuguese (Brazil)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LANG_PORTUGUESE_PORTUGAL,
      "Portuguese (Portugal)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LANG_RUSSIAN,
      "Russian")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LANG_SPANISH,
      "Spanish")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LANG_VIETNAMESE,
      "Vietnamese")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LEFT_ANALOG,
      "Левый аналог")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LIBRETRO_DIR_PATH,
      "Ядро")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LIBRETRO_INFO_PATH,
      "Ядро инфо")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LIBRETRO_LOG_LEVEL,
      "Уровень ведения журнала")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LINEAR,
      "Линейный")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LOAD_ARCHIVE,
      "Загрузить архив")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LOAD_CONTENT_HISTORY,
      "Загрузить последние")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LOAD_CONTENT_LIST,
      "Загрузить контент")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LOAD_STATE,
      "Состояние загрузки")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LOCATION_ALLOW,
      "Разрешить местоположение")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LOCATION_DRIVER,
      "Местоположение")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LOGGING_SETTINGS,
      "Ввод логина")
MSG_HASH(MENU_ENUM_LABEL_VALUE_LOG_VERBOSITY,
      "Ведение журнала")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MAIN_MENU,
      "Моё меню")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MANAGEMENT,
      "Настройки баз данных")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MATERIALUI_MENU_COLOR_THEME,
      "Цветовая тема меню")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MATERIALUI_MENU_COLOR_THEME_BLUE,
      "Синий")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MATERIALUI_MENU_COLOR_THEME_BLUE_GREY,
      "Серо-голубой")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MATERIALUI_MENU_COLOR_THEME_DARK_BLUE,
      "Тёмно-синий")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MATERIALUI_MENU_COLOR_THEME_GREEN,
      "Зелёный")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MATERIALUI_MENU_COLOR_THEME_NVIDIA_SHIELD,
      "Щит")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MATERIALUI_MENU_COLOR_THEME_RED,
      "Красный")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MATERIALUI_MENU_COLOR_THEME_YELLOW,
      "Жёлтый")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MATERIALUI_MENU_FOOTER_OPACITY,
      "Непрозрачность нижнего колонтитула")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MATERIALUI_MENU_HEADER_OPACITY,
      "Непрозрачность заголовка")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MENU_DRIVER,
      "Драйвер меню")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MENU_ENUM_THROTTLE_FRAMERATE,
      "Максимальная частота кадров меню")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MENU_FILE_BROWSER_SETTINGS,
      "Настройки")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MENU_LINEAR_FILTER,
      "Линейный фильтр меню")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MENU_SETTINGS,
      "Меню")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MENU_WALLPAPER,
      "Задний фон")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MENU_WALLPAPER_OPACITY,
      "Непрозрачность фона")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MISSING,
      "Отсутствует")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MORE,
      "...")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MOUSE_ENABLE,
      "Поддержка мыши")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MULTIMEDIA_SETTINGS,
      "Мультимедия")
MSG_HASH(MENU_ENUM_LABEL_VALUE_MUSIC_TAB,
      "Музыка")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NAVIGATION_BROWSER_FILTER_SUPPORTED_EXTENSIONS_ENABLE,
      "Фильтрация неизвестных расширений")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NAVIGATION_WRAPAROUND,
      "Навигация автоматической-прокруткой")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NEAREST,
      "Ближайший")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY,
      "Netplay")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY_CHECK_FRAMES,
      "Проверка фреймов Netplay")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY_CLIENT_SWAP_INPUT,
      "Netplay P2 использует C1")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY_DELAY_FRAMES,
      "Задержка кадров Netplay")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY_DISCONNECT,
      "Отключено")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY_ENABLE,
      "Включить Netplay")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY_ENABLE_CLIENT,
      "Подключение к Netplay-хосту")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY_ENABLE_HOST,
      "Старт хостинг")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY_DISABLE_HOST,
      "Stop netplay host")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY_IP_ADDRESS,
      "Адрес сервера")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY_MODE,
      "Включить клиент Netplay")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY_NICKNAME,
      "Имя пользователя")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY_SETTINGS,
      "Настройки Netplay")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY_SPECTATOR_MODE_ENABLE,
      "Включить режим зрителя в Netplay")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETPLAY_TCP_UDP_PORT,
      "Порт Netplay TCP / UDP")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETWORK_CMD_ENABLE,
      "Сетевые команды")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETWORK_CMD_PORT,
      "Сетевой командный порт")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETWORK_INFORMATION,
      "Информация о сети")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETWORK_REMOTE_ENABLE,
      "Сетевой геймпад")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETWORK_REMOTE_PORT,
      "Сетевой удаленный базовый порт")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NETWORK_SETTINGS,
      "Сеть")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NO,
      "Нет")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NONE,
      "Отсутствует")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NOT_AVAILABLE,
      "N/A")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NO_ACHIEVEMENTS_TO_DISPLAY,
      "Никаких достижений для показа.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NO_CORE,
      "Без ядра")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NO_CORES_AVAILABLE,
      "Нет доступных ядер.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NO_CORE_INFORMATION_AVAILABLE,
      "Нет информации о ядре.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NO_CORE_OPTIONS_AVAILABLE,
      "Нет доступных опций ядра.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NO_ENTRIES_TO_DISPLAY,
      "Нет записей для отображения.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NO_HISTORY_AVAILABLE,
      "История недоступна.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NO_INFORMATION_AVAILABLE,
      "Нет информации.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NO_ITEMS,
      "Нет элементов.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NO_PERFORMANCE_COUNTERS,
      "Нет счетчиков производительности.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NO_PLAYLISTS,
      "Нет плейлистов.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NO_PLAYLIST_ENTRIES_AVAILABLE,
      "Нет доступных записей в плейлисте.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NO_SETTINGS_FOUND,
      "Настройки не найдены.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_NO_SHADER_PARAMETERS,
      "Нет параметров шейдера.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_OFF,
      "ВЫКЛ")
MSG_HASH(MENU_ENUM_LABEL_VALUE_ON,
      "ВКЛ")
MSG_HASH(MENU_ENUM_LABEL_VALUE_ONLINE,
      "Онлайн")
MSG_HASH(MENU_ENUM_LABEL_VALUE_ONLINE_UPDATER,
      "Онлайн-обновление")
MSG_HASH(MENU_ENUM_LABEL_VALUE_ONSCREEN_DISPLAY_SETTINGS,
      "Экранное отображение")
MSG_HASH(MENU_ENUM_LABEL_VALUE_ONSCREEN_OVERLAY_SETTINGS,
      "Экранное наложение")
MSG_HASH(MENU_ENUM_LABEL_VALUE_ONSCREEN_NOTIFICATIONS_SETTINGS,
      "Экранные уведомления")
MSG_HASH(MENU_ENUM_LABEL_VALUE_OPEN_ARCHIVE,
      "Обзор архива")
MSG_HASH(MENU_ENUM_LABEL_VALUE_OPTIONAL,
      "Опционально")
MSG_HASH(MENU_ENUM_LABEL_VALUE_OVERLAY,
      "Наложение")
MSG_HASH(MENU_ENUM_LABEL_VALUE_OVERLAY_AUTOLOAD_PREFERRED,
      "Автозагрузка наложения")
MSG_HASH(MENU_ENUM_LABEL_VALUE_OVERLAY_DIRECTORY,
      "Наложение")
MSG_HASH(MENU_ENUM_LABEL_VALUE_OVERLAY_OPACITY,
      "Наложение преднастроек")
MSG_HASH(MENU_ENUM_LABEL_VALUE_OVERLAY_PRESET,
      "Масштаб наложения")
MSG_HASH(MENU_ENUM_LABEL_VALUE_OVERLAY_SCALE,
      "Overlay Scale")
MSG_HASH(MENU_ENUM_LABEL_VALUE_OVERLAY_SETTINGS,
      "Экранное наложение")
MSG_HASH(MENU_ENUM_LABEL_VALUE_PAL60_ENABLE,
      "Использовать режим PAL60")
MSG_HASH(MENU_ENUM_LABEL_VALUE_PARENT_DIRECTORY,
      "Родительский каталог")
MSG_HASH(MENU_ENUM_LABEL_VALUE_PAUSE_LIBRETRO,
      "Пауза при активации меню")
MSG_HASH(MENU_ENUM_LABEL_VALUE_PAUSE_NONACTIVE,
      "Не работать в фоновом режиме")
MSG_HASH(MENU_ENUM_LABEL_VALUE_PERFCNT_ENABLE,
      "Счетчики производительности")
MSG_HASH(MENU_ENUM_LABEL_VALUE_PLAYLISTS_TAB,
      "Плейлисты")
MSG_HASH(MENU_ENUM_LABEL_VALUE_PLAYLIST_DIRECTORY,
      "Плейлист")
MSG_HASH(MENU_ENUM_LABEL_VALUE_PLAYLIST_SETTINGS,
      "Плейлисты")
MSG_HASH(MENU_ENUM_LABEL_VALUE_POINTER_ENABLE,
      "Поддержка Touch")
MSG_HASH(MENU_ENUM_LABEL_VALUE_PORT,
      "Порт")
MSG_HASH(MENU_ENUM_LABEL_VALUE_PRESENT,
      "Отображать")
MSG_HASH(MENU_ENUM_LABEL_VALUE_PRIVACY_SETTINGS,
      "Конфиденциальность")
MSG_HASH(MENU_ENUM_LABEL_VALUE_QUIT_RETROARCH,
      "Выход из RetroArch")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_ANALOG,
      "Поддерживается аналоговый сигнал")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_BBFC_RATING,
      "Рейтинг BBFC")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_CERO_RATING,
      "Рейтинг CERO")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_COOP,
      "Кооператив поддерживается")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_CRC32,
      "CRC32")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_DESCRIPTION,
      "Описание")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_DEVELOPER,
      "Разработчик")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_EDGE_MAGAZINE_ISSUE,
      "Проблема журнала Edge")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_EDGE_MAGAZINE_RATING,
      "Рейтинг журнала Edge")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_EDGE_MAGAZINE_REVIEW,
      "Обзор журнала Edge")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_ELSPA_RATING,
      "Рейтинг ELSPA")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_ENHANCEMENT_HW,
      "Оборудование для улучшения")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_ESRB_RATING,
      "Рейтинг ESRB")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_FAMITSU_MAGAZINE_RATING,
      "Рейтинг журнала Famitsu")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_FRANCHISE,
      "Франчайзинг")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_GENRE,
      "Жанр")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_MD5,
      "MD5")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_NAME,
      "Имя")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_ORIGIN,
      "Происхождение")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_PEGI_RATING,
      "Рейтинг PEGI")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_PUBLISHER,
      "Издатель")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_RELEASE_MONTH,
      "Месяц выхода")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_RELEASE_YEAR,
      "Год выхода")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_RUMBLE,
      "Rumble поддерживается")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_SERIAL,
      "Серия")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_SHA1,
      "SHA1")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_START_CONTENT,
      "Запустить контент")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RDB_ENTRY_TGDB_RATING,
      "Рейтинг TGDB")
MSG_HASH(MENU_ENUM_LABEL_VALUE_REBOOT,
      "Перезагрузить")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RECORDING_CONFIG_DIRECTORY,
      "Конфигурация записи")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RECORDING_OUTPUT_DIRECTORY,
      "Выход записи")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RECORDING_SETTINGS,
      "Запись")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RECORD_CONFIG,
      "Загрузка конфигурации записи...")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RECORD_DRIVER,
      "Драйвер записи")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RECORD_ENABLE,
      "Включить запись")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RECORD_PATH,
      "Сохранить запись вывода как ...")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RECORD_USE_OUTPUT_DIRECTORY,
      "Сохранить записи в выходном каталоге")
MSG_HASH(MENU_ENUM_LABEL_VALUE_REMAP_FILE,
      "Файл переназначения")
MSG_HASH(MENU_ENUM_LABEL_VALUE_REMAP_FILE_LOAD,
      "Загрузить файл переназначения")
MSG_HASH(MENU_ENUM_LABEL_VALUE_REMAP_FILE_SAVE_CORE,
      "Сохранить файл переопределения ядра")
MSG_HASH(MENU_ENUM_LABEL_VALUE_REMAP_FILE_SAVE_GAME,
      "Сохранить файл переопределения игры")
MSG_HASH(MENU_ENUM_LABEL_VALUE_REQUIRED,
      "Необходимые")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RESTART_CONTENT,
      "Перезапуск")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RESTART_RETROARCH,
      "Перезапустить RetroArch")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RESUME,
      "Продолжить")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RESUME_CONTENT,
      "Продолжить")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RETROKEYBOARD,
      "Ретро-клавиатура")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RETROPAD,
      "Ретро-геймпад")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RETROPAD_WITH_ANALOG,
      "Ретро-геймпад с аналогами")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RETRO_ACHIEVEMENTS_SETTINGS,
      "Достижения")
MSG_HASH(MENU_ENUM_LABEL_VALUE_REWIND_ENABLE,
      "Включить перемотку назад")
MSG_HASH(MENU_ENUM_LABEL_VALUE_REWIND_GRANULARITY,
      "Гранулярность перемотки")
MSG_HASH(MENU_ENUM_LABEL_VALUE_REWIND_SETTINGS,
      "Перемотка назад")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RGUI_BROWSER_DIRECTORY,
      "Браузер файлов")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RGUI_CONFIG_DIRECTORY,
      "Конфигурация")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RGUI_SHOW_START_SCREEN,
      "Запуск записи экрана")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RIGHT_ANALOG,
      "Правый аналог")
MSG_HASH(MENU_ENUM_LABEL_VALUE_RUN,
      "Запустить")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SAMBA_ENABLE,
      "Включить SAMBA")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SAVEFILE_DIRECTORY,
      "Сохранить файл")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SAVESTATE_AUTO_INDEX,
      "Сохранить индекс автосостояния")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SAVESTATE_AUTO_LOAD,
      "Автозагрузка")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SAVESTATE_AUTO_SAVE,
      "Автосохранение")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SAVESTATE_DIRECTORY,
      "Сохранить статистику")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SAVE_CURRENT_CONFIG,
      "Сохранить текущую конфигурацию")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SAVE_CURRENT_CONFIG_OVERRIDE_CORE,
      "Сохранить переопределения ядра")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SAVE_CURRENT_CONFIG_OVERRIDE_GAME,
      "Сохранить переопределения игры")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SAVE_NEW_CONFIG,
      "Сохранить новую конфигурацию")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SAVE_STATE,
      "Сохранить статистику")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SAVING_SETTINGS,
      "Сохранить")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SCAN_DIRECTORY,
      "Сканировать каталог")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SCAN_FILE,
      "Сканировать файл")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SCAN_THIS_DIRECTORY,
      "<Сканировать этот каталог>")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SCREENSHOT_DIRECTORY,
      "Скриншот")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SCREEN_RESOLUTION,
      "Разрешение экрана")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SEARCH,
      "Поиск")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SECONDS,
      "секунды")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SETTINGS,
      "Настройки")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SETTINGS_TAB,
      "Настройки")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SHADER,
      "Шейдер")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SHADER_APPLY_CHANGES,
      "Применение изменений шейдера")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SHADER_OPTIONS,
      "Шейдеры")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SHADER_PIPELINE_RIBBON,
      "Лента")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SHADER_PIPELINE_RIBBON_SIMPLIFIED,
      "Лента (упрощённая)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SHADER_PIPELINE_SIMPLE_SNOW,
      "Простой снег")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SHADER_PIPELINE_SNOW,
      "Снег")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SHOW_ADVANCED_SETTINGS,
      "Показать дополнительные настройки")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SHOW_HIDDEN_FILES,
      "Показать скрытые файлы и папки")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SHUTDOWN,
      "Неисправность")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SLOWMOTION_RATIO,
      "Коэффициент замедленного движения ")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SORT_SAVEFILES_ENABLE,
      "Сохранить сортировку в папках")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SORT_SAVESTATES_ENABLE,
      "Sort Savestates In Folders")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SSH_ENABLE,
      "SSH включён")
MSG_HASH(MENU_ENUM_LABEL_VALUE_START_CORE,
      "запустить ядро")
MSG_HASH(MENU_ENUM_LABEL_VALUE_START_NET_RETROPAD,
      "Запустить удаленный Ретро-геймпад")
MSG_HASH(MENU_ENUM_LABEL_VALUE_START_VIDEO_PROCESSOR,
      "Запустить видеопроцессор")
MSG_HASH(MENU_ENUM_LABEL_VALUE_STATE_SLOT,
      "Статистика слота")
MSG_HASH(MENU_ENUM_LABEL_VALUE_STATUS,
      "Статус")
MSG_HASH(MENU_ENUM_LABEL_VALUE_STDIN_CMD_ENABLE,
      "Команды stdin")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SUPPORTED_CORES,
      "Рекомендуемые ядра")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SUSPEND_SCREENSAVER_ENABLE,
      "Приостановить экран")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_BGM_ENABLE,
      "Включен режим BGM")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_DIRECTORY,
      "Система / BIOS")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFORMATION,
      "Системная информация")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_7ZIP_SUPPORT,
      "Поддержка 7zip")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_ALSA_SUPPORT,
      "Поддержка ALSA")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_BUILD_DATE,
      "Дата создания")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_CG_SUPPORT,
      "Поддержка Cg")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_COCOA_SUPPORT,
      "Поддержка Cocoa")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_COMMAND_IFACE_SUPPORT,
      "Поддержка командного интерфейса")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_CORETEXT_SUPPORT,
      "Поддержка CoreText")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_CPU_FEATURES,
      "Особенности CPU")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_DISPLAY_METRIC_DPI,
      "Отображать индекс DPI")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_DISPLAY_METRIC_MM_HEIGHT,
      "Отображать высоту (mm)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_DISPLAY_METRIC_MM_WIDTH,
      "Отображать ширину (mm)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_DSOUND_SUPPORT,
      "Поддержка DirectSound")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_DYLIB_SUPPORT,
      "Поддержка динамических библиотек")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_DYNAMIC_SUPPORT,
      "Загрузка динамических библиотек во время выполнения")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_EGL_SUPPORT,
      "Поддержка EGL")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_FBO_SUPPORT,
      "Поддержка OpenGL/Direct3D рендеринга для текстур")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_FFMPEG_SUPPORT,
      "Поддержка FFmpeg")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_FREETYPE_SUPPORT,
      "Поддержка FreeType")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_FRONTEND_IDENTIFIER,
      "Идентификатор внешнего интерфейса")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_FRONTEND_NAME,
      "Имя внешнего интерфейса")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_FRONTEND_OS,
      "Внешний интерфейс")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_GIT_VERSION,
      "Версия Git")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_GLSL_SUPPORT,
      "Поддержка GLSL")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_HLSL_SUPPORT,
      "Поддержка HLSL")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_JACK_SUPPORT,
      "Поддержка JACK")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_KMS_SUPPORT,
      "поддержка KMS/EGL")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_LIBRETRODB_SUPPORT,
      "Поддержка LibretroDB")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_LIBUSB_SUPPORT,
      "Поддержка Libusb")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_LIBXML2_SUPPORT,
      "Поддержка синтаксического анализа libxml2 XML")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_NETPLAY_SUPPORT,
      "Поддержка Netplay (peer-to-peer)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_NETWORK_COMMAND_IFACE_SUPPORT,
      "Поддержка сетевого командного интерфейса")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_NETWORK_REMOTE_SUPPORT,
      "Поддержка геймпада в сети")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_OPENAL_SUPPORT,
      "Поддержка OpenAL")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_OPENGLES_SUPPORT,
      "Поддержка OpenGL ES")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_OPENGL_SUPPORT,
      "Поддержка OpenGL")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_OPENSL_SUPPORT,
      "Поддержка OpenSL")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_OPENVG_SUPPORT,
      "Поддержка OpenVG")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_OSS_SUPPORT,
      "Поддержка OSS")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_OVERLAY_SUPPORT,
      "Поддержка Overlay")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_POWER_SOURCE,
      "Источник питания")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_POWER_SOURCE_CHARGED,
      "Заряжена")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_POWER_SOURCE_CHARGING,
      "Заряжается ")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_POWER_SOURCE_DISCHARGING,
      "Разряжается")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_POWER_SOURCE_NO_SOURCE,
      "Нет источника")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_PULSEAUDIO_SUPPORT,
      "Поддержка PulseAudio")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_PYTHON_SUPPORT,
      "Поддержка Python (поддержка скриптов в шейдерах)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_RBMP_SUPPORT,
      "Поддержка BMP(RBMP)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_RETRORATING_LEVEL,
      "Уровень RetroRating")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_RJPEG_SUPPORT,
      "Поддержка JPEG (RJPEG)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_ROARAUDIO_SUPPORT,
      "Поддержка RoarAudio")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_RPNG_SUPPORT,
      "Поддержка PNG(RPNG)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_RSOUND_SUPPORT,
      "Поддержка RSound")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_RTGA_SUPPORT,
      "Поддержка TGA(RTGA)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_SDL2_SUPPORT,
      "Поддержка SDL2")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_SDL_IMAGE_SUPPORT,
      "Поддержка изображений SDL")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_SDL_SUPPORT,
      "Поддержка SDL1.2")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_SLANG_SUPPORT,
      "Поддержка Slang")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_THREADING_SUPPORT,
      "Поддержка Threading")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_UDEV_SUPPORT,
      "Поддержка Udev")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_V4L2_SUPPORT,
      "Поддержка Video4Linux2")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_VIDEO_CONTEXT_DRIVER,
      "Драйвер контекстного видео")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_VULKAN_SUPPORT,
      "Поддержка Vulkan")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_WAYLAND_SUPPORT,
      "Поддержка Wayland")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_X11_SUPPORT,
      "Поддержка X11")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_XAUDIO2_SUPPORT,
      "Поддержка XAudio2")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_XVIDEO_SUPPORT,
      "Поддержка XVideo")
MSG_HASH(MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_ZLIB_SUPPORT,
      "Поддержка Zlib")
MSG_HASH(MENU_ENUM_LABEL_VALUE_TAKE_SCREENSHOT,
      "Сделать скриншот")
MSG_HASH(MENU_ENUM_LABEL_VALUE_THREADED_DATA_RUNLOOP_ENABLE,
      "Реализованные задачи")
MSG_HASH(MENU_ENUM_LABEL_VALUE_THUMBNAILS,
      "Миниатюры")
MSG_HASH(MENU_ENUM_LABEL_VALUE_THUMBNAILS_DIRECTORY,
      "Миниатюры")
MSG_HASH(MENU_ENUM_LABEL_VALUE_THUMBNAILS_UPDATER_LIST,
      "Обновление эскизов")
MSG_HASH(MENU_ENUM_LABEL_VALUE_THUMBNAIL_MODE_BOXARTS,
      "Boxarts")
MSG_HASH(MENU_ENUM_LABEL_VALUE_THUMBNAIL_MODE_SCREENSHOTS,
      "Скриншоты")
MSG_HASH(MENU_ENUM_LABEL_VALUE_THUMBNAIL_MODE_TITLE_SCREENS,
      "Экраны заголовков")
MSG_HASH(MENU_ENUM_LABEL_VALUE_TIMEDATE_ENABLE,
      "Показывать время / дата")
MSG_HASH(MENU_ENUM_LABEL_VALUE_TITLE_COLOR,
      "Цвет заголовков в меню")
MSG_HASH(MENU_ENUM_LABEL_VALUE_TRUE,
      "True")
MSG_HASH(MENU_ENUM_LABEL_VALUE_UI_COMPANION_ENABLE,
      "UI Companion включён")
MSG_HASH(MENU_ENUM_LABEL_VALUE_UI_COMPANION_START_ON_BOOT,
      "Включить UI Companion при загрузке")
MSG_HASH(MENU_ENUM_LABEL_VALUE_UI_MENUBAR_ENABLE,
      "Строка меню")
MSG_HASH(MENU_ENUM_LABEL_VALUE_UNABLE_TO_READ_COMPRESSED_FILE,
      "Не удалось прочитать сжатый файл.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_UNDO_LOAD_STATE,
      "Отменить загрузку")
MSG_HASH(MENU_ENUM_LABEL_VALUE_UNDO_SAVE_STATE,
      "Отменить сохранение")
MSG_HASH(MENU_ENUM_LABEL_VALUE_UNKNOWN,
      "Неизвестно")
MSG_HASH(MENU_ENUM_LABEL_VALUE_UPDATER_SETTINGS,
      "Обновитель")
MSG_HASH(MENU_ENUM_LABEL_VALUE_UPDATE_ASSETS,
      "Обновить активы")
MSG_HASH(MENU_ENUM_LABEL_VALUE_UPDATE_AUTOCONFIG_PROFILES,
      "Обновить профили авто-конфигурации")
MSG_HASH(MENU_ENUM_LABEL_VALUE_UPDATE_CG_SHADERS,
      "Обновление Cg шейдеров")
MSG_HASH(MENU_ENUM_LABEL_VALUE_UPDATE_CHEATS,
      "Обновить читы")
MSG_HASH(MENU_ENUM_LABEL_VALUE_UPDATE_CORE_INFO_FILES,
      "Обновить основные информационные файлы")
MSG_HASH(MENU_ENUM_LABEL_VALUE_UPDATE_DATABASES,
      "Обновить базы данных")
MSG_HASH(MENU_ENUM_LABEL_VALUE_UPDATE_GLSL_SHADERS,
      "Обновить GLSL шейдеры")
MSG_HASH(MENU_ENUM_LABEL_VALUE_UPDATE_LAKKA,
      "Обновить Lakka")
MSG_HASH(MENU_ENUM_LABEL_VALUE_UPDATE_OVERLAYS,
      "Обновить Overlays")
MSG_HASH(MENU_ENUM_LABEL_VALUE_UPDATE_SLANG_SHADERS,
      "Обновить сленговые шейдеры")
MSG_HASH(MENU_ENUM_LABEL_VALUE_USER,
      "Пользователь")
MSG_HASH(MENU_ENUM_LABEL_VALUE_USER_INTERFACE_SETTINGS,
      "Интерфейс пользователя")
MSG_HASH(MENU_ENUM_LABEL_VALUE_USER_LANGUAGE,
      "Language")
MSG_HASH(MENU_ENUM_LABEL_VALUE_USER_SETTINGS,
      "Пользователь")
MSG_HASH(MENU_ENUM_LABEL_VALUE_USE_BUILTIN_IMAGE_VIEWER,
      "Использовать встроенный просмотрщик изображений")
MSG_HASH(MENU_ENUM_LABEL_VALUE_USE_BUILTIN_PLAYER,
      "Использовать встроенный медиа-плеер")
MSG_HASH(MENU_ENUM_LABEL_VALUE_USE_THIS_DIRECTORY,
      "<Использовать этот катало>")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_ALLOW_ROTATE,
      "Разрешить вращение")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_ASPECT_RATIO_AUTO,
      "Автоотношение сторон")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_ASPECT_RATIO_INDEX,
      "Соотношение сторон")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_BLACK_FRAME_INSERTION,
      "Вставка черного кадра")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_CROP_OVERSCAN,
      "Обрезка обрезки (перезагрузка)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_DISABLE_COMPOSITION,
      "Отключить компоновку рабочего стола")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_DRIVER,
      "Видео драйвер")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_FILTER,
      "Видео фильтр")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_FILTER_DIR,
      "Видео фильтр")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_FILTER_FLICKER,
      "Мерцающий фильтр")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_FONT_ENABLE,
      "Onscreen Notification включить")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_FONT_PATH,
      "Экранный шрифт уведомления")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_FONT_SIZE,
      "Размер уведомлений на экране")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_FORCE_ASPECT,
      "Форсировать пропорции")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_FORCE_SRGB_DISABLE,
      "Принудительное отключение sRGB FBO")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_FRAME_DELAY,
      "Задержка кадра")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_FULLSCREEN,
      "Использовать полноэкранный режим")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_GAMMA,
      "Видео гамма")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_GPU_RECORD,
      "Использовать GPU Recording")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_GPU_SCREENSHOT,
      "GPU Screenshot включен")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_HARD_SYNC,
      "GPU Sync максимум")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_HARD_SYNC_FRAMES,
      "GPU Sync Frames максимум")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_MAX_SWAPCHAIN_IMAGES,
      "Максимальное количество образов свопчейнов")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_MESSAGE_POS_X,
      "Позиция X по уведомлению на экране")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_MESSAGE_POS_Y,
      "Позиция Y на экранном уведомлении")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_MONITOR_INDEX,
      "Индекс монитора")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_POST_FILTER_RECORD,
      "Использовать запись после фильтра")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_REFRESH_RATE,
      "Вертикальная частота обновления")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_REFRESH_RATE_AUTO,
      "Оценочная частота экрана")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_ROTATION,
      "Вращение")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_SCALE,
      "Оконная шкала")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_SCALE_INTEGER,
      "Целочисленная шкала")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_SETTINGS,
      "Видео")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_SHADER_DIR,
      "Видео шейдер")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_SHADER_NUM_PASSES,
      "Шейдерные проходы")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_SHADER_PARAMETERS,
      "Предварительный просмотр параметров шейдера")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_SHADER_PRESET,
      "Загрузить предварительную настройку шейдера")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_SHADER_PRESET_PARAMETERS,
      "Параметры меню шейдера")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_SHADER_PRESET_SAVE_AS,
      "Сохранить предустановку шейдера как")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_SHADER_PRESET_SAVE_CORE,
      "Сохранить предварительную настройку ядра")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_SHADER_PRESET_SAVE_GAME,
      "Сохранить предварительную настройку игры")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_SHARED_CONTEXT,
      "Включить Hardware Shared Context")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_SMOOTH,
      "Билинейная фильтрация")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_SOFT_FILTER,
      "Включён мягкий фильтр")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_SWAP_INTERVAL,
      "Интервал свопинга по вертикальной синхронизации")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_TAB,
      "Видео")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_THREADED,
      "Количество потоков видео")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_VFILTER,
      "Дефликер")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_VIEWPORT_CUSTOM_HEIGHT,
      "Высота пользовательского видового экрана")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_VIEWPORT_CUSTOM_WIDTH,
      "Пользовательская ширина видового экрана")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_VIEWPORT_CUSTOM_X,
      "Пользовательский видовой экран X Поз.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_VIEWPORT_CUSTOM_Y,
      "Пользовательский видовой экран Y Поз.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_VI_WIDTH,
      "Установить ширину экрана VI")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_VSYNC,
      "Вертикальная синхронизация (Vsync)")
MSG_HASH(MENU_ENUM_LABEL_VALUE_VIDEO_WINDOWED_FULLSCREEN,
      "Полноэкранный режим")
MSG_HASH(MENU_ENUM_LABEL_VALUE_WIFI_DRIVER,
      "Wi-Fi драйвер")
MSG_HASH(MENU_ENUM_LABEL_VALUE_WIFI_SETTINGS,
      "Wi-Fi")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_ALPHA_FACTOR,
      "Меню Alpha Factor")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_FONT,
      "Шрифт")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_ICON_THEME_CUSTOM,
      "Пользовательский")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_ICON_THEME_FLATUI,
      "FlatUI")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_ICON_THEME_MONOCHROME,
      "Монохромный")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_ICON_THEME_SYSTEMATIC,
      "Систематический")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_ICON_THEME_NEOACTIVE,
      "NeoActive")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_ICON_THEME_PIXEL,
      "Пиксель")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_ICON_THEME_RETROACTIVE,
      "RetroActive")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_ICON_THEME_DOTART,
      "Dot-Art")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_MENU_COLOR_THEME,
      "Цветная тема меню")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_MENU_COLOR_THEME_APPLE_GREEN,
      "Зеленое яблоко")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_MENU_COLOR_THEME_DARK,
      "Темно")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_MENU_COLOR_THEME_DARK_PURPLE,
      "Темно фиолетовый")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_MENU_COLOR_THEME_ELECTRIC_BLUE,
      "Электрический синий")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_MENU_COLOR_THEME_GOLDEN,
      "Золотой")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_MENU_COLOR_THEME_LEGACY_RED,
      "Красный")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_MENU_COLOR_THEME_MIDNIGHT_BLUE,
      "Темно-синий")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_MENU_COLOR_THEME_PLAIN,
      "Обычный")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_MENU_COLOR_THEME_UNDERSEA,
      "Водные глубины")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_MENU_COLOR_THEME_VOLCANIC_RED,
      "Вулканический красный")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_RIBBON_ENABLE,
      "Шейдерный канал меню")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_SCALE_FACTOR,
      "Масштаб в меню")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_SHADOWS_ENABLE,
      "Тени иконок включена")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_SHOW_HISTORY,
      "Показать вкладку история просмотров")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_SHOW_IMAGES,
      "Показать вкладку изображение")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_SHOW_MUSIC,
      "Показать вкладку музыка")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_SHOW_SETTINGS,
      "Показать вкладку настройки")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_SHOW_VIDEO,
      "Показать вкладку видео")
MSG_HASH(MENU_ENUM_LABEL_VALUE_XMB_THEME,
      "Тема значка меню")
MSG_HASH(MENU_ENUM_LABEL_VALUE_YES,
      "Да")
MSG_HASH(MENU_ENUM_LABEL_VIDEO_SHADER_PRESET_TWO,
      "Предустановка шейдера")
MSG_HASH(MENU_ENUM_SUBLABEL_CHEEVOS_ENABLE,
      "Включение или отключение достижений. Для получения дополнительной информации посетите страницу http://retroachievements.org")
MSG_HASH(MENU_ENUM_SUBLABEL_CHEEVOS_TEST_UNOFFICIAL,
      "Включение или отключение неофициальных достижений и / или бета-функций в целях тестирования.")
MSG_HASH(MENU_ENUM_SUBLABEL_CHEEVOS_HARDCORE_MODE_ENABLE,
      "Включить или отключить сохранения, читы, перемотка назад, перемотка вперед, пауза и замедленное воспроизведение для всех игр.")
MSG_HASH(MENU_ENUM_SUBLABEL_DRIVER_SETTINGS,
      "Изменение драйверов для этой системы.")
MSG_HASH(MENU_ENUM_SUBLABEL_RETRO_ACHIEVEMENTS_SETTINGS,
      "Изменение настроек для достижений.")
MSG_HASH(MENU_ENUM_SUBLABEL_CORE_SETTINGS,
      "Изменить настройки для ядра.")
MSG_HASH(MENU_ENUM_SUBLABEL_RECORDING_SETTINGS,
      "Изменить настройки для записи.")
MSG_HASH(MENU_ENUM_SUBLABEL_ONSCREEN_DISPLAY_SETTINGS,
      "Измените настройки отображения перекрытия, наложения клавиатуры и уведомлений на экране.")
MSG_HASH(MENU_ENUM_SUBLABEL_FRAME_THROTTLE_SETTINGS,
      "Измените настройки для перемотки, быстрой перемотки и замедленного воспроизведения.")
MSG_HASH(MENU_ENUM_SUBLABEL_SAVING_SETTINGS,
      "Измените настройки для сохранения.")
MSG_HASH(MENU_ENUM_SUBLABEL_LOGGING_SETTINGS,
      "Изменить настройки для ведения журнала.")
MSG_HASH(MENU_ENUM_SUBLABEL_USER_INTERFACE_SETTINGS,
      "Изменить настройки для пользовательского интерфейса.")
MSG_HASH(MENU_ENUM_SUBLABEL_USER_SETTINGS,
      "Измените учетные записи, имя пользователя и язык.")
MSG_HASH(MENU_ENUM_SUBLABEL_PRIVACY_SETTINGS,
      "Измените настройки конфиденциальности.")
MSG_HASH(MENU_ENUM_SUBLABEL_DIRECTORY_SETTINGS,
      "Изменение каталогов по умолчанию для этой системы.")
MSG_HASH(MENU_ENUM_SUBLABEL_PLAYLIST_SETTINGS,
      "Изменить настройки для списков воспроизведения.")
MSG_HASH(MENU_ENUM_SUBLABEL_NETWORK_SETTINGS,
      "Настроить параметры сервера и сети.")
MSG_HASH(MENU_ENUM_SUBLABEL_ADD_CONTENT_LIST,
      "Сканировать содержимое и добавить в базу данных.")
MSG_HASH(MENU_ENUM_SUBLABEL_AUDIO_SETTINGS,
      "Настройка параметров аудиовыхода.")
MSG_HASH(MENU_ENUM_SUBLABEL_BLUETOOTH_ENABLE,
      "Включить или отключить Bluetooth.")
MSG_HASH(MENU_ENUM_SUBLABEL_CONFIG_SAVE_ON_EXIT,
      "Сохраняет изменения в файле конфигурации при выходе.")
MSG_HASH(MENU_ENUM_SUBLABEL_CONFIGURATION_SETTINGS,
      "Измените настройки по умолчанию для файлов конфигурации.")
MSG_HASH(MENU_ENUM_SUBLABEL_CONFIGURATIONS_LIST,
      "Управление и создание файлов конфигурации.")
MSG_HASH(MENU_ENUM_SUBLABEL_CPU_CORES,
      "«Количество ядер CPU.")
MSG_HASH(MENU_ENUM_SUBLABEL_FPS_SHOW,
      "Отображает текущую частоту кадров в секунду на экране.")
MSG_HASH(MENU_ENUM_SUBLABEL_INPUT_HOTKEY_BINDS,
      "Настроить параметры горячих клавиш.")
MSG_HASH(MENU_ENUM_SUBLABEL_INPUT_MENU_ENUM_TOGGLE_GAMEPAD_COMBO,
      "Комбинация кнопок геймпада для переключения меню.")
MSG_HASH(MENU_ENUM_SUBLABEL_INPUT_SETTINGS,
      "Настройки управления для джойстика, клавиатуры и мыши.")
MSG_HASH(MENU_ENUM_SUBLABEL_INPUT_USER_BINDS,
      "Настройки элементов управления для этого пользователя.")
MSG_HASH(MENU_ENUM_SUBLABEL_LOG_VERBOSITY,
      "Включить или отключить ведение журнала в терминале.")
MSG_HASH(MENU_ENUM_SUBLABEL_NETPLAY,
      "Присоединиться или создать сеанс netplay.")
MSG_HASH(MENU_ENUM_SUBLABEL_INFORMATION_LIST_LIST,
      "Отображать информацию о ядре, сети и системе.")
MSG_HASH(MENU_ENUM_SUBLABEL_ONLINE_UPDATER,
      "Загрузите надстройки, компоненты и содержимое для RetroArch.")
MSG_HASH(MENU_ENUM_SUBLABEL_SAMBA_ENABLE,
      "Включить или отключить сетевой доступ к папкам.")
MSG_HASH(MENU_ENUM_SUBLABEL_SERVICES_SETTINGS,
      "Управление службами операционной системы.")
MSG_HASH(MENU_ENUM_SUBLABEL_SHOW_HIDDEN_FILES,
      "Показывать скрытые файлы / каталоги внутри файлового менеджера.")
MSG_HASH(MENU_ENUM_SUBLABEL_SSH_ENABLE,
      "Включить или отключить удаленный доступ к командной строке.")
MSG_HASH(MENU_ENUM_SUBLABEL_SUSPEND_SCREENSAVER_ENABLE,
      "Запрещается активация заставки вашей системы.")
MSG_HASH(MENU_ENUM_SUBLABEL_USER_LANGUAGE,
      "Устанавливает язык интерфейса.")
MSG_HASH(MENU_ENUM_SUBLABEL_VIDEO_BLACK_FRAME_INSERTION,
      "Вставляет черную рамку между кадрами. Полезно для пользователей с экранами с частотой 120 Гц, которые хотят проигрывать материал с частотой 60 Гц с устраненным ореолом.")
MSG_HASH(MENU_ENUM_SUBLABEL_VIDEO_FRAME_DELAY,
      "Уменьшает задержку за счет более высокого риска заикания видео. Добавляет задержку после V-Sync (в мс).")
MSG_HASH(MENU_ENUM_SUBLABEL_VIDEO_HARD_SYNC_FRAMES,
      "Устанавливает, сколько кадров процессор может запустить перед графическим процессором при использовании« Hard GPU Sync.")
MSG_HASH(MENU_ENUM_SUBLABEL_VIDEO_MAX_SWAPCHAIN_IMAGES,
      "Указывает видеодрайверу какой режим буферизации использовать.")
MSG_HASH(MENU_ENUM_SUBLABEL_VIDEO_MONITOR_INDEX,
      "Выбирает, какой экран дисплея использовать.")
MSG_HASH(MENU_ENUM_SUBLABEL_VIDEO_REFRESH_RATE_AUTO,
      "Точная оценка частоты обновления экрана в Гц.")
MSG_HASH(MENU_ENUM_SUBLABEL_VIDEO_SETTINGS,
      "Настройка параметров вывода видео.")
MSG_HASH(MENU_ENUM_SUBLABEL_WIFI_SETTINGS,
      "Сканирует беспроводные сети и устанавливает соединение.")
MSG_HASH(MENU_ENUM_SUBLABEL_HELP_LIST,
      "Узнайте больше о том, как это работает.")
MSG_HASH(MSG_APPENDED_DISK,
      "Вставлен диск")
MSG_HASH(MSG_APPLICATION_DIR,
      "Каталог приложений")
MSG_HASH(MSG_APPLYING_CHEAT,
      "Применение читов.")
MSG_HASH(MSG_APPLYING_SHADER,
      "Применён шейдер")
MSG_HASH(MSG_AUDIO_MUTED,
      "Звук откл.")
MSG_HASH(MSG_AUDIO_UNMUTED,
      "Звук вкл.")
MSG_HASH(MSG_AUTOCONFIG_FILE_ERROR_SAVING,
      "Ошибка при сохранении файла авто-конфигурации.")
MSG_HASH(MSG_AUTOCONFIG_FILE_SAVED_SUCCESSFULLY,
      "Файл авто-конфигурации успешно сохранен.")
MSG_HASH(MSG_AUTOSAVE_FAILED,
      "Ошибка автосохранения.")
MSG_HASH(MSG_AUTO_SAVE_STATE_TO,
      "Процесс авто-сохранения")
MSG_HASH(MSG_BLOCKING_SRAM_OVERWRITE,
      "Перезапись SRAM запрещена.")
MSG_HASH(MSG_BRINGING_UP_COMMAND_INTERFACE_ON_PORT,
      "Вывод командного интерфейса на порт")
MSG_HASH(MSG_BYTES,
      "Байт")
MSG_HASH(MSG_CANNOT_INFER_NEW_CONFIG_PATH,
      "Вывод командного интерфейса на порт.")
MSG_HASH(MSG_CHEEVOS_HARDCORE_MODE_ENABLE,
      "Режим Hardcore включен, режим сохранения и перемотки отключен.")
MSG_HASH(MSG_COMPARING_WITH_KNOWN_MAGIC_NUMBERS,
      "Сравнение с известными магическими числами ...")
MSG_HASH(MSG_COMPILED_AGAINST_API,
      "Скомпилирован против API")
MSG_HASH(MSG_CONFIG_DIRECTORY_NOT_SET,
      "Не задана папка хранения настроек. Невозможно сохранить конфигурацию.")
MSG_HASH(MSG_CONNECTED_TO,
      "Подключен к")
MSG_HASH(MSG_CONTENT_CRC32S_DIFFER,
      "Содержимое CRC32 различается. Нельзя использовать разные игры.")
MSG_HASH(MSG_CONTENT_LOADING_SKIPPED_IMPLEMENTATION_WILL_DO_IT,
      "Загрузка контента пропущена, реализация будет загружена сама по себе.")
MSG_HASH(MSG_CORE_DOES_NOT_SUPPORT_SAVESTATES,
      "Ядро не поддерживает быстрые сохранение.")
MSG_HASH(MSG_CORE_OPTIONS_FILE_CREATED_SUCCESSFULLY,
      "Файл основных настроек успешно создан.")
MSG_HASH(MSG_COULD_NOT_FIND_ANY_NEXT_DRIVER,
      "Не удалось найти следующий драйвер")
MSG_HASH(MSG_COULD_NOT_FIND_COMPATIBLE_SYSTEM,
      "Не удалось найти совместимую систему.")
MSG_HASH(MSG_COULD_NOT_FIND_VALID_DATA_TRACK,
      "Не удалось найти дорожку данных")
MSG_HASH(MSG_COULD_NOT_OPEN_DATA_TRACK,
      "Не удалось открыть дорожку данных")
MSG_HASH(MSG_COULD_NOT_READ_CONTENT_FILE,
      "Не удалось прочитать файл контента")
MSG_HASH(MSG_COULD_NOT_READ_MOVIE_HEADER,
      "Не удалось прочитать заголовок видео ролика.")
MSG_HASH(MSG_COULD_NOT_READ_STATE_FROM_MOVIE,
      "Не удалось прочитать состояние видео ролика.")
MSG_HASH(MSG_CRC32_CHECKSUM_MISMATCH,
      "Ошибка контрольной суммы CRC32 между файлом содержимого и контрольной суммой сохраненного содержимого в заголовке файла воспроизведения), что, скорее всего, приведет к рассинхронизации при воспроизведении.")
MSG_HASH(MSG_CUSTOM_TIMING_GIVEN,
      "Задано ручное значение тайминга.")
MSG_HASH(MSG_DECOMPRESSION_ALREADY_IN_PROGRESS,
      "Декомпрессия уже выполняется.")
MSG_HASH(MSG_DECOMPRESSION_FAILED,
      "Ошибка декомпрессии.")
MSG_HASH(MSG_DETECTED_VIEWPORT_OF,
      "Обнаружено окно проекции")
MSG_HASH(MSG_DID_NOT_FIND_A_VALID_CONTENT_PATCH,
      "Не найден правильный патч для контента.")
MSG_HASH(MSG_DISCONNECT_DEVICE_FROM_A_VALID_PORT,
      "Отключите устройство от действительного порта.")
MSG_HASH(MSG_DISK_CLOSED,
      "Закрыто")
MSG_HASH(MSG_DISK_EJECTED,
      "Выброс")
MSG_HASH(MSG_DOWNLOADING,
      "Прогресс загрузки")
MSG_HASH(MSG_DOWNLOAD_FAILED,
      "Загрузка не удалась")
MSG_HASH(MSG_ERROR,
      "Ошибка")
MSG_HASH(MSG_ERROR_LIBRETRO_CORE_REQUIRES_CONTENT,
      "Ядру Libretro требуется контент, но ничего не было предоставлено.")
MSG_HASH(MSG_ERROR_LIBRETRO_CORE_REQUIRES_SPECIAL_CONTENT,
      "Ядру Libretro требуется особый контент, но его не было.")
MSG_HASH(MSG_ERROR_PARSING_ARGUMENTS,
      "Ошибка при анализе аргументов.")
MSG_HASH(MSG_ERROR_SAVING_CORE_OPTIONS_FILE,
      "Ошибка при сохранении файла основных опций.")
MSG_HASH(MSG_ERROR_SAVING_REMAP_FILE,
      "Ошибка при сохранении файла переопределения.")
MSG_HASH(MSG_ERROR_SAVING_SHADER_PRESET,
      "Ошибка сохранения пресетов шейдера.")
MSG_HASH(MSG_EXTERNAL_APPLICATION_DIR,
      "Внешний каталог приложений")
MSG_HASH(MSG_EXTRACTING,
      "Извлечение")
MSG_HASH(MSG_EXTRACTING_FILE,
      "Извлечение файла")
MSG_HASH(MSG_FAILED_SAVING_CONFIG_TO,
      "Ошибка сохранения конфигурации в")
MSG_HASH(MSG_FAILED_TO,
      "Ошибка")
MSG_HASH(MSG_FAILED_TO_ACCEPT_INCOMING_SPECTATOR,
      "Не удалось принять зрителя.")
MSG_HASH(MSG_FAILED_TO_ALLOCATE_MEMORY_FOR_PATCHED_CONTENT,
      "Не удалось выделить память для пропатченного содержимого ...")
MSG_HASH(MSG_FAILED_TO_APPLY_SHADER,
      "Не удалось применить шейдер")
MSG_HASH(MSG_FAILED_TO_BIND_SOCKET,
      "Не удалось привязать сокет.")
MSG_HASH(MSG_FAILED_TO_CREATE_THE_DIRECTORY,
      "Не удалось создать каталог.")
MSG_HASH(MSG_FAILED_TO_EXTRACT_CONTENT_FROM_COMPRESSED_FILE,
      "Не удалось извлечь содержимое из сжатого файла")
MSG_HASH(MSG_FAILED_TO_GET_NICKNAME_FROM_CLIENT,
      "Не удалось получить псевдоним от клиента.")
MSG_HASH(MSG_FAILED_TO_LOAD,
      "Ошибка загрузки")
MSG_HASH(MSG_FAILED_TO_LOAD_CONTENT,
      "Не удалось загрузить контент")
MSG_HASH(MSG_FAILED_TO_LOAD_MOVIE_FILE,
      "Не удалось загрузить файл записи.")
MSG_HASH(MSG_FAILED_TO_LOAD_OVERLAY,
      "Ошибка загрузки оверлея.")
MSG_HASH(MSG_FAILED_TO_LOAD_STATE,
      "Ошибка загрузки сохранения из")
MSG_HASH(MSG_FAILED_TO_OPEN_LIBRETRO_CORE,
      "Не удалось открыть ядро libretro")
MSG_HASH(MSG_FAILED_TO_PATCH,
      "Не удалось пропатчить")
MSG_HASH(MSG_FAILED_TO_RECEIVE_HEADER_FROM_CLIENT,
      "Не удалось получить заголовок от клиента.")
MSG_HASH(MSG_FAILED_TO_RECEIVE_NICKNAME,
      "Не удалось получить никнейм.")
MSG_HASH(MSG_FAILED_TO_RECEIVE_NICKNAME_FROM_HOST,
      "Не удалось получить никнейм с узла.")
MSG_HASH(MSG_FAILED_TO_RECEIVE_NICKNAME_SIZE_FROM_HOST,
      "Не удалось получить размер никнейма от хоста.")
MSG_HASH(MSG_FAILED_TO_RECEIVE_SRAM_DATA_FROM_HOST,
      "Не удалось получить данные SRAM с хоста.")
MSG_HASH(MSG_FAILED_TO_REMOVE_DISK_FROM_TRAY,
      "Невозможно извлечь диск.")
MSG_HASH(MSG_FAILED_TO_REMOVE_TEMPORARY_FILE,
      "Ошибка удаления временного файла.")
MSG_HASH(MSG_FAILED_TO_SAVE_SRAM,
      "Ошибка сохранения SRAM")
MSG_HASH(MSG_FAILED_TO_SAVE_STATE_TO,
      "Ошибка записи сохранения в")
MSG_HASH(MSG_FAILED_TO_SEND_NICKNAME,
      "Не удалось отправить никнейм.")
MSG_HASH(MSG_FAILED_TO_SEND_NICKNAME_SIZE,
      "Не удалось отправить размер никнейма.")
MSG_HASH(MSG_FAILED_TO_SEND_NICKNAME_TO_CLIENT,
      "Не удалось отправить никнейм клиенту.")
MSG_HASH(MSG_FAILED_TO_SEND_NICKNAME_TO_HOST,
      "FНе удалось отправить никнейм на хост.")
MSG_HASH(MSG_FAILED_TO_SEND_SRAM_DATA_TO_CLIENT,
      "Не удалось отправить данные SRAM клиенту.")
MSG_HASH(MSG_FAILED_TO_START_AUDIO_DRIVER,
      "Не удалось запустить звуковой драйвер. Будет продолжено без звука.")
MSG_HASH(MSG_FAILED_TO_START_MOVIE_RECORD,
      "Невозможно начать запись видео.")
MSG_HASH(MSG_FAILED_TO_START_RECORDING,
      "Невозможно начать запись.")
MSG_HASH(MSG_FAILED_TO_TAKE_SCREENSHOT,
      "Невозможно создать скриншот.")
MSG_HASH(MSG_FAILED_TO_UNDO_LOAD_STATE,
      "Не удалось отменить загрузку.")
MSG_HASH(MSG_FAILED_TO_UNDO_SAVE_STATE,
      "Не удалось отменить сохранение.")
MSG_HASH(MSG_FAILED_TO_UNMUTE_AUDIO,
      "Не удалось включить звук.")
MSG_HASH(MSG_FATAL_ERROR_RECEIVED_IN,
      "Получена критическая ошибка")
MSG_HASH(MSG_FILE_NOT_FOUND,
      "Файл не найден")
MSG_HASH(MSG_FOUND_AUTO_SAVESTATE_IN,
      "Найдено автосохранение в")
MSG_HASH(MSG_FOUND_DISK_LABEL,
      "Метка найденного диска")
MSG_HASH(MSG_FOUND_FIRST_DATA_TRACK_ON_FILE,
      "Найдена первая дорожка данных в файле")
MSG_HASH(MSG_FOUND_LAST_STATE_SLOT,
      "Найдено последний слот состояния")
MSG_HASH(MSG_FOUND_SHADER,
      "Обнаружен шейдер")
MSG_HASH(MSG_FRAMES,
      "Рамки")
MSG_HASH(MSG_GAME_SPECIFIC_CORE_OPTIONS_FOUND_AT,
      "Параметры игры: параметры ядра, определенные для игры")
MSG_HASH(MSG_GOT_INVALID_DISK_INDEX,
      "Задан неверный номер диска.")
MSG_HASH(MSG_GRAB_MOUSE_STATE,
      "Режим перехвата мыши")
MSG_HASH(MSG_HW_RENDERED_MUST_USE_POSTSHADED_RECORDING,
      "Ядро использует аппаратный рендеринг. Включите запись с GPU.")
MSG_HASH(MSG_INFLATED_CHECKSUM_DID_NOT_MATCH_CRC32,
      "Завышенная контрольная сумма не соответствует CRC32.")
MSG_HASH(MSG_INPUT_CHEAT,
      "Исходный чит")
MSG_HASH(MSG_INPUT_CHEAT_FILENAME,
      "Имя чита")
MSG_HASH(MSG_INPUT_PRESET_FILENAME,
      "Имя настроек")
MSG_HASH(MSG_INTERFACE,
      "Интерфейс")
MSG_HASH(MSG_INTERNAL_STORAGE,
      "Внутреннее хранилище")
MSG_HASH(MSG_REMOVABLE_STORAGE,
      "Внешнее хранилище")
MSG_HASH(MSG_INVALID_NICKNAME_SIZE,
      "Недопустимый размер никнейма.")
MSG_HASH(MSG_IN_BYTES,
      "В байтах")
MSG_HASH(MSG_IN_GIGABYTES,
      "В гигабайтах")
MSG_HASH(MSG_IN_MEGABYTES,
      "В мегабайтах")
MSG_HASH(MSG_LIBRETRO_ABI_BREAK,
      "Скомпилировано для другой версии libretro.")
MSG_HASH(MSG_LIBRETRO_FRONTEND,
      "Внешний интерфейс для libretro")
MSG_HASH(MSG_LOADED_STATE_FROM_SLOT,
      "Загружено сохранение из слота #%d.")
MSG_HASH(MSG_LOADED_STATE_FROM_SLOT_AUTO,
      "Загружено сохранение из слота #-1 (auto).")
MSG_HASH(MSG_LOADING,
      "Загрузка")
MSG_HASH(MSG_FIRMWARE,
      "Отсутствуют один или несколько файлов прошивки")
MSG_HASH(MSG_LOADING_CONTENT_FILE,
      "Загружен файл контента")
MSG_HASH(MSG_LOADING_HISTORY_FILE,
      "Загрузка файла истории")
MSG_HASH(MSG_LOADING_STATE,
      "Загружено сохранение")
MSG_HASH(MSG_MEMORY,
      "Память")
MSG_HASH(MSG_MOVIE_FILE_IS_NOT_A_VALID_BSV1_FILE,
      "Видеофайл не является допустимым файлом BSV1.")
MSG_HASH(MSG_MOVIE_FORMAT_DIFFERENT_SERIALIZER_VERSION,
      "Формат фильма, похоже, отличается от версии сериализатора.")
MSG_HASH(MSG_MOVIE_PLAYBACK_ENDED,
      "Достигнут конец записи.")
MSG_HASH(MSG_MOVIE_RECORD_STOPPED,
      "Запись остановлена.")
MSG_HASH(MSG_NETPLAY_FAILED,
      "Ошибка запуска сетевой игры.")
MSG_HASH(MSG_NO_CONTENT_STARTING_DUMMY_CORE,
      "Нет содержимого, начиная с фиктивного ядра.")
MSG_HASH(MSG_NO_SAVE_STATE_HAS_BEEN_OVERWRITTEN_YET,
      "Сохраненное состояние не было перезаписано.")
MSG_HASH(MSG_NO_STATE_HAS_BEEN_LOADED_YET,
      "Состояние еще не загружено.")
MSG_HASH(MSG_OVERRIDES_ERROR_SAVING,
      "Ошибка сохранения переопределений.")
MSG_HASH(MSG_OVERRIDES_SAVED_SUCCESSFULLY,
      "Переопределения сохранены успешно.")
MSG_HASH(MSG_PAUSED,
      "Пауза вкл.")
MSG_HASH(MSG_PROGRAM,
      "RetroArch")
MSG_HASH(MSG_READING_FIRST_DATA_TRACK,
      "Чтение первой дорожки данных ...")
MSG_HASH(MSG_RECEIVED,
      "Получено")
MSG_HASH(MSG_RECORDING_TERMINATED_DUE_TO_RESIZE,
      "Размеры окна были изменены. Запись остановлена.")
MSG_HASH(MSG_RECORDING_TO,
      "Запись в")
MSG_HASH(MSG_REDIRECTING_CHEATFILE_TO,
      "Файл с чит-кодами перенаправлен в")
MSG_HASH(MSG_REDIRECTING_SAVEFILE_TO,
      "Файл карты памяти перенаправлен в")
MSG_HASH(MSG_REDIRECTING_SAVESTATE_TO,
      "Файл сохранения перенаправлен в")
MSG_HASH(MSG_REMAP_FILE_SAVED_SUCCESSFULLY,
      "Remap file saved successfully.")
MSG_HASH(MSG_REMOVED_DISK_FROM_TRAY,
      "Диск извлечён.")
MSG_HASH(MSG_REMOVING_TEMPORARY_CONTENT_FILE,
      "Удалён временный файл контента")
MSG_HASH(MSG_RESET,
      "Сброс")
MSG_HASH(MSG_RESTARTING_RECORDING_DUE_TO_DRIVER_REINIT,
      "Реинициализация драйвера. Запись перезапущена.")
MSG_HASH(MSG_RESTORED_OLD_SAVE_STATE,
      "Восстановлено старое состояние сохранения.")
MSG_HASH(MSG_RESTORING_DEFAULT_SHADER_PRESET_TO,
      "Шейдеры: восстановление стандартных настроек шейдера")
MSG_HASH(MSG_REVERTING_SAVEFILE_DIRECTORY_TO,
      "Возврат каталога savefile на")
MSG_HASH(MSG_REVERTING_SAVESTATE_DIRECTORY_TO,
      "Возврат каталога savestate к")
MSG_HASH(MSG_REWINDING,
      "Перемотка.")
MSG_HASH(MSG_REWIND_INIT,
      "Инициализация буфера перемотки с размером")
MSG_HASH(MSG_REWIND_INIT_FAILED,
      "Ошибка создания буфера перемотки. Перемотка будет отключена.")
MSG_HASH(MSG_REWIND_INIT_FAILED_THREADED_AUDIO,
      "Ядро использует многопоточный звук. Перемотка невозможна.")
MSG_HASH(MSG_REWIND_REACHED_END,
      "Достигнут предел буфера перемотки.")
MSG_HASH(MSG_SAVED_NEW_CONFIG_TO,
      "Сохранено новое имя конфигурации")
MSG_HASH(MSG_SAVED_STATE_TO_SLOT,
      "Сохранено в слот #%d.")
MSG_HASH(MSG_SAVED_STATE_TO_SLOT_AUTO,
      "Сохранено в слот #-1 (auto).")
MSG_HASH(MSG_SAVED_SUCCESSFULLY_TO,
      "Успешно сохранено в")
MSG_HASH(MSG_SAVING_RAM_TYPE,
      "Запись RAM")
MSG_HASH(MSG_SAVING_STATE,
      "Сохранено")
MSG_HASH(MSG_SCANNING,
      "Сканирование")
MSG_HASH(MSG_SCANNING_OF_DIRECTORY_FINISHED,
      "Сканирование папки завершено")
MSG_HASH(MSG_SENDING_COMMAND,
      "Отправка команды")
MSG_HASH(MSG_SEVERAL_PATCHES_ARE_EXPLICITLY_DEFINED,
      "Несколько патчей явно определены, игнорируя все...")
MSG_HASH(MSG_SHADER,
      "Шейдер")
MSG_HASH(MSG_SHADER_PRESET_SAVED_SUCCESSFULLY,
      "Предварительная установка шейдера успешно сохранена.")
MSG_HASH(MSG_SKIPPING_SRAM_LOAD,
      "Пропуск загрузки SRAM.")
MSG_HASH(MSG_SLOW_MOTION,
      "Замедление.")
MSG_HASH(MSG_SLOW_MOTION_REWIND,
      "Замедленная перемотка.")
MSG_HASH(MSG_SRAM_WILL_NOT_BE_SAVED,
      "Невозможно сохранить SRAM.")
MSG_HASH(MSG_STARTING_MOVIE_PLAYBACK,
      "Воспроизведение записи.")
MSG_HASH(MSG_STARTING_MOVIE_RECORD_TO,
      "Запись видео в")
MSG_HASH(MSG_STATE_SIZE,
      "Размер сохранения")
MSG_HASH(MSG_STATE_SLOT,
      "Слот сохранения")
MSG_HASH(MSG_TAKING_SCREENSHOT,
      "Скриншот сохранён.")
MSG_HASH(MSG_TO,
      "в")
MSG_HASH(MSG_UNDID_LOAD_STATE,
      "Отключить состояние загрузки.")
MSG_HASH(MSG_UNDOING_SAVE_STATE,
      "Отмена сохранения состояния")
MSG_HASH(MSG_UNKNOWN,
      "Неизвестно.")
MSG_HASH(MSG_UNPAUSED,
      "Пауза откл.")
MSG_HASH(MSG_UNRECOGNIZED_COMMAND,
      "Неизвестная команда")
MSG_HASH(MSG_USING_CORE_NAME_FOR_NEW_CONFIG,
      "Использование имени ядра для новой конфигурации.")
MSG_HASH(MSG_USING_LIBRETRO_DUMMY_CORE_RECORDING_SKIPPED,
      "Используется фиктивное ядро. Запись не производится.")
MSG_HASH(MSG_VALUE_CONNECT_DEVICE_FROM_A_VALID_PORT,
      "Подключите устройство к действительному порту.")
MSG_HASH(MSG_VALUE_DISCONNECTING_DEVICE_FROM_PORT,
      "Отключение устройства от порта")
MSG_HASH(MSG_VALUE_REBOOTING,
      "Перезагрузка ...")
MSG_HASH(MSG_VALUE_SHUTTING_DOWN,
      "Выключение...")
MSG_HASH(MSG_VERSION_OF_LIBRETRO_API,
      "Версия API libretro")
MSG_HASH(MSG_VIEWPORT_SIZE_CALCULATION_FAILED,
      "Ошибка расчёта размеров окна проекции. Будут использованы необработанные данные. Возможны ошибки.")
MSG_HASH(MSG_VIRTUAL_DISK_TRAY,
      "Виртуальный лоток cd-привода")
MSG_HASH(MENU_ENUM_SUBLABEL_AUDIO_LATENCY,
      "Требуемая длительность звукового сигнала в миллисекундах. Невозможно удостовериться, что звуковой драйвер не может обеспечить заданную задержку.")
MSG_HASH(MENU_ENUM_SUBLABEL_AUDIO_MUTE,
      "Отключить / включить звук.")
MSG_HASH(
      MENU_ENUM_SUBLABEL_AUDIO_RATE_CONTROL_DELTA,
      "Помогает сгладить недостатки времени при синхронизации аудио и видео в одно и то же время. Имейте в виду, что если отключено, правильную синхронизацию получить почти невозможно."
      )
MSG_HASH(
      MENU_ENUM_SUBLABEL_CAMERA_ALLOW,
      "Разрешить или запретить доступ к камере с помощью ядер."
      )
MSG_HASH(
      MENU_ENUM_SUBLABEL_LOCATION_ALLOW,
      "Разрешить или запретить доступ к службам определения местоположения по ядрам."
      )
MSG_HASH(
      MENU_ENUM_SUBLABEL_INPUT_MAX_USERS,
      "Максимальное количество пользователей, поддерживаемых RetroArch."
      )
MSG_HASH(
      MENU_ENUM_SUBLABEL_INPUT_POLL_TYPE_BEHAVIOR,
      "Влияйте на то, как входной опрос выполняется внутри RetroArch. Установка его на« Early »или« Late »может привести к меньшему времени ожидания в зависимости от вашей конфигурации."
      )
MSG_HASH(
      MENU_ENUM_SUBLABEL_INPUT_ALL_USERS_CONTROL_MENU,
      "Позволяет любому пользователю управлять меню. Если отключено, только пользователь 1 может управлять меню."
      )
MSG_HASH(
      MENU_ENUM_SUBLABEL_AUDIO_VOLUME,
      "Громкость звука (в дБ). 0 дБ - это нормальный уровень громкости, при этом не применяется усиление."
      )
MSG_HASH(
   MENU_ENUM_SUBLABEL_AUDIO_SYNC,
   "Синхронизировать звук. Рекомендуется."
   )
MSG_HASH(
   MENU_ENUM_SUBLABEL_INPUT_AXIS_THRESHOLD,
   "Как далеко ось должна быть наклонена, чтобы вызвать нажатие кнопки."
   )
MSG_HASH(
   MENU_ENUM_SUBLABEL_INPUT_BIND_TIMEOUT,
   "Количество секунд ожидания до перехода к следующей привязке."
   )
MSG_HASH(
   MENU_ENUM_SUBLABEL_INPUT_TURBO_PERIOD,
   "Описывает период, в котором переключаются турбо кнопки. Значение описывается в кадрах."
   )
MSG_HASH(
   MENU_ENUM_SUBLABEL_INPUT_DUTY_CYCLE,
   "Описывает, как долго должен действовать период турбо кнопки. Значение описывается в кадрах."
   )
MSG_HASH(
   MENU_ENUM_SUBLABEL_VIDEO_VSYNC,
   "Синхронизирует видеовыход видеокарты с частотой обновления экрана. Рекомендуется."
   )
MSG_HASH(
   MENU_ENUM_SUBLABEL_VIDEO_ALLOW_ROTATE,
   "AРазрешить ядрам задавать поворот, при отключении, запросы на поворот игнорируются, что полезно при настройках, когда один из них поворачивает экран вручную."
   )
MSG_HASH(
   MENU_ENUM_SUBLABEL_DUMMY_ON_CORE_SHUTDOWN,
   "Некоторые ядра могут иметь функцию отключения, если она включена, это предотвратит остановку ядра от RetroArch, вместо этого он загрузит фиктивное ядро."
   )
MSG_HASH(
   MENU_ENUM_SUBLABEL_CHECK_FOR_MISSING_FIRMWARE,
   "Проверьте, все ли необходимые микропрограммы присутствуют, прежде чем пытаться загрузить контент."
   )
MSG_HASH(
   MENU_ENUM_SUBLABEL_VIDEO_REFRESH_RATE,
   "Вертикальная частота обновления экрана. Используется для расчета подходящей скорости ввода аудиосигнала. ПРИМЕЧАНИЕ: Это будет проигнорировано, если включено« Потоковое видео."
   )
MSG_HASH(
   MENU_ENUM_SUBLABEL_AUDIO_ENABLE,
   "Включить вывод звука."
   )
MSG_HASH(
   MENU_ENUM_SUBLABEL_AUDIO_MAX_TIMING_SKEW,
   "Максимальное изменение скорости ввода аудиосигнала. Возможно, вы захотите увеличить его, чтобы обеспечить очень большие изменения во времени, например, запуск PAL-ядер на дисплеях NTSC за счет неточности звукового поля."
   )
MSG_HASH(
   MSG_FAILED,
   "Не вышло"
   )
MSG_HASH(
   MSG_SUCCEEDED,
   "Удалось"
   )
MSG_HASH(
   MSG_DEVICE_NOT_CONFIGURED,
   "Не настроено"
   )
MSG_HASH(
   MSG_DEVICE_NOT_CONFIGURED_FALLBACK,
   "Не настроен, используется резервный"
   )
MSG_HASH(
   MENU_ENUM_LABEL_VALUE_DATABASE_CURSOR_LIST,
   "Список курсоров баз данных"
   )
MSG_HASH(
   MENU_ENUM_LABEL_VALUE_DATABASE_CURSOR_LIST_ENTRY_DEVELOPER,
   "База данных - Фильтр: Разработчик"
   )
MSG_HASH(
   MENU_ENUM_LABEL_VALUE_DATABASE_CURSOR_LIST_ENTRY_PUBLISHER,
   "База данных - Фильтр: Издатель"
   )
MSG_HASH(
   MENU_ENUM_LABEL_VALUE_DISABLED,
   "Отключено"
   )
MSG_HASH(
   MENU_ENUM_LABEL_VALUE_ENABLED,
   "Включено"
   )
MSG_HASH(
   MENU_ENUM_LABEL_VALUE_CONTENT_HISTORY_PATH,
   "Путь к истории контента"
   )
MSG_HASH(
      MENU_ENUM_LABEL_DATABASE_CURSOR_LIST_ENTRY_ORIGIN,
      "Database - Filter : Origin")
MSG_HASH(MENU_ENUM_LABEL_DATABASE_CURSOR_LIST_ENTRY_FRANCHISE,
      "Database - Filter : Franchise")
MSG_HASH(MENU_ENUM_LABEL_DATABASE_CURSOR_LIST_ENTRY_ESRB_RATING,
      "Database - Filter : ESRB Rating")
MSG_HASH(MENU_ENUM_LABEL_DATABASE_CURSOR_LIST_ENTRY_ELSPA_RATING,
      "Database - Filter : ELSPA Rating")
MSG_HASH(MENU_ENUM_LABEL_DATABASE_CURSOR_LIST_ENTRY_PEGI_RATING,
      "Database - Filter : PEGI Rating")
MSG_HASH(MENU_ENUM_LABEL_DATABASE_CURSOR_LIST_ENTRY_CERO_RATING,
      "Database - Filter : CERO Rating")
MSG_HASH(MENU_ENUM_LABEL_DATABASE_CURSOR_LIST_ENTRY_BBFC_RATING,
      "Database - Filter : BBFC Rating")
MSG_HASH(MENU_ENUM_LABEL_DATABASE_CURSOR_LIST_ENTRY_MAX_USERS,
      "Database - Filter : Max Users")
MSG_HASH(MENU_ENUM_LABEL_DATABASE_CURSOR_LIST_ENTRY_RELEASEDATE_BY_MONTH,
      "Database - Filter : Releasedate By Month")
MSG_HASH(MENU_ENUM_LABEL_DATABASE_CURSOR_LIST_ENTRY_RELEASEDATE_BY_YEAR,
      "Database - Filter : Releasedate By Year")
MSG_HASH(MENU_ENUM_LABEL_DATABASE_CURSOR_LIST_ENTRY_EDGE_MAGAZINE_ISSUE,
      "Database - Filter : Edge Magazine Issue")
MSG_HASH(MENU_ENUM_LABEL_DATABASE_CURSOR_LIST_ENTRY_EDGE_MAGAZINE_RATING,
      "Database - Filter : Edge Magazine Rating")
MSG_HASH(MENU_ENUM_LABEL_VALUE_DATABASE_CURSOR_LIST_ENTRY_DATABASE_INFO,
      "Database Info")
MSG_HASH(MENU_ENUM_SUBLABEL_PAUSE_NONACTIVE,
      "Pause gameplay when window focus is lost.")
MSG_HASH(MENU_ENUM_SUBLABEL_VIDEO_DISABLE_COMPOSITION,
      "Enable or disable composition (Windows only).")
MSG_HASH(MENU_ENUM_SUBLABEL_HISTORY_LIST_ENABLE,
      "Enable or disable recent playlist for games, images, music, and videos.")
MSG_HASH(MENU_ENUM_SUBLABEL_CONTENT_HISTORY_SIZE,
      "Limit the number of entries in recent playlist for games, images, music, and videos.")
MSG_HASH(MENU_ENUM_LABEL_VALUE_INPUT_UNIFIED_MENU_CONTROLS,
      "Unified Menu Controls")
MSG_HASH(MENU_ENUM_SUBLABEL_INPUT_UNIFIED_MENU_CONTROLS,
      "Use the same controls for both the menu and the game. Applies to the keyboard.")
MSG_HASH(MENU_ENUM_SUBLABEL_VIDEO_FONT_ENABLE,
      "Show onscreen messages.")
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BROWSE_URL_LIST,
      "Browse URL"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BROWSE_URL,
      "URL Path"
      )
MSG_HASH(
      MENU_ENUM_LABEL_VALUE_BROWSE_START,
      "Start"
      )
MSG_HASH(MENU_ENUM_LABEL_VALUE_SHADER_PIPELINE_BOKEH,
      "Bokeh")
