/* Arabic */
#define LANGUAGE_PROGRESS_ARABIC_TRANSLATED 46
#define LANGUAGE_PROGRESS_ARABIC_APPROVED   0

/* Asturian */
#define LANGUAGE_PROGRESS_ASTURIAN_TRANSLATED 11
#define LANGUAGE_PROGRESS_ASTURIAN_APPROVED   5

/* Catalan */
#define LANGUAGE_PROGRESS_CATALAN_TRANSLATED 47
#define LANGUAGE_PROGRESS_CATALAN_APPROVED   0

/* Czech */
#define LANGUAGE_PROGRESS_CZECH_TRANSLATED 99
#define LANGUAGE_PROGRESS_CZECH_APPROVED   0

/* Welsh */
#define LANGUAGE_PROGRESS_WELSH_TRANSLATED 4
#define LANGUAGE_PROGRESS_WELSH_APPROVED   0

/* Danish */
#define LANGUAGE_PROGRESS_DANISH_TRANSLATED 4
#define LANGUAGE_PROGRESS_DANISH_APPROVED   0

/* German */
#define LANGUAGE_PROGRESS_GERMAN_TRANSLATED 100
#define LANGUAGE_PROGRESS_GERMAN_APPROVED   17

/* Greek */
#define LANGUAGE_PROGRESS_GREEK_TRANSLATED 20
#define LANGUAGE_PROGRESS_GREEK_APPROVED   0

/* English, United Kingdom */
#define LANGUAGE_PROGRESS_ENGLISH_UNITED_KINGDOM_TRANSLATED 92
#define LANGUAGE_PROGRESS_ENGLISH_UNITED_KINGDOM_APPROVED   0

/* Esperanto */
#define LANGUAGE_PROGRESS_ESPERANTO_TRANSLATED 2
#define LANGUAGE_PROGRESS_ESPERANTO_APPROVED   0

/* Spanish */
#define LANGUAGE_PROGRESS_SPANISH_TRANSLATED 100
#define LANGUAGE_PROGRESS_SPANISH_APPROVED   99

/* Persian */
#define LANGUAGE_PROGRESS_PERSIAN_TRANSLATED 7
#define LANGUAGE_PROGRESS_PERSIAN_APPROVED   0

/* Finnish */
#define LANGUAGE_PROGRESS_FINNISH_TRANSLATED 80
#define LANGUAGE_PROGRESS_FINNISH_APPROVED   47

/* French */
#define LANGUAGE_PROGRESS_FRENCH_TRANSLATED 99
#define LANGUAGE_PROGRESS_FRENCH_APPROVED   99

/* Galician */
#define LANGUAGE_PROGRESS_GALICIAN_TRANSLATED 7
#define LANGUAGE_PROGRESS_GALICIAN_APPROVED   0

/* Hebrew */
#define LANGUAGE_PROGRESS_HEBREW_TRANSLATED 0
#define LANGUAGE_PROGRESS_HEBREW_APPROVED   0

/* Croatian */
#define LANGUAGE_PROGRESS_CROATIAN_TRANSLATED 2
#define LANGUAGE_PROGRESS_CROATIAN_APPROVED   0

/* Hungarian */
#define LANGUAGE_PROGRESS_HUNGARIAN_TRANSLATED 100
#define LANGUAGE_PROGRESS_HUNGARIAN_APPROVED   0

/* Indonesian */
#define LANGUAGE_PROGRESS_INDONESIAN_TRANSLATED 19
#define LANGUAGE_PROGRESS_INDONESIAN_APPROVED   0

/* Italian */
#define LANGUAGE_PROGRESS_ITALIAN_TRANSLATED 99
#define LANGUAGE_PROGRESS_ITALIAN_APPROVED   0

/* Japanese */
#define LANGUAGE_PROGRESS_JAPANESE_TRANSLATED 65
#define LANGUAGE_PROGRESS_JAPANESE_APPROVED   0

/* Korean */
#define LANGUAGE_PROGRESS_KOREAN_TRANSLATED 84
#define LANGUAGE_PROGRESS_KOREAN_APPROVED   0

/* Dutch */
#define LANGUAGE_PROGRESS_DUTCH_TRANSLATED 36
#define LANGUAGE_PROGRESS_DUTCH_APPROVED   0

/* Norwegian */
#define LANGUAGE_PROGRESS_NORWEGIAN_TRANSLATED 11
#define LANGUAGE_PROGRESS_NORWEGIAN_APPROVED   0

/* Polish */
#define LANGUAGE_PROGRESS_POLISH_TRANSLATED 77
#define LANGUAGE_PROGRESS_POLISH_APPROVED   26

/* Portuguese, Brazilian */
#define LANGUAGE_PROGRESS_PORTUGUESE_BRAZILIAN_TRANSLATED 82
#define LANGUAGE_PROGRESS_PORTUGUESE_BRAZILIAN_APPROVED   3

/* Portuguese */
#define LANGUAGE_PROGRESS_PORTUGUESE_TRANSLATED 22
#define LANGUAGE_PROGRESS_PORTUGUESE_APPROVED   0

/* Russian */
#define LANGUAGE_PROGRESS_RUSSIAN_TRANSLATED 88
#define LANGUAGE_PROGRESS_RUSSIAN_APPROVED   20

/* Slovak */
#define LANGUAGE_PROGRESS_SLOVAK_TRANSLATED 20
#define LANGUAGE_PROGRESS_SLOVAK_APPROVED   0

/* Serbian (Latin) */
#define LANGUAGE_PROGRESS_SERBIAN_LATIN_TRANSLATED 9
#define LANGUAGE_PROGRESS_SERBIAN_LATIN_APPROVED   0

/* Swedish */
#define LANGUAGE_PROGRESS_SWEDISH_TRANSLATED 15
#define LANGUAGE_PROGRESS_SWEDISH_APPROVED   0

/* Turkish */
#define LANGUAGE_PROGRESS_TURKISH_TRANSLATED 84
#define LANGUAGE_PROGRESS_TURKISH_APPROVED   84

/* Ukrainian */
#define LANGUAGE_PROGRESS_UKRAINIAN_TRANSLATED 34
#define LANGUAGE_PROGRESS_UKRAINIAN_APPROVED   8

/* Valencian */
#define LANGUAGE_PROGRESS_VALENCIAN_TRANSLATED 16
#define LANGUAGE_PROGRESS_VALENCIAN_APPROVED   0

/* Vietnamese */
#define LANGUAGE_PROGRESS_VIETNAMESE_TRANSLATED 7
#define LANGUAGE_PROGRESS_VIETNAMESE_APPROVED   0

/* Chinese Simplified */
#define LANGUAGE_PROGRESS_CHINESE_SIMPLIFIED_TRANSLATED 75
#define LANGUAGE_PROGRESS_CHINESE_SIMPLIFIED_APPROVED   52

/* Chinese Traditional */
#define LANGUAGE_PROGRESS_CHINESE_TRADITIONAL_TRANSLATED 83
#define LANGUAGE_PROGRESS_CHINESE_TRADITIONAL_APPROVED   81

