/* Arabic */
#define LANGUAGE_PROGRESS_ARABIC_TRANSLATED 0
#define LANGUAGE_PROGRESS_ARABIC_APPROVED   0

/* Chinese Simplified */
#define LANGUAGE_PROGRESS_CHINESE_SIMPLIFIED_TRANSLATED 72
#define LANGUAGE_PROGRESS_CHINESE_SIMPLIFIED_APPROVED   13

/* Chinese Traditional */
#define LANGUAGE_PROGRESS_CHINESE_TRADITIONAL_TRANSLATED 26
#define LANGUAGE_PROGRESS_CHINESE_TRADITIONAL_APPROVED   0

/* Dutch */
#define LANGUAGE_PROGRESS_DUTCH_TRANSLATED 15
#define LANGUAGE_PROGRESS_DUTCH_APPROVED   0

/* Esperanto */
#define LANGUAGE_PROGRESS_ESPERANTO_TRANSLATED 0
#define LANGUAGE_PROGRESS_ESPERANTO_APPROVED   0

/* French */
#define LANGUAGE_PROGRESS_FRENCH_TRANSLATED 100
#define LANGUAGE_PROGRESS_FRENCH_APPROVED   100

/* German */
#define LANGUAGE_PROGRESS_GERMAN_TRANSLATED 50
#define LANGUAGE_PROGRESS_GERMAN_APPROVED   0

/* Greek */
#define LANGUAGE_PROGRESS_GREEK_TRANSLATED 33
#define LANGUAGE_PROGRESS_GREEK_APPROVED   0

/* Italian */
#define LANGUAGE_PROGRESS_ITALIAN_TRANSLATED 53
#define LANGUAGE_PROGRESS_ITALIAN_APPROVED   0

/* Japanese */
#define LANGUAGE_PROGRESS_JAPANESE_TRANSLATED 74
#define LANGUAGE_PROGRESS_JAPANESE_APPROVED   0

/* Korean */
#define LANGUAGE_PROGRESS_KOREAN_TRANSLATED 85
#define LANGUAGE_PROGRESS_KOREAN_APPROVED   0

/* Polish */
#define LANGUAGE_PROGRESS_POLISH_TRANSLATED 98
#define LANGUAGE_PROGRESS_POLISH_APPROVED   0

/* Portuguese */
#define LANGUAGE_PROGRESS_PORTUGUESE_TRANSLATED 45
#define LANGUAGE_PROGRESS_PORTUGUESE_APPROVED   0

/* Portuguese, Brazilian */
#define LANGUAGE_PROGRESS_PORTUGUESE_BRAZILIAN_TRANSLATED 98
#define LANGUAGE_PROGRESS_PORTUGUESE_BRAZILIAN_APPROVED   0

/* Russian */
#define LANGUAGE_PROGRESS_RUSSIAN_TRANSLATED 55
#define LANGUAGE_PROGRESS_RUSSIAN_APPROVED   0

/* Slovak */
#define LANGUAGE_PROGRESS_SLOVAK_TRANSLATED 3
#define LANGUAGE_PROGRESS_SLOVAK_APPROVED   0

/* Spanish */
#define LANGUAGE_PROGRESS_SPANISH_TRANSLATED 99
#define LANGUAGE_PROGRESS_SPANISH_APPROVED   0

/* Turkish */
#define LANGUAGE_PROGRESS_TURKISH_TRANSLATED 100
#define LANGUAGE_PROGRESS_TURKISH_APPROVED   0

/* Vietnamese */
#define LANGUAGE_PROGRESS_VIETNAMESE_TRANSLATED 5
#define LANGUAGE_PROGRESS_VIETNAMESE_APPROVED   0

