#!/bin/sh
# Compiles the test's shaders into slang_rect_spirv.h as slang does:
# SPIR-V 1.0 for Vulkan, unoptimised. Needs glslangValidator; run from
# this directory after changing a shader.
set -eu
out=../slang_rect_spirv.h
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
{
   echo '/* Generated by shaders/gen.sh from shaders/: do not edit. */'
   echo
   echo '#ifndef SLANG_RECT_SPIRV_H__'
   echo '#define SLANG_RECT_SPIRV_H__'
   echo
   echo '#include <stdint.h>'
   for f in *.frag *.vert; do
      name=spv_$(echo "$f" | tr . _)
      glslangValidator -V --vn "$name" -o "$tmp/$name.h" "$f" >/dev/null
      echo
      sed -n '/^const uint32_t/,/^};/p' "$tmp/$name.h" \
         | sed 's/^const uint32_t/static const uint32_t/'
   done
   echo
   echo '#endif'
} > "$out"
