/*  RetroArch - A frontend for libretro.
 *  Copyright (C) 2010-2014 - Hans-Kristian Arntzen
 *  Copyright (C) 2011-2017 - Daniel De Matteis
 *
 *  RetroArch is free software: you can redistribute it and/or modify it under the terms
 *  of the GNU General Public License as published by the Free Software Found-
 *  ation, either version 3 of the License, or (at your option) any later version.
 *
 *  RetroArch is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 *  without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 *  PURPOSE.  See the GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along with RetroArch.
 *  If not, see <http://www.gnu.org/licenses/>.
 */

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <ctype.h>

#include <compat/strl.h>
#include <retro_assert.h>
#include <retro_miscellaneous.h>

#ifdef HAVE_CONFIG_H
#include "../config.h"
#endif

#include "../config.def.h"

#ifdef ANDROID
#include <android/keycodes.h>
#include "drivers_keyboard/keyboard_event_android.h"
#endif

#ifdef DJGPP
#include "drivers_keyboard/keyboard_event_dos.h"
#endif

#ifdef __QNX__
#include <sys/keycodes.h>
#endif

#if defined(HAVE_SDL) || defined(HAVE_SDL2)
#include "SDL.h"
#endif

#if defined(__linux__) || defined(HAVE_WAYLAND)
#include <linux/input.h>
#include <linux/kd.h>
#endif

#ifdef HAVE_X11
#include "input/include/xfree86_keycodes.h"
#endif

#ifdef HAVE_DINPUT
#undef DIRECTINPUT_VERSION
#define DIRECTINPUT_VERSION 0x0800

#include <dinput.h>
#endif

#include "input_keymaps.h"

#ifdef __APPLE__
#include "drivers_keyboard/keyboard_event_apple.h"

const struct apple_key_name_map_entry apple_key_name_map[] =
{
   { "left", KEY_Left },
   { "right", KEY_Right },
   { "up", KEY_Up },
   { "down", KEY_Down },
   { "enter", KEY_Enter },
   { "kp_enter", KP_Enter },
   { "space", KEY_Space },
   { "tab", KEY_Tab },
   { "shift", KEY_LeftShift },
   { "rshift", KEY_RightShift },
   { "ctrl", KEY_LeftControl },
   { "alt", KEY_LeftAlt },
   { "escape", KEY_Escape },
   { "backspace", KEY_DeleteForward },
   { "backquote", KEY_Grave },
   { "pause", KEY_Pause },
   { "f1", KEY_F1 },
   { "f2", KEY_F2 },
   { "f3", KEY_F3 },
   { "f4", KEY_F4 },
   { "f5", KEY_F5 },
   { "f6", KEY_F6 },
   { "f7", KEY_F7 },
   { "f8", KEY_F8 },
   { "f9", KEY_F9 },
   { "f10", KEY_F10 },
   { "f11", KEY_F11 },
   { "f12", KEY_F12 },
   { "num0", KEY_0 },
   { "num1", KEY_1 },
   { "num2", KEY_2 },
   { "num3", KEY_3 },
   { "num4", KEY_4 },
   { "num5", KEY_5 },
   { "num6", KEY_6 },
   { "num7", KEY_7 },
   { "num8", KEY_8 },
   { "num9", KEY_9 },

   { "insert", KEY_Insert },
   { "del", KEY_DeleteForward },
   { "home", KEY_Home },
   { "end", KEY_End },
   { "pageup", KEY_PageUp },
   { "pagedown", KEY_PageDown },

   { "add", KP_Add },
   { "subtract", KP_Subtract },
   { "multiply", KP_Multiply },
   { "divide", KP_Divide },
   { "keypad0", KP_0 },
   { "keypad1", KP_1 },
   { "keypad2", KP_2 },
   { "keypad3", KP_3 },
   { "keypad4", KP_4 },
   { "keypad5", KP_5 },
   { "keypad6", KP_6 },
   { "keypad7", KP_7 },
   { "keypad8", KP_8 },
   { "keypad9", KP_9 },

   { "period", KEY_Period },
   { "capslock", KEY_CapsLock },
   { "numlock", KP_NumLock },
   { "print_screen", KEY_PrintScreen },
   { "scroll_lock", KEY_ScrollLock },

   { "a", KEY_A },
   { "b", KEY_B },
   { "c", KEY_C },
   { "d", KEY_D },
   { "e", KEY_E },
   { "f", KEY_F },
   { "g", KEY_G },
   { "h", KEY_H },
   { "i", KEY_I },
   { "j", KEY_J },
   { "k", KEY_K },
   { "l", KEY_L },
   { "m", KEY_M },
   { "n", KEY_N },
   { "o", KEY_O },
   { "p", KEY_P },
   { "q", KEY_Q },
   { "r", KEY_R },
   { "s", KEY_S },
   { "t", KEY_T },
   { "u", KEY_U },
   { "v", KEY_V },
   { "w", KEY_W },
   { "x", KEY_X },
   { "y", KEY_Y },
   { "z", KEY_Z },

   { "nul", 0x00},
};
#endif

const struct input_key_map input_config_key_map[] = {
   { "left", RETROK_LEFT },
   { "right", RETROK_RIGHT },
   { "up", RETROK_UP },
   { "down", RETROK_DOWN },
   { "enter", RETROK_RETURN },
   { "kp_enter", RETROK_KP_ENTER },
   { "tab", RETROK_TAB },
   { "insert", RETROK_INSERT },
   { "del", RETROK_DELETE },
   { "end", RETROK_END },
   { "home", RETROK_HOME },
   { "rshift", RETROK_RSHIFT },
   { "shift", RETROK_LSHIFT },
   { "ctrl", RETROK_LCTRL },
   { "alt", RETROK_LALT },
   { "space", RETROK_SPACE },
   { "escape", RETROK_ESCAPE },
   { "add", RETROK_KP_PLUS },
   { "subtract", RETROK_KP_MINUS },
   { "kp_plus", RETROK_KP_PLUS },
   { "kp_minus", RETROK_KP_MINUS },
   { "f1", RETROK_F1 },
   { "f2", RETROK_F2 },
   { "f3", RETROK_F3 },
   { "f4", RETROK_F4 },
   { "f5", RETROK_F5 },
   { "f6", RETROK_F6 },
   { "f7", RETROK_F7 },
   { "f8", RETROK_F8 },
   { "f9", RETROK_F9 },
   { "f10", RETROK_F10 },
   { "f11", RETROK_F11 },
   { "f12", RETROK_F12 },
   { "num0", RETROK_0 },
   { "num1", RETROK_1 },
   { "num2", RETROK_2 },
   { "num3", RETROK_3 },
   { "num4", RETROK_4 },
   { "num5", RETROK_5 },
   { "num6", RETROK_6 },
   { "num7", RETROK_7 },
   { "num8", RETROK_8 },
   { "num9", RETROK_9 },
   { "pageup", RETROK_PAGEUP },
   { "pagedown", RETROK_PAGEDOWN },
   { "keypad0", RETROK_KP0 },
   { "keypad1", RETROK_KP1 },
   { "keypad2", RETROK_KP2 },
   { "keypad3", RETROK_KP3 },
   { "keypad4", RETROK_KP4 },
   { "keypad5", RETROK_KP5 },
   { "keypad6", RETROK_KP6 },
   { "keypad7", RETROK_KP7 },
   { "keypad8", RETROK_KP8 },
   { "keypad9", RETROK_KP9 },
   { "period", RETROK_PERIOD },
   { "capslock", RETROK_CAPSLOCK },
   { "numlock", RETROK_NUMLOCK },
   { "backspace", RETROK_BACKSPACE },
   { "multiply", RETROK_KP_MULTIPLY },
   { "divide", RETROK_KP_DIVIDE },
   { "print_screen", RETROK_PRINT },
   { "scroll_lock", RETROK_SCROLLOCK },
   { "tilde", RETROK_BACKQUOTE },
   { "backquote", RETROK_BACKQUOTE },
   { "pause", RETROK_PAUSE },

   /* Keys that weren't mappable before */
   { "quote", RETROK_QUOTE },
   { "comma", RETROK_COMMA },
   { "minus", RETROK_MINUS },
   { "slash", RETROK_SLASH },
   { "semicolon", RETROK_SEMICOLON },
   { "equals", RETROK_EQUALS },
   { "leftbracket", RETROK_LEFTBRACKET },
   { "backslash", RETROK_BACKSLASH },
   { "rightbracket", RETROK_RIGHTBRACKET },
   { "kp_period", RETROK_KP_PERIOD },
   { "kp_equals", RETROK_KP_EQUALS },
   { "rctrl", RETROK_RCTRL },
   { "ralt", RETROK_RALT },

   /* Keys not referenced in any keyboard mapping
    * (except perhaps rarch_key_map_apple_hid) */
   { "caret", RETROK_CARET },
   { "underscore", RETROK_UNDERSCORE },
   { "exclaim", RETROK_EXCLAIM },
   { "quotedbl", RETROK_QUOTEDBL },
   { "hash", RETROK_HASH },
   { "dollar", RETROK_DOLLAR },
   { "ampersand", RETROK_AMPERSAND },
   { "leftparen", RETROK_LEFTPAREN },
   { "rightparen", RETROK_RIGHTPAREN },
   { "asterisk", RETROK_ASTERISK },
   { "plus", RETROK_PLUS },
   { "colon", RETROK_COLON },
   { "less", RETROK_LESS },
   { "greater", RETROK_GREATER },
   { "question", RETROK_QUESTION },
   { "at", RETROK_AT },

   { "f13", RETROK_F13 },
   { "f14", RETROK_F14 },
   { "f15", RETROK_F15 },

   { "rmeta", RETROK_RMETA },
   { "lmeta", RETROK_LMETA },
   { "lsuper", RETROK_LSUPER },
   { "rsuper", RETROK_RSUPER },
   { "mode", RETROK_MODE },
   { "compose", RETROK_COMPOSE },

   { "help", RETROK_HELP },
   { "sysreq", RETROK_SYSREQ },
   { "break", RETROK_BREAK },
   { "menu", RETROK_MENU },
   { "power", RETROK_POWER },
   { "euro", RETROK_EURO },
   { "undo", RETROK_UNDO },
   { "clear", RETROK_CLEAR },
   { "oem102", RETROK_OEM_102 },

   { "nul", RETROK_UNKNOWN },
   { NULL, RETROK_UNKNOWN },
};

#ifdef HAVE_LIBNX
const struct rarch_key_map rarch_key_map_switch[] = {
   { KBD_A, RETROK_a },
   { KBD_B, RETROK_b },
   { KBD_C, RETROK_c },
   { KBD_D, RETROK_d },
   { KBD_E, RETROK_e },
   { KBD_F, RETROK_f },
   { KBD_G, RETROK_g },
   { KBD_H, RETROK_h },
   { KBD_I, RETROK_i },
   { KBD_J, RETROK_j },
   { KBD_K, RETROK_k },
   { KBD_L, RETROK_l },
   { KBD_M, RETROK_m },
   { KBD_N, RETROK_n },
   { KBD_O, RETROK_o },
   { KBD_P, RETROK_p },
   { KBD_Q, RETROK_q },
   { KBD_R, RETROK_r },
   { KBD_S, RETROK_s },
   { KBD_T, RETROK_t },
   { KBD_U, RETROK_u },
   { KBD_V, RETROK_v },
   { KBD_W, RETROK_w },
   { KBD_X, RETROK_x },
   { KBD_Y, RETROK_y },
   { KBD_Z, RETROK_z },
   { KBD_BACKSPACE, RETROK_BACKSPACE },
   { KBD_TAB, RETROK_TAB },
   { KBD_ENTER, RETROK_RETURN },
   { KBD_PAUSE, RETROK_PAUSE },
   { KBD_ESC, RETROK_ESCAPE },
   { KBD_SPACE, RETROK_SPACE },
   { KBD_HASHTILDE, RETROK_HASH },
   { KBD_APOSTROPHE, RETROK_QUOTE },
   { KBD_KPLEFTPAREN, RETROK_LEFTPAREN },
   { KBD_KPRIGHTPAREN, RETROK_RIGHTPAREN },
   { KBD_COMMA, RETROK_COMMA },
   { KBD_MINUS, RETROK_MINUS },
   { KBD_DOT, RETROK_PERIOD },
   { KBD_SLASH, RETROK_SLASH },
   { KBD_0, RETROK_0 },
   { KBD_1, RETROK_1 },
   { KBD_2, RETROK_2 },
   { KBD_3, RETROK_3 },
   { KBD_4, RETROK_4 },
   { KBD_5, RETROK_5 },
   { KBD_6, RETROK_6 },
   { KBD_7, RETROK_7 },
   { KBD_8, RETROK_8 },
   { KBD_9, RETROK_9 },
   { KBD_SEMICOLON, RETROK_SEMICOLON },
   { KBD_EQUAL, RETROK_EQUALS },
   { KBD_LEFTBRACE, RETROK_LEFTBRACKET },
   { KBD_BACKSLASH, RETROK_BACKSLASH },
   { KBD_RIGHTBRACE, RETROK_RIGHTBRACKET },
   { KBD_DELETE, RETROK_DELETE },
   { KBD_KP0, RETROK_KP0 },
   { KBD_KP1, RETROK_KP1 },
   { KBD_KP2, RETROK_KP2 },
   { KBD_KP3, RETROK_KP3 },
   { KBD_KP4, RETROK_KP4 },
   { KBD_KP5, RETROK_KP5 },
   { KBD_KP6, RETROK_KP6 },
   { KBD_KP7, RETROK_KP7 },
   { KBD_KP8, RETROK_KP8 },
   { KBD_KP9, RETROK_KP9 },
   { KBD_KPDOT, RETROK_KP_PERIOD },
   { KBD_KPSLASH, RETROK_KP_DIVIDE },
   { KBD_KPASTERISK, RETROK_KP_MULTIPLY },
   { KBD_KPMINUS, RETROK_KP_MINUS },
   { KBD_KPPLUS, RETROK_KP_PLUS },
   { KBD_KPENTER, RETROK_KP_ENTER },
   { KBD_KPEQUAL, RETROK_KP_EQUALS },
   { KBD_UP, RETROK_UP },
   { KBD_DOWN, RETROK_DOWN },
   { KBD_RIGHT, RETROK_RIGHT },
   { KBD_LEFT, RETROK_LEFT },
   { KBD_INSERT, RETROK_INSERT },
   { KBD_HOME, RETROK_HOME },
   { KBD_END, RETROK_END },
   { KBD_PAGEUP, RETROK_PAGEUP },
   { KBD_PAGEDOWN, RETROK_PAGEDOWN },
   { KBD_F1, RETROK_F1 },
   { KBD_F2, RETROK_F2 },
   { KBD_F3, RETROK_F3 },
   { KBD_F4, RETROK_F4 },
   { KBD_F5, RETROK_F5 },
   { KBD_F6, RETROK_F6 },
   { KBD_F7, RETROK_F7 },
   { KBD_F8, RETROK_F8 },
   { KBD_F9, RETROK_F9 },
   { KBD_F10, RETROK_F10 },
   { KBD_F11, RETROK_F11 },
   { KBD_F12, RETROK_F12 },
   { KBD_F13, RETROK_F13 },
   { KBD_F14, RETROK_F14 },
   { KBD_F15, RETROK_F15 },
   { KBD_NUMLOCK, RETROK_NUMLOCK },
   { KBD_CAPSLOCK, RETROK_CAPSLOCK },
   { KBD_SCROLLLOCK, RETROK_SCROLLOCK },
   { KBD_RIGHTSHIFT, RETROK_RSHIFT },
   { KBD_LEFTSHIFT, RETROK_LSHIFT },
   { KBD_RIGHTCTRL, RETROK_RCTRL },
   { KBD_LEFTCTRL, RETROK_LCTRL },
   { KBD_RIGHTALT, RETROK_RALT },
   { KBD_LEFTALT, RETROK_LALT },
   { KBD_LEFTMETA, RETROK_LMETA },
   { KBD_RIGHTMETA, RETROK_RMETA },
   { KBD_COMPOSE, RETROK_COMPOSE },
   { KBD_HELP, RETROK_HELP },
   { KBD_PAUSE, RETROK_BREAK },
   { KBD_POWER, RETROK_POWER },
   { KBD_UNDO, RETROK_UNDO },
   { 0, RETROK_UNKNOWN }
};
#endif

#ifdef VITA
// Vita scancodes are identical to USB 2.0 standard, e.g. SDL2
const struct rarch_key_map rarch_key_map_vita[] = {
   { 0x02A, RETROK_BACKSPACE },
   { 0x02B, RETROK_TAB },
   { 0x09C, RETROK_CLEAR },
   { 0x028, RETROK_RETURN },
   { 0x048, RETROK_PAUSE },
   { 0x029, RETROK_ESCAPE },
   { 0x02C, RETROK_SPACE },
   /*{ ?, RETROK_EXCLAIM },*/
   /*{ ?, RETROK_QUOTEDBL },*/
   /*{ ?, RETROK_HASH },*/
   /*{ ?, RETROK_DOLLAR },*/
   /*{ ?, RETROK_AMPERSAND },*/
   { 0x034, RETROK_QUOTE },
   /*{ ?, RETROK_LEFTPAREN },*/
   /*{ ?, RETROK_RIGHTPAREN },*/
   /*{ ?, RETROK_ASTERISK },*/
   /*{ ?, RETROK_PLUS },*/
   { 0x036, RETROK_COMMA },
   { 0x02D, RETROK_MINUS },
   { 0x037, RETROK_PERIOD },
   { 0x038, RETROK_SLASH },
   { 0x027, RETROK_0 },
   { 0x01E, RETROK_1 },
   { 0x01F, RETROK_2 },
   { 0x020, RETROK_3 },
   { 0x021, RETROK_4 },
   { 0x022, RETROK_5 },
   { 0x023, RETROK_6 },
   { 0x024, RETROK_7 },
   { 0x025, RETROK_8 },
   { 0x026, RETROK_9 },
   /*{ ?, RETROK_COLON },*/
   { 0x033, RETROK_SEMICOLON },
   /*{ ?, RETROK_OEM_102 },*/
   { 0x02E, RETROK_EQUALS },
   /*{ ?, RETROK_GREATER },*/
   /*{ ?, RETROK_QUESTION },*/
   /*{ ?, RETROK_AT },*/
   { 0x02F, RETROK_LEFTBRACKET },
   { 0x031, RETROK_BACKSLASH },
   { 0x030, RETROK_RIGHTBRACKET },
   /*{ ?, RETROK_CARET },*/
   /*{ ?, RETROK_UNDERSCORE },*/
   { 0x035, RETROK_BACKQUOTE },
   { 0x004, RETROK_a },
   { 0x005, RETROK_b },
   { 0x006, RETROK_c },
   { 0x007, RETROK_d },
   { 0x008, RETROK_e },
   { 0x009, RETROK_f },
   { 0x00A, RETROK_g },
   { 0x00B, RETROK_h },
   { 0x00C, RETROK_i },
   { 0x00D, RETROK_j },
   { 0x00E, RETROK_k },
   { 0x00F, RETROK_l },
   { 0x010, RETROK_m },
   { 0x011, RETROK_n },
   { 0x012, RETROK_o },
   { 0x013, RETROK_p },
   { 0x014, RETROK_q },
   { 0x015, RETROK_r },
   { 0x016, RETROK_s },
   { 0x017, RETROK_t },
   { 0x018, RETROK_u },
   { 0x019, RETROK_v },
   { 0x01A, RETROK_w },
   { 0x01B, RETROK_x },
   { 0x01C, RETROK_y },
   { 0x01D, RETROK_z },
   { 0x04C, RETROK_DELETE },
   { 0x062, RETROK_KP0 },
   { 0x059, RETROK_KP1 },
   { 0x05A, RETROK_KP2 },
   { 0x05B, RETROK_KP3 },
   { 0x05C, RETROK_KP4 },
   { 0x05D, RETROK_KP5 },
   { 0x05E, RETROK_KP6 },
   { 0x05F, RETROK_KP7 },
   { 0x060, RETROK_KP8 },
   { 0x061, RETROK_KP9 },
   { 0x063, RETROK_KP_PERIOD },
   { 0x054, RETROK_KP_DIVIDE },
   { 0x055, RETROK_KP_MULTIPLY },
   { 0x056, RETROK_KP_MINUS },
   { 0x057, RETROK_KP_PLUS },
   { 0x058, RETROK_KP_ENTER },
   { 0x067, RETROK_KP_EQUALS },
   { 0x052, RETROK_UP },
   { 0x051, RETROK_DOWN },
   { 0x04F, RETROK_RIGHT },
   { 0x050, RETROK_LEFT },
   { 0x049, RETROK_INSERT },
   { 0x04A, RETROK_HOME },
   { 0x04D, RETROK_END },
   { 0x04B, RETROK_PAGEUP },
   { 0x04E, RETROK_PAGEDOWN },
   { 0x03A, RETROK_F1 },
   { 0x03B, RETROK_F2 },
   { 0x03C, RETROK_F3 },
   { 0x03D, RETROK_F4 },
   { 0x03E, RETROK_F5 },
   { 0x03F, RETROK_F6 },
   { 0x040, RETROK_F7 },
   { 0x041, RETROK_F8 },
   { 0x042, RETROK_F9 },
   { 0x043, RETROK_F10 },
   { 0x044, RETROK_F11 },
   { 0x045, RETROK_F12 },
   { 0x068, RETROK_F13 },
   { 0x069, RETROK_F14 },
   { 0x06A, RETROK_F15 },
   { 0x053, RETROK_NUMLOCK },
   { 0x039, RETROK_CAPSLOCK },
   { 0x047, RETROK_SCROLLOCK },
   { 0x0E5, RETROK_RSHIFT },
   { 0x0E1, RETROK_LSHIFT },
   { 0x0E4, RETROK_RCTRL },
   { 0x0E0, RETROK_LCTRL },
   { 0x0E6, RETROK_RALT },
   { 0x0E2, RETROK_LALT },
   /* { ?, RETROK_RMETA }, */
   /* { ?, RETROK_LMETA }, */
   { 0x0E3, RETROK_LSUPER },
   { 0x0E7, RETROK_RSUPER },
   /* { ?, RETROK_MODE },*/
   { 0x075, RETROK_HELP },
   { 0x046, RETROK_PRINT },
   { 0x09A, RETROK_SYSREQ },
   { 0x048, RETROK_BREAK },
   { 0x076, RETROK_MENU },
   { 0x066, RETROK_POWER },
   /*{ ?, RETROK_EURO },*/
   { 0x07A, RETROK_UNDO },
   { 0, RETROK_UNKNOWN },
};
#endif

#if defined(HAVE_SDL) || defined(HAVE_SDL2)
const struct rarch_key_map rarch_key_map_sdl[] = {
   { SDLK_BACKSPACE, RETROK_BACKSPACE },
   { SDLK_TAB, RETROK_TAB },
   { SDLK_CLEAR, RETROK_CLEAR },
   { SDLK_RETURN, RETROK_RETURN },
   { SDLK_PAUSE, RETROK_PAUSE },
   { SDLK_ESCAPE, RETROK_ESCAPE },
   { SDLK_SPACE, RETROK_SPACE },
   { SDLK_EXCLAIM, RETROK_EXCLAIM },
   { SDLK_QUOTEDBL, RETROK_QUOTEDBL },
   { SDLK_HASH, RETROK_HASH },
   { SDLK_DOLLAR, RETROK_DOLLAR },
   { SDLK_AMPERSAND, RETROK_AMPERSAND },
   { SDLK_QUOTE, RETROK_QUOTE },
   { SDLK_LEFTPAREN, RETROK_LEFTPAREN },
   { SDLK_RIGHTPAREN, RETROK_RIGHTPAREN },
   { SDLK_ASTERISK, RETROK_ASTERISK },
   { SDLK_PLUS, RETROK_PLUS },
   { SDLK_COMMA, RETROK_COMMA },
   { SDLK_MINUS, RETROK_MINUS },
   { SDLK_PERIOD, RETROK_PERIOD },
   { SDLK_SLASH, RETROK_SLASH },
   { SDLK_0, RETROK_0 },
   { SDLK_1, RETROK_1 },
   { SDLK_2, RETROK_2 },
   { SDLK_3, RETROK_3 },
   { SDLK_4, RETROK_4 },
   { SDLK_5, RETROK_5 },
   { SDLK_6, RETROK_6 },
   { SDLK_7, RETROK_7 },
   { SDLK_8, RETROK_8 },
   { SDLK_9, RETROK_9 },
   { SDLK_COLON, RETROK_COLON },
   { SDLK_SEMICOLON, RETROK_SEMICOLON },
   { SDLK_LESS, RETROK_OEM_102 },
   { SDLK_EQUALS, RETROK_EQUALS },
   { SDLK_GREATER, RETROK_GREATER },
   { SDLK_QUESTION, RETROK_QUESTION },
   { SDLK_AT, RETROK_AT },
   { SDLK_LEFTBRACKET, RETROK_LEFTBRACKET },
   { SDLK_BACKSLASH, RETROK_BACKSLASH },
   { SDLK_RIGHTBRACKET, RETROK_RIGHTBRACKET },
   { SDLK_CARET, RETROK_CARET },
   { SDLK_UNDERSCORE, RETROK_UNDERSCORE },
   { SDLK_BACKQUOTE, RETROK_BACKQUOTE },
   { SDLK_a, RETROK_a },
   { SDLK_b, RETROK_b },
   { SDLK_c, RETROK_c },
   { SDLK_d, RETROK_d },
   { SDLK_e, RETROK_e },
   { SDLK_f, RETROK_f },
   { SDLK_g, RETROK_g },
   { SDLK_h, RETROK_h },
   { SDLK_i, RETROK_i },
   { SDLK_j, RETROK_j },
   { SDLK_k, RETROK_k },
   { SDLK_l, RETROK_l },
   { SDLK_m, RETROK_m },
   { SDLK_n, RETROK_n },
   { SDLK_o, RETROK_o },
   { SDLK_p, RETROK_p },
   { SDLK_q, RETROK_q },
   { SDLK_r, RETROK_r },
   { SDLK_s, RETROK_s },
   { SDLK_t, RETROK_t },
   { SDLK_u, RETROK_u },
   { SDLK_v, RETROK_v },
   { SDLK_w, RETROK_w },
   { SDLK_x, RETROK_x },
   { SDLK_y, RETROK_y },
   { SDLK_z, RETROK_z },
   { SDLK_DELETE, RETROK_DELETE },
#ifdef HAVE_SDL2
   { SDLK_KP_0, RETROK_KP0 },
   { SDLK_KP_1, RETROK_KP1 },
   { SDLK_KP_2, RETROK_KP2 },
   { SDLK_KP_3, RETROK_KP3 },
   { SDLK_KP_4, RETROK_KP4 },
   { SDLK_KP_5, RETROK_KP5 },
   { SDLK_KP_6, RETROK_KP6 },
   { SDLK_KP_7, RETROK_KP7 },
   { SDLK_KP_8, RETROK_KP8 },
   { SDLK_KP_9, RETROK_KP9 },
#else
   { SDLK_KP0, RETROK_KP0 },
   { SDLK_KP1, RETROK_KP1 },
   { SDLK_KP2, RETROK_KP2 },
   { SDLK_KP3, RETROK_KP3 },
   { SDLK_KP4, RETROK_KP4 },
   { SDLK_KP5, RETROK_KP5 },
   { SDLK_KP6, RETROK_KP6 },
   { SDLK_KP7, RETROK_KP7 },
   { SDLK_KP8, RETROK_KP8 },
   { SDLK_KP9, RETROK_KP9 },
#endif
   { SDLK_KP_PERIOD, RETROK_KP_PERIOD },
   { SDLK_KP_DIVIDE, RETROK_KP_DIVIDE },
   { SDLK_KP_MULTIPLY, RETROK_KP_MULTIPLY },
   { SDLK_KP_MINUS, RETROK_KP_MINUS },
   { SDLK_KP_PLUS, RETROK_KP_PLUS },
   { SDLK_KP_ENTER, RETROK_KP_ENTER },
   { SDLK_KP_EQUALS, RETROK_KP_EQUALS },
   { SDLK_UP, RETROK_UP },
   { SDLK_DOWN, RETROK_DOWN },
   { SDLK_RIGHT, RETROK_RIGHT },
   { SDLK_LEFT, RETROK_LEFT },
   { SDLK_INSERT, RETROK_INSERT },
   { SDLK_HOME, RETROK_HOME },
   { SDLK_END, RETROK_END },
   { SDLK_PAGEUP, RETROK_PAGEUP },
   { SDLK_PAGEDOWN, RETROK_PAGEDOWN },
   { SDLK_F1, RETROK_F1 },
   { SDLK_F2, RETROK_F2 },
   { SDLK_F3, RETROK_F3 },
   { SDLK_F4, RETROK_F4 },
   { SDLK_F5, RETROK_F5 },
   { SDLK_F6, RETROK_F6 },
   { SDLK_F7, RETROK_F7 },
   { SDLK_F8, RETROK_F8 },
   { SDLK_F9, RETROK_F9 },
   { SDLK_F10, RETROK_F10 },
   { SDLK_F11, RETROK_F11 },
   { SDLK_F12, RETROK_F12 },
   { SDLK_F13, RETROK_F13 },
   { SDLK_F14, RETROK_F14 },
   { SDLK_F15, RETROK_F15 },
#ifdef HAVE_SDL2
   { SDLK_NUMLOCKCLEAR, RETROK_NUMLOCK },
#else
   { SDLK_NUMLOCK, RETROK_NUMLOCK },
#endif
   { SDLK_CAPSLOCK, RETROK_CAPSLOCK },
#ifdef HAVE_SDL2
   { SDLK_SCROLLLOCK, RETROK_SCROLLOCK },
#else
   { SDLK_SCROLLOCK, RETROK_SCROLLOCK },
#endif
   { SDLK_RSHIFT, RETROK_RSHIFT },
   { SDLK_LSHIFT, RETROK_LSHIFT },
   { SDLK_RCTRL, RETROK_RCTRL },
   { SDLK_LCTRL, RETROK_LCTRL },
   { SDLK_RALT, RETROK_RALT },
   { SDLK_LALT, RETROK_LALT },
#ifdef HAVE_SDL2
   /* { ?, RETROK_RMETA }, */
   /* { ?, RETROK_LMETA }, */
   { SDLK_LGUI, RETROK_LSUPER },
   { SDLK_RGUI, RETROK_RSUPER },
#else
   { SDLK_RMETA, RETROK_RMETA },
   { SDLK_LMETA, RETROK_LMETA },
   { SDLK_LSUPER, RETROK_LSUPER },
   { SDLK_RSUPER, RETROK_RSUPER },
#endif
   { SDLK_MODE, RETROK_MODE },
#ifndef HAVE_SDL2
   { SDLK_COMPOSE, RETROK_COMPOSE },
#endif
   { SDLK_HELP, RETROK_HELP },
#ifdef HAVE_SDL2
   { SDLK_PRINTSCREEN, RETROK_PRINT },
#else
   { SDLK_PRINT, RETROK_PRINT },
#endif
   { SDLK_SYSREQ, RETROK_SYSREQ },
   { SDLK_PAUSE, RETROK_BREAK },
   { SDLK_MENU, RETROK_MENU },
   { SDLK_POWER, RETROK_POWER },

#ifndef HAVE_SDL2
   { SDLK_EURO, RETROK_EURO },
#endif
   { SDLK_UNDO, RETROK_UNDO },

   { 0, RETROK_UNKNOWN },
};
#endif

#ifdef HAVE_DINPUT
const struct rarch_key_map rarch_key_map_dinput[] = {
   { DIK_LEFT, RETROK_LEFT },
   { DIK_RIGHT, RETROK_RIGHT },
   { DIK_UP, RETROK_UP },
   { DIK_DOWN, RETROK_DOWN },
   { DIK_RETURN, RETROK_RETURN },
   { DIK_TAB, RETROK_TAB },
   { DIK_INSERT, RETROK_INSERT },
   { DIK_DELETE, RETROK_DELETE },
   { DIK_RSHIFT, RETROK_RSHIFT },
   { DIK_LSHIFT, RETROK_LSHIFT },
   { DIK_LCONTROL, RETROK_LCTRL },
   { DIK_END, RETROK_END },
   { DIK_HOME, RETROK_HOME },
   { DIK_NEXT, RETROK_PAGEDOWN },
   { DIK_PRIOR, RETROK_PAGEUP },
   { DIK_LALT, RETROK_LALT },
   { DIK_SPACE, RETROK_SPACE },
   { DIK_ESCAPE, RETROK_ESCAPE },
   { DIK_BACKSPACE, RETROK_BACKSPACE },
   { DIK_NUMPADENTER, RETROK_KP_ENTER },
   { DIK_NUMPADPLUS, RETROK_KP_PLUS },
   { DIK_NUMPADMINUS, RETROK_KP_MINUS },
   { DIK_NUMPADSTAR, RETROK_KP_MULTIPLY },
   { DIK_DIVIDE, RETROK_KP_DIVIDE },
   { DIK_GRAVE, RETROK_BACKQUOTE },
   { DIK_PAUSE, RETROK_PAUSE },
   { DIK_NUMPAD0, RETROK_KP0 },
   { DIK_NUMPAD1, RETROK_KP1 },
   { DIK_NUMPAD2, RETROK_KP2 },
   { DIK_NUMPAD3, RETROK_KP3 },
   { DIK_NUMPAD4, RETROK_KP4 },
   { DIK_NUMPAD5, RETROK_KP5 },
   { DIK_NUMPAD6, RETROK_KP6 },
   { DIK_NUMPAD7, RETROK_KP7 },
   { DIK_NUMPAD8, RETROK_KP8 },
   { DIK_NUMPAD9, RETROK_KP9 },
   { DIK_0, RETROK_0 },
   { DIK_1, RETROK_1 },
   { DIK_2, RETROK_2 },
   { DIK_3, RETROK_3 },
   { DIK_4, RETROK_4 },
   { DIK_5, RETROK_5 },
   { DIK_6, RETROK_6 },
   { DIK_7, RETROK_7 },
   { DIK_8, RETROK_8 },
   { DIK_9, RETROK_9 },
   { DIK_F1, RETROK_F1 },
   { DIK_F2, RETROK_F2 },
   { DIK_F3, RETROK_F3 },
   { DIK_F4, RETROK_F4 },
   { DIK_F5, RETROK_F5 },
   { DIK_F6, RETROK_F6 },
   { DIK_F7, RETROK_F7 },
   { DIK_F8, RETROK_F8 },
   { DIK_F9, RETROK_F9 },
   { DIK_F10, RETROK_F10 },
   { DIK_F11, RETROK_F11 },
   { DIK_F12, RETROK_F12 },
   { DIK_A, RETROK_a },
   { DIK_B, RETROK_b },
   { DIK_C, RETROK_c },
   { DIK_D, RETROK_d },
   { DIK_E, RETROK_e },
   { DIK_F, RETROK_f },
   { DIK_G, RETROK_g },
   { DIK_H, RETROK_h },
   { DIK_I, RETROK_i },
   { DIK_J, RETROK_j },
   { DIK_K, RETROK_k },
   { DIK_L, RETROK_l },
   { DIK_M, RETROK_m },
   { DIK_N, RETROK_n },
   { DIK_O, RETROK_o },
   { DIK_P, RETROK_p },
   { DIK_Q, RETROK_q },
   { DIK_R, RETROK_r },
   { DIK_S, RETROK_s },
   { DIK_T, RETROK_t },
   { DIK_U, RETROK_u },
   { DIK_V, RETROK_v },
   { DIK_W, RETROK_w },
   { DIK_X, RETROK_x },
   { DIK_Y, RETROK_y },
   { DIK_Z, RETROK_z },
   { DIK_APOSTROPHE, RETROK_QUOTE },
   { DIK_COMMA, RETROK_COMMA },
   { DIK_MINUS, RETROK_MINUS },
   { DIK_SLASH, RETROK_SLASH },
   { DIK_SEMICOLON, RETROK_SEMICOLON },
   { DIK_EQUALS, RETROK_EQUALS },
   { DIK_LBRACKET, RETROK_LEFTBRACKET },
   { DIK_BACKSLASH, RETROK_BACKSLASH },
   { DIK_RBRACKET, RETROK_RIGHTBRACKET },
   { DIK_DECIMAL, RETROK_KP_PERIOD },
   { DIK_RCONTROL, RETROK_RCTRL },
   { DIK_RMENU, RETROK_RALT },
   { DIK_PERIOD, RETROK_PERIOD },
   { DIK_SCROLL, RETROK_SCROLLOCK },
   { DIK_CAPSLOCK, RETROK_CAPSLOCK },
   { DIK_NUMLOCK, RETROK_NUMLOCK },
   { DIK_OEM_102, RETROK_OEM_102 },
   { 0, RETROK_UNKNOWN },
};
#endif

#ifdef EMSCRIPTEN
/* this is generated at runtime, so it isn't constant */
struct rarch_key_map rarch_key_map_rwebinput[RARCH_KEY_MAP_RWEBINPUT_SIZE];
#endif

#ifdef WIIU
const struct rarch_key_map rarch_key_map_wiiu[] = {
   { 4, RETROK_a },
   { 5, RETROK_b },
   { 6, RETROK_c },
   { 7, RETROK_d },
   { 8, RETROK_e },
   { 9, RETROK_f },
   { 10, RETROK_g },
   { 11, RETROK_h },
   { 12, RETROK_i },
   { 13, RETROK_j },
   { 14, RETROK_k },
   { 15, RETROK_l },
   { 16, RETROK_m },
   { 17, RETROK_n },
   { 18, RETROK_o },
   { 19, RETROK_p },
   { 20, RETROK_q },
   { 21, RETROK_r },
   { 22, RETROK_s },
   { 23, RETROK_t },
   { 24, RETROK_u },
   { 25, RETROK_v },
   { 26, RETROK_w },
   { 27, RETROK_x },
   { 28, RETROK_y },
   { 29, RETROK_z },
   { 30, RETROK_1 },
   { 31, RETROK_2 },
   { 32, RETROK_3 },
   { 33, RETROK_4 },
   { 34, RETROK_5 },
   { 35, RETROK_6 },
   { 36, RETROK_7 },
   { 37, RETROK_8 },
   { 38, RETROK_9 },
   { 39, RETROK_0 },
   { 40, RETROK_RETURN },
   { 41, RETROK_ESCAPE },
   { 42, RETROK_BACKSPACE },
   { 43, RETROK_TAB },
   { 44, RETROK_SPACE },
   { 45, RETROK_MINUS },
   { 46, RETROK_EQUALS },
   { 47, RETROK_LEFTBRACKET },
   { 48, RETROK_RIGHTBRACKET },
   { 49, RETROK_BACKSLASH },
   { 51, RETROK_SEMICOLON },
   { 52, RETROK_QUOTE },
   { 53, RETROK_BACKQUOTE },
   { 54, RETROK_COMMA },
   { 55, RETROK_PERIOD },
   { 56, RETROK_SLASH },
   { 57, RETROK_CAPSLOCK },
   { 58, RETROK_F1 },
   { 59, RETROK_F2 },
   { 60, RETROK_F3 },
   { 61, RETROK_F4 },
   { 62, RETROK_F5 },
   { 63, RETROK_F6 },
   { 64, RETROK_F7 },
   { 65, RETROK_F8 },
   { 66, RETROK_F9 },
   { 67, RETROK_F10 },
   { 68, RETROK_F11 },
   { 69, RETROK_F12 },
   { 71, RETROK_SCROLLOCK },
   { 72, RETROK_PAUSE },
   { 73, RETROK_INSERT },
   { 74, RETROK_HOME },
   { 75, RETROK_PAGEUP },
   { 76, RETROK_DELETE },
   { 77, RETROK_END },
   { 78, RETROK_PAGEDOWN },
   { 79, RETROK_RIGHT },
   { 80, RETROK_LEFT },
   { 81, RETROK_DOWN },
   { 82, RETROK_UP },
   { 83, RETROK_NUMLOCK },
   { 84, RETROK_KP_DIVIDE },
   { 85, RETROK_KP_MULTIPLY },
   { 86, RETROK_KP_MINUS },
   { 87, RETROK_KP_PLUS },
   { 88, RETROK_KP_ENTER },
   { 89, RETROK_KP1 },
   { 90, RETROK_KP2 },
   { 91, RETROK_KP3 },
   { 92, RETROK_KP4 },
   { 93, RETROK_KP5 },
   { 94, RETROK_KP6 },
   { 95, RETROK_KP7 },
   { 96, RETROK_KP8 },
   { 97, RETROK_KP9 },
   { 98, RETROK_KP0 },
   { 99, RETROK_KP_PERIOD },
   { 224, RETROK_LCTRL },
   { 225, RETROK_LSHIFT },
   { 226, RETROK_LALT },
   { 228, RETROK_RCTRL },
   { 229, RETROK_RSHIFT },
   { 230, RETROK_RALT },
   { 0, RETROK_UNKNOWN },
};
#endif

#ifdef HAVE_X11

const struct rarch_key_map rarch_key_map_x11[] = {

   { XFVK_ESC, RETROK_ESCAPE },
   { XFVK_FK01, RETROK_F1 },
   { XFVK_FK02, RETROK_F2 },
   { XFVK_FK03, RETROK_F3 },
   { XFVK_FK04, RETROK_F4 },
   { XFVK_FK05, RETROK_F5 },
   { XFVK_FK06, RETROK_F6 },
   { XFVK_FK07, RETROK_F7 },
   { XFVK_FK08, RETROK_F8 },
   { XFVK_FK09, RETROK_F9 },
   { XFVK_FK10, RETROK_F10 },
   { XFVK_FK11, RETROK_F11 },
   { XFVK_FK12, RETROK_F12 },

   { XFVK_TLDE, RETROK_BACKQUOTE },
   { XFVK_AE01, RETROK_1 },
   { XFVK_AE02, RETROK_2 },
   { XFVK_AE03, RETROK_3 },
   { XFVK_AE04, RETROK_4 },
   { XFVK_AE05, RETROK_5 },
   { XFVK_AE06, RETROK_6 },
   { XFVK_AE07, RETROK_7 },
   { XFVK_AE08, RETROK_8 },
   { XFVK_AE09, RETROK_9 },
   { XFVK_AE10, RETROK_0 },
   { XFVK_AE11, RETROK_MINUS },
   { XFVK_AE12, RETROK_EQUALS },
   { XFVK_BKSP, RETROK_BACKSPACE },

   { XFVK_TAB, RETROK_TAB },
   { XFVK_AD01, RETROK_q },
   { XFVK_AD02, RETROK_w },
   { XFVK_AD03, RETROK_e },
   { XFVK_AD04, RETROK_r },
   { XFVK_AD05, RETROK_t },
   { XFVK_AD06, RETROK_y },
   { XFVK_AD07, RETROK_u },
   { XFVK_AD08, RETROK_i },
   { XFVK_AD09, RETROK_o },
   { XFVK_AD10, RETROK_p },
   { XFVK_AD11, RETROK_LEFTBRACKET },
   { XFVK_AD12, RETROK_RIGHTBRACKET },
   { XFVK_RTRN, RETROK_RETURN },

   { XFVK_CAPS, RETROK_CAPSLOCK },
   { XFVK_AC01, RETROK_a },
   { XFVK_AC02, RETROK_s },
   { XFVK_AC03, RETROK_d },
   { XFVK_AC04, RETROK_f },
   { XFVK_AC05, RETROK_g },
   { XFVK_AC06, RETROK_h },
   { XFVK_AC07, RETROK_j },
   { XFVK_AC08, RETROK_k },
   { XFVK_AC09, RETROK_l },
   { XFVK_AC10, RETROK_SEMICOLON },
   { XFVK_AC11, RETROK_QUOTE },
   { XFVK_AC12, RETROK_BACKSLASH },

   { XFVK_LFSH, RETROK_LSHIFT },
   { XFVK_AB01, RETROK_z },
   { XFVK_AB02, RETROK_x },
   { XFVK_AB03, RETROK_c },
   { XFVK_AB04, RETROK_v },
   { XFVK_AB05, RETROK_b },
   { XFVK_AB06, RETROK_n },
   { XFVK_AB07, RETROK_m },
   { XFVK_AB08, RETROK_COMMA },
   { XFVK_AB09, RETROK_PERIOD },
   { XFVK_AB10, RETROK_SLASH },
   { XFVK_RTSH, RETROK_RSHIFT },

   { XFVK_LALT, RETROK_LALT },
   { XFVK_LCTL, RETROK_LCTRL },
   { XFVK_SPCE, RETROK_SPACE },
   { XFVK_RCTL, RETROK_RCTRL },
   { XFVK_RALT, RETROK_RALT },

   { XFVK_LSGT, RETROK_OEM_102 },
   { XFVK_MENU, RETROK_MENU },
   { XFVK_LWIN, RETROK_LSUPER },
   { XFVK_RWIN, RETROK_RSUPER },
   { XFVK_CALC, RETROK_HELP },

   { XFVK_PRSC, RETROK_PRINT },
   { XFVK_SCLK, RETROK_SCROLLOCK },
   { XFVK_PAUS, RETROK_PAUSE },
   { XFVK_INS, RETROK_INSERT },
   { XFVK_HOME, RETROK_HOME },
   { XFVK_PGUP, RETROK_PAGEUP },
   { XFVK_DELE, RETROK_DELETE },
   { XFVK_END, RETROK_END },
   { XFVK_PGDN, RETROK_PAGEDOWN },
   { XFVK_UP, RETROK_UP },
   { XFVK_LEFT, RETROK_LEFT },
   { XFVK_DOWN, RETROK_DOWN },
   { XFVK_RGHT, RETROK_RIGHT },

   { XFVK_NMLK, RETROK_NUMLOCK },
   { XFVK_KPDV, RETROK_KP_DIVIDE },
   { XFVK_KPMU, RETROK_KP_MULTIPLY },
   { XFVK_KPSU, RETROK_KP_MINUS },
   { XFVK_KP7, RETROK_KP7 },
   { XFVK_KP8, RETROK_KP8 },
   { XFVK_KP9, RETROK_KP9 },
   { XFVK_KPAD, RETROK_KP_PLUS },
   { XFVK_KP4, RETROK_KP4 },
   { XFVK_KP5, RETROK_KP5 },
   { XFVK_KP6, RETROK_KP6 },
   { XFVK_KP1, RETROK_KP1 },
   { XFVK_KP2, RETROK_KP2 },
   { XFVK_KP3, RETROK_KP3 },
   { XFVK_KPEN, RETROK_KP_ENTER },
   { XFVK_KP0, RETROK_KP0 },
   { XFVK_KPDL, RETROK_KP_PERIOD },
   { XFVK_KPEQ, RETROK_KP_EQUALS },

   { 0, RETROK_UNKNOWN },
};
#endif

#if defined(__linux__) || defined(HAVE_WAYLAND)
const struct rarch_key_map rarch_key_map_linux[] = {
   { KEY_BACKSPACE, RETROK_BACKSPACE },
   { KEY_TAB, RETROK_TAB },
   { KEY_CLEAR, RETROK_CLEAR },
   { KEY_ENTER, RETROK_RETURN },
   { KEY_PAUSE, RETROK_PAUSE },
   { KEY_ESC, RETROK_ESCAPE },
   { KEY_SPACE, RETROK_SPACE },
   /* { ?, RETROK_EXCLAIM }, */
   /* { ?, RETROK_QUOTEDBL }, */
   /* { ?, RETROK_HASH }, */
#ifndef ANDROID
   { KEY_DOLLAR, RETROK_DOLLAR },
#endif
   /* { ?, RETROK_AMPERSAND }, */
   { KEY_APOSTROPHE, RETROK_QUOTE },
   { KEY_KPLEFTPAREN, RETROK_LEFTPAREN },
   { KEY_KPRIGHTPAREN, RETROK_RIGHTPAREN },
   { KEY_KPASTERISK, RETROK_ASTERISK },
   { KEY_KPPLUS, RETROK_PLUS },
   { KEY_COMMA, RETROK_COMMA },
   { KEY_MINUS, RETROK_MINUS },
   { KEY_DOT, RETROK_PERIOD },
   { KEY_SLASH, RETROK_SLASH },
   { KEY_0, RETROK_0 },
   { KEY_1, RETROK_1 },
   { KEY_2, RETROK_2 },
   { KEY_3, RETROK_3 },
   { KEY_4, RETROK_4 },
   { KEY_5, RETROK_5 },
   { KEY_6, RETROK_6 },
   { KEY_7, RETROK_7 },
   { KEY_8, RETROK_8 },
   { KEY_9, RETROK_9 },
   /* { KEY_COLON, RETROK_COLON }, */
   { KEY_SEMICOLON, RETROK_SEMICOLON },
   /* { KEY_LESS, RETROK_LESS }, */
   { KEY_EQUAL, RETROK_EQUALS },
   /* { KEY_GREATER, RETROK_GREATER }, */
   { KEY_QUESTION, RETROK_QUESTION },
   /* { KEY_AT, RETROK_AT }, */
   { KEY_LEFTBRACE, RETROK_LEFTBRACKET },
   { KEY_BACKSLASH, RETROK_BACKSLASH },
   { KEY_RIGHTBRACE, RETROK_RIGHTBRACKET },
   /* { ?, RETROK_CARET }, */
   /* { ?, RETROK_UNDERSCORE }, */
   { KEY_GRAVE, RETROK_BACKQUOTE },
   { KEY_A, RETROK_a },
   { KEY_B, RETROK_b },
   { KEY_C, RETROK_c },
   { KEY_D, RETROK_d },
   { KEY_E, RETROK_e },
   { KEY_F, RETROK_f },
   { KEY_G, RETROK_g },
   { KEY_H, RETROK_h },
   { KEY_I, RETROK_i },
   { KEY_J, RETROK_j },
   { KEY_K, RETROK_k },
   { KEY_L, RETROK_l },
   { KEY_M, RETROK_m },
   { KEY_N, RETROK_n },
   { KEY_O, RETROK_o },
   { KEY_P, RETROK_p },
   { KEY_Q, RETROK_q },
   { KEY_R, RETROK_r },
   { KEY_S, RETROK_s },
   { KEY_T, RETROK_t },
   { KEY_U, RETROK_u },
   { KEY_V, RETROK_v },
   { KEY_W, RETROK_w },
   { KEY_X, RETROK_x },
   { KEY_Y, RETROK_y },
   { KEY_Z, RETROK_z },
   { KEY_DELETE, RETROK_DELETE },
   { KEY_KP0, RETROK_KP0 },
   { KEY_KP1, RETROK_KP1 },
   { KEY_KP2, RETROK_KP2 },
   { KEY_KP3, RETROK_KP3 },
   { KEY_KP4, RETROK_KP4 },
   { KEY_KP5, RETROK_KP5 },
   { KEY_KP6, RETROK_KP6 },
   { KEY_KP7, RETROK_KP7 },
   { KEY_KP8, RETROK_KP8 },
   { KEY_KP9, RETROK_KP9 },
   { KEY_KPDOT, RETROK_KP_PERIOD },
   { KEY_KPSLASH, RETROK_KP_DIVIDE },
   { KEY_KPASTERISK, RETROK_KP_MULTIPLY },
   { KEY_KPMINUS, RETROK_KP_MINUS },
   { KEY_KPPLUS, RETROK_KP_PLUS },
   { KEY_KPENTER, RETROK_KP_ENTER },
   { KEY_KPEQUAL, RETROK_KP_EQUALS },
   { KEY_UP, RETROK_UP },
   { KEY_DOWN, RETROK_DOWN },
   { KEY_RIGHT, RETROK_RIGHT },
   { KEY_LEFT, RETROK_LEFT },
   { KEY_INSERT, RETROK_INSERT },
   { KEY_HOME, RETROK_HOME },
   { KEY_END, RETROK_END },
   { KEY_PAGEUP, RETROK_PAGEUP },
   { KEY_PAGEDOWN, RETROK_PAGEDOWN },
   { KEY_F1, RETROK_F1 },
   { KEY_F2, RETROK_F2 },
   { KEY_F3, RETROK_F3 },
   { KEY_F4, RETROK_F4 },
   { KEY_F5, RETROK_F5 },
   { KEY_F6, RETROK_F6 },
   { KEY_F7, RETROK_F7 },
   { KEY_F8, RETROK_F8 },
   { KEY_F9, RETROK_F9 },
   { KEY_F10, RETROK_F10 },
   { KEY_F11, RETROK_F11 },
   { KEY_F12, RETROK_F12 },
   { KEY_F13, RETROK_F13 },
   { KEY_F14, RETROK_F14 },
   { KEY_F15, RETROK_F15 },
   { KEY_NUMLOCK, RETROK_NUMLOCK },
   { KEY_CAPSLOCK, RETROK_CAPSLOCK },
   { KEY_SCROLLLOCK, RETROK_SCROLLOCK },
   { KEY_RIGHTSHIFT, RETROK_RSHIFT },
   { KEY_LEFTSHIFT, RETROK_LSHIFT },
   { KEY_RIGHTCTRL, RETROK_RCTRL },
   { KEY_LEFTCTRL, RETROK_LCTRL },
   { KEY_RIGHTALT, RETROK_RALT },
   { KEY_LEFTALT, RETROK_LALT },
   /* { ?, RETROK_RMETA }, */
   /* { ?, RETROK_LMETA }, */
   { KEY_LEFTMETA, RETROK_LSUPER },
   { KEY_RIGHTMETA, RETROK_RSUPER },
   { KEY_MODE, RETROK_MODE },
   { KEY_COMPOSE, RETROK_COMPOSE },
   { KEY_HELP, RETROK_HELP },
   { KEY_PRINT, RETROK_PRINT },
   { KEY_SYSRQ, RETROK_SYSREQ },
   { KEY_BREAK, RETROK_BREAK },
   { KEY_MENU, RETROK_MENU },
   { KEY_POWER, RETROK_POWER },
#ifndef ANDROID
   { KEY_EURO, RETROK_EURO },
#endif
   { KEY_UNDO, RETROK_UNDO },
   { KEY_102ND, RETROK_OEM_102 },
   { 0, RETROK_UNKNOWN },
};
#endif

#ifdef ANDROID
const struct rarch_key_map rarch_key_map_android[] = {
   { AKEYCODE_DEL, RETROK_BACKSPACE },
   { AKEYCODE_TAB, RETROK_TAB },
   { AKEYCODE_CLEAR, RETROK_CLEAR },
   { AKEYCODE_ENTER, RETROK_RETURN },
   { AKEYCODE_BREAK, RETROK_PAUSE },
   { AKEYCODE_ESCAPE, RETROK_ESCAPE },
   { AKEYCODE_SPACE, RETROK_SPACE },
   { AKEYCODE_APOSTROPHE, RETROK_QUOTE },
   { AKEYCODE_NUMPAD_LEFT_PAREN, RETROK_LEFTPAREN },
   { AKEYCODE_NUMPAD_RIGHT_PAREN, RETROK_RIGHTPAREN },
   { AKEYCODE_NUMPAD_MULTIPLY, RETROK_ASTERISK },
   { AKEYCODE_NUMPAD_ADD, RETROK_PLUS },
   { AKEYCODE_COMMA, RETROK_COMMA },
   { AKEYCODE_MINUS, RETROK_MINUS },
   { AKEYCODE_PERIOD, RETROK_PERIOD },
   { AKEYCODE_SLASH, RETROK_SLASH },
   { AKEYCODE_0, RETROK_0 },
   { AKEYCODE_1, RETROK_1 },
   { AKEYCODE_2, RETROK_2 },
   { AKEYCODE_3, RETROK_3 },
   { AKEYCODE_4, RETROK_4 },
   { AKEYCODE_5, RETROK_5 },
   { AKEYCODE_6, RETROK_6 },
   { AKEYCODE_7, RETROK_7 },
   { AKEYCODE_8, RETROK_8 },
   { AKEYCODE_9, RETROK_9 },
   { AKEYCODE_SEMICOLON, RETROK_SEMICOLON },
   { AKEYCODE_EQUALS, RETROK_EQUALS },
   { AKEYCODE_LEFT_BRACKET, RETROK_LEFTBRACKET },
   { AKEYCODE_BACKSLASH, RETROK_BACKSLASH },
   { AKEYCODE_RIGHT_BRACKET, RETROK_RIGHTBRACKET },
   { AKEYCODE_GRAVE, RETROK_BACKQUOTE },
   { AKEYCODE_A, RETROK_a },
   { AKEYCODE_B, RETROK_b },
   { AKEYCODE_C, RETROK_c },
   { AKEYCODE_D, RETROK_d },
   { AKEYCODE_E, RETROK_e },
   { AKEYCODE_F, RETROK_f },
   { AKEYCODE_G, RETROK_g },
   { AKEYCODE_H, RETROK_h },
   { AKEYCODE_I, RETROK_i },
   { AKEYCODE_J, RETROK_j },
   { AKEYCODE_K, RETROK_k },
   { AKEYCODE_L, RETROK_l },
   { AKEYCODE_M, RETROK_m },
   { AKEYCODE_N, RETROK_n },
   { AKEYCODE_O, RETROK_o },
   { AKEYCODE_P, RETROK_p },
   { AKEYCODE_Q, RETROK_q },
   { AKEYCODE_R, RETROK_r },
   { AKEYCODE_S, RETROK_s },
   { AKEYCODE_T, RETROK_t },
   { AKEYCODE_U, RETROK_u },
   { AKEYCODE_V, RETROK_v },
   { AKEYCODE_W, RETROK_w },
   { AKEYCODE_X, RETROK_x },
   { AKEYCODE_Y, RETROK_y },
   { AKEYCODE_Z, RETROK_z },
   { AKEYCODE_DEL, RETROK_DELETE },
   { AKEYCODE_NUMPAD_0, RETROK_KP0 },
   { AKEYCODE_NUMPAD_1, RETROK_KP1 },
   { AKEYCODE_NUMPAD_2, RETROK_KP2 },
   { AKEYCODE_NUMPAD_3, RETROK_KP3 },
   { AKEYCODE_NUMPAD_4, RETROK_KP4 },
   { AKEYCODE_NUMPAD_5, RETROK_KP5 },
   { AKEYCODE_NUMPAD_6, RETROK_KP6 },
   { AKEYCODE_NUMPAD_7, RETROK_KP7 },
   { AKEYCODE_NUMPAD_8, RETROK_KP8 },
   { AKEYCODE_NUMPAD_9, RETROK_KP9 },
   { AKEYCODE_NUMPAD_DOT, RETROK_KP_PERIOD },
   { AKEYCODE_NUMPAD_DIVIDE, RETROK_KP_DIVIDE },
   { AKEYCODE_NUMPAD_MULTIPLY, RETROK_KP_MULTIPLY },
   { AKEYCODE_NUMPAD_SUBTRACT, RETROK_KP_MINUS },
   { AKEYCODE_NUMPAD_ADD, RETROK_KP_PLUS },
   { AKEYCODE_NUMPAD_ENTER, RETROK_KP_ENTER },
   { AKEYCODE_NUMPAD_EQUALS, RETROK_KP_EQUALS },
   { AKEYCODE_DPAD_UP, RETROK_UP },
   { AKEYCODE_DPAD_DOWN, RETROK_DOWN },
   { AKEYCODE_DPAD_RIGHT, RETROK_RIGHT },
   { AKEYCODE_DPAD_LEFT, RETROK_LEFT },
   { AKEYCODE_INSERT, RETROK_INSERT },
   { AKEYCODE_MOVE_HOME, RETROK_HOME },
   { AKEYCODE_MOVE_END, RETROK_END },
   { AKEYCODE_PAGE_UP, RETROK_PAGEUP },
   { AKEYCODE_PAGE_DOWN, RETROK_PAGEDOWN },
   { AKEYCODE_F1, RETROK_F1 },
   { AKEYCODE_F2, RETROK_F2 },
   { AKEYCODE_F3, RETROK_F3 },
   { AKEYCODE_F4, RETROK_F4 },
   { AKEYCODE_F5, RETROK_F5 },
   { AKEYCODE_F6, RETROK_F6 },
   { AKEYCODE_F7, RETROK_F7 },
   { AKEYCODE_F8, RETROK_F8 },
   { AKEYCODE_F9, RETROK_F9 },
   { AKEYCODE_F10, RETROK_F10 },
   { AKEYCODE_F11, RETROK_F11 },
   { AKEYCODE_F12, RETROK_F12 },
   { AKEYCODE_NUM_LOCK, RETROK_NUMLOCK },
   { AKEYCODE_CAPS_LOCK, RETROK_CAPSLOCK },
   { AKEYCODE_SCROLL_LOCK, RETROK_SCROLLOCK },
   { AKEYCODE_SHIFT_LEFT, RETROK_RSHIFT },
   { AKEYCODE_SHIFT_RIGHT, RETROK_LSHIFT },
   { AKEYCODE_CTRL_RIGHT, RETROK_RCTRL },
   { AKEYCODE_CTRL_LEFT, RETROK_LCTRL },
   { AKEYCODE_ALT_RIGHT, RETROK_RALT },
   { AKEYCODE_ALT_LEFT, RETROK_LALT },
   { 0, RETROK_UNKNOWN },
};
#endif

#ifdef __QNX__
const struct rarch_key_map rarch_key_map_qnx[] = {
   { KEYCODE_BACKSPACE, RETROK_BACKSPACE },
   { KEYCODE_RETURN, RETROK_RETURN },
   { KEYCODE_SPACE, RETROK_SPACE },
   { KEYCODE_UP, RETROK_UP },
   { KEYCODE_DOWN, RETROK_DOWN },
   { KEYCODE_LEFT, RETROK_LEFT },
   { KEYCODE_RIGHT, RETROK_RIGHT },
   { KEYCODE_A, RETROK_a },
   { KEYCODE_B, RETROK_b },
   { KEYCODE_C, RETROK_c },
   { KEYCODE_D, RETROK_d },
   { KEYCODE_E, RETROK_e },
   { KEYCODE_F, RETROK_f },
   { KEYCODE_G, RETROK_g },
   { KEYCODE_H, RETROK_h },
   { KEYCODE_I, RETROK_i },
   { KEYCODE_J, RETROK_j },
   { KEYCODE_K, RETROK_k },
   { KEYCODE_L, RETROK_l },
   { KEYCODE_M, RETROK_m },
   { KEYCODE_N, RETROK_n },
   { KEYCODE_O, RETROK_o },
   { KEYCODE_P, RETROK_p },
   { KEYCODE_Q, RETROK_q },
   { KEYCODE_R, RETROK_r },
   { KEYCODE_S, RETROK_s },
   { KEYCODE_T, RETROK_t },
   { KEYCODE_U, RETROK_u },
   { KEYCODE_V, RETROK_v },
   { KEYCODE_W, RETROK_w },
   { KEYCODE_X, RETROK_x },
   { KEYCODE_Y, RETROK_y },
   { KEYCODE_Z, RETROK_z },
   { KEYCODE_ZERO, RETROK_0 },
   { KEYCODE_ONE, RETROK_1 },
   { KEYCODE_TWO, RETROK_2 },
   { KEYCODE_THREE, RETROK_3 },
   { KEYCODE_FOUR, RETROK_4 },
   { KEYCODE_FIVE, RETROK_5 },
   { KEYCODE_SIX, RETROK_6 },
   { KEYCODE_SEVEN, RETROK_7 },
   { KEYCODE_EIGHT, RETROK_8 },
   { KEYCODE_NINE, RETROK_9 },
   { KEYCODE_INSERT, RETROK_INSERT },
   { KEYCODE_HOME, RETROK_HOME },
   { KEYCODE_END, RETROK_END },
   { KEYCODE_PG_UP, RETROK_PAGEUP },
   { KEYCODE_PG_DOWN, RETROK_PAGEDOWN },
   { KEYCODE_F1, RETROK_F1 },
   { KEYCODE_F2, RETROK_F2 },
   { KEYCODE_F3, RETROK_F3 },
   { KEYCODE_F4, RETROK_F4 },
   { KEYCODE_F5, RETROK_F5 },
   { KEYCODE_F6, RETROK_F6 },
   { KEYCODE_F7, RETROK_F7 },
   { KEYCODE_F8, RETROK_F8 },
   { KEYCODE_F9, RETROK_F9 },
   { KEYCODE_F10, RETROK_F10 },
   { KEYCODE_F11, RETROK_F11 },
   { KEYCODE_F12, RETROK_F12 },
   { KEYCODE_LEFT_SHIFT, RETROK_LSHIFT },
   { KEYCODE_RIGHT_SHIFT, RETROK_RSHIFT },
   { KEYCODE_LEFT_CTRL, RETROK_LCTRL },
   { KEYCODE_RIGHT_CTRL, RETROK_RCTRL },
   { KEYCODE_LEFT_ALT, RETROK_LALT },
   { KEYCODE_RIGHT_ALT, RETROK_RALT },
   // TODO/FIXME: Code for 'sym' key on BB keyboards. Figure out which sys/keycodes.h define this maps to.
   { 61651, RETROK_RSUPER },
   { KEYCODE_DOLLAR, RETROK_DOLLAR },
   { KEYCODE_MENU, RETROK_MENU },
   { 0, RETROK_UNKNOWN },
};
#endif

#ifdef __APPLE__
const struct rarch_key_map rarch_key_map_apple_hid[] = {
   { KEY_Delete, RETROK_BACKSPACE },
   { KEY_Tab, RETROK_TAB },
   /* { ?, RETROK_CLEAR }, */
   { KEY_Enter, RETROK_RETURN },
   { KEY_Pause, RETROK_PAUSE },
   { KEY_Escape, RETROK_ESCAPE },
   { KEY_Space, RETROK_SPACE },
   /* { ?, RETROK_EXCLAIM }, */
   /* { ?, RETROK_QUOTEDBL }, */
   /* { ?, RETROK_HASH }, */
   /* { ?, RETROK_DOLLAR }, */
   /* { ?, RETROK_AMPERSAND }, */
   { KEY_Quote, RETROK_QUOTE },
   /* { ?, RETROK_LEFTPAREN }, */
   /* { ?, RETROK_RIGHTPAREN }, */
   /* { ?, RETROK_ASTERISK }, */
   /* { ?, RETROK_PLUS }, */
   { KEY_Comma, RETROK_COMMA },
   { KEY_Minus, RETROK_MINUS },
   { KEY_Period, RETROK_PERIOD },
   { KEY_Slash, RETROK_SLASH },
   { KEY_0, RETROK_0 },
   { KEY_1, RETROK_1 },
   { KEY_2, RETROK_2 },
   { KEY_3, RETROK_3 },
   { KEY_4, RETROK_4 },
   { KEY_5, RETROK_5 },
   { KEY_6, RETROK_6 },
   { KEY_7, RETROK_7 },
   { KEY_8, RETROK_8 },
   { KEY_9, RETROK_9 },
   /* { ?, RETROK_COLON }, */
   { KEY_Semicolon, RETROK_SEMICOLON },
   /* { ?, RETROK_LESS }, */
   { KEY_Equals, RETROK_EQUALS },
   /* { ?, RETROK_GREATER }, */
   /* { ?, RETROK_QUESTION }, */
   /* { ?, RETROK_AT }, */
   { KEY_LeftBracket, RETROK_LEFTBRACKET },
   { KEY_Backslash, RETROK_BACKSLASH },
   { KEY_RightBracket, RETROK_RIGHTBRACKET },
   /* { ?, RETROK_CARET }, */
   /* { ?, RETROK_UNDERSCORE }, */
   { KEY_Grave, RETROK_BACKQUOTE },
   { KEY_A, RETROK_a },
   { KEY_B, RETROK_b },
   { KEY_C, RETROK_c },
   { KEY_D, RETROK_d },
   { KEY_E, RETROK_e },
   { KEY_F, RETROK_f },
   { KEY_G, RETROK_g },
   { KEY_H, RETROK_h },
   { KEY_I, RETROK_i },
   { KEY_J, RETROK_j },
   { KEY_K, RETROK_k },
   { KEY_L, RETROK_l },
   { KEY_M, RETROK_m },
   { KEY_N, RETROK_n },
   { KEY_O, RETROK_o },
   { KEY_P, RETROK_p },
   { KEY_Q, RETROK_q },
   { KEY_R, RETROK_r },
   { KEY_S, RETROK_s },
   { KEY_T, RETROK_t },
   { KEY_U, RETROK_u },
   { KEY_V, RETROK_v },
   { KEY_W, RETROK_w },
   { KEY_X, RETROK_x },
   { KEY_Y, RETROK_y },
   { KEY_Z, RETROK_z },
   { KEY_DeleteForward, RETROK_DELETE },

   { KP_0, RETROK_KP0 },
   { KP_1, RETROK_KP1 },
   { KP_2, RETROK_KP2 },
   { KP_3, RETROK_KP3 },
   { KP_4, RETROK_KP4 },
   { KP_5, RETROK_KP5 },
   { KP_6, RETROK_KP6 },
   { KP_7, RETROK_KP7 },
   { KP_8, RETROK_KP8 },
   { KP_9, RETROK_KP9 },
   { KP_Point, RETROK_KP_PERIOD },
   { KP_Divide, RETROK_KP_DIVIDE },
   { KP_Multiply, RETROK_KP_MULTIPLY },
   { KP_Subtract, RETROK_KP_MINUS },
   { KP_Add, RETROK_KP_PLUS },
   { KP_Enter, RETROK_KP_ENTER },
   { KP_Equals, RETROK_KP_EQUALS },

   { KEY_Up, RETROK_UP },
   { KEY_Down, RETROK_DOWN },
   { KEY_Right, RETROK_RIGHT },
   { KEY_Left, RETROK_LEFT },
   { KEY_Insert, RETROK_INSERT },
   { KEY_Home, RETROK_HOME },
   { KEY_End, RETROK_END },
   { KEY_PageUp, RETROK_PAGEUP },
   { KEY_PageDown, RETROK_PAGEDOWN },

   { KEY_F1, RETROK_F1 },
   { KEY_F2, RETROK_F2 },
   { KEY_F3, RETROK_F3 },
   { KEY_F4, RETROK_F4 },
   { KEY_F5, RETROK_F5 },
   { KEY_F6, RETROK_F6 },
   { KEY_F7, RETROK_F7 },
   { KEY_F8, RETROK_F8 },
   { KEY_F9, RETROK_F9 },
   { KEY_F10, RETROK_F10 },
   { KEY_F11, RETROK_F11 },
   { KEY_F12, RETROK_F12 },
   { KEY_F13, RETROK_F13 },
   { KEY_F14, RETROK_F14 },
   { KEY_F15, RETROK_F15 },

   /* { ?, RETROK_NUMLOCK }, */
   { KEY_CapsLock, RETROK_CAPSLOCK },
   /* { ?, RETROK_SCROLLOCK }, */
   { KEY_RightShift, RETROK_RSHIFT },
   { KEY_LeftShift, RETROK_LSHIFT },
   { KEY_RightControl, RETROK_RCTRL },
   { KEY_LeftControl, RETROK_LCTRL },
   { KEY_RightAlt, RETROK_RALT },
   { KEY_LeftAlt, RETROK_LALT },
   { KEY_RightGUI, RETROK_RMETA },
   { KEY_LeftGUI, RETROK_RMETA },
   /* { ?, RETROK_LSUPER }, */
   /* { ?, RETROK_RSUPER }, */
   /* { ?, RETROK_MODE }, */
   /* { ?, RETROK_COMPOSE }, */

   /* { ?, RETROK_HELP }, */
   { KEY_PrintScreen, RETROK_PRINT },
   /* { ?, RETROK_SYSREQ }, */
   /* { ?, RETROK_BREAK }, */
   { KEY_Menu, RETROK_MENU },
   /* { ?, RETROK_POWER }, */
   /* { ?, RETROK_EURO }, */
   /* { ?, RETROK_UNDO }, */
   { KEY_NonUSBackslash, RETROK_OEM_102 },
   { 0, RETROK_UNKNOWN }
};
#endif

#ifdef DJGPP
const struct rarch_key_map rarch_key_map_dos[] = {
   { DOSKEY_ESCAPE, RETROK_ESCAPE },
   { DOSKEY_F1, RETROK_F1 },
   { DOSKEY_F2, RETROK_F2 },
   { DOSKEY_F3, RETROK_F3 },
   { DOSKEY_F4, RETROK_F4 },
   { DOSKEY_F5, RETROK_F5 },
   { DOSKEY_F6, RETROK_F6 },
   { DOSKEY_F7, RETROK_F7 },
   { DOSKEY_F8, RETROK_F8 },
   { DOSKEY_F9, RETROK_F9 },
   { DOSKEY_F10, RETROK_F10 },

   { DOSKEY_BACKQUOTE, RETROK_BACKQUOTE },
   { DOSKEY_1, RETROK_1 },
   { DOSKEY_2, RETROK_2 },
   { DOSKEY_3, RETROK_3 },
   { DOSKEY_4, RETROK_4 },
   { DOSKEY_5, RETROK_5 },
   { DOSKEY_6, RETROK_6 },
   { DOSKEY_7, RETROK_7 },
   { DOSKEY_8, RETROK_8 },
   { DOSKEY_9, RETROK_9 },
   { DOSKEY_0, RETROK_0 },
   { DOSKEY_MINUS, RETROK_MINUS },
   { DOSKEY_EQUAL, RETROK_EQUALS },
   { DOSKEY_BACKSPACE, RETROK_BACKSPACE },

   { DOSKEY_TAB, RETROK_TAB },
   { DOSKEY_q, RETROK_q },
   { DOSKEY_w, RETROK_w },
   { DOSKEY_e, RETROK_e },
   { DOSKEY_r, RETROK_r },
   { DOSKEY_t, RETROK_t },
   { DOSKEY_y, RETROK_y },
   { DOSKEY_u, RETROK_u },
   { DOSKEY_i, RETROK_i },
   { DOSKEY_o, RETROK_o },
   { DOSKEY_p, RETROK_p },
   { DOSKEY_LBRACKET, RETROK_LEFTBRACKET },
   { DOSKEY_RBRACKET, RETROK_RIGHTBRACKET },
   { DOSKEY_BACKSLASH, RETROK_BACKSLASH },

   { DOSKEY_CAPSLOCK, RETROK_CAPSLOCK },
   { DOSKEY_a, RETROK_a },
   { DOSKEY_s, RETROK_s },
   { DOSKEY_d, RETROK_d },
   { DOSKEY_f, RETROK_f },
   { DOSKEY_g, RETROK_g },
   { DOSKEY_h, RETROK_h },
   { DOSKEY_j, RETROK_j },
   { DOSKEY_k, RETROK_k },
   { DOSKEY_l, RETROK_l },
   { DOSKEY_SEMICOLON, RETROK_SEMICOLON },
   { DOSKEY_QUOTE, RETROK_QUOTE },
   { DOSKEY_RETURN, RETROK_RETURN },

   { DOSKEY_LSHIFT, RETROK_LSHIFT },
   { DOSKEY_z, RETROK_z },
   { DOSKEY_x, RETROK_x },
   { DOSKEY_c, RETROK_c },
   { DOSKEY_v, RETROK_v },
   { DOSKEY_b, RETROK_b },
   { DOSKEY_n, RETROK_n },
   { DOSKEY_m, RETROK_m },
   { DOSKEY_COMMA, RETROK_COMMA },
   { DOSKEY_PERIOD, RETROK_PERIOD },
   { DOSKEY_SLASH, RETROK_SLASH },
   { DOSKEY_RSHIFT, RETROK_RSHIFT },

   { DOSKEY_LCTRL, RETROK_LCTRL },
   { DOSKEY_LSUPER, RETROK_LSUPER },
   { DOSKEY_LALT, RETROK_LALT },
   { DOSKEY_SPACE, RETROK_SPACE },
   { DOSKEY_RALT, RETROK_RALT },
   { DOSKEY_RSUPER, RETROK_RSUPER },
   { DOSKEY_MENU, RETROK_MENU },
   { DOSKEY_RCTRL, RETROK_RCTRL },

   { DOSKEY_UP, RETROK_UP },
   { DOSKEY_DOWN, RETROK_DOWN },
   { DOSKEY_LEFT, RETROK_LEFT },
   { DOSKEY_RIGHT, RETROK_RIGHT },

   { DOSKEY_HOME, RETROK_HOME },
   { DOSKEY_END, RETROK_END },
   { DOSKEY_PGUP, RETROK_PAGEUP },
   { DOSKEY_PGDN, RETROK_PAGEDOWN },

   { 0, RETROK_UNKNOWN }
};
#endif

#if defined(_WIN32) && _WIN32_WINNT >= 0x0501 && !defined(__WINRT__)
const struct rarch_key_map rarch_key_map_winraw[] = {
   { VK_BACK, RETROK_BACKSPACE },
   { VK_TAB, RETROK_TAB },
   { VK_CLEAR, RETROK_CLEAR },
   { VK_RETURN, RETROK_RETURN },
   { VK_PAUSE, RETROK_PAUSE },
   { VK_ESCAPE, RETROK_ESCAPE },
   { VK_MODECHANGE, RETROK_MODE },
   { VK_SPACE, RETROK_SPACE },
   { VK_PRIOR, RETROK_PAGEUP },
   { VK_NEXT, RETROK_PAGEDOWN },
   { VK_END, RETROK_END },
   { VK_HOME, RETROK_HOME },
   { VK_LEFT, RETROK_LEFT },
   { VK_UP, RETROK_UP },
   { VK_RIGHT, RETROK_RIGHT },
   { VK_DOWN, RETROK_DOWN },
   { VK_PRINT, RETROK_PRINT },
   { VK_INSERT, RETROK_INSERT },
   { VK_DELETE, RETROK_DELETE },
   { VK_HELP, RETROK_HELP },
   { 0x30, RETROK_0 },
   { 0x31, RETROK_1 },
   { 0x32, RETROK_2 },
   { 0x33, RETROK_3 },
   { 0x34, RETROK_4 },
   { 0x35, RETROK_5 },
   { 0x36, RETROK_6 },
   { 0x37, RETROK_7 },
   { 0x38, RETROK_8 },
   { 0x39, RETROK_9 },
   { 0x41, RETROK_a },
   { 0x42, RETROK_b },
   { 0x43, RETROK_c },
   { 0x44, RETROK_d },
   { 0x45, RETROK_e },
   { 0x46, RETROK_f },
   { 0x47, RETROK_g },
   { 0x48, RETROK_h },
   { 0x49, RETROK_i },
   { 0x4A, RETROK_j },
   { 0x4B, RETROK_k },
   { 0x4C, RETROK_l },
   { 0x4D, RETROK_m },
   { 0x4E, RETROK_n },
   { 0x4F, RETROK_o },
   { 0x50, RETROK_p },
   { 0x51, RETROK_q },
   { 0x52, RETROK_r },
   { 0x53, RETROK_s },
   { 0x54, RETROK_t },
   { 0x55, RETROK_u },
   { 0x56, RETROK_v },
   { 0x57, RETROK_w },
   { 0x58, RETROK_x },
   { 0x59, RETROK_y },
   { 0x5A, RETROK_z },
   { VK_LWIN, RETROK_LSUPER },
   { VK_RWIN, RETROK_RSUPER },
   { VK_APPS, RETROK_MENU },
   { VK_NUMPAD0, RETROK_KP0 },
   { VK_NUMPAD1, RETROK_KP1 },
   { VK_NUMPAD2, RETROK_KP2 },
   { VK_NUMPAD3, RETROK_KP3 },
   { VK_NUMPAD4, RETROK_KP4 },
   { VK_NUMPAD5, RETROK_KP5 },
   { VK_NUMPAD6, RETROK_KP6 },
   { VK_NUMPAD7, RETROK_KP7 },
   { VK_NUMPAD8, RETROK_KP8 },
   { VK_NUMPAD9, RETROK_KP9 },
   { VK_MULTIPLY, RETROK_KP_MULTIPLY },
   { VK_ADD, RETROK_KP_PLUS },
   { VK_SUBTRACT, RETROK_KP_MINUS },
   { VK_DECIMAL, RETROK_KP_PERIOD },
   { VK_DIVIDE, RETROK_KP_DIVIDE },
   { VK_F1, RETROK_F1 },
   { VK_F2, RETROK_F2 },
   { VK_F3, RETROK_F3 },
   { VK_F4, RETROK_F4 },
   { VK_F5, RETROK_F5 },
   { VK_F6, RETROK_F6 },
   { VK_F7, RETROK_F7 },
   { VK_F8, RETROK_F8 },
   { VK_F9, RETROK_F9 },
   { VK_F10, RETROK_F10 },
   { VK_F11, RETROK_F11 },
   { VK_F12, RETROK_F12 },
   { VK_F13, RETROK_F13 },
   { VK_F14, RETROK_F14 },
   { VK_F15, RETROK_F15 },
   { VK_NUMLOCK, RETROK_NUMLOCK },
   { VK_SCROLL, RETROK_SCROLLOCK },
   { VK_LSHIFT, RETROK_LSHIFT },
   { VK_RSHIFT, RETROK_RSHIFT },
   { VK_LCONTROL, RETROK_LCTRL },
   { VK_RCONTROL, RETROK_RCTRL },
   { VK_LMENU, RETROK_LALT },
   { VK_RMENU, RETROK_RALT },
   { VK_RETURN, RETROK_KP_ENTER },
   { VK_CAPITAL, RETROK_CAPSLOCK },
   { VK_OEM_1, RETROK_SEMICOLON },
   { VK_OEM_PLUS, RETROK_EQUALS },
   { VK_OEM_COMMA, RETROK_COMMA },
   { VK_OEM_MINUS, RETROK_MINUS },
   { VK_OEM_PERIOD, RETROK_PERIOD },
   { VK_OEM_2, RETROK_SLASH },
   { VK_OEM_3, RETROK_BACKQUOTE },
   { VK_OEM_4, RETROK_LEFTBRACKET },
   { VK_OEM_5, RETROK_BACKSLASH },
   { VK_OEM_6, RETROK_RIGHTBRACKET },
   { VK_OEM_7, RETROK_QUOTE },
   { 0, RETROK_UNKNOWN }
};
#endif

#ifdef __WINRT__
/* Refer to uwp_main.cpp - on WinRT these constants are defined as C++ enum classes
 * so they can't be placed in a C source file */
#endif

enum retro_key rarch_keysym_lut[RETROK_LAST];

/**
 * input_keymaps_init_keyboard_lut:
 * @map                   : Keyboard map.
 *
 * Initializes and sets the keyboard layout to a keyboard map (@map).
 **/
void input_keymaps_init_keyboard_lut(const struct rarch_key_map *map)
{
   memset(rarch_keysym_lut, 0, sizeof(rarch_keysym_lut));

   for (; map->rk != RETROK_UNKNOWN; map++)
      rarch_keysym_lut[map->rk] = (enum retro_key)map->sym;
}

/**
 * input_keymaps_translate_keysym_to_rk:
 * @sym                   : Key symbol.
 *
 * Translates a key symbol from the keyboard layout table
 * to an associated retro key identifier.
 *
 * Returns: Retro key identifier.
 **/
enum retro_key input_keymaps_translate_keysym_to_rk(unsigned sym)
{
   unsigned i;

   for (i = 0; i < ARRAY_SIZE(rarch_keysym_lut); i++)
   {
      if (rarch_keysym_lut[i] != sym)
         continue;

      return (enum retro_key)i;
   }

   return RETROK_UNKNOWN;
}

/**
 * input_keymaps_translate_rk_to_str:
 * @key                   : Retro key identifier.
 * @buf                   : Buffer.
 * @size                  : Size of @buf.
 *
 * Translates a retro key identifier to a human-readable
 * identifier string.
 **/
void input_keymaps_translate_rk_to_str(enum retro_key key, char *buf, size_t size)
{
   unsigned i;

   retro_assert(size >= 2);
   *buf = '\0';

   if (key >= RETROK_a && key <= RETROK_z)
   {
      buf[0] = (key - RETROK_a) + 'a';
      buf[1] = '\0';
      return;
   }

   for (i = 0; input_config_key_map[i].str; i++)
   {
      if (input_config_key_map[i].key != key)
         continue;

      strlcpy(buf, input_config_key_map[i].str, size);
      break;
   }
}
