/* Generated from AUTHORS.h by tools/gen_authors_c.py - do not edit. */
#ifndef __RETROARCH_AUTHORS_C_H
#define __RETROARCH_AUTHORS_C_H
static const char *retroarch_contributors_list =
   "\n"
   "RetroArch and the libretro team would like to\n"
   "acknowledge the following contributors:\n"
   "\n"
   "1ch (L0sted)\n"
   "23rd\n"
   "6lackmag3\n"
   "A Schain (aschain)\n"
   "Aaron Oneal (aarononeal)\n"
   "Aaron Ramirez (aaronbytes)\n"
   "Abadede\n"
   "Adam Londero (alondero)\n"
   "Adam Mechtley (amechtley)\n"
   "Adriano de Moura Leite (amlib)\n"
   "Adrien Moulin (elyosh)\n"
   "Aethyrion\n"
   "ajefr\n"
   "AKuHAK\n"
   "Alberto Alonso Ruibal (albertoruibal)\n"
   "Alberto Fustinoni (albertofustinoni)\n"
   "Alberto Simon (asimonf)\n"
   "Alcaro\n"
   "aldebaran27\n"
   "Aleksey Samoilov (Sunderland93)\n"
   "Alessandro Mangone (Vektor) (zevektor)\n"
   "Alex Folland (AlexFolland)\n"
   "Alex Kornitzer (alexkornitzer)\n"
   "Alexander Spady (alkaseltzerspadt)\n"
   "Alexander Trufanov (trufanov-nok)\n"
   "Alexandre Garcia (Alexandre-Garcia)\n"
   "Alfredo Monclus (alfrix)\n"
   "aliaspider\n"
   "alphanu1\n"
   "altiereslima\n"
   "Alwin Garside (Yogarine)\n"
   "amtz\n"
   "Anders Storhaug (andersstorhaug)\n"
   "Andre Leiradella (leiradel)\n"
   "Andrés (fr500)\n"
   "Andy Nguyen (TheOfficialFloW)\n"
   "Anthony J. Bentley (bentley)\n"
   "Antonio Jose Ramos Marquez (psxdev)\n"
   "antonioginer\n"
   "Apaczer\n"
   "AridRayne\n"
   "ArnaudFaucher\n"
   "arpruss\n"
   "arstn\n"
   "Artem Polishchuk (tim77)\n"
   "Arto Vainiolehto (arakerlu)\n"
   "asavah\n"
   "Ash (ashquarky)\n"
   "Ashura (CoalaJoe)\n"
   "Avton1\n"
   "ayssia\n"
   "BananaRama203\n"
   "barbudreadmon\n"
   "Barry Rowe (BarryJRowe)\n"
   "Bartłomiej Burdukiewicz (dev-0x7C6)\n"
   "Bashar Astifan (basharast)\n"
   "bearoso\n"
   "Ben Hamilton (Ben Gertzfield) (bhamiltoncx)\n"
   "benklop\n"
   "benutzer193\n"
   "Bernhard Schelling (schellingb)\n"
   "blackgur\n"
   "bmaupin\n"
   "Bobby Smith (bslenul)\n"
   "Boris Timofeev (btimofeev)\n"
   "Brad (SpiralBrad)\n"
   "Braden Farmer (farmerbb)\n"
   "Brandon Johnson (BinaryFissionGames)\n"
   "Breno Dantas Mendonça (brenodantas10)\n"
   "Brian Hoem (ZornTaov)\n"
   "Brian Koropoff (bkoropoff)\n"
   "Brian S. Stephan (bsstephan)\n"
   "BringerethOfLight\n"
   "Brunnis\n"
   "bsmith (DogParty)\n"
   "bubuleur\n"
   "bulzipke\n"
   "C.W. Betts (MaddTheSane)\n"
   "Casey Borders (CaseyB)\n"
   "CatGreen90\n"
   "ceb33\n"
   "cedorg\n"
   "celerizer\n"
   "Charlène (julianaito)\n"
   "CheezeCake\n"
   "Chris Merrett (chrisfu)\n"
   "Christian Murphy (grimpunch)\n"
   "christianhaitian\n"
   "Christoffer Tibell (Brottweiler)\n"
   "Christopher Snowhill (kode54)\n"
   "chu (9chu)\n"
   "Chuck Smith (chucksmith)\n"
   "CidVonHighwind\n"
   "clienthax\n"
   "cold-brewed\n"
   "Colin Kinloch (ColinKinloch)\n"
   "CompCom\n"
   "ComradeEcho\n"
   "confusedguy9\n"
   "Conn O'Griofa (psyke83)\n"
   "Connor McLaughlin (stenzek)\n"
   "Conrad Kreyling (konistehrad)\n"
   "CozmoP\n"
   "Cpasjuste\n"
   "cpsw\n"
   "Cray Elliott (MP2E)\n"
   "Crestwave\n"
   "CrewMdk\n"
   "Cristi Mitrana (cmitu)\n"
   "Cristian Sandu (crazyquark)\n"
   "crystalct\n"
   "CTCaer\n"
   "cucholix\n"
   "cudencuden\n"
   "CyberLabSystems\n"
   "Daehan Kim (iAmGhost)\n"
   "dalter\n"
   "Dan Weiss (Dwedit)\n"
   "danieljg\n"
   "Daniil Zhilin (LaserMoai)\n"
   "dankcushions\n"
   "Darren Thompson (DiscoStarslayer)\n"
   "Dave (freakdave)\n"
   "Dave Leaver (danzel)\n"
   "David CARLIER (devnexen)\n"
   "David Demelier (markand)\n"
   "David Erickson (daviderickson)\n"
   "David G. F. (davidgfnet)\n"
   "David Lawson (dmrlawson)\n"
   "David Walters (hiddenasbestos)\n"
   "dbaronica\n"
   "DEX357\n"
   "diablodiab\n"
   "dibas\n"
   "Diego A. (SuperrSonic)\n"
   "Diego Viola (diegoviola)\n"
   "digitalisland-nino\n"
   "Diogo Barros (BlueKore)\n"
   "Dmitry Sergeenkov (DuMOHsmol)\n"
   "dor3k\n"
   "Doug Christman (dobyrch)\n"
   "driver1998\n"
   "Dudu Akiva (duduke)\n"
   "duganchen\n"
   "dukemiller\n"
   "duskgao\n"
   "Dylan Scott (dyscott)\n"
   "Dystopian\n"
   "eadmaster\n"
   "Eduard Strehlau (Herdinger)\n"
   "ekipan\n"
   "Elvira Khabirova (parport0)\n"
   "embercold\n"
   "Emmanuel Martin (daliaetnano)\n"
   "Ethan Lee (flibitijibibo)\n"
   "extrowerk\n"
   "Ezio-PS\n"
   "F (erbridge)\n"
   "Fabio (Oibaf66)\n"
   "Fabio Ritrovato (Sephiroth87)\n"
   "Fayne Aldan (FayneAldan)\n"
   "fff (felinben)\n"
   "Filipe Azevedo (pasnox)\n"
   "FIX94\n"
   "Flame Sage (flamesage)\n"
   "flyinghead\n"
   "FmT0\n"
   "francescotintori\n"
   "Francisco Javier Trujillo Mata (fjtrujy)\n"
   "Francisco José García García (frangarcj)\n"
   "FreeShippingParty\n"
   "fuzzydunlops732 (JKoppel93)\n"
   "GABO1423\n"
   "Gabriel (Ghabry)\n"
   "GameDragon2k\n"
   "Garrett Brown (garbear)\n"
   "gatecat (daveshah1)\n"
   "GavinDarkglider\n"
   "gblues\n"
   "Geoffrey Plitt (GeoffreyPlitt)\n"
   "Giovanni Cascione (spleen1981)\n"
   "Glenn Hevey (hevey)\n"
   "Googer\n"
   "gordon-fish\n"
   "gouchi\n"
   "Gregor Richards (GregorR)\n"
   "Grzegorz Raciborski (graciborski)\n"
   "Gui Andrade (archshift)\n"
   "Guillaume Thiolliere (thiolliere)\n"
   "Guo Yunhe (guoyunhe)\n"
   "Gustavo Maciel Dias Vieira (gmdvieira)\n"
   "gvbr\n"
   "hadess\n"
   "Hans-Kristian Arntzen (Themaister)\n"
   "Henri Gomez (hgomez)\n"
   "Henri Gomez (hgomez-sonarsource)\n"
   "Henry Castro (hcvcastro)\n"
   "Higor E. (heuripedes)\n"
   "hizzlekizzle\n"
   "Hugo B. (hug0b)\n"
   "Hugo Hromic (hhromic)\n"
   "hunterk\n"
   "Hyllian\n"
   "HyperspaceMadness\n"
   "i30817\n"
   "im4potato\n"
   "ImJezze\n"
   "İbrahim Güngör (igungor)\n"
   "Jack (jakcron)\n"
   "Jacob (cubtekki)\n"
   "Jacob (RegenJacob)\n"
   "Jacob Patterson (jacobpa)\n"
   "jacobsson (Roet-Ivar)\n"
   "Jahed\n"
   "Jake Stine (jstine35)\n"
   "James Le Cuirot (chewi)\n"
   "James Sexton (Bezier89)\n"
   "Jamiras\n"
   "Jan Holthuis (Holzhaus)\n"
   "Jason Tomsic (plaidman)\n"
   "Javier Martinez Canillas (martinezjavier)\n"
   "Jay McCarthy (jeapostrophe)\n"
   "jdgleaver\n"
   "Jean-André Santoni (kivutar)\n"
   "Jean-Paul Mari (djipi)\n"
   "Jean-Sébastien Guay (Skylark13)\n"
   "Jeff (jeffbdavenport)\n"
   "Jeff Sousa (LordeIlluminati)\n"
   "jess (winneon)\n"
   "Jesse Talavera-Greenberg (JesseTG)\n"
   "Joan Coll Cerdán (johanbcn)\n"
   "Job Adrian Salinas Gonzalez (efylan)\n"
   "Joe Osborn (JoeOsborn)\n"
   "Joel (joel16)\n"
   "Joel Puig Rubio (XXLuigiMario)\n"
   "Joerg Sonnenberger (jsonn)\n"
   "Johannes Schickel (lordhoto)\n"
   "John Parton (john-parton)\n"
   "John Regan (jprjr)\n"
   "Jon Maddox (maddox)\n"
   "Jonathan (JonnyMe)\n"
   "Jonathan Relf (jonathanrelf)\n"
   "Joohan Lee (losernator)\n"
   "Jools Wills (joolswills)\n"
   "Jose Lage Miguez (Joselagem)\n"
   "Joseph Carter (knghtbrd)\n"
   "Joseph Conan Montgomery (Grotke)\n"
   "jsd1982 (JamesDunne)\n"
   "jSTE0\n"
   "JuanVCS\n"
   "Justin Jacobs (dorkster)\n"
   "Justin Weiss (justinweiss)\n"
   "JustMeDaFaq\n"
   "Kangmo-Ahn\n"
   "Karl Forshaw (karlforshaw)\n"
   "Kate Eckhart (katepango)\n"
   "Keith Bowes (keithbowes)\n"
   "Ken Rossato (rossato)\n"
   "kikmon\n"
   "Kopert\n"
   "Krzysztof Haładyn (krzys_h) (krzys-h)\n"
   "kurumushi\n"
   "kwyxz\n"
   "l3iggs\n"
   "lambolighting\n"
   "lasers\n"
   "Lawrence Kesteloot (lkesteloot)\n"
   "LazyBumHorse\n"
   "LazyFunker\n"
   "Lennard Kittner (Lennard599)\n"
   "LibretroAdmin\n"
   "Lionel Flandrin (simias)\n"
   "littleguy77\n"
   "liushuyu\n"
   "Logan McNaughton (loganmc10)\n"
   "lordashram\n"
   "Lothar Serra Mari (lotharsm)\n"
   "Lubosz Sarnecki (lubosz)\n"
   "lucasmr\n"
   "lucianposton\n"
   "lxerandrew\n"
   "m4xw\n"
   "mahoneyt944\n"
   "Mahyar Koshkouei (deltabeard)\n"
   "Mai (lioncash)\n"
   "MajorPainTheCactus\n"
   "maksun\n"
   "Manuel Alfayate Corchete (vanfanel)\n"
   "Marcelo Munhoz Pélos (mpelos)\n"
   "Marcus Crisostomo (mcrisostomo)\n"
   "markwkidd\n"
   "Maschell\n"
   "Mats (Myaats)\n"
   "Matt Sephton (gingerbeardman)\n"
   "Matthew Bauer (matthewbauer)\n"
   "Matthew Wang (asakous)\n"
   "Max K. (langerhans)\n"
   "Maxime Gauduin (alucryd)\n"
   "meancoot\n"
   "meepingsnesroms\n"
   "meleu\n"
   "Merry Mello (merryMellody)\n"
   "micechal\n"
   "Michael Burgardt (DisasterMo)\n"
   "Michael K. (kuxii2016)\n"
   "Michael Lelli (ToadKing)\n"
   "mickski56\n"
   "Mico Chopitea (micochops)\n"
   "miguelpinheiro\n"
   "Mike Swanson (chungy)\n"
   "mikeOSX\n"
   "minucce\n"
   "misson20000\n"
   "esoptron\n"
   "Monroe88\n"
   "Morgane (MorganeAD)\n"
   "mprobinson\n"
   "MrHuu\n"
   "MrJs (mrjschulte)\n"
   "Muhamed Hobi (mmhobi7)\n"
   "muzuiget\n"
   "N/A (inactive123)\n"
   "Nargash\n"
   "Nathan S. (natinusala)\n"
   "NathanStrong-Tripwire\n"
   "nattycleopatra\n"
   "Naveen (naveensrinivasan)\n"
   "nayslayer\n"
   "negativeExponent\n"
   "Neil Barkhina (nbarkhina)\n"
   "neil4\n"
   "netux79\n"
   "nfnty\n"
   "nfp0\n"
   "nia (alarixnia)\n"
   "Nicolas Adenis-Lamarre (nadenislamarre)\n"
   "Nicolas Guillaumin (nguillaumin)\n"
   "Nicolas Roehm (NicolasRoehm)\n"
   "Nik (WerWolv)\n"
   "Nikita Vakhrushev (XF10C)\n"
   "Nikola Kocić (nikola-kocic)\n"
   "Nikos Chantziaras (realnc)\n"
   "Nils Hasenbanck (hasenbanck)\n"
   "njordan64\n"
   "nosh01\n"
   "not6 (r-type)\n"
   "notaz\n"
   "nstCactus\n"
   "nurupo\n"
   "Oggom\n"
   "Oh Won Sik (dnjstlr555)\n"
   "Oleg Shevchenko (olsh)\n"
   "Omar Saleem (ofsaleem)\n"
   "opendata26\n"
   "Ophidon\n"
   "orbea\n"
   "Oschowa\n"
   "OsirizX\n"
   "OV2\n"
   "Palmic (mpalomas)\n"
   "pamapa\n"
   "Paolo Bonzini (bonzini)\n"
   "Paul McCarty (notabeatle)\n"
   "pcjco\n"
   "Pedro Ferraz (ferrazpedro)\n"
   "Pedro Ribeiro (pedrib)\n"
   "Peter J Kos (pkos)\n"
   "Philippe Simons (loki666)\n"
   "pinumbernumber\n"
   "Piotr Dobrowolski (Informatic)\n"
   "pjft\n"
   "Poligraf\n"
   "pponso1\n"
   "pyroesp\n"
   "R-YaTian\n"
   "Rafael Toledo (rafaeltoledo)\n"
   "Ramiro Morales (ramiro)\n"
   "Raphaël Zumer (rzumer)\n"
   "redenvelope2000\n"
   "Reid Kleckner (rnk)\n"
   "repojohnray\n"
   "retrotails\n"
   "revvv\n"
   "reztek\n"
   "Richard Howell (rmaz)\n"
   "Rinnegatamante\n"
   "rlnilsen\n"
   "Rob Loach (RobLoach)\n"
   "Robin de Rooij (rrooij)\n"
   "Romain Gay (vikbez)\n"
   "Romain Graillot (notnotme)\n"
   "Romain TISSERAND (rtissera)\n"
   "Roman Fomin (rfomin)\n"
   "Roman Kalashnikov (lunixoid)\n"
   "Royerson\n"
   "rsn8887\n"
   "Ruben Nine (rnine)\n"
   "Ryan C. Gordon (icculus)\n"
   "Ryan Kuba (thelamer)\n"
   "Ryunam\n"
   "rz5\n"
   "Sage (neonfuz)\n"
   "Saggi Mizrahi (ficoos)\n"
   "SAKUJ0\n"
   "Salvador (salvacam)\n"
   "Sam (44100hertz)\n"
   "Sam Lantinga (slouken)\n"
   "Sam Stenvall (Jalle19)\n"
   "Samuel P. (p-sam)\n"
   "Sanaki\n"
   "Scheiker\n"
   "Sean O'Neil (seanocali)\n"
   "Sebastien Ronsse (sronsse)\n"
   "SecularSteve\n"
   "Sefa Eyeoglu (Scrumplex)\n"
   "Sergei Nikitin (Kert)\n"
   "Sergei Trofimovich (trofi)\n"
   "Sergi Granell (xerpi)\n"
   "Sergio Padrino (sergiou87)\n"
   "sergio-br2 (sergiobenrocha2)\n"
   "Seth Kingsley (sethk)\n"
   "Shadow (ShadowOne333)\n"
   "Shane Mouton (ismouton)\n"
   "shantigilbert\n"
   "Shfty\n"
   "Shizeeg Unadequatov (shizeeg)\n"
   "SimpleTease\n"
   "SindenLightgun\n"
   "Sirrempat\n"
   "slotek\n"
   "Soar Qin (soarqin)\n"
   "sonninnos\n"
   "Sou Bunnbu (iyzsong)\n"
   "sparklewind\n"
   "spec-chum\n"
   "Stefan (gizmo98)\n"
   "stefan-gr\n"
   "stellarporter\n"
   "Stephanie Gawroriski (XerTheSquirrel)\n"
   "Steve Cox (stevenjamescox)\n"
   "Stevoisiak\n"
   "stoofin\n"
   "StormedBubbles\n"
   "strotlog\n"
   "Stuart Carnie (stuartcarnie)\n"
   "Sunguk Lee (d3m3vilurr)\n"
   "Supernature2k\n"
   "Sven (RetroSven)\n"
   "Swizzy\n"
   "Sylvain Colinet (Skarsnik)\n"
   "Szunti\n"
   "Tadek Kijkowski (monkeyman79)\n"
   "Tatsuya79\n"
   "Terry Lewis (terry-au)\n"
   "thedax\n"
   "theheroGAC\n"
   "TheMrIron2\n"
   "ThePhxRises\n"
   "TheRhysWyrill\n"
   "Thomas Lorblanchès (Zlika)\n"
   "Tilman M. Jaeschke (asciibeats)\n"
   "Tim Van den Langenbergh (tmtvl)\n"
   "Tobias Gruetzmacher (TobiX)\n"
   "Tobias Jakobi (tobiasjakobi)\n"
   "Todd Laney (ToddLa)\n"
   "Tomáš Kelemen (ToKe79)\n"
   "Tor Arne Vestbø (torarnv)\n"
   "Torsten Paul (t-paul)\n"
   "TotalCaesar659\n"
   "tr12345\n"
   "TroggleMonkey\n"
   "tunip3\n"
   "txorion\n"
   "Tyler Loch (TylerLoch)\n"
   "URBANsUNITED\n"
   "vaguerant\n"
   "Val Packett (valpackett)\n"
   "Valerio Proietti (kamicane)\n"
   "vgmoose\n"
   "Viachaslau Khalikin (viachaslavic)\n"
   "Vicki Pfau (endrift)\n"
   "Vicky C Lau (vickychenglau)\n"
   "vin (suseme)\n"
   "Vincent Pelletier (vpelletier)\n"
   "Vladimir Panteleev (CyberShadow)\n"
   "Vladimir Serbinenko (phcoder)\n"
   "Víctor \"IlDucci\" (IlDucci)\n"
   "waitingmoon\n"
   "Warning: Non-Potable Water (warningnonpotablewater)\n"
   "webgeek1234\n"
   "Weedy Weed Smoker (WeedyWeedSmoker)\n"
   "whorsemaster\n"
   "Wiimpathy\n"
   "Wiktor Strzębała (wiktorek140)\n"
   "Woohyun Shin (sinusinu)\n"
   "xenomorph-us\n"
   "xhp-creations\n"
   "Xitee (Xitee1)\n"
   "Yari (hyarsan)\n"
   "yesfish (huwpascoe)\n"
   "Yongwoon Cho (ssangkong)\n"
   "yoshisuga\n"
   "Zer0xFF\n"
   "zeromus\n"
   "zlice\n"
   "Érico Nogueira Rolim (ericonr)\n"
   "Ömercan Kömür (fpscan)\n"
   "シーはディー四を取る (cxd4)\n"
   "\n"
   ;
#endif
