/*  RetroArch - A frontend for libretro.
 *  Copyright (C) 2010-2014 - Hans-Kristian Arntzen
 *  Copyright (C) 2011-2016 - Daniel De Matteis
 *  Copyright (C) 2016-2019 - Brad Parker
 *
 *  RetroArch is free software: you can redistribute it and/or modify it under the terms
 *  of the GNU General Public License as published by the Free Software Found-
 *  ation, either version 3 of the License, or (at your option) any later version.
 *
 *  RetroArch is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 *  without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 *  PURPOSE.  See the GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along with RetroArch.
 *  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef __CONFIG_DEF_KEYBINDS_H
#define __CONFIG_DEF_KEYBINDS_H

#ifndef IS_SALAMANDER

/* User 1 */
static const struct retro_keybind retro_keybinds_1[] = {
#ifdef __QNX__
   { 
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_B, RETROK_k, true),
      RETRO_DEVICE_ID_JOYPAD_B, NO_BTN, NO_BTN, 0
   },
   { 
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_Y, RETROK_i, true),
      RETRO_DEVICE_ID_JOYPAD_Y, NO_BTN, NO_BTN, 0
   },
   { 
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_SELECT, RETROK_v, true),
      RETRO_DEVICE_ID_JOYPAD_SELECT, NO_BTN, NO_BTN, 0
   },
   { 
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_START, RETROK_b, true),
      RETRO_DEVICE_ID_JOYPAD_START, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_UP, RETROK_e, true),
      RETRO_DEVICE_ID_JOYPAD_UP, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_DOWN, RETROK_s, true),
      RETRO_DEVICE_ID_JOYPAD_DOWN, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_LEFT, RETROK_w, true),
      RETRO_DEVICE_ID_JOYPAD_LEFT, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_RIGHT, RETROK_d, true),
      RETRO_DEVICE_ID_JOYPAD_RIGHT, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_A, RETROK_l, true),
      RETRO_DEVICE_ID_JOYPAD_A, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_X, RETROK_o, true),
      RETRO_DEVICE_ID_JOYPAD_X, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_L, RETROK_f, true),
      RETRO_DEVICE_ID_JOYPAD_L, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_R, RETROK_j, true),
      RETRO_DEVICE_ID_JOYPAD_R, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_L2, RETROK_r, true),
      RETRO_DEVICE_ID_JOYPAD_L2, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_R2, RETROK_u, true),
      RETRO_DEVICE_ID_JOYPAD_R2, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_L3, RETROK_g, true),
      RETRO_DEVICE_ID_JOYPAD_L3, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_R3, RETROK_h, true),
      RETRO_DEVICE_ID_JOYPAD_R3, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_LEFT_X_PLUS, RETROK_UNKNOWN, true),
      RARCH_ANALOG_LEFT_X_PLUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_LEFT_X_MINUS, RETROK_UNKNOWN, true),
      RARCH_ANALOG_LEFT_X_MINUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_LEFT_Y_PLUS, RETROK_UNKNOWN, true),
      RARCH_ANALOG_LEFT_Y_PLUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_LEFT_Y_MINUS, RETROK_UNKNOWN, true),
      RARCH_ANALOG_LEFT_Y_MINUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_RIGHT_X_PLUS, RETROK_UNKNOWN, true),
      RARCH_ANALOG_RIGHT_X_PLUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_RIGHT_X_MINUS, RETROK_UNKNOWN, true),
      RARCH_ANALOG_RIGHT_X_MINUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_RIGHT_Y_PLUS, RETROK_UNKNOWN, true),
      RARCH_ANALOG_RIGHT_Y_PLUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_RIGHT_Y_MINUS, RETROK_UNKNOWN, true),
      RARCH_ANALOG_RIGHT_Y_MINUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_TRIGGER, RETROK_UNKNOWN, true),
      RARCH_LIGHTGUN_TRIGGER, RETRO_DEVICE_ID_MOUSE_LEFT, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_RELOAD, RETROK_UNKNOWN, true),
      RARCH_LIGHTGUN_RELOAD, RETRO_DEVICE_ID_MOUSE_RIGHT, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_AUX_A, RETROK_UNKNOWN, true),
      RARCH_LIGHTGUN_AUX_A, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_AUX_B, RETROK_UNKNOWN, true),
      RARCH_LIGHTGUN_AUX_B, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_AUX_C, RETROK_UNKNOWN, true),
      RARCH_LIGHTGUN_AUX_C, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_START, RETROK_UNKNOWN, true),
      RARCH_LIGHTGUN_START, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_SELECT, RETROK_UNKNOWN, true),
      RARCH_LIGHTGUN_SELECT, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_DPAD_UP, RETROK_UNKNOWN, true),
      RARCH_LIGHTGUN_DPAD_UP, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_DPAD_DOWN, RETROK_UNKNOWN, true),
      RARCH_LIGHTGUN_DPAD_DOWN, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_DPAD_LEFT, RETROK_UNKNOWN, true),
      RARCH_LIGHTGUN_DPAD_LEFT, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_DPAD_RIGHT, RETROK_UNKNOWN, true),
      RARCH_LIGHTGUN_DPAD_RIGHT, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_TURBO, RETROK_UNKNOWN, true),
      RARCH_TURBO_ENABLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_HOLD, RETROK_UNKNOWN, true),
      RARCH_HOLD_ENABLE, NO_BTN, NO_BTN, 0
   },
   /* Hotkeys */
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_ENABLE_HOTKEY, RETROK_UNKNOWN, true),
      RARCH_ENABLE_HOTKEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_MENU_TOGGLE, RETROK_SPACE, true),
      RARCH_MENU_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_QUIT_KEY, RETROK_UNKNOWN, true),
      RARCH_QUIT_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_CLOSE_CONTENT_KEY, RETROK_UNKNOWN, true),
      RARCH_CLOSE_CONTENT_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_RESET, RETROK_UNKNOWN, true),
      RARCH_RESET, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_FAST_FORWARD_KEY, RETROK_UNKNOWN, true),
      RARCH_FAST_FORWARD_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_FAST_FORWARD_HOLD_KEY, RETROK_UNKNOWN, true),
      RARCH_FAST_FORWARD_HOLD_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_SLOWMOTION_KEY, RETROK_UNKNOWN, true),
      RARCH_SLOWMOTION_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_SLOWMOTION_HOLD_KEY, RETROK_UNKNOWN, true),
      RARCH_SLOWMOTION_HOLD_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_REWIND, RETROK_UNKNOWN, true),
      RARCH_REWIND, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_PAUSE_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_PAUSE_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_FRAMEADVANCE, RETROK_UNKNOWN, true),
      RARCH_FRAMEADVANCE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_MUTE, RETROK_UNKNOWN, true),
      RARCH_MUTE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_VOLUME_UP, RETROK_UNKNOWN, true),
      RARCH_VOLUME_UP, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_VOLUME_DOWN, RETROK_UNKNOWN, true),
      RARCH_VOLUME_DOWN, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_LOAD_STATE_KEY, RETROK_UNKNOWN, true),
      RARCH_LOAD_STATE_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_SAVE_STATE_KEY, RETROK_UNKNOWN, true),
      RARCH_SAVE_STATE_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_STATE_SLOT_PLUS, RETROK_UNKNOWN, true),
      RARCH_STATE_SLOT_PLUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_STATE_SLOT_MINUS, RETROK_UNKNOWN, true),
      RARCH_STATE_SLOT_MINUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_PLAY_REPLAY_KEY, RETROK_UNKNOWN, true),
      RARCH_PLAY_REPLAY_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_RECORD_REPLAY_KEY, RETROK_UNKNOWN, true),
      RARCH_RECORD_REPLAY_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_HALT_REPLAY_KEY, RETROK_UNKNOWN, true),
      RARCH_HALT_REPLAY_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_SAVE_REPLAY_CHECKPOINT_KEY, RETROK_UNKNOWN, true),
      RARCH_SAVE_REPLAY_CHECKPOINT_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_PREV_REPLAY_CHECKPOINT_KEY, RETROK_UNKNOWN, true),
      RARCH_PREV_REPLAY_CHECKPOINT_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_NEXT_REPLAY_CHECKPOINT_KEY, RETROK_UNKNOWN, true),
      RARCH_NEXT_REPLAY_CHECKPOINT_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_REPLAY_SLOT_PLUS, RETROK_UNKNOWN, true),
      RARCH_REPLAY_SLOT_PLUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_REPLAY_SLOT_MINUS, RETROK_UNKNOWN, true),
      RARCH_REPLAY_SLOT_MINUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_DISK_EJECT_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_DISK_EJECT_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_DISK_NEXT, RETROK_UNKNOWN, true),
      RARCH_DISK_NEXT, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_DISK_PREV, RETROK_UNKNOWN, true),
      RARCH_DISK_PREV, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_SHADER_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_SHADER_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_SHADER_HOLD, RETROK_UNKNOWN, true),
      RARCH_SHADER_HOLD, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_SHADER_NEXT, RETROK_UNKNOWN, true),
      RARCH_SHADER_NEXT, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_SHADER_PREV, RETROK_UNKNOWN, true),
      RARCH_SHADER_PREV, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_CHEAT_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_CHEAT_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_CHEAT_INDEX_PLUS, RETROK_UNKNOWN, true),
      RARCH_CHEAT_INDEX_PLUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_CHEAT_INDEX_MINUS, RETROK_UNKNOWN, true),
      RARCH_CHEAT_INDEX_MINUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_SCREENSHOT, RETROK_UNKNOWN, true),
      RARCH_SCREENSHOT, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_RECORDING_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_RECORDING_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_STREAMING_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_STREAMING_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_TURBO_FIRE_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_TURBO_FIRE_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_GRAB_MOUSE_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_GRAB_MOUSE_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_GAME_FOCUS_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_GAME_FOCUS_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_FULLSCREEN_TOGGLE_KEY, RETROK_UNKNOWN, true),
      RARCH_FULLSCREEN_TOGGLE_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_UI_COMPANION_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_UI_COMPANION_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_VRR_RUNLOOP_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_VRR_RUNLOOP_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_RUNAHEAD_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_RUNAHEAD_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_PREEMPT_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_PREEMPT_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_VIDEO_FILTER_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_VIDEO_FILTER_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_FPS_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_FPS_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_STATISTICS_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_STATISTICS_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_AI_SERVICE, RETROK_UNKNOWN, true),
      RARCH_AI_SERVICE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_NETPLAY_PING_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_NETPLAY_PING_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_NETPLAY_HOST_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_NETPLAY_HOST_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_NETPLAY_GAME_WATCH, RETROK_UNKNOWN, true),
      RARCH_NETPLAY_GAME_WATCH, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_NETPLAY_PLAYER_CHAT, RETROK_UNKNOWN, true),
      RARCH_NETPLAY_PLAYER_CHAT, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_NETPLAY_FADE_CHAT_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_NETPLAY_FADE_CHAT_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_OVERLAY_NEXT, RETROK_UNKNOWN, true),
      RARCH_OVERLAY_NEXT, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_OSK, RETROK_UNKNOWN, true),
      RARCH_OSK, NO_BTN, NO_BTN, 0
   },
#elif defined(DINGUX)
   { 
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_B, RETROK_LALT, true),
      RETRO_DEVICE_ID_JOYPAD_B, NO_BTN, NO_BTN, 0
   },
   { 
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_Y, RETROK_LSHIFT, true),
      RETRO_DEVICE_ID_JOYPAD_Y, NO_BTN, NO_BTN, 0
   },
   { 
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_SELECT, RETROK_ESCAPE, true),
      RETRO_DEVICE_ID_JOYPAD_SELECT, NO_BTN, NO_BTN, 0
   },
   { 
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_START, RETROK_RETURN, true),
      RETRO_DEVICE_ID_JOYPAD_START, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_UP, RETROK_UP, true),
      RETRO_DEVICE_ID_JOYPAD_UP, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_DOWN, RETROK_DOWN, true),
      RETRO_DEVICE_ID_JOYPAD_DOWN, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_LEFT, RETROK_LEFT, true),
      RETRO_DEVICE_ID_JOYPAD_LEFT, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_RIGHT, RETROK_RIGHT, true),
      RETRO_DEVICE_ID_JOYPAD_RIGHT, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_A, RETROK_LCTRL, true),
      RETRO_DEVICE_ID_JOYPAD_A, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_X, RETROK_SPACE, true),
      RETRO_DEVICE_ID_JOYPAD_X, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_L, RETROK_TAB, true),
      RETRO_DEVICE_ID_JOYPAD_L, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_R, RETROK_BACKSPACE, true),
      RETRO_DEVICE_ID_JOYPAD_R, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_L2, RETROK_PAGEUP, true),
      RETRO_DEVICE_ID_JOYPAD_L2, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_R2, RETROK_PAGEDOWN, true),
      RETRO_DEVICE_ID_JOYPAD_R2, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_L3, RETROK_KP_DIVIDE, true),
      RETRO_DEVICE_ID_JOYPAD_L3, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_R3, RETROK_KP_PERIOD, true),
      RETRO_DEVICE_ID_JOYPAD_R3, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_LEFT_X_PLUS, RETROK_UNKNOWN, true),
      RARCH_ANALOG_LEFT_X_PLUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_LEFT_X_MINUS, RETROK_UNKNOWN, true),
      RARCH_ANALOG_LEFT_X_MINUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_LEFT_Y_PLUS, RETROK_UNKNOWN, true),
      RARCH_ANALOG_LEFT_Y_PLUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_LEFT_Y_MINUS, RETROK_UNKNOWN, true),
      RARCH_ANALOG_LEFT_Y_MINUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_RIGHT_X_PLUS, RETROK_UNKNOWN, true),
      RARCH_ANALOG_RIGHT_X_PLUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_RIGHT_X_MINUS, RETROK_UNKNOWN, true),
      RARCH_ANALOG_RIGHT_X_MINUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_RIGHT_Y_PLUS, RETROK_UNKNOWN, true),
      RARCH_ANALOG_RIGHT_Y_PLUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_RIGHT_Y_MINUS, RETROK_UNKNOWN, true),
      RARCH_ANALOG_RIGHT_Y_MINUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_TRIGGER, RETROK_UNKNOWN, true),
      RARCH_LIGHTGUN_TRIGGER, RETRO_DEVICE_ID_MOUSE_LEFT, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_RELOAD, RETROK_UNKNOWN, true),
      RARCH_LIGHTGUN_RELOAD, RETRO_DEVICE_ID_MOUSE_RIGHT, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_AUX_A, RETROK_UNKNOWN, true),
      RARCH_LIGHTGUN_AUX_A, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_AUX_B, RETROK_UNKNOWN, true),
      RARCH_LIGHTGUN_AUX_B, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_AUX_C, RETROK_UNKNOWN, true),
      RARCH_LIGHTGUN_AUX_C, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_START, RETROK_UNKNOWN, true),
      RARCH_LIGHTGUN_START, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_SELECT, RETROK_UNKNOWN, true),
      RARCH_LIGHTGUN_SELECT, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_DPAD_UP, RETROK_UNKNOWN, true),
      RARCH_LIGHTGUN_DPAD_UP, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_DPAD_DOWN, RETROK_UNKNOWN, true),
      RARCH_LIGHTGUN_DPAD_DOWN, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_DPAD_LEFT, RETROK_UNKNOWN, true),
      RARCH_LIGHTGUN_DPAD_LEFT, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_DPAD_RIGHT, RETROK_UNKNOWN, true),
      RARCH_LIGHTGUN_DPAD_RIGHT, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_TURBO, RETROK_UNKNOWN, true),
      RARCH_TURBO_ENABLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_HOLD, RETROK_UNKNOWN, true),
      RARCH_HOLD_ENABLE, NO_BTN, NO_BTN, 0
   },
   /* Hotkeys */
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_ENABLE_HOTKEY, RETROK_UNKNOWN, true),
      RARCH_ENABLE_HOTKEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_MENU_TOGGLE, RETROK_HOME, true),
      RARCH_MENU_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_QUIT_KEY, RETROK_UNKNOWN, true),
      RARCH_QUIT_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_CLOSE_CONTENT_KEY, RETROK_UNKNOWN, true),
      RARCH_CLOSE_CONTENT_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_RESET, RETROK_UNKNOWN, true),
      RARCH_RESET, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_FAST_FORWARD_KEY, RETROK_UNKNOWN, true),
      RARCH_FAST_FORWARD_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_FAST_FORWARD_HOLD_KEY, RETROK_UNKNOWN, true),
      RARCH_FAST_FORWARD_HOLD_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_SLOWMOTION_KEY, RETROK_UNKNOWN, true),
      RARCH_SLOWMOTION_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_SLOWMOTION_HOLD_KEY, RETROK_UNKNOWN, true),
      RARCH_SLOWMOTION_HOLD_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_REWIND, RETROK_UNKNOWN, true),
      RARCH_REWIND, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_PAUSE_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_PAUSE_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_FRAMEADVANCE, RETROK_UNKNOWN, true),
      RARCH_FRAMEADVANCE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_MUTE, RETROK_UNKNOWN, true),
      RARCH_MUTE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_VOLUME_UP, RETROK_UNKNOWN, true),
      RARCH_VOLUME_UP, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_VOLUME_DOWN, RETROK_UNKNOWN, true),
      RARCH_VOLUME_DOWN, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_LOAD_STATE_KEY, RETROK_UNKNOWN, true),
      RARCH_LOAD_STATE_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_SAVE_STATE_KEY, RETROK_UNKNOWN, true),
      RARCH_SAVE_STATE_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_STATE_SLOT_PLUS, RETROK_UNKNOWN, true),
      RARCH_STATE_SLOT_PLUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_STATE_SLOT_MINUS, RETROK_UNKNOWN, true),
      RARCH_STATE_SLOT_MINUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_PLAY_REPLAY_KEY, RETROK_UNKNOWN, true),
      RARCH_PLAY_REPLAY_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_RECORD_REPLAY_KEY, RETROK_UNKNOWN, true),
      RARCH_RECORD_REPLAY_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_HALT_REPLAY_KEY, RETROK_UNKNOWN, true),
      RARCH_HALT_REPLAY_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_SAVE_REPLAY_CHECKPOINT_KEY, RETROK_UNKNOWN, true),
      RARCH_SAVE_REPLAY_CHECKPOINT_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_PREV_REPLAY_CHECKPOINT_KEY, RETROK_UNKNOWN, true),
      RARCH_PREV_REPLAY_CHECKPOINT_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_NEXT_REPLAY_CHECKPOINT_KEY, RETROK_UNKNOWN, true),
      RARCH_NEXT_REPLAY_CHECKPOINT_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_REPLAY_SLOT_PLUS, RETROK_UNKNOWN, true),
      RARCH_REPLAY_SLOT_PLUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_REPLAY_SLOT_MINUS, RETROK_UNKNOWN, true),
      RARCH_REPLAY_SLOT_MINUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_DISK_EJECT_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_DISK_EJECT_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_DISK_NEXT, RETROK_UNKNOWN, true),
      RARCH_DISK_NEXT, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_DISK_PREV, RETROK_UNKNOWN, true),
      RARCH_DISK_PREV, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_SHADER_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_SHADER_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_SHADER_HOLD, RETROK_UNKNOWN, true),
      RARCH_SHADER_HOLD, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_SHADER_NEXT, RETROK_UNKNOWN, true),
      RARCH_SHADER_NEXT, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_SHADER_PREV, RETROK_UNKNOWN, true),
      RARCH_SHADER_PREV, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_CHEAT_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_CHEAT_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_CHEAT_INDEX_PLUS, RETROK_UNKNOWN, true),
      RARCH_CHEAT_INDEX_PLUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_CHEAT_INDEX_MINUS, RETROK_UNKNOWN, true),
      RARCH_CHEAT_INDEX_MINUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_SCREENSHOT, RETROK_UNKNOWN, true),
      RARCH_SCREENSHOT, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_RECORDING_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_RECORDING_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_STREAMING_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_STREAMING_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_TURBO_FIRE_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_TURBO_FIRE_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_GRAB_MOUSE_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_GRAB_MOUSE_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_GAME_FOCUS_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_GAME_FOCUS_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_FULLSCREEN_TOGGLE_KEY, RETROK_UNKNOWN, true),
      RARCH_FULLSCREEN_TOGGLE_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_UI_COMPANION_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_UI_COMPANION_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_VRR_RUNLOOP_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_VRR_RUNLOOP_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_RUNAHEAD_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_RUNAHEAD_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_PREEMPT_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_PREEMPT_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_VIDEO_FILTER_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_VIDEO_FILTER_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_FPS_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_FPS_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_STATISTICS_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_STATISTICS_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_AI_SERVICE, RETROK_UNKNOWN, true),
      RARCH_AI_SERVICE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_NETPLAY_PING_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_NETPLAY_PING_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_NETPLAY_HOST_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_NETPLAY_HOST_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_NETPLAY_GAME_WATCH, RETROK_UNKNOWN, true),
      RARCH_NETPLAY_GAME_WATCH, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_NETPLAY_PLAYER_CHAT, RETROK_UNKNOWN, true),
      RARCH_NETPLAY_PLAYER_CHAT, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_NETPLAY_FADE_CHAT_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_NETPLAY_FADE_CHAT_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_OVERLAY_NEXT, RETROK_UNKNOWN, true),
      RARCH_OVERLAY_NEXT, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_OSK, RETROK_UNKNOWN, true),
      RARCH_OSK, NO_BTN, NO_BTN, 0
   },
#else
   { 
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_B, RETROK_z, true),
      RETRO_DEVICE_ID_JOYPAD_B, NO_BTN, NO_BTN, 0
   },
   { 
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_Y, RETROK_a, true),
      RETRO_DEVICE_ID_JOYPAD_Y, NO_BTN, NO_BTN, 0
   },
   { 
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_SELECT, RETROK_RSHIFT, true),
      RETRO_DEVICE_ID_JOYPAD_SELECT, NO_BTN, NO_BTN, 0
   },
   { 
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_START, RETROK_RETURN, true),
      RETRO_DEVICE_ID_JOYPAD_START, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_UP, RETROK_UP, true),
      RETRO_DEVICE_ID_JOYPAD_UP, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_DOWN, RETROK_DOWN, true),
      RETRO_DEVICE_ID_JOYPAD_DOWN, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_LEFT, RETROK_LEFT, true),
      RETRO_DEVICE_ID_JOYPAD_LEFT, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_RIGHT, RETROK_RIGHT, true),
      RETRO_DEVICE_ID_JOYPAD_RIGHT, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_A, RETROK_x, true),
      RETRO_DEVICE_ID_JOYPAD_A, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_X, RETROK_s, true),
      RETRO_DEVICE_ID_JOYPAD_X, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_L, RETROK_q, true),
      RETRO_DEVICE_ID_JOYPAD_L, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_R, RETROK_w, true),
      RETRO_DEVICE_ID_JOYPAD_R, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_L2, RETROK_UNKNOWN, true),
      RETRO_DEVICE_ID_JOYPAD_L2, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_R2, RETROK_UNKNOWN, true),
      RETRO_DEVICE_ID_JOYPAD_R2, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_L3, RETROK_UNKNOWN, true),
      RETRO_DEVICE_ID_JOYPAD_L3, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_R3, RETROK_UNKNOWN, true),
      RETRO_DEVICE_ID_JOYPAD_R3, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_LEFT_X_PLUS, RETROK_UNKNOWN, true),
      RARCH_ANALOG_LEFT_X_PLUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_LEFT_X_MINUS, RETROK_UNKNOWN, true),
      RARCH_ANALOG_LEFT_X_MINUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_LEFT_Y_PLUS, RETROK_UNKNOWN, true),
      RARCH_ANALOG_LEFT_Y_PLUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_LEFT_Y_MINUS, RETROK_UNKNOWN, true),
      RARCH_ANALOG_LEFT_Y_MINUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_RIGHT_X_PLUS, RETROK_UNKNOWN, true),
      RARCH_ANALOG_RIGHT_X_PLUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_RIGHT_X_MINUS, RETROK_UNKNOWN, true),
      RARCH_ANALOG_RIGHT_X_MINUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_RIGHT_Y_PLUS, RETROK_UNKNOWN, true),
      RARCH_ANALOG_RIGHT_Y_PLUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_RIGHT_Y_MINUS, RETROK_UNKNOWN, true),
      RARCH_ANALOG_RIGHT_Y_MINUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_TRIGGER, RETROK_UNKNOWN, true),
      RARCH_LIGHTGUN_TRIGGER, RETRO_DEVICE_ID_MOUSE_LEFT, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_RELOAD, RETROK_UNKNOWN, true),
      RARCH_LIGHTGUN_RELOAD, RETRO_DEVICE_ID_MOUSE_RIGHT, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_AUX_A, RETROK_UNKNOWN, true),
      RARCH_LIGHTGUN_AUX_A, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_AUX_B, RETROK_UNKNOWN, true),
      RARCH_LIGHTGUN_AUX_B, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_AUX_C, RETROK_UNKNOWN, true),
      RARCH_LIGHTGUN_AUX_C, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_START, RETROK_RETURN, true),
      RARCH_LIGHTGUN_START, RETRO_DEVICE_ID_MOUSE_BUTTON_4, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_SELECT, RETROK_RSHIFT, true),
      RARCH_LIGHTGUN_SELECT, RETRO_DEVICE_ID_MOUSE_BUTTON_5, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_DPAD_UP, RETROK_UNKNOWN, true),
      RARCH_LIGHTGUN_DPAD_UP, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_DPAD_DOWN, RETROK_UNKNOWN, true),
      RARCH_LIGHTGUN_DPAD_DOWN, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_DPAD_LEFT, RETROK_UNKNOWN, true),
      RARCH_LIGHTGUN_DPAD_LEFT, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_DPAD_RIGHT, RETROK_UNKNOWN, true),
      RARCH_LIGHTGUN_DPAD_RIGHT, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_TURBO, RETROK_UNKNOWN, true),
      RARCH_TURBO_ENABLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_HOLD, RETROK_UNKNOWN, true),
      RARCH_HOLD_ENABLE, NO_BTN, NO_BTN, 0
   },
   /* Hotkeys */
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_ENABLE_HOTKEY, RETROK_UNKNOWN, true),
      RARCH_ENABLE_HOTKEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_MENU_TOGGLE, RETROK_F1, true),
      RARCH_MENU_TOGGLE, NO_BTN, NO_BTN, 0
   },
#ifdef HAVE_LAKKA
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_RESTART_KEY, RETROK_ESCAPE, true),
      RARCH_QUIT_KEY, NO_BTN, NO_BTN, 0
   },
#else
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_QUIT_KEY, RETROK_ESCAPE, true),
      RARCH_QUIT_KEY, NO_BTN, NO_BTN, 0
   },
#endif
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_CLOSE_CONTENT_KEY, RETROK_UNKNOWN, true),
      RARCH_CLOSE_CONTENT_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_RESET, RETROK_h, true),
      RARCH_RESET, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_FAST_FORWARD_KEY, RETROK_SPACE, true),
      RARCH_FAST_FORWARD_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_FAST_FORWARD_HOLD_KEY, RETROK_l, true),
      RARCH_FAST_FORWARD_HOLD_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_SLOWMOTION_KEY, RETROK_UNKNOWN, true),
      RARCH_SLOWMOTION_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_SLOWMOTION_HOLD_KEY, RETROK_e, true),
      RARCH_SLOWMOTION_HOLD_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_REWIND, RETROK_r, true),
      RARCH_REWIND, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_PAUSE_TOGGLE, RETROK_p, true),
      RARCH_PAUSE_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_FRAMEADVANCE, RETROK_k, true),
      RARCH_FRAMEADVANCE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_MUTE, RETROK_F9, true),
      RARCH_MUTE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_VOLUME_UP, RETROK_KP_PLUS, true),
      RARCH_VOLUME_UP, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_VOLUME_DOWN, RETROK_KP_MINUS, true),
      RARCH_VOLUME_DOWN, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_LOAD_STATE_KEY, RETROK_F4, true),
      RARCH_LOAD_STATE_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_SAVE_STATE_KEY, RETROK_F2, true),
      RARCH_SAVE_STATE_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_STATE_SLOT_PLUS, RETROK_F7, true),
      RARCH_STATE_SLOT_PLUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_STATE_SLOT_MINUS, RETROK_F6, true),
      RARCH_STATE_SLOT_MINUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_PLAY_REPLAY_KEY, RETROK_UNKNOWN, true),
      RARCH_PLAY_REPLAY_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_RECORD_REPLAY_KEY, RETROK_UNKNOWN, true),
      RARCH_RECORD_REPLAY_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_HALT_REPLAY_KEY, RETROK_UNKNOWN, true),
      RARCH_HALT_REPLAY_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_SAVE_REPLAY_CHECKPOINT_KEY, RETROK_UNKNOWN, true),
      RARCH_SAVE_REPLAY_CHECKPOINT_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_PREV_REPLAY_CHECKPOINT_KEY, RETROK_UNKNOWN, true),
      RARCH_PREV_REPLAY_CHECKPOINT_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_NEXT_REPLAY_CHECKPOINT_KEY, RETROK_UNKNOWN, true),
      RARCH_NEXT_REPLAY_CHECKPOINT_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_REPLAY_SLOT_PLUS, RETROK_UNKNOWN, true),
      RARCH_REPLAY_SLOT_PLUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_REPLAY_SLOT_MINUS, RETROK_UNKNOWN, true),
      RARCH_REPLAY_SLOT_MINUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_DISK_EJECT_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_DISK_EJECT_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_DISK_NEXT, RETROK_UNKNOWN, true),
      RARCH_DISK_NEXT, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_DISK_PREV, RETROK_UNKNOWN, true),
      RARCH_DISK_PREV, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_SHADER_TOGGLE, RETROK_COMMA, true),
      RARCH_SHADER_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_SHADER_HOLD, RETROK_UNKNOWN, true),
      RARCH_SHADER_HOLD, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_SHADER_NEXT, RETROK_m, true),
      RARCH_SHADER_NEXT, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_SHADER_PREV, RETROK_n, true),
      RARCH_SHADER_PREV, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_CHEAT_TOGGLE, RETROK_u, true),
      RARCH_CHEAT_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_CHEAT_INDEX_PLUS, RETROK_y, true),
      RARCH_CHEAT_INDEX_PLUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_CHEAT_INDEX_MINUS, RETROK_t, true),
      RARCH_CHEAT_INDEX_MINUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_SCREENSHOT, RETROK_F8, true),
      RARCH_SCREENSHOT, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_RECORDING_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_RECORDING_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_STREAMING_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_STREAMING_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_TURBO_FIRE_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_TURBO_FIRE_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_GRAB_MOUSE_TOGGLE, RETROK_F11, true),
      RARCH_GRAB_MOUSE_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_GAME_FOCUS_TOGGLE, RETROK_SCROLLOCK, true),
      RARCH_GAME_FOCUS_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_FULLSCREEN_TOGGLE_KEY, RETROK_f, true),
      RARCH_FULLSCREEN_TOGGLE_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_UI_COMPANION_TOGGLE, RETROK_F5, true),
      RARCH_UI_COMPANION_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_VRR_RUNLOOP_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_VRR_RUNLOOP_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_RUNAHEAD_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_RUNAHEAD_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_PREEMPT_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_PREEMPT_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_VIDEO_FILTER_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_VIDEO_FILTER_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_FPS_TOGGLE, RETROK_F3, true),
      RARCH_FPS_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_STATISTICS_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_STATISTICS_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_AI_SERVICE, RETROK_UNKNOWN, true),
      RARCH_AI_SERVICE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_NETPLAY_PING_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_NETPLAY_PING_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_NETPLAY_HOST_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_NETPLAY_HOST_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_NETPLAY_GAME_WATCH, RETROK_i, true),
      RARCH_NETPLAY_GAME_WATCH, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_NETPLAY_PLAYER_CHAT, RETROK_BACKQUOTE, true),
      RARCH_NETPLAY_PLAYER_CHAT, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_NETPLAY_FADE_CHAT_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_NETPLAY_FADE_CHAT_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_OVERLAY_NEXT, RETROK_UNKNOWN, true),
      RARCH_OVERLAY_NEXT, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_OSK, RETROK_UNKNOWN, true),
      RARCH_OSK, NO_BTN, NO_BTN, 0
   },
#endif
};

/* Users 2 to MAX_USERS */
static const struct retro_keybind retro_keybinds_rest[] = {
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_B, RETROK_UNKNOWN, true),
      RETRO_DEVICE_ID_JOYPAD_B, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_Y, RETROK_UNKNOWN, true),
      RETRO_DEVICE_ID_JOYPAD_Y, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_SELECT, RETROK_UNKNOWN, true),
      RETRO_DEVICE_ID_JOYPAD_SELECT, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_START, RETROK_UNKNOWN, true),
      RETRO_DEVICE_ID_JOYPAD_START, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_UP, RETROK_UNKNOWN, true),
      RETRO_DEVICE_ID_JOYPAD_UP, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_DOWN, RETROK_UNKNOWN, true),
      RETRO_DEVICE_ID_JOYPAD_DOWN, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_LEFT, RETROK_UNKNOWN, true),
      RETRO_DEVICE_ID_JOYPAD_LEFT, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_RIGHT, RETROK_UNKNOWN, true),
      RETRO_DEVICE_ID_JOYPAD_RIGHT, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_A, RETROK_UNKNOWN, true),
      RETRO_DEVICE_ID_JOYPAD_A, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_X, RETROK_UNKNOWN, true),
      RETRO_DEVICE_ID_JOYPAD_X, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_L, RETROK_UNKNOWN, true),
      RETRO_DEVICE_ID_JOYPAD_L, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_R, RETROK_UNKNOWN, true),
      RETRO_DEVICE_ID_JOYPAD_R, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_L2, RETROK_UNKNOWN, true),
      RETRO_DEVICE_ID_JOYPAD_L2, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_R2, RETROK_UNKNOWN, true),
      RETRO_DEVICE_ID_JOYPAD_R2, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_L3, RETROK_UNKNOWN, true),
      RETRO_DEVICE_ID_JOYPAD_L3, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_JOYPAD_R3, RETROK_UNKNOWN, true),
      RETRO_DEVICE_ID_JOYPAD_R3, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_LEFT_X_PLUS, RETROK_UNKNOWN, true),
      RARCH_ANALOG_LEFT_X_PLUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_LEFT_X_MINUS, RETROK_UNKNOWN, true),
      RARCH_ANALOG_LEFT_X_MINUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_LEFT_Y_PLUS, RETROK_UNKNOWN, true),
      RARCH_ANALOG_LEFT_Y_PLUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_LEFT_Y_MINUS, RETROK_UNKNOWN, true),
      RARCH_ANALOG_LEFT_Y_MINUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_RIGHT_X_PLUS, RETROK_UNKNOWN, true),
      RARCH_ANALOG_RIGHT_X_PLUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_RIGHT_X_MINUS, RETROK_UNKNOWN, true),
      RARCH_ANALOG_RIGHT_X_MINUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_RIGHT_Y_PLUS, RETROK_UNKNOWN, true),
      RARCH_ANALOG_RIGHT_Y_PLUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_ANALOG_RIGHT_Y_MINUS, RETROK_UNKNOWN, true),
      RARCH_ANALOG_RIGHT_Y_MINUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_TRIGGER, RETROK_UNKNOWN, true),
      RARCH_LIGHTGUN_TRIGGER, RETRO_DEVICE_ID_MOUSE_LEFT, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_RELOAD, RETROK_UNKNOWN, true),
      RARCH_LIGHTGUN_RELOAD, RETRO_DEVICE_ID_MOUSE_RIGHT, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_AUX_A, RETROK_UNKNOWN, true),
      RARCH_LIGHTGUN_AUX_A, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_AUX_B, RETROK_UNKNOWN, true),
      RARCH_LIGHTGUN_AUX_B, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_AUX_C, RETROK_UNKNOWN, true),
      RARCH_LIGHTGUN_AUX_C, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_START, RETROK_UNKNOWN, true),
      RARCH_LIGHTGUN_START, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_SELECT, RETROK_UNKNOWN, true),
      RARCH_LIGHTGUN_SELECT, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_DPAD_UP, RETROK_UNKNOWN, true),
      RARCH_LIGHTGUN_DPAD_UP, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_DPAD_DOWN, RETROK_UNKNOWN, true),
      RARCH_LIGHTGUN_DPAD_DOWN, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_DPAD_LEFT, RETROK_UNKNOWN, true),
      RARCH_LIGHTGUN_DPAD_LEFT, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_DPAD_RIGHT, RETROK_UNKNOWN, true),
      RARCH_LIGHTGUN_DPAD_RIGHT, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_TURBO, RETROK_UNKNOWN, true),
      RARCH_TURBO_ENABLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_HOLD, RETROK_UNKNOWN, true),
      RARCH_HOLD_ENABLE, NO_BTN, NO_BTN, 0
   },
   /* Hotkeys */
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_ENABLE_HOTKEY, RETROK_UNKNOWN, true),
      RARCH_ENABLE_HOTKEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_MENU_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_MENU_TOGGLE, NO_BTN, NO_BTN, 0
   },
#ifdef HAVE_LAKKA
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_RESTART_KEY, RETROK_UNKNOWN, true),
      RARCH_QUIT_KEY, NO_BTN, NO_BTN, 0
   },
#else
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_QUIT_KEY, RETROK_UNKNOWN, true),
      RARCH_QUIT_KEY, NO_BTN, NO_BTN, 0
   },
#endif
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_CLOSE_CONTENT_KEY, RETROK_UNKNOWN, true),
      RARCH_CLOSE_CONTENT_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_RESET, RETROK_UNKNOWN, true),
      RARCH_RESET, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_FAST_FORWARD_KEY, RETROK_UNKNOWN, true),
      RARCH_FAST_FORWARD_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_FAST_FORWARD_HOLD_KEY, RETROK_UNKNOWN, true),
      RARCH_FAST_FORWARD_HOLD_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_SLOWMOTION_KEY, RETROK_UNKNOWN, true),
      RARCH_SLOWMOTION_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_SLOWMOTION_HOLD_KEY, RETROK_UNKNOWN, true),
      RARCH_SLOWMOTION_HOLD_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_REWIND, RETROK_UNKNOWN, true),
      RARCH_REWIND, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_PAUSE_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_PAUSE_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_FRAMEADVANCE, RETROK_UNKNOWN, true),
      RARCH_FRAMEADVANCE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_MUTE, RETROK_UNKNOWN, true),
      RARCH_MUTE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_VOLUME_UP, RETROK_UNKNOWN, true),
      RARCH_VOLUME_UP, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_VOLUME_DOWN, RETROK_UNKNOWN, true),
      RARCH_VOLUME_DOWN, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_LOAD_STATE_KEY, RETROK_UNKNOWN, true),
      RARCH_LOAD_STATE_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_SAVE_STATE_KEY, RETROK_UNKNOWN, true),
      RARCH_SAVE_STATE_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_STATE_SLOT_PLUS, RETROK_UNKNOWN, true),
      RARCH_STATE_SLOT_PLUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_STATE_SLOT_MINUS, RETROK_UNKNOWN, true),
      RARCH_STATE_SLOT_MINUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_PLAY_REPLAY_KEY, RETROK_UNKNOWN, true),
      RARCH_PLAY_REPLAY_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_RECORD_REPLAY_KEY, RETROK_UNKNOWN, true),
      RARCH_RECORD_REPLAY_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_HALT_REPLAY_KEY, RETROK_UNKNOWN, true),
      RARCH_HALT_REPLAY_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_REPLAY_SLOT_PLUS, RETROK_UNKNOWN, true),
      RARCH_REPLAY_SLOT_PLUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_REPLAY_SLOT_MINUS, RETROK_UNKNOWN, true),
      RARCH_REPLAY_SLOT_MINUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_DISK_EJECT_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_DISK_EJECT_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_DISK_NEXT, RETROK_UNKNOWN, true),
      RARCH_DISK_NEXT, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_DISK_PREV, RETROK_UNKNOWN, true),
      RARCH_DISK_PREV, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_SHADER_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_SHADER_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_SHADER_HOLD, RETROK_UNKNOWN, true),
      RARCH_SHADER_HOLD, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_SHADER_NEXT, RETROK_UNKNOWN, true),
      RARCH_SHADER_NEXT, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_SHADER_PREV, RETROK_UNKNOWN, true),
      RARCH_SHADER_PREV, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_CHEAT_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_CHEAT_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_CHEAT_INDEX_PLUS, RETROK_UNKNOWN, true),
      RARCH_CHEAT_INDEX_PLUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_CHEAT_INDEX_MINUS, RETROK_UNKNOWN, true),
      RARCH_CHEAT_INDEX_MINUS, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_SCREENSHOT, RETROK_UNKNOWN, true),
      RARCH_SCREENSHOT, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_RECORDING_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_RECORDING_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_STREAMING_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_STREAMING_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_TURBO_FIRE_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_TURBO_FIRE_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_GRAB_MOUSE_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_GRAB_MOUSE_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_GAME_FOCUS_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_GAME_FOCUS_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_FULLSCREEN_TOGGLE_KEY, RETROK_UNKNOWN, true),
      RARCH_FULLSCREEN_TOGGLE_KEY, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_UI_COMPANION_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_UI_COMPANION_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_VRR_RUNLOOP_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_VRR_RUNLOOP_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_RUNAHEAD_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_RUNAHEAD_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_PREEMPT_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_PREEMPT_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_VIDEO_FILTER_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_VIDEO_FILTER_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_FPS_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_FPS_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_STATISTICS_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_STATISTICS_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_AI_SERVICE, RETROK_UNKNOWN, true),
      RARCH_AI_SERVICE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_NETPLAY_PING_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_NETPLAY_PING_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_NETPLAY_HOST_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_NETPLAY_HOST_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_NETPLAY_GAME_WATCH, RETROK_UNKNOWN, true),
      RARCH_NETPLAY_GAME_WATCH, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_NETPLAY_PLAYER_CHAT, RETROK_UNKNOWN, true),
      RARCH_NETPLAY_PLAYER_CHAT, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_NETPLAY_FADE_CHAT_TOGGLE, RETROK_UNKNOWN, true),
      RARCH_NETPLAY_FADE_CHAT_TOGGLE, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_OVERLAY_NEXT, RETROK_UNKNOWN, true),
      RARCH_OVERLAY_NEXT, NO_BTN, NO_BTN, 0
   },
   {
      AXIS_NONE, AXIS_NONE,
      RETRO_KEYBIND_PACK(MENU_ENUM_LABEL_VALUE_INPUT_META_OSK, RETROK_UNKNOWN, true),
      RARCH_OSK, NO_BTN, NO_BTN, 0
   },
};

#endif

#endif
