###
##
# Makefile for RetroArch Android.
##

all:
	ndk-build
	
clean:
	ndk-build clean
	
headers:
	javah -o android/com_retroarch_rruntime.h -classpath android/bin/classes com.retroarch.rruntime
	
install:
	adb install retroarch-android.apk
	
uninstall:
	adb uninstall com.retroarch
	
test_shader:
	cgc -ogles -profile glslf $(FILE)
