// GLSL shader autogenerated by cg2glsl.py.
#if defined(VERTEX)
varying     vec2 _DR;
varying     vec2 _DL;
varying     vec2 _UR;
varying     vec2 _UL;
varying     float _frame_rotation;
varying     vec4 _color;
struct output_dummy {
    vec4 _color;
};
struct input_dummy {
    vec2 _video_size;
    vec2 _texture_size;
    vec2 _output_dummy_size;
    float _frame_count;
    float _frame_direction;
    float _frame_rotation;
};
struct deltas {
    vec2 _UL;
    vec2 _UR;
    vec2 _DL;
    vec2 _DR;
};
vec4 _oPosition1;
uniform mat4 MVPMatrix;
vec4 _r0002;
attribute vec4 VertexCoord;
attribute vec4 TexCoord;
varying vec4 TEX0;
 

         mat4 transpose_(mat4 matrix)
         {
            mat4 ret;
            for (int i = 0; i < 4; i++)
               for (int j = 0; j < 4; j++)
                  ret[i][j] = matrix[j][i];

            return ret;
         }
         
uniform int FrameDirection;
uniform int FrameCount;
#ifdef GL_ES
uniform mediump vec2 OutputSize;
uniform mediump vec2 TextureSize;
uniform mediump vec2 InputSize;
#else
uniform vec2 OutputSize;
uniform vec2 TextureSize;
uniform vec2 InputSize;
#endif
void main()
{
    mat4 MVPMatrix_ = transpose_(MVPMatrix);
    vec2 _otexCoord;
    _r0002.x = dot(MVPMatrix_[0], VertexCoord);
    _r0002.y = dot(MVPMatrix_[1], VertexCoord);
    _r0002.z = dot(MVPMatrix_[2], VertexCoord);
    _r0002.w = dot(MVPMatrix_[3], VertexCoord);
    _oPosition1 = _r0002;
    _otexCoord = TexCoord.xy;
    gl_Position = _r0002;
    TEX0.xy = TexCoord.xy;
} 
#elif defined(FRAGMENT)
#ifdef GL_ES
precision mediump float;
#endif
varying     vec2 _DR;
varying     vec2 _DL;
varying     vec2 _UR;
varying     vec2 _UL;
varying     float _frame_rotation;
varying     vec4 _color;
struct output_dummy {
    vec4 _color;
};
struct input_dummy {
    vec2 _video_size;
    vec2 _texture_size;
    vec2 _output_dummy_size;
    float _frame_count;
    float _frame_direction;
    float _frame_rotation;
};
struct deltas {
    vec2 _UL;
    vec2 _UR;
    vec2 _DL;
    vec2 _DR;
};
float _TMP9;
vec3 _TMP8;
float _TMP7;
vec3 _TMP6;
vec4 _TMP5;
vec4 _TMP4;
vec4 _TMP3;
vec4 _TMP2;
float _TMP1;
float _TMP0;
input_dummy _IN1;
uniform sampler2D Texture;
vec3 _a0023;
vec3 _a0027;
varying vec4 TEX0;
 
uniform int FrameDirection;
uniform int FrameCount;
#ifdef GL_ES
uniform mediump vec2 OutputSize;
uniform mediump vec2 TextureSize;
uniform mediump vec2 InputSize;
#else
uniform vec2 OutputSize;
uniform vec2 TextureSize;
uniform vec2 InputSize;
#endif
void main()
{
    float _dx;
    float _dy;
    float _m1;
    float _m2;
    output_dummy _OUT;
    vec3 _TMP12;
    deltas _TMP13;
    _TMP0 = 1.00000000E+00/TextureSize.x;
    _dx = _TMP0*2.50000000E-01;
    _TMP1 = 1.00000000E+00/TextureSize.y;
    _dy = _TMP1*2.50000000E-01;
    _TMP13._UL = TEX0.xy + vec2(-_dx, -_dy);
    _TMP13._UR = TEX0.xy + vec2(_dx, -_dy);
    _TMP13._DL = TEX0.xy + vec2(-_dx, _dy);
    _TMP13._DR = TEX0.xy + vec2(_dx, _dy);
    _TMP2 = texture2D(Texture, _TMP13._UL);
    _TMP3 = texture2D(Texture, _TMP13._UR);
    _TMP4 = texture2D(Texture, _TMP13._DL);
    _TMP5 = texture2D(Texture, _TMP13._DR);
    _a0023 = _TMP2.xyz - _TMP5.xyz;
    _TMP6 = abs(_a0023);
    _TMP7 = dot(_TMP6, vec3( 1.00000000E+00, 1.00000000E+00, 1.00000000E+00));
    _m1 = _TMP7 + 1.00000005E-03;
    _a0027 = _TMP4.xyz - _TMP3.xyz;
    _TMP8 = abs(_a0027);
    _TMP9 = dot(_TMP8, vec3( 1.00000000E+00, 1.00000000E+00, 1.00000000E+00));
    _m2 = _TMP9 + 1.00000005E-03;
    _TMP12 = (_m1*(_TMP4.xyz + _TMP3.xyz) + _m2*(_TMP5.xyz + _TMP2.xyz))/(2.00000000E+00*(_m1 + _m2));
    _OUT._color = vec4(_TMP12.x, _TMP12.y, _TMP12.z, 1.00000000E+00);
    gl_FragColor = _OUT._color;
    return;
} 
#endif
