blank_issues_enabled: true
contact_links:
  - name: Libretro Forums
    url: https://forums.libretro.com
    about: A place to discuss all things libretro
  - name: Discord
    url: https://ra-link.web.app/discord
    about: Join our Discord server for help
  - name: RetroArch/libretro subreddit
    url: https://www.reddit.com/r/RetroArch
    about: Subreddit dedicated to RetroArch and the libretro API framework
  - name: Documentation
    url: https://docs.libretro.com
    about: Official RetroArch documentation for users and developers
