<?xml version="1.0" encoding="UTF-8"?>
<!-- XML/GLSL shader autogenerated by cg2xml.py -->
<shader language="GLSL" style="GLES2">
    <vertex><![CDATA[
varying     float _frame_rotation;
varying     float _frame_direction;
varying     float _frame_count;
varying     vec2 _output_dummy_size;
varying     vec4 _color1;
struct output_dummy {
    vec4 _color1;
};
struct input_dummy {
    vec2 _video_size;
    vec2 _texture_size;
    vec2 _output_dummy_size;
    float _frame_count;
    float _frame_direction;
    float _frame_rotation;
};
vec4 _oPosition1;
uniform mat4 rubyMVPMatrix;
vec4 _r0003;
attribute vec4 rubyVertexCoord;
attribute vec4 COLOR;
attribute vec4 rubyTexCoord;
varying vec4 COL0;
varying vec4 TEX0;
 

         mat4 transpose_(mat4 matrix)
         {
            mat4 ret;
            for (int i = 0; i < 4; i++)
               for (int j = 0; j < 4; j++)
                  ret[i][j] = matrix[j][i];

            return ret;
         }
         
uniform mediump vec2 rubyOutputSize;
uniform mediump vec2 rubyTextureSize;
uniform mediump vec2 rubyInputSize;
void main()
{
    mat4 rubyMVPMatrix_ = transpose_(rubyMVPMatrix);
    vec4 _oColor;
    vec2 _otexCoord;
    _r0003.x = dot(rubyMVPMatrix_[0], rubyVertexCoord);
    _r0003.y = dot(rubyMVPMatrix_[1], rubyVertexCoord);
    _r0003.z = dot(rubyMVPMatrix_[2], rubyVertexCoord);
    _r0003.w = dot(rubyMVPMatrix_[3], rubyVertexCoord);
    _oPosition1 = _r0003;
    _oColor = COLOR;
    _otexCoord = rubyTexCoord.xy;
    gl_Position = _r0003;
    COL0 = COLOR;
    TEX0.xy = rubyTexCoord.xy;
} 
 ]]></vertex>
    <fragment><![CDATA[
#ifdef GL_ES
precision mediump float;
#endif
varying     float _frame_rotation;
varying     float _frame_direction;
varying     float _frame_count;
varying     vec2 _output_dummy_size;
varying     vec4 _color1;
struct output_dummy {
    vec4 _color1;
};
struct input_dummy {
    vec2 _video_size;
    vec2 _texture_size;
    vec2 _output_dummy_size;
    float _frame_count;
    float _frame_direction;
    float _frame_rotation;
};
vec3 _TMP25;
vec3 _TMP27;
vec3 _TMP26;
float _TMP28;
float _TMP29;
vec4 _TMP24;
vec4 _TMP23;
vec4 _TMP22;
vec4 _TMP21;
vec4 _TMP20;
vec4 _TMP19;
vec4 _TMP18;
vec4 _TMP17;
vec4 _TMP16;
vec4 _TMP15;
vec4 _TMP14;
vec4 _TMP13;
vec4 _TMP12;
vec4 _TMP11;
vec4 _TMP10;
vec4 _TMP9;
vec4 _TMP8;
vec4 _TMP7;
vec4 _TMP6;
vec4 _TMP5;
vec4 _TMP4;
vec4 _TMP3;
vec4 _TMP2;
vec4 _TMP1;
vec4 _TMP0;
uniform sampler2D rubyTexture;
uniform input_dummy _IN1;
vec2 _c0037;
vec2 _c0039;
vec2 _c0041;
vec2 _c0043;
vec2 _c0047;
vec2 _c0049;
vec2 _c0051;
vec2 _c0053;
vec2 _c0055;
vec2 _c0057;
vec2 _c0059;
vec2 _c0061;
vec2 _c0063;
vec2 _c0065;
vec2 _c0067;
vec2 _c0069;
vec2 _c0071;
vec2 _c0073;
vec2 _c0075;
vec2 _c0077;
vec2 _c0079;
vec2 _c0081;
vec2 _c0083;
vec2 _c0085;
varying vec4 TEX0;
 
uniform mediump vec2 rubyOutputSize;
uniform mediump vec2 rubyTextureSize;
uniform mediump vec2 rubyInputSize;
void main()
{
    vec2 _ps;
    vec2 _dx;
    vec2 _dy;
    vec2 _pixcoord;
    vec2 _fp;
    vec2 _d11;
    vec3 _A;
    vec3 _B;
    vec3 _C;
    vec3 _D;
    vec3 _E;
    vec3 _F;
    vec3 _G;
    vec3 _H;
    vec3 _I;
    vec3 _P00;
    vec3 _P04;
    vec3 _P40;
    vec3 _P44;
    vec3 _A1;
    vec3 _B1;
    vec3 _C1;
    vec3 _A0;
    vec3 _D0;
    vec3 _G0;
    vec3 _C4;
    vec3 _F4;
    vec3 _I4;
    vec3 _G5;
    vec3 _H5;
    vec3 _I5;
    vec3 _E0;
    vec3 _E1;
    vec3 _E2;
    vec3 _E3;
    float _a;
    float _b;
    float _c;
    float _d;
    float _e;
    float _f;
    float _g;
    float _h;
    float _i;
    float _p00;
    float _p04;
    float _p40;
    float _p44;
    float _a1;
    float _b1;
    float _c1;
    float _a0;
    float _d0;
    float _g0;
    float _c4;
    float _f4;
    float _i4;
    float _g5;
    float _h5;
    float _i5;
    vec3 _res;
    output_dummy _OUT;
    _ps = vec2(9.99899983E-01/rubyTextureSize.x, 9.99899983E-01/rubyTextureSize.y);
    _dx = vec2(float(_ps.x), 0.00000000E+00);
    _dy = vec2(0.00000000E+00, float(_ps.y));
    _pixcoord = TEX0.xy/_ps;
    _fp = fract(_pixcoord);
    _d11 = TEX0.xy - _fp*_ps;
    _c0037 = (_d11 - vec2(float(_dx.x), float(_dx.y))) - vec2(float(_dy.x), float(_dy.y));
    _TMP0 = texture2D(rubyTexture, _c0037);
    _A = vec3(float(_TMP0.x), float(_TMP0.y), float(_TMP0.z));
    _c0039 = _d11 - vec2(float(_dy.x), float(_dy.y));
    _TMP1 = texture2D(rubyTexture, _c0039);
    _B = vec3(float(_TMP1.x), float(_TMP1.y), float(_TMP1.z));
    _c0041 = (_d11 + vec2(float(_dx.x), float(_dx.y))) - vec2(float(_dy.x), float(_dy.y));
    _TMP2 = texture2D(rubyTexture, _c0041);
    _C = vec3(float(_TMP2.x), float(_TMP2.y), float(_TMP2.z));
    _c0043 = _d11 - vec2(float(_dx.x), float(_dx.y));
    _TMP3 = texture2D(rubyTexture, _c0043);
    _D = vec3(float(_TMP3.x), float(_TMP3.y), float(_TMP3.z));
    _TMP4 = texture2D(rubyTexture, _d11);
    _E = vec3(float(_TMP4.x), float(_TMP4.y), float(_TMP4.z));
    _c0047 = _d11 + vec2(float(_dx.x), float(_dx.y));
    _TMP5 = texture2D(rubyTexture, _c0047);
    _F = vec3(float(_TMP5.x), float(_TMP5.y), float(_TMP5.z));
    _c0049 = (_d11 - vec2(float(_dx.x), float(_dx.y))) + vec2(float(_dy.x), float(_dy.y));
    _TMP6 = texture2D(rubyTexture, _c0049);
    _G = vec3(float(_TMP6.x), float(_TMP6.y), float(_TMP6.z));
    _c0051 = _d11 + vec2(float(_dy.x), float(_dy.y));
    _TMP7 = texture2D(rubyTexture, _c0051);
    _H = vec3(float(_TMP7.x), float(_TMP7.y), float(_TMP7.z));
    _c0053 = _d11 + vec2(float(_dx.x), float(_dx.y)) + vec2(float(_dy.x), float(_dy.y));
    _TMP8 = texture2D(rubyTexture, _c0053);
    _I = vec3(float(_TMP8.x), float(_TMP8.y), float(_TMP8.z));
    _c0055 = (((_d11 - vec2(float(_dx.x), float(_dx.y))) - vec2(float(_dx.x), float(_dx.y))) - vec2(float(_dy.x), float(_dy.y))) - vec2(float(_dy.x), float(_dy.y));
    _TMP9 = texture2D(rubyTexture, _c0055);
    _P00 = vec3(float(_TMP9.x), float(_TMP9.y), float(_TMP9.z));
    _c0057 = ((_d11 + vec2(float(_dx.x), float(_dx.y)) + vec2(float(_dx.x), float(_dx.y))) - vec2(float(_dy.x), float(_dy.y))) - vec2(float(_dy.x), float(_dy.y));
    _TMP10 = texture2D(rubyTexture, _c0057);
    _P04 = vec3(float(_TMP10.x), float(_TMP10.y), float(_TMP10.z));
    _c0059 = ((_d11 - vec2(float(_dx.x), float(_dx.y))) - vec2(float(_dx.x), float(_dx.y))) + vec2(float(_dy.x), float(_dy.y)) + vec2(float(_dy.x), float(_dy.y));
    _TMP11 = texture2D(rubyTexture, _c0059);
    _P40 = vec3(float(_TMP11.x), float(_TMP11.y), float(_TMP11.z));
    _c0061 = _d11 + vec2(float(_dx.x), float(_dx.y)) + vec2(float(_dx.x), float(_dx.y)) + vec2(float(_dy.x), float(_dy.y)) + vec2(float(_dy.x), float(_dy.y));
    _TMP12 = texture2D(rubyTexture, _c0061);
    _P44 = vec3(float(_TMP12.x), float(_TMP12.y), float(_TMP12.z));
    _c0063 = ((_d11 - vec2(float(_dx.x), float(_dx.y))) - vec2(float(_dy.x), float(_dy.y))) - vec2(float(_dy.x), float(_dy.y));
    _TMP13 = texture2D(rubyTexture, _c0063);
    _A1 = vec3(float(_TMP13.x), float(_TMP13.y), float(_TMP13.z));
    _c0065 = (_d11 - vec2(float(_dy.x), float(_dy.y))) - vec2(float(_dy.x), float(_dy.y));
    _TMP14 = texture2D(rubyTexture, _c0065);
    _B1 = vec3(float(_TMP14.x), float(_TMP14.y), float(_TMP14.z));
    _c0067 = ((_d11 + vec2(float(_dx.x), float(_dx.y))) - vec2(float(_dy.x), float(_dy.y))) - vec2(float(_dy.x), float(_dy.y));
    _TMP15 = texture2D(rubyTexture, _c0067);
    _C1 = vec3(float(_TMP15.x), float(_TMP15.y), float(_TMP15.z));
    _c0069 = ((_d11 - vec2(float(_dx.x), float(_dx.y))) - vec2(float(_dx.x), float(_dx.y))) - vec2(float(_dy.x), float(_dy.y));
    _TMP16 = texture2D(rubyTexture, _c0069);
    _A0 = vec3(float(_TMP16.x), float(_TMP16.y), float(_TMP16.z));
    _c0071 = (_d11 - vec2(float(_dx.x), float(_dx.y))) - vec2(float(_dx.x), float(_dx.y));
    _TMP17 = texture2D(rubyTexture, _c0071);
    _D0 = vec3(float(_TMP17.x), float(_TMP17.y), float(_TMP17.z));
    _c0073 = ((_d11 - vec2(float(_dx.x), float(_dx.y))) - vec2(float(_dx.x), float(_dx.y))) + vec2(float(_dy.x), float(_dy.y));
    _TMP18 = texture2D(rubyTexture, _c0073);
    _G0 = vec3(float(_TMP18.x), float(_TMP18.y), float(_TMP18.z));
    _c0075 = (_d11 + vec2(float(_dx.x), float(_dx.y)) + vec2(float(_dx.x), float(_dx.y))) - vec2(float(_dy.x), float(_dy.y));
    _TMP19 = texture2D(rubyTexture, _c0075);
    _C4 = vec3(float(_TMP19.x), float(_TMP19.y), float(_TMP19.z));
    _c0077 = _d11 + vec2(float(_dx.x), float(_dx.y)) + vec2(float(_dx.x), float(_dx.y));
    _TMP20 = texture2D(rubyTexture, _c0077);
    _F4 = vec3(float(_TMP20.x), float(_TMP20.y), float(_TMP20.z));
    _c0079 = _d11 + vec2(float(_dx.x), float(_dx.y)) + vec2(float(_dx.x), float(_dx.y)) + vec2(float(_dy.x), float(_dy.y));
    _TMP21 = texture2D(rubyTexture, _c0079);
    _I4 = vec3(float(_TMP21.x), float(_TMP21.y), float(_TMP21.z));
    _c0081 = (_d11 - vec2(float(_dx.x), float(_dx.y))) + vec2(float(_dy.x), float(_dy.y)) + vec2(float(_dy.x), float(_dy.y));
    _TMP22 = texture2D(rubyTexture, _c0081);
    _G5 = vec3(float(_TMP22.x), float(_TMP22.y), float(_TMP22.z));
    _c0083 = _d11 + vec2(float(_dy.x), float(_dy.y)) + vec2(float(_dy.x), float(_dy.y));
    _TMP23 = texture2D(rubyTexture, _c0083);
    _H5 = vec3(float(_TMP23.x), float(_TMP23.y), float(_TMP23.z));
    _c0085 = _d11 + vec2(float(_dx.x), float(_dx.y)) + vec2(float(_dy.x), float(_dy.y)) + vec2(float(_dy.x), float(_dy.y));
    _TMP24 = texture2D(rubyTexture, _c0085);
    _I5 = vec3(float(_TMP24.x), float(_TMP24.y), float(_TMP24.z));
    _E0 = _E;
    _E1 = _E;
    _E2 = _E;
    _E3 = _E;
    _TMP29 = dot(vec3(float(_A.x), float(_A.y), float(_A.z)), vec3( 6.55360000E+04, 2.55000000E+02, 1.00000000E+00));
    _TMP28 = float(_TMP29);
    _a = float(_TMP28);
    _TMP29 = dot(vec3(float(_B.x), float(_B.y), float(_B.z)), vec3( 6.55360000E+04, 2.55000000E+02, 1.00000000E+00));
    _TMP28 = float(_TMP29);
    _b = float(_TMP28);
    _TMP29 = dot(vec3(float(_C.x), float(_C.y), float(_C.z)), vec3( 6.55360000E+04, 2.55000000E+02, 1.00000000E+00));
    _TMP28 = float(_TMP29);
    _c = float(_TMP28);
    _TMP29 = dot(vec3(float(_D.x), float(_D.y), float(_D.z)), vec3( 6.55360000E+04, 2.55000000E+02, 1.00000000E+00));
    _TMP28 = float(_TMP29);
    _d = float(_TMP28);
    _TMP29 = dot(vec3(float(_E.x), float(_E.y), float(_E.z)), vec3( 6.55360000E+04, 2.55000000E+02, 1.00000000E+00));
    _TMP28 = float(_TMP29);
    _e = float(_TMP28);
    _TMP29 = dot(vec3(float(_F.x), float(_F.y), float(_F.z)), vec3( 6.55360000E+04, 2.55000000E+02, 1.00000000E+00));
    _TMP28 = float(_TMP29);
    _f = float(_TMP28);
    _TMP29 = dot(vec3(float(_G.x), float(_G.y), float(_G.z)), vec3( 6.55360000E+04, 2.55000000E+02, 1.00000000E+00));
    _TMP28 = float(_TMP29);
    _g = float(_TMP28);
    _TMP29 = dot(vec3(float(_H.x), float(_H.y), float(_H.z)), vec3( 6.55360000E+04, 2.55000000E+02, 1.00000000E+00));
    _TMP28 = float(_TMP29);
    _h = float(_TMP28);
    _TMP29 = dot(vec3(float(_I.x), float(_I.y), float(_I.z)), vec3( 6.55360000E+04, 2.55000000E+02, 1.00000000E+00));
    _TMP28 = float(_TMP29);
    _i = float(_TMP28);
    _TMP29 = dot(vec3(float(_P00.x), float(_P00.y), float(_P00.z)), vec3( 6.55360000E+04, 2.55000000E+02, 1.00000000E+00));
    _TMP28 = float(_TMP29);
    _p00 = float(_TMP28);
    _TMP29 = dot(vec3(float(_P04.x), float(_P04.y), float(_P04.z)), vec3( 6.55360000E+04, 2.55000000E+02, 1.00000000E+00));
    _TMP28 = float(_TMP29);
    _p04 = float(_TMP28);
    _TMP29 = dot(vec3(float(_P40.x), float(_P40.y), float(_P40.z)), vec3( 6.55360000E+04, 2.55000000E+02, 1.00000000E+00));
    _TMP28 = float(_TMP29);
    _p40 = float(_TMP28);
    _TMP29 = dot(vec3(float(_P44.x), float(_P44.y), float(_P44.z)), vec3( 6.55360000E+04, 2.55000000E+02, 1.00000000E+00));
    _TMP28 = float(_TMP29);
    _p44 = float(_TMP28);
    _TMP29 = dot(vec3(float(_A1.x), float(_A1.y), float(_A1.z)), vec3( 6.55360000E+04, 2.55000000E+02, 1.00000000E+00));
    _TMP28 = float(_TMP29);
    _a1 = float(_TMP28);
    _TMP29 = dot(vec3(float(_B1.x), float(_B1.y), float(_B1.z)), vec3( 6.55360000E+04, 2.55000000E+02, 1.00000000E+00));
    _TMP28 = float(_TMP29);
    _b1 = float(_TMP28);
    _TMP29 = dot(vec3(float(_C1.x), float(_C1.y), float(_C1.z)), vec3( 6.55360000E+04, 2.55000000E+02, 1.00000000E+00));
    _TMP28 = float(_TMP29);
    _c1 = float(_TMP28);
    _TMP29 = dot(vec3(float(_A0.x), float(_A0.y), float(_A0.z)), vec3( 6.55360000E+04, 2.55000000E+02, 1.00000000E+00));
    _TMP28 = float(_TMP29);
    _a0 = float(_TMP28);
    _TMP29 = dot(vec3(float(_D0.x), float(_D0.y), float(_D0.z)), vec3( 6.55360000E+04, 2.55000000E+02, 1.00000000E+00));
    _TMP28 = float(_TMP29);
    _d0 = float(_TMP28);
    _TMP29 = dot(vec3(float(_G0.x), float(_G0.y), float(_G0.z)), vec3( 6.55360000E+04, 2.55000000E+02, 1.00000000E+00));
    _TMP28 = float(_TMP29);
    _g0 = float(_TMP28);
    _TMP29 = dot(vec3(float(_C4.x), float(_C4.y), float(_C4.z)), vec3( 6.55360000E+04, 2.55000000E+02, 1.00000000E+00));
    _TMP28 = float(_TMP29);
    _c4 = float(_TMP28);
    _TMP29 = dot(vec3(float(_F4.x), float(_F4.y), float(_F4.z)), vec3( 6.55360000E+04, 2.55000000E+02, 1.00000000E+00));
    _TMP28 = float(_TMP29);
    _f4 = float(_TMP28);
    _TMP29 = dot(vec3(float(_I4.x), float(_I4.y), float(_I4.z)), vec3( 6.55360000E+04, 2.55000000E+02, 1.00000000E+00));
    _TMP28 = float(_TMP29);
    _i4 = float(_TMP28);
    _TMP29 = dot(vec3(float(_G5.x), float(_G5.y), float(_G5.z)), vec3( 6.55360000E+04, 2.55000000E+02, 1.00000000E+00));
    _TMP28 = float(_TMP29);
    _g5 = float(_TMP28);
    _TMP29 = dot(vec3(float(_H5.x), float(_H5.y), float(_H5.z)), vec3( 6.55360000E+04, 2.55000000E+02, 1.00000000E+00));
    _TMP28 = float(_TMP29);
    _h5 = float(_TMP28);
    _TMP29 = dot(vec3(float(_I5.x), float(_I5.y), float(_I5.z)), vec3( 6.55360000E+04, 2.55000000E+02, 1.00000000E+00));
    _TMP28 = float(_TMP29);
    _i5 = float(_TMP28);
    if (_e != _h && _h == _f && (_e != _i && (_e != _b || _e != _d || _f != _b && _f != _c || _h != _d && _h != _g) || _e == _g && (_i == _h || _e == _d || _h != _d) || _e == _c && (_i == _h || _e == _b || _f != _b))) { 
        if (_e == _c && _e == _d && _h == _g) { 
            if (_d == _d0 && _g == _g0) { 
                _E3 = _E + 8.33496094E-01*(_H - _E);
                _E2 = _E + 5.00000000E-01*(_H - _E);
            } else {
                _E3 = _E + 7.50000000E-01*(_H - _E);
                _E2 = (_E + _H) - _E3;
            } 
        } else {
            if (_e == _g && _e == _b && _f == _c) { 
                if (_b == _b1 && _c == _c1) { 
                    _E3 = _E + 8.33496094E-01*(_F - _E);
                    _E1 = _E + 5.00000000E-01*(_F - _E);
                } else {
                    _E3 = _E + 7.50000000E-01*(_F - _E);
                    _E1 = (_E + _F) - _E3;
                } 
            } else {
                _E3 = _E + 5.00000000E-01*(_F - _E);
            } 
        } 
    } else {
        if (_e != _h && _e != _i && _e != _f && _e == _g && _e == _c) { 
            _E3 = _E + 5.00000000E-01*(_F - _E);
        } else {
            if (_f != _i && _i == _f4 && (_f != _i4 || _i != _p44) && _f == _c4 && _f == _e && _i == _h && _e == _d && _h == _g) { 
                _E3 = _E + 2.50000000E-01*(_H - _E);
            } else {
                if (_h != _i && _i == _h5 && (_h != _i5 || _i != _p44) && _h == _g5 && _h == _e && _i == _f && _e == _b && _f == _c) { 
                    _E3 = _E + 2.50000000E-01*(_F - _E);
                } 
            } 
        } 
    } 
    if (_e != _f && _f == _b && (_e != _c && (_e != _d || _e != _h || _b != _d && _b != _a || _f != _h && _f != _i) || _e == _i && (_c == _f || _e == _h || _f != _h) || _e == _a && (_c == _f || _e == _d || _b != _d))) { 
        if (_e == _a && _e == _h && _f == _i) { 
            if (_h == _h5 && _i == _i5) { 
                _E1 = _E1 + 8.33496094E-01*(_F - _E1);
                _E3 = _E3 + 5.00000000E-01*(_F - _E3);
            } else {
                _E1 = _E1 + 7.50000000E-01*(_F - _E1);
                _E3 = (_E3 + _F) - _E1;
            } 
        } else {
            if (_e == _i && _e == _d && _b == _a) { 
                if (_d == _d0 && _a == _a0) { 
                    _E1 = _E1 + 8.33496094E-01*(_B - _E1);
                    _E0 = _E + 5.00000000E-01*(_B - _E);
                } else {
                    _E1 = _E1 + 7.50000000E-01*(_B - _E1);
                    _E0 = (_E + _B) - _E1;
                } 
            } else {
                _E1 = _E1 + 5.00000000E-01*(_B - _E1);
            } 
        } 
    } else {
        if (_e != _f && _e != _c && _e != _b && _e == _i && _e == _a) { 
            _E1 = _E1 + 5.00000000E-01*(_B - _E1);
        } else {
            if (_b != _c && _c == _b1 && (_b != _c1 || _c != _p04) && _b == _a1 && _b == _e && _c == _f && _e == _h && _f == _i) { 
                _E1 = _E1 + 2.50000000E-01*(_F - _E1);
            } else {
                if (_f != _c && _c == _f4 && (_f != _c4 || _c != _p04) && _f == _i4 && _f == _e && _c == _b && _e == _d && _b == _a) { 
                    _E1 = _E1 + 2.50000000E-01*(_B - _E1);
                } 
            } 
        } 
    } 
    if (_e != _b && _b == _d && (_e != _a && (_e != _h || _e != _f || _d != _h && _d != _g || _b != _f && _b != _c) || _e == _c && (_a == _b || _e == _f || _b != _f) || _e == _g && (_a == _b || _e == _h || _d != _h))) { 
        if (_e == _g && _e == _f && _b == _c) { 
            if (_f == _f4 && _c == _c4) { 
                _E0 = _E0 + 8.33496094E-01*(_B - _E0);
                _E1 = _E1 + 5.00000000E-01*(_B - _E1);
            } else {
                _E0 = _E0 + 7.50000000E-01*(_B - _E0);
                _E1 = (_E1 + _B) - _E0;
            } 
        } else {
            if (_e == _c && _e == _h && _d == _g) { 
                if (_h == _h5 && _g == _g5) { 
                    _E0 = _E0 + 8.33496094E-01*(_D - _E0);
                    _E2 = _E2 + 5.00000000E-01*(_D - _E2);
                } else {
                    _E0 = _E0 + 7.50000000E-01*(_D - _E0);
                    _E2 = (_E2 + _D) - _E0;
                } 
            } else {
                _E0 = _E0 + 5.00000000E-01*(_D - _E0);
            } 
        } 
    } else {
        if (_e != _b && _e != _a && _e != _d && _e == _c && _e == _g) { 
            _E0 = _E0 + 5.00000000E-01*(_D - _E0);
        } else {
            if (_d != _a && _a == _d0 && (_d != _a0 || _a != _p00) && _d == _g0 && _d == _e && _a == _b && _e == _f && _b == _c) { 
                _E0 = _E0 + 2.50000000E-01*(_B - _E0);
            } else {
                if (_b != _a && _a == _b1 && (_b != _a1 || _a != _p00) && _b == _c1 && _b == _e && _a == _d && _e == _h && _d == _g) { 
                    _E0 = _E0 + 2.50000000E-01*(_D - _E0);
                } 
            } 
        } 
    } 
    if (_e != _d && _d == _h && (_e != _g && (_e != _f || _e != _b || _h != _f && _h != _i || _d != _b && _d != _a) || _e == _a && (_g == _d || _e == _b || _d != _b) || _e == _i && (_g == _d || _e == _f || _h != _f))) { 
        if (_e == _i && _e == _b && _d == _a) { 
            if (_b == _b1 && _a == _a1) { 
                _E2 = _E2 + 8.33496094E-01*(_D - _E2);
                _E0 = _E0 + 5.00000000E-01*(_D - _E0);
            } else {
                _E2 = _E2 + 7.50000000E-01*(_D - _E2);
                _E0 = (_E0 + _D) - _E2;
            } 
        } else {
            if (_e == _a && _e == _f && _h == _i) { 
                if (_f == _f4 && _i == _i4) { 
                    _E2 = _E2 + 8.33496094E-01*(_H - _E2);
                    _E3 = _E3 + 5.00000000E-01*(_H - _E3);
                } else {
                    _E2 = _E2 + 7.50000000E-01*(_H - _E2);
                    _E3 = (_E3 + _H) - _E2;
                } 
            } else {
                _E2 = _E2 + 5.00000000E-01*(_H - _E2);
            } 
        } 
    } else {
        if (_e != _d && _e != _g && _e != _h && _e == _a && _e == _i) { 
            _E2 = _E2 + 5.00000000E-01*(_H - _E2);
        } else {
            if (_h != _g && _g == _h5 && (_h != _g5 || _g != _p40) && _h == _i5 && _h == _e && _g == _d && _e == _b && _d == _a) { 
                _E2 = _E2 + 2.50000000E-01*(_D - _E2);
            } else {
                if (_d != _g && _g == _d0 && (_d != _g0 || _g != _p40) && _d == _a0 && _d == _e && _g == _h && _e == _f && _h == _i) { 
                    _E2 = _E2 + 2.50000000E-01*(_H - _E2);
                } 
            } 
        } 
    } 
    if (_fp.x < 5.00000000E-01) { 
        if (_fp.y < 5.00000000E-01) { 
            _TMP26 = _E0;
        } else {
            _TMP26 = _E2;
        } 
        _TMP25 = _TMP26;
    } else {
        if (_fp.y < 5.00000000E-01) { 
            _TMP27 = _E1;
        } else {
            _TMP27 = _E3;
        } 
        _TMP25 = _TMP27;
    } 
    _res = vec3(float(_TMP25.x), float(_TMP25.y), float(_TMP25.z));
    _OUT._color1 = vec4(_res.x, _res.y, _res.z, 1.00000000E+00);
    gl_FragColor = _OUT._color1;
    return;
} 
 ]]></fragment>
</shader>
