#!/bin/bash

set -e

. script/build.config

xcodebuild clean
rm -rf build

xcodebuild -verbose -sdk iphoneos -configuration Release

if [ -z "$NOCODESIGN" ] ; then
  echo "CODESIGNING DYNAMIC LIBRARIES AND BUILDING IPA"
  
  for file in $(find "$BUILD_PATH/RetroArch.app/modules/" -name "*.dylib") ; do
    codesign -fs "$CODE_SIGN_IDENTITY" "$file"
  done
  
  xcrun -sdk iphoneos PackageApplication "$BUILD_PATH/RetroArch.app" -o "$BUILD_PATH/RetroArch.ipa" --sign "$CODE_SIGN_IDENTITY" --embed "$PROVISIONING"
else
  echo "Building for Jailbroken system"
fi

echo "######### RetroArch build Complete!! #########"
echo "You can find the resulting app in the $BUILD_PATH directory.\n"
