#!/bin/sh

set -e

export IOSSDK=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS6.1.sdk/

test ! -d "tmp" && {
  mkdir tmp
}

script/cores/nestopia
script/cores/snes9x_next

