/*
 * ctr_bottom_kbd_keydef.h
 */

#ifndef CTR_BOTTOM_KBD_KEYDEF_H_
#define CTR_BOTTOM_KBD_KEYDEF_H_

enum Keys
{
	CTR_KEY_NONE = 0,
	CTR_KEY_A   = 1,  // , RETROK_COMMA
	CTR_KEY_B   = 2,  // . RETROK_PERIOD
	CTR_KEY_C   = 3,  // ^ RETROK_CARET
	CTR_KEY_D   = 4,  // \ RETROK_BACKSLASH
	CTR_KEY_E   = 5,  // # RETROK_HASH
	CTR_KEY_F   = 6,  // / RETROK_SLASH
	CTR_KEY_G   = 7,  // : RETROK_COLON
	CTR_KEY_H   = 8,  // ; RETROK_SEMICOLON
	CTR_KEY_I   = 9,  // * RETROK_ASTERISK
	CTR_KEY_J   = 10, // = RETROK_EQUALS
	CTR_KEY_K   = 11, // < RETROK_LESS
	CTR_KEY_L   = 12, // > RETROK_GREATER
	CTR_KEY_M   = 13, // } RETROK_RIGHTBRACE
	CTR_KEY_N   = 14, // { RETROK_LEFTBRACE
	CTR_KEY_O   = 15, // ( RETROK_LEFTPAREN
	CTR_KEY_P   = 16, // ) RETROK_RIGHTPAREN
	CTR_KEY_Q   = 17, // ! RETROK_EXCLAIM
	CTR_KEY_R   = 18, // $ RETROK_DOLLAR
	CTR_KEY_S   = 19, // + RETROK_PLUS
	CTR_KEY_T   = 20, // - RETROK_MINUS
	CTR_KEY_U   = 21, // ' RETROK_QUOTE
	CTR_KEY_V   = 22, // _ RETROK_UNDERSCORE
	CTR_KEY_W   = 23, // " RETROK_QUOTEDBL
	CTR_KEY_X   = 24, // @ RETROK_AT
	CTR_KEY_Y   = 25, // & RETROK_AMPERSAND
	CTR_KEY_Z   = 26, // ? RETROK_QUESTION

	CTR_KEY_1   = 27,
	CTR_KEY_2   = 28,
	CTR_KEY_3   = 29,
	CTR_KEY_4   = 30,
	CTR_KEY_5   = 31,
	CTR_KEY_6   = 32,
	CTR_KEY_7   = 33,
	CTR_KEY_8   = 34,
	CTR_KEY_9   = 35,
	CTR_KEY_0   = 36,

	CTR_KEY_F1  = 37, // RETROK_F1
	CTR_KEY_F2  = 38, // RETROK_F2
	CTR_KEY_F3  = 39, // RETROK_F3
	CTR_KEY_F4  = 40, // RETROK_F4
	CTR_KEY_F5  = 41, // RETROK_F5
	CTR_KEY_F6  = 42, // RETROK_F6
	CTR_KEY_F7  = 43, // RETROK_F7
	CTR_KEY_F8  = 44, // RETROK_F8
	CTR_KEY_F9  = 45, // RETROK_F9
	CTR_KEY_F10 = 46, // RETROK_F10
	CTR_KEY_F11 = 47, // RETROK_F11
	CTR_KEY_F12 = 48, // RETROK_F12

	CTR_KEY_COMMA        = 49, // , RETROK_COMMA
	CTR_KEY_PERIOD       = 50, // . RETROK_PERIOD
	CTR_KEY_CARET        = 51, // ^ RETROK_CARET
	CTR_KEY_BACKSLASH    = 52, // \ RETROK_BACKSLASH
	CTR_KEY_HASH         = 53, // # RETROK_HASH
	CTR_KEY_SLASH        = 54, // / RETROK_SLASH
	CTR_KEY_COLON        = 55, // : RETROK_COLON
	CTR_KEY_SEMICOLON    = 56, // ; RETROK_SEMICOLON
	CTR_KEY_ASTERISK     = 57, // * RETROK_ASTERISK
	CTR_KEY_EQUALS       = 58, // = RETROK_EQUALS
	CTR_KEY_LESS         = 59, // < RETROK_LESS
	CTR_KEY_GREATER      = 60, // > RETROK_GREATER
	CTR_KEY_RIGHTBRACE   = 61, // } RETROK_RIGHTBRACE
	CTR_KEY_LEFTBRACE    = 62, // { RETROK_LEFTBRACE // RETROK_LEFTBRACKET
	CTR_KEY_LEFTPAREN    = 63, // ( RETROK_LEFTPAREN // RETROK_RIGHTBRACKET
	CTR_KEY_RIGHTPAREN   = 64, // ) RETROK_RIGHTPAREN
	CTR_KEY_EXCLAIM      = 65, // ! RETROK_EXCLAIM
	CTR_KEY_DOLLAR       = 66, // $ RETROK_DOLLAR
	CTR_KEY_PLUS         = 67, // + RETROK_PLUS
	CTR_KEY_MINUS        = 68, // - RETROK_MINUS
	CTR_KEY_QUOTE        = 69, // ' RETROK_QUOTE
	CTR_KEY_UNDERSCORE   = 70, // _ RETROK_UNDERSCORE
	CTR_KEY_QUOTEDBL     = 71, // " RETROK_QUOTEDBL
	CTR_KEY_AT           = 72, // @ RETROK_AT
	CTR_KEY_AMPERSAND    = 73, // & RETROK_AMPERSAND
	CTR_KEY_QUESTION     = 74, // ? RETROK_QUESTION

	CTR_KEY_SPACE        = 75, // RETROK_SPACE
	CTR_KEY_RETURN       = 76, // RETROK_RETURN
	CTR_KEY_BACKSPACE    = 77, // RETROK_BACKSPACE
	CTR_KEY_ESCAPE       = 78, // RETROK_ESCAPE
	CTR_KEY_TAB          = 79, // RETROK_TAB

    /* KEYBOARD MODIFIERS */
	CTR_KEY_SHIFT        = 80, // RETROK_RSHIFT
	CTR_KEY_CAPS         = 81, // RETROK_CAPSLOCK
	CTR_KEY_ALT          = 82, // RETROK_RALT
	CTR_KEY_CTRL         = 83, // RETROK_RCTRL

    /* CTR KEYBOARD MODIFIERS */
	CTR_KEY_SYMBOL       = 84,
	CTR_KEY_NUMBER       = 85,

	CTR_KEY_LAST = 86,
};

#endif /* CTR_BOTTOM_KBD_KEYDEF_H_ */
