/*  RetroArch - A frontend for libretro.
 *  Copyright (C) 2011-2017 - Daniel De Matteis
 *
 *  RetroArch is free software: you can redistribute it and/or modify it under the terms
 *  of the GNU General Public License as published by the Free Software Found-
 *  ation, either version 3 of the License, or (at your option) any later version.
 *
 *  RetroArch is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 *  without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 *  PURPOSE.  See the GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along with RetroArch.
 *  If not, see <http://www.gnu.org/licenses/>.
 */

#include <string/stdstring.h>
#include <file/file_path.h>

#include <compat/strl.h>

#include "../menu_driver.h"
#include "../menu_cbs.h"

#include "../../msg_hash_lbl_str.h"
#include "../../configuration.h"
#include "../../file_path_special.h"
#include "../../retroarch.h"
#include "../../core_option_manager.h"
#include "../../core_info.h"

#ifdef HAVE_CHEEVOS
#include "../../cheevos/cheevos.h"
#endif

#include "../../audio/audio_driver.h"

#ifndef BIND_ACTION_GET_TITLE
#define BIND_ACTION_GET_TITLE(cbs, name) (cbs)->action_get_title = (name)
#endif

#define DEFAULT_TITLE_GENERIC_MACRO(func_name, lbl) \
   static int (func_name)(const char *path, const char *label, unsigned menu_type, char *s, size_t len) \
  { \
   return action_get_title_generic(s, len, path, msg_hash_to_str(lbl)); \
} \

static void sanitize_to_string(char *s, const char *lbl, size_t len)
{
   const char *src = lbl;
   const char *end = s + len - 1;
   char *dst = s;

   if (len == 0)
      return;

   /* Combine copy and replace into a single pass */
   while (*src != '\0' && dst < end)
   {
      *dst = (*src == '_') ? ' ' : *src;
      ++src;
      ++dst;
   }

   *dst = '\0';
}

#define DEFAULT_TITLE_MACRO(func_name, lbl) \
  static int (func_name)(const char *path, const char *label, unsigned menu_type, char *s, size_t len) \
{ \
   const char *str = msg_hash_to_str(lbl); \
   if (s && str && (*str != '\0')) \
      sanitize_to_string(s, str, len); \
   return 1; \
}

#define DEFAULT_FILL_TITLE_MACRO(func_name, lbl) \
  static int (func_name)(const char *path, const char *label, unsigned menu_type, char *s, size_t len) \
{ \
   size_t _len = 0; \
   const char *title = msg_hash_to_str(lbl); \
   if (title && *title) \
   { \
      _len = strlcpy(s, title, len); \
      if (_len >= len) \
         _len = len - 1; \
   } \
   if (path && *path && _len + STRLEN_CONST(": ") < len) \
   { \
      memcpy(s + _len, ": ", STRLEN_CONST(": ")); \
      _len += STRLEN_CONST(": "); \
      strlcpy(s + _len, path, len - _len); \
   } \
   return 1; \
}

#define DEFAULT_TITLE_COPY_MACRO(func_name, lbl) \
  static int (func_name)(const char *path, const char *label, unsigned menu_type, char *s, size_t len) \
{ \
   strlcpy(s, msg_hash_to_str(lbl), len); \
   return 1; \
}

static void action_get_title_fill_search_filter_default(
      enum msg_hash_enums lbl, char *s, size_t len)
{
   /* Copy label value */
   strlcpy(s, msg_hash_to_str(lbl), len);

   /* Add current search terms */
   menu_entries_search_append_terms_string(s, len);
}

#define DEFAULT_TITLE_SEARCH_FILTER_MACRO(func_name, lbl) \
  static int (func_name)(const char *path, const char *label, unsigned menu_type, char *s, size_t len) \
{ \
   action_get_title_fill_search_filter_default(lbl, s, len); \
   return 0; \
}

static void action_get_title_fill_path_search_filter_default(
      const char *path, enum msg_hash_enums lbl, char *s, size_t len)
{
   size_t _len       = 0;
   const char *title = msg_hash_to_str(lbl);

   if (title && *title != '\0')
   {
      _len = strlcpy(s, title, len);
      if (_len >= len)
         _len = len - 1;
      if (_len + 1 < len)
      {
         s[_len]     = ' ';
         s[_len + 1] = '\0';
         _len++;
      }
   }

   if (path && *path != '\0')
      _len += strlcpy(s + _len, path, len - _len);

   menu_entries_search_append_terms_string(s, len);
}

#define DEFAULT_FILL_TITLE_SEARCH_FILTER_MACRO(func_name, lbl) \
  static int (func_name)(const char *path, const char *label, unsigned menu_type, char *s, size_t len) \
{ \
   action_get_title_fill_path_search_filter_default(path, lbl, s, len); \
   return 0; \
}

/* Variant selector for the data-driven title handler: each value
 * matches one of the former DEFAULT_*_TITLE macros so a single
 * function replaces the ~200 generated ones. */
enum title_variant
{
   TITLE_VARIANT_PLAIN = 0,   /* DEFAULT_TITLE_MACRO: sanitize      */
   TITLE_VARIANT_FILL,        /* DEFAULT_FILL_TITLE_MACRO           */
   TITLE_VARIANT_COPY,        /* DEFAULT_TITLE_COPY_MACRO           */
   TITLE_VARIANT_SEARCH,      /* DEFAULT_TITLE_SEARCH_FILTER_MACRO  */
   TITLE_VARIANT_FILL_SEARCH  /* DEFAULT_FILL_TITLE_SEARCH_FILTER   */
};

typedef struct title_enum_map
{
   uint32_t label;      /* MENU_ENUM_LABEL_* matched by string    */
   uint32_t title;      /* MENU_ENUM_LABEL_VALUE_* to render       */
   uint8_t  variant;    /* enum title_variant                      */
} title_enum_map_t;

static const title_enum_map_t title_enum_map[] = {
   { MENU_ENUM_LABEL_DEFERRED_CORE_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_CORE_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_DUMP_DISC_LIST, MENU_ENUM_LABEL_VALUE_DUMP_DISC, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_LOAD_DISC_LIST, MENU_ENUM_LABEL_VALUE_LOAD_DISC, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_CONFIGURATION_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_CONFIGURATION_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_SAVING_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_SAVING_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_CLOUD_SYNC_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_CLOUD_SYNC_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_LOGGING_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_LOGGING_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_FRAME_TIME_COUNTER_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_FRAME_TIME_COUNTER_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_FRAME_THROTTLE_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_FRAME_THROTTLE_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_REWIND_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_REWIND_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_CHEAT_DETAILS_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_CHEAT_DETAILS_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_CHEAT_SEARCH_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_CHEAT_SEARCH_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_ONSCREEN_DISPLAY_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_ONSCREEN_DISPLAY_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_ONSCREEN_NOTIFICATIONS_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_ONSCREEN_NOTIFICATIONS_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_ONSCREEN_NOTIFICATIONS_VIEWS_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_ONSCREEN_NOTIFICATIONS_VIEWS_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_ONSCREEN_OVERLAY_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_ONSCREEN_OVERLAY_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_OSK_OVERLAY_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_OSK_OVERLAY_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_OVERLAY_LIGHTGUN_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_OVERLAY_LIGHTGUN_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_OVERLAY_MOUSE_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_OVERLAY_MOUSE_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_MENU_VIEWS_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_MENU_VIEWS_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_SETTINGS_VIEWS_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_SETTINGS_VIEWS_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_QUICK_MENU_VIEWS_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_QUICK_MENU_VIEWS_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_MENU_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_MENU_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_USER_INTERFACE_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_USER_INTERFACE_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_AI_SERVICE_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_AI_SERVICE_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_ACCESSIBILITY_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_ACCESSIBILITY_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_POWER_MANAGEMENT_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_POWER_MANAGEMENT_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_CPU_PERFPOWER_LIST, MENU_ENUM_LABEL_VALUE_CPU_PERFPOWER, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_CPU_POLICY_ENTRY, MENU_ENUM_LABEL_VALUE_CPU_POLICY_ENTRY, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_MENU_SOUNDS_LIST, MENU_ENUM_LABEL_VALUE_MENU_SOUNDS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_MENU_FILE_BROWSER_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_MENU_FILE_BROWSER_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_RETRO_ACHIEVEMENTS_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_RETRO_ACHIEVEMENTS_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_CHEEVOS_APPEARANCE_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_CHEEVOS_APPEARANCE_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_CHEEVOS_VISIBILITY_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_CHEEVOS_VISIBILITY_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_BLUETOOTH_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_BLUETOOTH_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_WIFI_NETWORKS_LIST, MENU_ENUM_LABEL_VALUE_WIFI_NETWORKS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_WIFI_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_WIFI_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_UPDATER_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_UPDATER_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_NETWORK_HOSTING_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_NETWORK_HOSTING_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_NETPLAY_KICK_LIST, MENU_ENUM_LABEL_VALUE_NETPLAY_KICK, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_NETPLAY_BAN_LIST, MENU_ENUM_LABEL_VALUE_NETPLAY_BAN, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_NETPLAY_LOBBY_FILTERS_LIST, MENU_ENUM_LABEL_VALUE_NETPLAY_LOBBY_FILTERS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_SUBSYSTEM_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_SUBSYSTEM_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_NETWORK_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_NETWORK_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_LAKKA_SERVICES_LIST, MENU_ENUM_LABEL_VALUE_LAKKA_SERVICES, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_USER_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_USER_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_DIRECTORY_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_DIRECTORY_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_PRIVACY_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_PRIVACY_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_MIDI_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_MIDI_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_CORE_CONTENT_DIRS_LIST, MENU_ENUM_LABEL_VALUE_DOWNLOAD_CORE_CONTENT, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_CORE_CONTENT_DIRS_SUBDIR_LIST, MENU_ENUM_LABEL_VALUE_DOWNLOAD_CORE_CONTENT, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_CORE_SYSTEM_FILES_LIST, MENU_ENUM_LABEL_VALUE_DOWNLOAD_CORE_SYSTEM_FILES, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_LOAD_CONTENT_HISTORY, MENU_ENUM_LABEL_VALUE_LOAD_CONTENT_HISTORY, TITLE_VARIANT_SEARCH },
   { MENU_ENUM_LABEL_DEFERRED_FAVORITES_LIST, MENU_ENUM_LABEL_VALUE_GOTO_FAVORITES, TITLE_VARIANT_SEARCH },
   { MENU_ENUM_LABEL_DEFERRED_IMAGES_LIST, MENU_ENUM_LABEL_VALUE_GOTO_IMAGES, TITLE_VARIANT_SEARCH },
   { MENU_ENUM_LABEL_DEFERRED_MUSIC_LIST, MENU_ENUM_LABEL_VALUE_GOTO_MUSIC, TITLE_VARIANT_SEARCH },
   { MENU_ENUM_LABEL_DEFERRED_VIDEO_LIST, MENU_ENUM_LABEL_VALUE_GOTO_VIDEO, TITLE_VARIANT_SEARCH },
   { MENU_ENUM_LABEL_DEFERRED_CONTENTLESS_CORES_LIST, MENU_ENUM_LABEL_VALUE_GOTO_CONTENTLESS_CORES, TITLE_VARIANT_SEARCH },
   { MENU_ENUM_LABEL_DEFERRED_DRIVER_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_DRIVER_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_AUDIO_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_AUDIO_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_AUDIO_OUTPUT_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_AUDIO_OUTPUT_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_AUDIO_SYNCHRONIZATION_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_AUDIO_SYNCHRONIZATION_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_AUDIO_MIXER_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_AUDIO_MIXER_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_LATENCY_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_LATENCY_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_SYSTEM_INFORMATION, MENU_ENUM_LABEL_VALUE_SYSTEM_INFORMATION, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DISC_INFORMATION, MENU_ENUM_LABEL_VALUE_DISC_INFORMATION, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_NETWORK_INFORMATION, MENU_ENUM_LABEL_VALUE_NETWORK_INFORMATION, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_QUICK_MENU_OVERRIDE_OPTIONS, MENU_ENUM_LABEL_VALUE_QUICK_MENU_OVERRIDE_OPTIONS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_CRT_SWITCHRES_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_CRT_SWITCHRES_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_ACCOUNTS_TWITCH_LIST, MENU_ENUM_LABEL_VALUE_ACCOUNTS_TWITCH, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_ACCOUNTS_YOUTUBE_LIST, MENU_ENUM_LABEL_VALUE_ACCOUNTS_YOUTUBE, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_ACCOUNTS_FACEBOOK_LIST, MENU_ENUM_LABEL_VALUE_ACCOUNTS_FACEBOOK, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_ACCOUNTS_KICK_LIST, MENU_ENUM_LABEL_VALUE_ACCOUNTS_KICK, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_ONLINE_UPDATER, MENU_ENUM_LABEL_VALUE_ONLINE_UPDATER, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_RECORDING_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_RECORDING_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_VIDEO_SCALING_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_VIDEO_SCALING_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_VIDEO_HDR_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_VIDEO_HDR_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_VIDEO_OUTPUT_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_VIDEO_OUTPUT_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_VIDEO_SYNCHRONIZATION_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_VIDEO_SYNCHRONIZATION_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_INPUT_MENU_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_INPUT_MENU_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_INPUT_TURBO_FIRE_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_INPUT_TURBO_FIRE_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_INPUT_HAPTIC_FEEDBACK_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_INPUT_HAPTIC_FEEDBACK_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_INPUT_SENSOR_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_INPUT_SENSOR_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_VIDEO_WINDOWED_MODE_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_VIDEO_WINDOWED_MODE_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_VIDEO_FULLSCREEN_MODE_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_VIDEO_FULLSCREEN_MODE_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_JOYPAD_AUTOCONFIG_DIR, MENU_ENUM_LABEL_VALUE_JOYPAD_AUTOCONFIG_DIR, TITLE_VARIANT_FILL },
   { MENU_ENUM_LABEL_CACHE_DIRECTORY, MENU_ENUM_LABEL_VALUE_CACHE_DIRECTORY, TITLE_VARIANT_FILL },
   { MENU_ENUM_LABEL_SYSTEM_DIRECTORY, MENU_ENUM_LABEL_VALUE_SYSTEM_DIRECTORY, TITLE_VARIANT_FILL },
   { MENU_ENUM_LABEL_ASSETS_DIRECTORY, MENU_ENUM_LABEL_VALUE_ASSETS_DIRECTORY, TITLE_VARIANT_FILL },
   { MENU_ENUM_LABEL_SAVEFILE_DIRECTORY, MENU_ENUM_LABEL_VALUE_SAVEFILE_DIRECTORY, TITLE_VARIANT_FILL },
   { MENU_ENUM_LABEL_OVERLAY_DIRECTORY, MENU_ENUM_LABEL_VALUE_OVERLAY_DIRECTORY, TITLE_VARIANT_FILL },
   { MENU_ENUM_LABEL_RGUI_BROWSER_DIRECTORY, MENU_ENUM_LABEL_VALUE_RGUI_BROWSER_DIRECTORY, TITLE_VARIANT_FILL },
   { MENU_ENUM_LABEL_USE_LAST_START_DIRECTORY, MENU_ENUM_LABEL_VALUE_USE_LAST_START_DIRECTORY, TITLE_VARIANT_FILL },
   { MENU_ENUM_LABEL_PLAYLIST_DIRECTORY, MENU_ENUM_LABEL_VALUE_PLAYLIST_DIRECTORY, TITLE_VARIANT_FILL },
   { MENU_ENUM_LABEL_CONTENT_FAVORITES_DIRECTORY, MENU_ENUM_LABEL_VALUE_CONTENT_FAVORITES_DIRECTORY, TITLE_VARIANT_FILL },
   { MENU_ENUM_LABEL_CONTENT_HISTORY_DIRECTORY, MENU_ENUM_LABEL_VALUE_CONTENT_HISTORY_DIRECTORY, TITLE_VARIANT_FILL },
   { MENU_ENUM_LABEL_CONTENT_IMAGE_HISTORY_DIRECTORY, MENU_ENUM_LABEL_VALUE_CONTENT_IMAGE_HISTORY_DIRECTORY, TITLE_VARIANT_FILL },
   { MENU_ENUM_LABEL_CONTENT_MUSIC_HISTORY_DIRECTORY, MENU_ENUM_LABEL_VALUE_CONTENT_MUSIC_HISTORY_DIRECTORY, TITLE_VARIANT_FILL },
   { MENU_ENUM_LABEL_CONTENT_VIDEO_HISTORY_DIRECTORY, MENU_ENUM_LABEL_VALUE_CONTENT_VIDEO_HISTORY_DIRECTORY, TITLE_VARIANT_FILL },
   { MENU_ENUM_LABEL_RUNTIME_LOG_DIRECTORY, MENU_ENUM_LABEL_VALUE_RUNTIME_LOG_DIRECTORY, TITLE_VARIANT_FILL },
   { MENU_ENUM_LABEL_SCREENSHOT_DIRECTORY, MENU_ENUM_LABEL_VALUE_SCREENSHOT_DIRECTORY, TITLE_VARIANT_FILL },
   { MENU_ENUM_LABEL_VIDEO_SHADER_DIR, MENU_ENUM_LABEL_VALUE_VIDEO_SHADER_DIR, TITLE_VARIANT_FILL },
   { MENU_ENUM_LABEL_VIDEO_FILTER_DIR, MENU_ENUM_LABEL_VALUE_VIDEO_FILTER_DIR, TITLE_VARIANT_FILL },
   { MENU_ENUM_LABEL_AUDIO_FILTER_DIR, MENU_ENUM_LABEL_VALUE_AUDIO_FILTER_DIR, TITLE_VARIANT_FILL },
   { MENU_ENUM_LABEL_RECORDING_CONFIG_DIRECTORY, MENU_ENUM_LABEL_VALUE_RECORDING_CONFIG_DIRECTORY, TITLE_VARIANT_FILL },
   { MENU_ENUM_LABEL_RECORDING_OUTPUT_DIRECTORY, MENU_ENUM_LABEL_VALUE_RECORDING_OUTPUT_DIRECTORY, TITLE_VARIANT_FILL },
   { MENU_ENUM_LABEL_OSK_OVERLAY_DIRECTORY, MENU_ENUM_LABEL_VALUE_OSK_OVERLAY_DIRECTORY, TITLE_VARIANT_FILL },
   { MENU_ENUM_LABEL_INPUT_REMAPPING_DIRECTORY, MENU_ENUM_LABEL_VALUE_INPUT_REMAPPING_DIRECTORY, TITLE_VARIANT_FILL },
   { MENU_ENUM_LABEL_CONTENT_DATABASE_DIRECTORY, MENU_ENUM_LABEL_VALUE_CONTENT_DATABASE_DIRECTORY, TITLE_VARIANT_FILL },
   { MENU_ENUM_LABEL_SAVESTATE_DIRECTORY, MENU_ENUM_LABEL_VALUE_SAVESTATE_DIRECTORY, TITLE_VARIANT_FILL },
   { MENU_ENUM_LABEL_DYNAMIC_WALLPAPERS_DIRECTORY, MENU_ENUM_LABEL_VALUE_DYNAMIC_WALLPAPERS_DIRECTORY, TITLE_VARIANT_FILL },
   { MENU_ENUM_LABEL_CORE_ASSETS_DIRECTORY, MENU_ENUM_LABEL_VALUE_CORE_ASSETS_DIRECTORY, TITLE_VARIANT_FILL },
   { MENU_ENUM_LABEL_THUMBNAILS_DIRECTORY, MENU_ENUM_LABEL_VALUE_THUMBNAILS_DIRECTORY, TITLE_VARIANT_FILL },
   { MENU_ENUM_LABEL_RGUI_CONFIG_DIRECTORY, MENU_ENUM_LABEL_VALUE_RGUI_CONFIG_DIRECTORY, TITLE_VARIANT_FILL },
   { MENU_ENUM_LABEL_LOG_DIR, MENU_ENUM_LABEL_VALUE_LOG_DIR, TITLE_VARIANT_FILL },
   { MENU_ENUM_LABEL_LOAD_CONTENT_LIST, MENU_ENUM_LABEL_VALUE_LOAD_CONTENT_LIST, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_NETPLAY, MENU_ENUM_LABEL_VALUE_NETPLAY, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_INFORMATION_LIST, MENU_ENUM_LABEL_VALUE_INFORMATION_LIST, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_INFORMATION, MENU_ENUM_LABEL_VALUE_INFORMATION, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_SETTINGS, MENU_ENUM_LABEL_VALUE_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DATABASE_MANAGER_LIST, MENU_ENUM_LABEL_VALUE_DATABASE_MANAGER, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_CORE_LIST, MENU_ENUM_LABEL_VALUE_CORE_LIST, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_LOAD_CONTENT_SPECIAL, MENU_ENUM_LABEL_VALUE_LOAD_CONTENT_SPECIAL, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_HELP_LIST, MENU_ENUM_LABEL_VALUE_HELP_LIST, TITLE_VARIANT_COPY },
   { MENU_ENUM_LABEL_HELP, MENU_ENUM_LABEL_VALUE_HELP_LIST, TITLE_VARIANT_COPY },
   { MENU_ENUM_LABEL_INPUT_OVERLAY, MENU_ENUM_LABEL_VALUE_OVERLAY_PRESET, TITLE_VARIANT_FILL_SEARCH },
   { MENU_ENUM_LABEL_DEFERRED_CORE_UPDATER_LIST, MENU_ENUM_LABEL_VALUE_CORE_UPDATER_LIST, TITLE_VARIANT_SEARCH },
   { MENU_ENUM_LABEL_DEFERRED_CORE_MANAGER_LIST, MENU_ENUM_LABEL_VALUE_CORE_MANAGER_LIST, TITLE_VARIANT_SEARCH },
   { MENU_ENUM_LABEL_CONFIGURATIONS_LIST, MENU_ENUM_LABEL_VALUE_CONFIGURATIONS_LIST, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_ADD_CONTENT_LIST, MENU_ENUM_LABEL_VALUE_ADD_CONTENT_LIST, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_SAVESTATE_LIST, MENU_ENUM_LABEL_VALUE_SAVESTATE_LIST, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_STATE_SLOT_RUN, MENU_ENUM_LABEL_VALUE_LOAD_STATE, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_CORE_OPTION_OVERRIDE_LIST, MENU_ENUM_LABEL_VALUE_CORE_OPTION_OVERRIDE_LIST, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_CONTENT_SETTINGS, MENU_ENUM_LABEL_VALUE_CONTENT_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_CORE_INPUT_REMAPPING_OPTIONS, MENU_ENUM_LABEL_VALUE_CORE_INPUT_REMAPPING_OPTIONS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_REMAP_FILE_MANAGER_LIST, MENU_ENUM_LABEL_VALUE_REMAP_FILE_MANAGER_LIST, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_CORE_CHEAT_OPTIONS, MENU_ENUM_LABEL_VALUE_CORE_CHEAT_OPTIONS, TITLE_VARIANT_SEARCH },
   { MENU_ENUM_LABEL_SHADER_OPTIONS, MENU_ENUM_LABEL_VALUE_SHADER_OPTIONS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DISK_OPTIONS, MENU_ENUM_LABEL_VALUE_DISK_OPTIONS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_FRONTEND_COUNTERS, MENU_ENUM_LABEL_VALUE_FRONTEND_COUNTERS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_CORE_COUNTERS, MENU_ENUM_LABEL_VALUE_CORE_COUNTERS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_PL_THUMBNAILS_UPDATER_LIST, MENU_ENUM_LABEL_VALUE_PL_THUMBNAILS_UPDATER_LIST, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_INPUT_RETROPAD_BINDS_LIST, MENU_ENUM_LABEL_VALUE_INPUT_RETROPAD_BINDS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_INPUT_HOTKEY_BINDS_LIST, MENU_ENUM_LABEL_VALUE_INPUT_HOTKEY_BINDS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_VIDEO_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_VIDEO_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_INPUT_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_INPUT_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_PLAYLIST_SETTINGS_LIST, MENU_ENUM_LABEL_VALUE_PLAYLIST_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_PLAYLIST_MANAGER_LIST, MENU_ENUM_LABEL_VALUE_PLAYLIST_MANAGER_LIST, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_ACHIEVEMENT_LIST, MENU_ENUM_LABEL_VALUE_ACHIEVEMENT_LIST, TITLE_VARIANT_COPY },
   { MENU_ENUM_LABEL_VIDEO_SHADER_PARAMETERS, MENU_ENUM_LABEL_VALUE_VIDEO_SHADER_PARAMETERS, TITLE_VARIANT_COPY },
   { MENU_ENUM_LABEL_VIDEO_SHADER_PRESET_PARAMETERS, MENU_ENUM_LABEL_VALUE_VIDEO_SHADER_PRESET_PARAMETERS, TITLE_VARIANT_COPY },
   { MENU_ENUM_LABEL_VIDEO_SHADER_PRESET_MANAGER, MENU_ENUM_LABEL_VALUE_VIDEO_SHADER_PRESET_MANAGER, TITLE_VARIANT_COPY },
   { MENU_ENUM_LABEL_DISK_IMAGE_APPEND, MENU_ENUM_LABEL_VALUE_DISK_IMAGE_APPEND, TITLE_VARIANT_FILL },
   { MENU_ENUM_LABEL_VIDEO_SHADER_PRESET, MENU_ENUM_LABEL_VIDEO_SHADER_PRESET_TWO, TITLE_VARIANT_FILL_SEARCH },
   { MENU_ENUM_LABEL_VIDEO_SHADER_PRESET_PREPEND, MENU_ENUM_LABEL_VIDEO_SHADER_PRESET_PREPEND_TWO, TITLE_VARIANT_FILL_SEARCH },
   { MENU_ENUM_LABEL_VIDEO_SHADER_PRESET_APPEND, MENU_ENUM_LABEL_VIDEO_SHADER_PRESET_APPEND_TWO, TITLE_VARIANT_FILL_SEARCH },
   { MENU_ENUM_LABEL_CHEAT_FILE_LOAD, MENU_ENUM_LABEL_VALUE_CHEAT_FILE, TITLE_VARIANT_FILL_SEARCH },
   { MENU_ENUM_LABEL_CHEAT_FILE_LOAD_APPEND, MENU_ENUM_LABEL_VALUE_CHEAT_FILE_APPEND, TITLE_VARIANT_FILL_SEARCH },
   { MENU_ENUM_LABEL_REMAP_FILE_LOAD, MENU_ENUM_LABEL_VALUE_REMAP_FILE, TITLE_VARIANT_FILL },
   { MENU_ENUM_LABEL_OVERRIDE_FILE_LOAD, MENU_ENUM_LABEL_VALUE_OVERRIDE_FILE_LOAD, TITLE_VARIANT_FILL },
   { MENU_ENUM_LABEL_DEFERRED_ACCOUNTS_CHEEVOS_LIST, MENU_ENUM_LABEL_VALUE_ACCOUNTS_RETRO_ACHIEVEMENTS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_CORE_CONTENT_LIST, MENU_ENUM_LABEL_VALUE_DOWNLOAD_CORE_CONTENT, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_ACCOUNTS_LIST, MENU_ENUM_LABEL_VALUE_ACCOUNTS_LIST, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_VIDEO_FONT_PATH, MENU_ENUM_LABEL_VALUE_VIDEO_FONT_PATH, TITLE_VARIANT_FILL },
   { MENU_ENUM_LABEL_XMB_FONT, MENU_ENUM_LABEL_VALUE_XMB_FONT, TITLE_VARIANT_FILL },
   { MENU_ENUM_LABEL_OZONE_FONT, MENU_ENUM_LABEL_VALUE_OZONE_FONT, TITLE_VARIANT_FILL },
   { MENU_ENUM_LABEL_VIDEO_FILTER, MENU_ENUM_LABEL_VALUE_VIDEO_FILTER, TITLE_VARIANT_FILL },
   { MENU_ENUM_LABEL_AUDIO_DSP_PLUGIN, MENU_ENUM_LABEL_VALUE_AUDIO_DSP_PLUGIN, TITLE_VARIANT_FILL },
   { MENU_ENUM_LABEL_CHEAT_DATABASE_PATH, MENU_ENUM_LABEL_VALUE_CHEAT_DATABASE_PATH, TITLE_VARIANT_FILL },
   { MENU_ENUM_LABEL_LIBRETRO_DIR_PATH, MENU_ENUM_LABEL_VALUE_LIBRETRO_DIR_PATH, TITLE_VARIANT_FILL },
   { MENU_ENUM_LABEL_LIBRETRO_INFO_PATH, MENU_ENUM_LABEL_VALUE_LIBRETRO_INFO_PATH, TITLE_VARIANT_FILL },
   { MENU_ENUM_LABEL_SWITCH_CPU_PROFILE, MENU_ENUM_LABEL_VALUE_SWITCH_CPU_PROFILE, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_MANUAL_CONTENT_SCAN_LIST, MENU_ENUM_LABEL_VALUE_MANUAL_CONTENT_SCAN_LIST, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_SCAN_METHOD, MENU_ENUM_LABEL_VALUE_SCAN_METHOD, TITLE_VARIANT_FILL },
   { MENU_ENUM_LABEL_SCAN_USE_DB, MENU_ENUM_LABEL_VALUE_SCAN_USE_DB, TITLE_VARIANT_FILL },
   { MENU_ENUM_LABEL_SCAN_DB_SELECT, MENU_ENUM_LABEL_VALUE_SCAN_DB_SELECT, TITLE_VARIANT_FILL },
   { MENU_ENUM_LABEL_MANUAL_CONTENT_SCAN_DIR, MENU_ENUM_LABEL_VALUE_MANUAL_CONTENT_SCAN_DIR, TITLE_VARIANT_FILL },
   { MENU_ENUM_LABEL_DEFERRED_CORE_LIST, MENU_ENUM_LABEL_VALUE_SUPPORTED_CORES, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_CORE_LIST_SET, MENU_ENUM_LABEL_VALUE_SUPPORTED_CORES, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_VIDEO_SHADER_PRESET_MANAGER_LIST, MENU_ENUM_LABEL_VALUE_VIDEO_SHADER_PRESET_MANAGER, TITLE_VARIANT_COPY },
   { MENU_ENUM_LABEL_DEFERRED_DROPDOWN_BOX_LIST_RESOLUTION, MENU_ENUM_LABEL_VALUE_SCREEN_RESOLUTION, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_DROPDOWN_BOX_LIST_VIDEO_SHADER_PARAMETER, MENU_ENUM_LABEL_VALUE_VIDEO_SHADER_PARAMETERS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_DROPDOWN_BOX_LIST_VIDEO_SHADER_PRESET_PARAMETER, MENU_ENUM_LABEL_VALUE_VIDEO_SHADER_PARAMETERS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_DROPDOWN_BOX_LIST_VIDEO_SHADER_NUM_PASSES, MENU_ENUM_LABEL_VALUE_VIDEO_SHADER_NUM_PASSES, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_DROPDOWN_BOX_LIST_PLAYLIST_DEFAULT_CORE, MENU_ENUM_LABEL_VALUE_PLAYLIST_MANAGER_DEFAULT_CORE, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_DROPDOWN_BOX_LIST_PLAYLIST_LABEL_DISPLAY_MODE, MENU_ENUM_LABEL_VALUE_PLAYLIST_MANAGER_LABEL_DISPLAY_MODE, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_DROPDOWN_BOX_LIST_PLAYLIST_SORT_MODE, MENU_ENUM_LABEL_VALUE_PLAYLIST_MANAGER_SORT_MODE, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_DROPDOWN_BOX_LIST_SCAN_METHOD, MENU_ENUM_LABEL_VALUE_SCAN_METHOD, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_DROPDOWN_BOX_LIST_SCAN_USE_DB, MENU_ENUM_LABEL_VALUE_SCAN_USE_DB, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_DROPDOWN_BOX_LIST_SCAN_DB_SELECT, MENU_ENUM_LABEL_VALUE_SCAN_DB_SELECT, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_DROPDOWN_BOX_LIST_MANUAL_CONTENT_SCAN_SYSTEM_NAME, MENU_ENUM_LABEL_VALUE_MANUAL_CONTENT_SCAN_SYSTEM_NAME, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_DROPDOWN_BOX_LIST_MANUAL_CONTENT_SCAN_CORE_NAME, MENU_ENUM_LABEL_VALUE_MANUAL_CONTENT_SCAN_CORE_NAME, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_DROPDOWN_BOX_LIST_DISK_INDEX, MENU_ENUM_LABEL_VALUE_DISK_INDEX, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_DEFERRED_RPL_ENTRY_ACTIONS, MENU_ENUM_LABEL_VALUE_QUICK_MENU_VIEWS_SETTINGS, TITLE_VARIANT_PLAIN },
   { MENU_ENUM_LABEL_PLAYLISTS_TAB, MENU_ENUM_LABEL_VALUE_PLAYLISTS_TAB, TITLE_VARIANT_PLAIN },
};

static const title_enum_map_t *title_enum_lookup(const char *label)
{
   size_t i;
   for (i = 0; i < ARRAY_SIZE(title_enum_map); i++)
      if (string_is_equal(label, msg_hash_to_str(
                  (enum msg_hash_enums)title_enum_map[i].label)))
         return &title_enum_map[i];
   return NULL;
}

static int action_get_title_from_enum(
      const char *path, const char *label,
      unsigned menu_type, char *s, size_t len)
{
   const title_enum_map_t *e = title_enum_lookup(label);
   const char *title;
   if (!e)
      return 1;
   title = msg_hash_to_str((enum msg_hash_enums)e->title);
   switch (e->variant)
   {
      case TITLE_VARIANT_FILL:
      {
         size_t _len = 0;
         if (title && *title)
         {
            _len = strlcpy(s, title, len);
            if (_len >= len)
               _len = len - 1;
         }
         if (path && *path && _len + STRLEN_CONST(": ") < len)
         {
            memcpy(s + _len, ": ", STRLEN_CONST(": "));
            _len += STRLEN_CONST(": ");
            strlcpy(s + _len, path, len - _len);
         }
         return 1;
      }
      case TITLE_VARIANT_COPY:
         strlcpy(s, title, len);
         return 1;
      case TITLE_VARIANT_SEARCH:
         action_get_title_fill_search_filter_default(
               (enum msg_hash_enums)e->title, s, len);
         return 0;
      case TITLE_VARIANT_FILL_SEARCH:
         action_get_title_fill_path_search_filter_default(
               path, (enum msg_hash_enums)e->title, s, len);
         return 0;
      case TITLE_VARIANT_PLAIN:
      default:
         if (s && title && (*title != '\0'))
            sanitize_to_string(s, title, len);
         return 1;
   }
}

static int action_get_title_remap_port(
      const char *path, const char *label,
      unsigned menu_type, char *s, size_t len)
{
   size_t i;
   if (!path)
      return 0;
   snprintf(s, len,
         msg_hash_to_str(MENU_ENUM_LABEL_VALUE_INPUT_USER_BINDS),
         atoi(path) + 1);
   for (i = 0; s[i] != '\0'; i++)
   {
      if (s[i] == '_')
         s[i] = ' ';
   }
   return 1;
}

static int action_get_title_icon_thumbnails(
      const char *path, const char *label, unsigned menu_type,
      char *s, size_t len)
{
   enum msg_hash_enums label_value = MENU_ENUM_LABEL_VALUE_ICON_THUMBNAILS;
   const char *title               = msg_hash_to_str(label_value);
   if (s && title && *title != '\0')
   {
      sanitize_to_string(s, title, len);
      return 1;
   }
   return 0;
}

static int action_get_title_thumbnails(
      const char *path, const char *label, unsigned menu_type,
      char *s, size_t len)
{
   const char *title               = NULL;
   enum msg_hash_enums label_value = MENU_ENUM_LABEL_VALUE_THUMBNAILS;
#ifdef HAVE_MENU
   const char *menu_ident          = menu_driver_ident();
   /* Get label value */
#ifdef HAVE_RGUI
   if (string_is_equal(menu_ident, "rgui"))
      label_value = MENU_ENUM_LABEL_VALUE_THUMBNAILS_RGUI;
   else
#endif
#ifdef HAVE_MATERIALUI
   if (string_is_equal(menu_ident, "glui"))
      label_value = MENU_ENUM_LABEL_VALUE_THUMBNAILS_MATERIALUI;
#endif
#endif
   title = msg_hash_to_str(label_value);
   if (s && title && *title)
   {
      sanitize_to_string(s, title, len);
      return 1;
   }
   return 0;
}

static int action_get_title_left_thumbnails(
      const char *path, const char *label, unsigned menu_type,
      char *s, size_t len)
{
   const char *title               = NULL;
   enum msg_hash_enums label_value = MENU_ENUM_LABEL_VALUE_LEFT_THUMBNAILS;
#if defined(HAVE_RGUI) || defined(HAVE_OZONE) || defined(HAVE_MATERIALUI)
   const char *menu_ident          = menu_driver_ident();
   /* Get label value */
#ifdef HAVE_RGUI
   if (string_is_equal(menu_ident, "rgui"))
      label_value = MENU_ENUM_LABEL_VALUE_LEFT_THUMBNAILS_RGUI;
   else
#endif
#ifdef HAVE_OZONE
   if (string_is_equal(menu_ident, "ozone"))
      label_value = MENU_ENUM_LABEL_VALUE_LEFT_THUMBNAILS_OZONE;
   else
#endif
#ifdef HAVE_MATERIALUI
   if (string_is_equal(menu_ident, "glui"))
      label_value = MENU_ENUM_LABEL_VALUE_LEFT_THUMBNAILS_MATERIALUI;
#endif
#endif

   title = msg_hash_to_str(label_value);

   if (s && title && *title)
   {
      sanitize_to_string(s, title, len);
      return 1;
   }

   return 0;
}

static int action_get_title_core_options_list(
      const char *path, const char *label, unsigned menu_type,
      char *s, size_t len)
{
   const char *category = path;
   const char *title    = NULL;

   /* If this is an options subcategory, fetch
    * the category description */
   if (category && *category)
   {
      core_option_manager_t *coreopts = NULL;

      if (retroarch_ctl(RARCH_CTL_CORE_OPTIONS_LIST_GET, &coreopts))
         title = core_option_manager_get_category_desc(
               coreopts, category);
   }

   /* If this isn't a subcategory (or something
    * went wrong...), use top level core options
    * menu label */
   if (!title || !*title)
      title = msg_hash_to_str(MENU_ENUM_LABEL_VALUE_CORE_OPTIONS);

   if (s && title && *title)
   {
      strlcpy(s, title, len);
      return 1;
   }

   return 0;
}

static int action_get_title_dropdown_item(
      const char *path, const char *label, unsigned menu_type,
      char *s, size_t len)
{
   if (!path || !*path)
      return 0;

   if (string_starts_with_size(path, "core_option_", STRLEN_CONST("core_option_")))
   {
      core_option_manager_t *coreopts = NULL;
      const char *opt = strrchr(path, '_');
      if (opt && opt[1] != '\0')
      {
         retroarch_ctl(RARCH_CTL_CORE_OPTIONS_LIST_GET, &coreopts);

         if (coreopts)
         {
            unsigned option_index = string_to_unsigned(opt + 1);
            const char *title     = core_option_manager_get_desc(
                  coreopts, option_index, true);

            if (s && title && *title)
            {
               strlcpy(s, title, len);
               return 1;
            }
         }
      }
   }
   else
   {
      enum msg_hash_enums enum_idx = (enum msg_hash_enums)
         (string_to_unsigned(path) + 2);

      if ((enum_idx > MSG_UNKNOWN) && (enum_idx < MSG_LAST))
      {
         switch (enum_idx)
         {
            case MENU_ENUM_LABEL_VALUE_THUMBNAILS:
               return action_get_title_thumbnails(
                     path, label, menu_type, s, len);
            case MENU_ENUM_LABEL_VALUE_LEFT_THUMBNAILS:
               return action_get_title_left_thumbnails(
                     path, label, menu_type, s, len);
            default:
               if ((enum_idx >= MENU_ENUM_LABEL_INPUT_LIBRETRO_DEVICE) &&
                     (enum_idx <= MENU_ENUM_LABEL_INPUT_LIBRETRO_DEVICE_LAST))
                  enum_idx = MENU_ENUM_LABEL_VALUE_INPUT_DEVICE_TYPE;
               else if ((enum_idx >= MENU_ENUM_LABEL_INPUT_PLAYER_ANALOG_DPAD_MODE) &&
                     (enum_idx <= MENU_ENUM_LABEL_INPUT_PLAYER_ANALOG_DPAD_MODE_LAST))
                  enum_idx = MENU_ENUM_LABEL_VALUE_INPUT_ADC_TYPE;
               else if ((enum_idx >= MENU_ENUM_LABEL_INPUT_DEVICE_INDEX) &&
                     (enum_idx <= MENU_ENUM_LABEL_INPUT_DEVICE_INDEX_LAST))
                  enum_idx = MENU_ENUM_LABEL_VALUE_INPUT_DEVICE_INDEX;
               else if ((enum_idx >= MENU_ENUM_LABEL_INPUT_DEVICE_RESERVATION_TYPE) &&
                     (enum_idx <= MENU_ENUM_LABEL_INPUT_DEVICE_RESERVATION_TYPE_LAST))
                  enum_idx = MENU_ENUM_LABEL_VALUE_INPUT_DEVICE_RESERVATION_TYPE;
               else if ((enum_idx >= MENU_ENUM_LABEL_INPUT_DEVICE_RESERVED_DEVICE_NAME) &&
                     (enum_idx <= MENU_ENUM_LABEL_INPUT_DEVICE_RESERVED_DEVICE_NAME_LAST))
                  enum_idx = MENU_ENUM_LABEL_VALUE_INPUT_DEVICE_RESERVED_DEVICE_NAME;
               else if ((enum_idx >= MENU_ENUM_LABEL_INPUT_MOUSE_INDEX) &&
                     (enum_idx <= MENU_ENUM_LABEL_INPUT_MOUSE_INDEX_LAST))
                  enum_idx = MENU_ENUM_LABEL_VALUE_INPUT_MOUSE_INDEX;
               else if ((enum_idx >= MENU_ENUM_LABEL_INPUT_REMAP_PORT) &&
                     (enum_idx <= MENU_ENUM_LABEL_INPUT_REMAP_PORT_LAST))
                  enum_idx = MENU_ENUM_LABEL_VALUE_INPUT_REMAP_PORT;

               {
                  const char *title = msg_hash_to_str(enum_idx);
                  if (s && title && *title)
                  {
                     sanitize_to_string(s, title, len);
                     return 1;
                  }
               }
               break;
         }
      }
   }

   return 0;
}

#ifdef HAVE_AUDIOMIXER
static int action_get_title_mixer_stream_actions(const char *path, const char *label, unsigned menu_type, char *s, size_t len)
{
   unsigned offset = (menu_type - MENU_SETTINGS_AUDIO_MIXER_STREAM_ACTIONS_BEGIN);
   snprintf(s, len , msg_hash_to_str(MENU_ENUM_LABEL_MIXER_STREAM), offset + 1, audio_driver_mixer_get_stream_name(offset));
   return 0;
}
#endif

static int action_get_title_deferred_playlist_list(const char *path, const char *label, unsigned menu_type, char *s, size_t len)
{
   if (path && *path)
   {
      const char *playlist_file = path_basename_nocompression(path);

      if (playlist_file && *playlist_file)
      {
         if (string_is_equal_noncase(path_get_extension(playlist_file),
                  "lpl"))
         {
            if (string_is_equal(playlist_file, FILE_PATH_CONTENT_HISTORY))
               strlcpy(s, msg_hash_to_str(MENU_ENUM_LABEL_VALUE_HISTORY_TAB), len);
            else if (string_is_equal(playlist_file, FILE_PATH_CONTENT_FAVORITES))
               strlcpy(s, msg_hash_to_str(MENU_ENUM_LABEL_VALUE_FAVORITES_TAB), len);
            else if (string_is_equal(playlist_file, FILE_PATH_CONTENT_IMAGE_HISTORY))
               strlcpy(s, msg_hash_to_str(MENU_ENUM_LABEL_VALUE_IMAGES_TAB), len);
            else if (string_is_equal(playlist_file, FILE_PATH_CONTENT_MUSIC_HISTORY))
               strlcpy(s, msg_hash_to_str(MENU_ENUM_LABEL_VALUE_MUSIC_TAB), len);
            else if (string_is_equal(playlist_file, FILE_PATH_CONTENT_VIDEO_HISTORY))
               strlcpy(s, msg_hash_to_str(MENU_ENUM_LABEL_VALUE_VIDEO_TAB), len);
            else
               fill_pathname(s, playlist_file, "", len);
         }
         /* This should never happen, but if it does just set
          * the label to the file name (it's better than nothing...) */
         else
            strlcpy(s, playlist_file, len);

         /* Add current search terms */
         menu_entries_search_append_terms_string(s, len);
      }
   }

   return 0;
}

static int action_get_title_deferred_core_backup_list(
      const char *core_path, const char *prefix, char *s, size_t len)
{
   size_t _len;
   core_info_t *core_info = NULL;

   if (!core_path || !*core_path || !prefix || !*prefix)
      return 0;

   _len = strlcpy(s, prefix, len);

   if (_len + 2 < len)
   {
      s[_len]     = ':';
      s[_len + 1] = ' ';
      _len       += 2;
      s[_len]     = '\0';
   }

   if (   core_info_find(core_path, &core_info)
       && core_info->display_name)
      strlcpy(s + _len, core_info->display_name, len - _len);
   else
   {
      const char *core_filename = path_basename_nocompression(core_path);
      if (core_filename && *core_filename)
         strlcpy(s + _len, core_filename, len - _len);
   }

   return 1;
}

static int action_get_title_deferred_core_restore_backup_list(
      const char *path, const char *label, unsigned menu_type, char *s, size_t len)
{
   return action_get_title_deferred_core_backup_list(path,
         msg_hash_to_str(MENU_ENUM_LABEL_VALUE_CORE_RESTORE_BACKUP_LIST),
         s, len);
}

static int action_get_title_deferred_core_delete_backup_list(
      const char *path, const char *label, unsigned menu_type, char *s, size_t len)
{
   return action_get_title_deferred_core_backup_list(path,
         msg_hash_to_str(MENU_ENUM_LABEL_VALUE_CORE_DELETE_BACKUP_LIST),
         s, len);
}

static int action_get_core_information_list(
      const char *path, const char *label, unsigned menu_type, char *s, size_t len)
{
   core_info_t *core_info = NULL;

   /* Check whether we are parsing information for a
    * core updater/manager entry or the currently loaded core */
   if (   (menu_type == FILE_TYPE_DOWNLOAD_CORE)
       || (menu_type == MENU_SETTING_ACTION_CORE_MANAGER_OPTIONS))
   {
      core_info_t *core_info_menu = NULL;

      if (!path || !*path)
         goto error;

      /* Core updater/manager entry - search for
       * corresponding core info */
      if (core_info_find(path, &core_info_menu))
         core_info = core_info_menu;
   }
   else
      core_info_get_current_core(&core_info);

   if (!core_info || !core_info->display_name || !*core_info->display_name)
      goto error;

   /* Copy display name */
   strlcpy(s, core_info->display_name, len);
   return 1;

error:
   /* An unknown error has occurred - just set the
    * title to the legacy 'Core Information' string */
   strlcpy(s, msg_hash_to_str(MENU_ENUM_LABEL_VALUE_CORE_INFORMATION), len);
   return 0;
}

#ifdef HAVE_MIST
static int action_get_core_information_steam_list(
      const char *path, const char *label, unsigned menu_type,
      char *s, size_t len)
{
   const char *info = msg_hash_to_str(MENU_ENUM_LABEL_VALUE_CORE_INFORMATION);
   size_t info_len  = strlen(info);

   if (info_len + 3 < len)
   {
      memcpy(s, info, info_len);
      memcpy(s + info_len, " - ", 3);
      strlcpy(s + info_len + 3, path, len - info_len - 3);
   }
   else
      strlcpy(s, info, len);

   return 1;
}
#endif

static int action_get_title_dropdown_input_description_common(
      const char *input_name, unsigned port, char *s, size_t len)
{
   size_t _len;
   const char *input_label_ptr = input_name;

   if (input_label_ptr && *input_label_ptr)
   {
      /* Strip off 'Auto:' prefix, if required */
      if (string_starts_with_size(input_label_ptr, "Auto:",
            STRLEN_CONST("Auto:")))
         input_label_ptr += STRLEN_CONST("Auto:");

      /* Skip leading whitespace in-place */
      while (*input_label_ptr == ' ')
         input_label_ptr++;
   }

   /* Build title string */
   _len  = strlcpy(s, msg_hash_to_str(MENU_ENUM_LABEL_VALUE_PORT), len);
   _len += snprintf(s + _len, len - _len, " %u - ", port + 1);
   if (input_label_ptr && *input_label_ptr)
      strlcpy(s + _len, input_label_ptr, len - _len);
   else
      strlcpy(s + _len, msg_hash_to_str(MENU_ENUM_LABEL_VALUE_NOT_AVAILABLE),
              len - _len);
   return 1;
}

static int action_get_title_dropdown_input_description(
      const char *path, const char *label, unsigned menu_type, char *s, size_t len)
{
   unsigned port = (menu_type - MENU_SETTINGS_INPUT_DESC_BEGIN) /
         (RARCH_FIRST_CUSTOM_BIND + 8);

   return action_get_title_dropdown_input_description_common(
      path, port, s, len);
}

static int action_get_title_dropdown_input_description_kbd(
      const char *path, const char *label, unsigned menu_type, char *s, size_t len)
{
   unsigned port = (menu_type - MENU_SETTINGS_INPUT_DESC_KBD_BEGIN) /
         RARCH_FIRST_CUSTOM_BIND;

   return action_get_title_dropdown_input_description_common(
      path, port, s, len);
}

#ifdef HAVE_CHEEVOS
static int action_get_title_achievement_pause_menu(
      const char* path, const char* label, unsigned menu_type, char* s, size_t len)
{
   if (rcheevos_hardcore_active())
      strlcpy(s, msg_hash_to_str(MENU_ENUM_LABEL_VALUE_ACHIEVEMENT_PAUSE), len);
   else
      strlcpy(s, msg_hash_to_str(MENU_ENUM_LABEL_VALUE_ACHIEVEMENT_RESUME), len);
   return 1;
}
#endif

DEFAULT_TITLE_MACRO(action_get_disk_options_list,               MENU_ENUM_LABEL_VALUE_DISK_OPTIONS)



#ifdef HAVE_LAKKA
DEFAULT_TITLE_MACRO(action_get_eject_disc,                      MENU_ENUM_LABEL_VALUE_EJECT_DISC)
#endif
#ifdef _3DS
DEFAULT_TITLE_MACRO(action_get_menu_bottom_settings_list,       MENU_ENUM_LABEL_VALUE_MENU_BOTTOM_SETTINGS)
#endif
#ifdef HAVE_LAKKA
DEFAULT_TITLE_MACRO(action_get_lakka_services_list,             MENU_ENUM_LABEL_VALUE_LAKKA_SERVICES)
#endif
#ifdef HAVE_LAKKA_SWITCH
DEFAULT_TITLE_MACRO(action_get_lakka_switch_options_list,       MENU_ENUM_LABEL_VALUE_LAKKA_SWITCH_OPTIONS)
#endif

#ifdef HAVE_MICROPHONE
DEFAULT_TITLE_MACRO(action_get_microphone_settings_list,            MENU_ENUM_LABEL_VALUE_MICROPHONE_SETTINGS)
#endif
#ifdef HAVE_AUDIOMIXER
DEFAULT_TITLE_MACRO(action_get_audio_mixer_settings_list,           MENU_ENUM_LABEL_VALUE_AUDIO_MIXER_SETTINGS)
#endif

DEFAULT_FILL_TITLE_MACRO(action_get_title_menu,                   MENU_ENUM_LABEL_VALUE_MENU_SETTINGS)

DEFAULT_TITLE_COPY_MACRO(action_get_title_input_settings,         MENU_ENUM_LABEL_VALUE_INPUT_SETTINGS)

#if defined(HAVE_LIBNX)
DEFAULT_TITLE_MACRO(action_get_title_switch_cpu_profile,          MENU_ENUM_LABEL_VALUE_SWITCH_CPU_PROFILE)
#endif


#ifdef HAVE_MIST
DEFAULT_TITLE_SEARCH_FILTER_MACRO(action_get_steam_settings_list,           MENU_ENUM_LABEL_VALUE_STEAM_SETTINGS)
DEFAULT_TITLE_SEARCH_FILTER_MACRO(action_get_core_manager_steam_list,       MENU_ENUM_LABEL_VALUE_CORE_MANAGER_STEAM_LIST)
#endif


#ifdef HAVE_GAME_AI
DEFAULT_TITLE_SEARCH_FILTER_MACRO(action_get_core_game_ai_options_list,       MENU_ENUM_LABEL_VALUE_CORE_GAME_AI_OPTIONS)
#endif

#ifdef HAVE_SMBCLIENT
DEFAULT_TITLE_MACRO(action_get_smb_client_settings_list,                      MENU_ENUM_LABEL_VALUE_SMB_CLIENT_SETTINGS)
#endif

static int action_get_title_deferred_database_manager_list(
      const char *path, const char *label,
      unsigned menu_type, char *s, size_t len)
{
   if (path && *path != '\0')
   {
      fill_pathname(s, path_basename(path), "", len);
      return 0;
   }
   strlcpy(s, msg_hash_to_str(MENU_ENUM_LABEL_VALUE_NOT_AVAILABLE), len);
   return 0;
}

static int action_get_sideload_core_list(const char *path, const char *label,
      unsigned menu_type, char *s, size_t len)
{
   const char *str = msg_hash_to_str(MENU_ENUM_LABEL_VALUE_SIDELOAD_CORE_LIST);
   size_t str_len  = strlen(str);

   if (str_len + 1 < len)
   {
      size_t _len;
      memcpy(s, str, str_len);
      s[str_len] = ' ';
      _len       = str_len + 1;

      if (path && *path)
      {
         size_t path_len = strlen(path);
         if (_len + path_len >= len)
            path_len = len - _len - 1;
         memcpy(s + _len, path, path_len);
         _len += path_len;
      }

      s[_len] = '\0';
   }
   else
      strlcpy(s, str, len);

   return 0;
}

static int action_get_title_default(const char *path, const char *label,
      unsigned menu_type, char *s, size_t len)
{
   size_t _len = strlcpy(s,
         msg_hash_to_str(MENU_ENUM_LABEL_VALUE_SELECT_FILE), len);
   if (_len >= len)
      _len = len - 1;
   if (path && *path)
   {
      if (_len + STRLEN_CONST(": ") < len)
      {
         s[_len]     = ':';
         s[_len + 1] = ' ';
         _len       += 2;
         s[_len]     = '\0';
      }
#if IOS
      fill_pathname_abbreviate_special(s + _len, path, len - _len);
#else
      strlcpy(s + _len, path, len - _len);
#endif
   }
   menu_entries_search_append_terms_string(s, len);
   return 0;
}

static int action_get_title_group_settings(const char *path, const char *label,
      unsigned menu_type, char *s, size_t len)
{
   unsigned i;
   typedef struct title_info_list
   {
      enum msg_hash_enums type;
      enum msg_hash_enums val;
      bool is_playlist_tab;
   } title_info_list_t;
   /* Note: MENU_ENUM_LABEL_HORIZONTAL_MENU *is* a playlist
    * tab, but its actual title is set elsewhere - so treat
    * it as a generic top-level item */
   static const title_info_list_t info_list[] = {
      {MENU_ENUM_LABEL_MAIN_MENU,             MENU_ENUM_LABEL_VALUE_MAIN_MENU,             false },
      {MENU_ENUM_LABEL_HISTORY_TAB,           MENU_ENUM_LABEL_VALUE_HISTORY_TAB,           true  },
      {MENU_ENUM_LABEL_FAVORITES_TAB,         MENU_ENUM_LABEL_VALUE_FAVORITES_TAB,         true  },
      {MENU_ENUM_LABEL_IMAGES_TAB,            MENU_ENUM_LABEL_VALUE_IMAGES_TAB,            true  },
      {MENU_ENUM_LABEL_MUSIC_TAB,             MENU_ENUM_LABEL_VALUE_MUSIC_TAB,             true  },
      {MENU_ENUM_LABEL_VIDEO_TAB,             MENU_ENUM_LABEL_VALUE_VIDEO_TAB,             true  },
      {MENU_ENUM_LABEL_SETTINGS_TAB,          MENU_ENUM_LABEL_VALUE_SETTINGS_TAB,          false },
      {MENU_ENUM_LABEL_PLAYLISTS_TAB,         MENU_ENUM_LABEL_VALUE_PLAYLISTS_TAB,         false },
      {MENU_ENUM_LABEL_ADD_TAB,               MENU_ENUM_LABEL_VALUE_ADD_TAB,               false },
      {MENU_ENUM_LABEL_EXPLORE_TAB,           MENU_ENUM_LABEL_VALUE_EXPLORE_TAB,           false },
      {MENU_ENUM_LABEL_CONTENTLESS_CORES_TAB, MENU_ENUM_LABEL_VALUE_CONTENTLESS_CORES_TAB, false },
      {MENU_ENUM_LABEL_NETPLAY_TAB,           MENU_ENUM_LABEL_VALUE_NETPLAY_TAB,           false },
      {MENU_ENUM_LABEL_HORIZONTAL_MENU,       MENU_ENUM_LABEL_VALUE_HORIZONTAL_MENU,       false },
   };
   for (i = 0; i < ARRAY_SIZE(info_list); i++)
   {
      if (string_is_equal(label, msg_hash_to_str(info_list[i].type)))
      {
         if (info_list[i].is_playlist_tab)
            action_get_title_fill_search_filter_default(
                  info_list[i].val, s, len);
         else
         {
            strlcpy(s, msg_hash_to_str(info_list[i].val), len);
            if (info_list[i].type == MENU_ENUM_LABEL_SETTINGS_TAB)
               menu_entries_search_append_terms_string(s, len);
         }
         return 0;
      }
   }
   /* Split label on '|' without heap allocation */
   if (label && *label)
   {
      const char *sep = strchr(label, '|');
      if (sep)
      {
         size_t first_len = (size_t)(sep - label);
         size_t _len;
         if (first_len >= len)
            first_len = len - 1;
         memcpy(s, label, first_len);
         s[first_len] = '\0';
         _len = first_len;
         if (sep[1] != '\0')
         {
            if (_len + STRLEN_CONST(" - ") < len)
            {
               memcpy(s + _len, " - ", STRLEN_CONST(" - "));
               _len        += STRLEN_CONST(" - ");
               s[_len]      = '\0';
            }
            strlcpy(s + _len, sep + 1, len - _len);
         }
      }
      else
         strlcpy(s, label, len);
   }
   return 0;
}

static int action_get_title_input_binds_list(
      const char *path, const char *label,
      unsigned menu_type, char *s, size_t len)
{
   unsigned val;
   if (!path || !*path)
      return 0;
   val = (((unsigned)path[0]) - 49) + 1;
   snprintf(s, len, msg_hash_to_str(MENU_ENUM_LABEL_VALUE_INPUT_USER_BINDS), val);
   return 0;
}

static int menu_cbs_init_bind_title_compare_label(menu_file_list_cbs_t *cbs,
      const char *label)
{
   unsigned i;
   typedef struct title_info_list
   {
      enum msg_hash_enums type;
      int (*cb)(const char *path, const char *label,
            unsigned type, char *s, size_t len);
   } title_info_list_t;

   static const title_info_list_t info_list[] = {
      {MENU_ENUM_LABEL_DEFERRED_REMAPPINGS_PORT_LIST,                 action_get_title_remap_port},
      {MENU_ENUM_LABEL_DEFERRED_CORE_INFORMATION_LIST,                action_get_core_information_list},
#ifdef HAVE_MIST
      {MENU_ENUM_LABEL_DEFERRED_CORE_INFORMATION_STEAM_LIST,          action_get_core_information_steam_list},
#endif
      {MENU_ENUM_LABEL_DEFERRED_CORE_RESTORE_BACKUP_LIST,             action_get_title_deferred_core_restore_backup_list},
      {MENU_ENUM_LABEL_DEFERRED_CORE_DELETE_BACKUP_LIST,              action_get_title_deferred_core_delete_backup_list},
#ifdef HAVE_LAKKA
      {MENU_ENUM_LABEL_DEFERRED_EJECT_DISC,                           action_get_eject_disc},
#endif
#ifdef _3DS
      {MENU_ENUM_LABEL_DEFERRED_MENU_BOTTOM_SETTINGS_LIST,            action_get_menu_bottom_settings_list},
#endif
#ifdef HAVE_SMBCLIENT
      {MENU_ENUM_LABEL_DEFERRED_SMB_CLIENT_SETTINGS_LIST,             action_get_smb_client_settings_list},
#endif
#ifdef HAVE_LAKKA
      {MENU_ENUM_LABEL_DEFERRED_LAKKA_SERVICES_LIST,                  action_get_lakka_services_list},
#endif
#ifdef HAVE_LAKKA_SWITCH
      {MENU_ENUM_LABEL_DEFERRED_LAKKA_SWITCH_OPTIONS_LIST,            action_get_lakka_switch_options_list},
#endif
#ifdef HAVE_MICROPHONE
      {MENU_ENUM_LABEL_DEFERRED_MICROPHONE_SETTINGS_LIST,             action_get_microphone_settings_list},
#endif
#ifdef HAVE_AUDIOMIXER
      {MENU_ENUM_LABEL_DEFERRED_AUDIO_MIXER_SETTINGS_LIST,            action_get_audio_mixer_settings_list},
#endif
      {MENU_ENUM_LABEL_SIDELOAD_CORE_LIST,                            action_get_sideload_core_list},
      {MENU_ENUM_LABEL_DEFERRED_DATABASE_MANAGER_LIST,                action_get_title_deferred_database_manager_list},
#ifdef HAVE_MIST
      {MENU_ENUM_LABEL_DEFERRED_STEAM_SETTINGS_LIST,
         action_get_steam_settings_list},
      {MENU_ENUM_LABEL_DEFERRED_CORE_MANAGER_STEAM_LIST,
         action_get_core_manager_steam_list},
#endif
      {MENU_ENUM_LABEL_CORE_OPTIONS,
         action_get_title_core_options_list},
      {MENU_ENUM_LABEL_DEFERRED_USER_BINDS_LIST,
         action_get_title_input_binds_list},
#ifdef HAVE_CHEEVOS
      {MENU_ENUM_LABEL_ACHIEVEMENT_PAUSE_MENU,
         action_get_title_achievement_pause_menu},
#endif
#if defined(HAVE_LIBNX)
#endif
#if defined(HAVE_GAME_AI)
      {MENU_ENUM_LABEL_CORE_GAME_AI_OPTIONS,
         action_get_core_game_ai_options_list},
#endif
#ifdef HAVE_SMBCLIENT
      {MENU_ENUM_LABEL_SMB_CLIENT_SETTINGS,
         action_get_smb_client_settings_list},
#endif
   };

   if (cbs->setting)
   {
      if (cbs->setting->free_flags & SD_FREE_FLAG_MAIN_MENU_GROUP)
      {
         BIND_ACTION_GET_TITLE(cbs, action_get_title_group_settings);
         return 0;
      }
   }

   for (i = 0; i < ARRAY_SIZE(info_list); i++)
   {
      if (string_is_equal(label, msg_hash_to_str(info_list[i].type)))
      {
         BIND_ACTION_GET_TITLE(cbs, info_list[i].cb);
         return 0;
      }
   }

   /* MENU_ENUM_LABEL_DEFERRED_RDB_ENTRY_DETAIL requires special
    * treatment, since the label has the format:
    *   <MENU_ENUM_LABEL_DEFERRED_RDB_ENTRY_DETAIL>|<entry_name>
    * i.e. cannot use a normal string_is_equal() */
   if (string_starts_with(label,
      MENU_ENUM_LABEL_DEFERRED_RDB_ENTRY_DETAIL_STR))
   {
      BIND_ACTION_GET_TITLE(cbs, action_get_title_deferred_database_manager_list);
      return 0;
   }

   return -1;
}

static int menu_cbs_init_bind_title_compare_type(menu_file_list_cbs_t *cbs,
      unsigned type)
{
   switch (type)
   {
      case MENU_SETTINGS:
         BIND_ACTION_GET_TITLE(cbs, action_get_title_menu);
         break;
      case MENU_SETTINGS_CUSTOM_BIND:
      case MENU_SETTINGS_CUSTOM_BIND_KEYBOARD:
         BIND_ACTION_GET_TITLE(cbs, action_get_title_input_settings);
         break;
      case MENU_SETTING_ACTION_CORE_DISK_OPTIONS:
         BIND_ACTION_GET_TITLE(cbs, action_get_disk_options_list);
         break;
      default:
         return -1;
   }

   return 0;
}

int menu_cbs_init_bind_title(menu_file_list_cbs_t *cbs,
      const char *path, const char *label, unsigned type, size_t idx)
{
   unsigned i;
   typedef struct title_info_list
   {
      enum msg_hash_enums type;
      int (*cb)(const char *path, const char *label,
            unsigned type, char *s, size_t len);
   } title_info_list_t;

   static const title_info_list_t info_list[] = {
#ifdef HAVE_AUDIOMIXER
      {MENU_ENUM_LABEL_DEFERRED_MIXER_STREAM_SETTINGS_LIST,                                 action_get_title_mixer_stream_actions},
#endif
      {MENU_ENUM_LABEL_DEFERRED_DROPDOWN_BOX_LIST,                                          action_get_title_dropdown_item},
      {MENU_ENUM_LABEL_DEFERRED_DROPDOWN_BOX_LIST_SPECIAL,                                  action_get_title_dropdown_item},
      {MENU_ENUM_LABEL_DEFERRED_DROPDOWN_BOX_LIST_AUDIO_DEVICE,                             action_get_title_dropdown_item},
      {MENU_ENUM_LABEL_DEFERRED_DROPDOWN_BOX_LIST_MIDI_DEVICE,                              action_get_title_dropdown_item},
#ifdef HAVE_MICROPHONE
      {MENU_ENUM_LABEL_DEFERRED_DROPDOWN_BOX_LIST_MICROPHONE_DEVICE,                        action_get_title_dropdown_item},
#endif
      {MENU_ENUM_LABEL_DEFERRED_DROPDOWN_BOX_LIST_PLAYLIST_RIGHT_THUMBNAIL_MODE,            action_get_title_thumbnails},
      {MENU_ENUM_LABEL_DEFERRED_DROPDOWN_BOX_LIST_PLAYLIST_LEFT_THUMBNAIL_MODE,             action_get_title_left_thumbnails},
      {MENU_ENUM_LABEL_DEFERRED_DROPDOWN_BOX_LIST_PLAYLIST_ICON_THUMBNAIL_MODE,             action_get_title_icon_thumbnails},
      {MENU_ENUM_LABEL_DEFERRED_DROPDOWN_BOX_LIST_INPUT_RETROPAD_BIND,                      action_get_title_dropdown_item},
      {MENU_ENUM_LABEL_DEFERRED_DROPDOWN_BOX_LIST_INPUT_DEVICE_TYPE,                        action_get_title_dropdown_item},
      {MENU_ENUM_LABEL_DEFERRED_DROPDOWN_BOX_LIST_INPUT_DESCRIPTION,                        action_get_title_dropdown_input_description},
      {MENU_ENUM_LABEL_DEFERRED_DROPDOWN_BOX_LIST_INPUT_DESCRIPTION_KBD,                    action_get_title_dropdown_input_description_kbd},
      {MENU_ENUM_LABEL_DEFERRED_DROPDOWN_BOX_LIST_INPUT_SELECT_RESERVED_DEVICE,             action_get_title_dropdown_item},
#ifdef ANDROID
      {MENU_ENUM_LABEL_DEFERRED_DROPDOWN_BOX_LIST_INPUT_SELECT_PHYSICAL_KEYBOARD,           action_get_title_dropdown_item},
#endif
#ifdef HAVE_NETWORKING
      {MENU_ENUM_LABEL_DEFERRED_DROPDOWN_BOX_LIST_NETPLAY_MITM_SERVER,                      action_get_title_dropdown_item},
#endif
      {MENU_ENUM_LABEL_DEFERRED_PLAYLIST_LIST,                                              action_get_title_deferred_playlist_list},
      {MENU_ENUM_LABEL_DEFERRED_PLAYLIST_MANAGER_SETTINGS,                                  action_get_title_deferred_playlist_list},
   };

   if (!cbs)
      return -1;

   BIND_ACTION_GET_TITLE(cbs, action_get_title_default);

   /* Data-driven titles: labels whose title is a plain lookup are
    * carried in title_enum_map and share one handler, replacing the
    * generated per-label functions. */
   if (title_enum_lookup(label))
   {
      BIND_ACTION_GET_TITLE(cbs, action_get_title_from_enum);
      return 0;
   }

   if (cbs->enum_idx != MENU_ENUM_LABEL_PLAYLIST_ENTRY &&
       cbs->enum_idx != MENU_ENUM_LABEL_EXPLORE_ITEM &&
       menu_cbs_init_bind_title_compare_label(cbs, label) == 0)
      return 0;

   if (menu_cbs_init_bind_title_compare_type(cbs, type) == 0)
      return 0;

   for (i = 0; i < ARRAY_SIZE(info_list); i++)
   {
      if (string_is_equal(label, msg_hash_to_str(info_list[i].type)))
      {
         BIND_ACTION_GET_TITLE(cbs, info_list[i].cb);
         return 0;
      }
   }

   return -1;
}
