/*
Copyright (c) 2012, Broadcom Europe Ltd
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of the copyright holder nor the
      names of its contributors may be used to endorse or promote products
      derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/* ID3 genre byte translation table */
static const char* id3_genres[] =
{
   "Blues",
   "Classic Rock",
   "Country",
   "Dance",
   "Disco",
   "Funk",
   "Grunge",
   "Hip-Hop",
   "Jazz",
   "Metal",
   "New Age",
   "Oldies",
   "Other",
   "Pop",
   "R&B",
   "Rap",
   "Reggae",
   "Rock",
   "Techno",
   "Industrial",
   "Alternative",
   "Ska",
   "Death Metal",
   "Pranks",
   "Soundtrack",
   "Euro-Techno",
   "Ambient",
   "Trip-Hop",
   "Vocal",
   "Jazz+Funk",
   "Fusion",
   "Trance",
   "Classical",
   "Instrumental",
   "Acid",
   "House",
   "Game",
   "Sound Clip",
   "Gospel",
   "Noise",
   "Alternative Rock",
   "Bass",
   "Soul",
   "Punk",
   "Space",
   "Meditative",
   "Instrumental Pop",
   "Instrumental Rock",
   "Ethnic",
   "Gothic",
   "Darkwave",
   "Techno-Industrial",
   "Electronic",
   "Pop-Folk",
   "Eurodance",
   "Dream",
   "Southern Rock",
   "Comedy",
   "Cult",
   "Gangsta",
   "Top 40",
   "Christian Rap",
   "Pop/Funk",
   "Jungle",
   "Native American",
   "Cabaret",
   "New Wave",
   "Psychadelic",
   "Rave",
   "Showtunes",
   "Trailer",
   "Lo-Fi",
   "Tribal",
   "Acid Punk",
   "Acid Jazz",
   "Polka",
   "Retro",
   "Musical",
   "Rock & Roll",
   "Hard Rock",
   "Folk",
   "Folk-Rock",
   "National Folk",
   "Swing",
   "Fast Fusion",
   "Bebob",
   "Latin",
   "Revival",
   "Celtic",
   "Bluegrass",
   "Avantgarde",
   "Gothic Rock",
   "Progressive Rock",
   "Psychedelic Rock",
   "Symphonic Rock",
   "Slow Rock",
   "Big Band",
   "Chorus",
   "Easy Listening",
   "Acoustic",
   "Humour",
   "Speech",
   "Chanson",
   "Opera",
   "Chamber Music",
   "Sonata",
   "Symphony",
   "Booty Bass",
   "Primus",
   "Porn Groove",
   "Satire",
   "Slow Jam",
   "Club",
   "Tango",
   "Samba",
   "Folklore",
   "Ballad",
   "Power Ballad",
   "Rhythmic Soul",
   "Freestyle",
   "Duet",
   "Punk Rock",
   "Drum Solo",
   "A capella",
   "Euro-House",
   "Dance Hall",
   "Goa",
   "Drum & Bass",
   "Club-House",
   "Hardcore",
   "Terror",
   "Indie",
   "BritPop",
   "Negerpunk",
   "Polsk Punk",
   "Beat",
   "Christian Gangsta Rap",
   "Heavy Metal",
   "Black Metal",
   "Crossover",
   "Contemporary Christian",
   "Christian Rock",
   "Merengue",
   "Salsa",
   "Thrash Metal",
   "Anime",
   "JPop",
   "SynthPop"
};
