#!/bin/sh

cd tmp

if [ -d "nestopia" ]
then
  echo "Updating Nestopia"
  cd nestopia
  git pull origin master
else
  git clone git@github.com:libretro/nestopia.git
  cd nestopia
fi

cd libretro

echo "Building Nestopia"
make clean
make -f Makefile platform=ios
mv nestopia_libretro.dylib ../../../modules
cd ../../../
