#!/bin/sh

cd tmp

if [ -d "snes9x-next" ]
then
  echo "Updating Snes9x-next"
  cd snes9x-next
  git pull origin master
else
  git clone git@github.com:libretro/snes9x-next.git
  cd snes9x-next
fi

echo "Building Snes9x-next"
make -f Makefile.libretro clean
make -f Makefile.libretro platform=ios
mv snes9x_next_libretro.dylib ../../modules
cd ../../
