sampler2D tex : register(s0);

struct PS_IN
{
	float2 coord : TEXCOORD0;
};

struct VS_IN
{
	float2 pos : POSITION;
	float2 coord : TEXCOORD0;
};

struct VS_OUT
{
	float4 pos : POSITION;
	float2 coord : TEXCOORD0;
};

float4 main_fragment(PS_IN input) : COLOR
{
	return tex2D(tex, input.coord);
}

VS_OUT main_vertex(VS_IN input)
{
	VS_OUT output;
	output.pos = float4(input.pos, 0.0, 1.0);
	output.coord = input.coord;
	return output;
}

