TARGET = iir_filter
OBJ = ssnes_iir_filter.o

all: $(TARGET)

$(TARGET): $(OBJ)
	$(CC) -o $@ $(OBJ) -lm

%.o: %.c
	$(CC) -c -o $@ $< -g -std=c99 -O3 -march=native $(CFLAGS) -DTEST -DLOG

clean:
	rm -f $(TARGET)
	rm -f $(OBJ)

.PHONY: clean
