#!/usr/bin/env python3
"""Generate gfx/common/d3d11_deferred_proxy.c from the ID3D11DeviceContext
vtable in gfx/include/dxsdk/d3d11.h. See the generated file's header
comment for what the proxy is for. Run from the tree root."""
import re, sys

hdr = open('gfx/include/dxsdk/d3d11.h').read()
a = hdr.index('typedef struct ID3D11DeviceContextVtbl')
b = hdr.index('} ID3D11DeviceContextVtbl;', a)
vt = re.sub(r'/\*.*?\*/', '', hdr[a:b], flags=re.S)
ents = re.findall(r'(\w[\w \*]*?)\s*\(\s*STDMETHODCALLTYPE\s*\*(\w+)\s*\)\s*\((.*?)\);', vt, re.S)

def split_top(s):
    out, depth, cur = [], 0, ''
    for ch in s:
        if ch == '(': depth += 1
        elif ch == ')': depth -= 1
        if ch == ',' and depth == 0:
            out.append(cur); cur = ''
        else:
            cur += ch
    if cur.strip(): out.append(cur)
    return out

methods = []
for ret, name, args in ents:
    ret = ' '.join(ret.split())
    parts = [' '.join(p.split()) for p in split_top(args)]
    parts = [re.sub(r'\b_[A-Z][A-Za-z_]*_(\((?:[^()]|\([^()]*\))*\))?\s*', '', p).strip() for p in parts]
    assert 'This' in parts[0], (name, parts[:1])
    rest = parts[1:]
    names = []
    for p in rest:
        m = re.search(r'([A-Za-z_]\w*)\s*(\[[^\]]*\])?\s*$', p)
        names.append(m.group(1))
    methods.append((ret, name, rest, names))

special = {'QueryInterface', 'AddRef', 'Release', 'Map', 'FinishCommandList'}
out = []
out.append(r'''/*  RetroArch - A frontend for libretro.
 *  Copyright (C) 2026 - libretroadmin
 *
 *  RetroArch is free software: you can redistribute it and/or modify it under the terms
 *  of the GNU General Public License as published by the Free Software Found-
 *  ation, either version 3 of the License, or (at your option) any later version.
 *
 *  RetroArch is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 *  without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 *  PURPOSE.  See the GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along with RetroArch.
 *  If not, see <http://www.gnu.org/licenses/>.
 */

/* A proxy ID3D11DeviceContext in front of a deferred context, for the
 * threaded wrapper's hardware ring.
 *
 * A deferred context has one rule the cores were not written for: the
 * first Map of a dynamic resource in each command list must discard.
 * The cores' stream buffers discard only when they wrap and map
 * no-overwrite otherwise, so once the ring closes a command list each
 * frame, the core's next map fails and it writes through the null it
 * got back. The proxy forwards every method to the deferred context and
 * rewrites just that: the first no-overwrite map of a resource in a
 * list becomes a discard. The core keeps writing at its own cursor and
 * drawing from its own offsets, none of which reach back into the
 * previous list, so the renamed buffer holds everything the list reads.
 * FinishCommandList starts the next list's bookkeeping.
 *
 * GENERATED by tools/gen_d3d11_deferred_proxy.py from the vtable in
 * gfx/include/dxsdk/d3d11.h. Regenerate rather than edit. */

#include <stdlib.h>
#include <string.h>

#include <boolean.h>

#include "d3d11_deferred_proxy.h"

#define PROXY_MAX_MAPPED 64

typedef struct
{
   ID3D11DeviceContextVtbl *lpVtbl;
   ID3D11DeviceContextVtbl  vtbl;
   ID3D11DeviceContext     *real;
   LONG                     ref;
   /* Resources mapped at least once in the current command list. */
   ID3D11Resource          *mapped[PROXY_MAX_MAPPED];
   unsigned                 num_mapped;
} proxy_t;

#define P(This) ((proxy_t*)(This))
#define R(This) (((proxy_t*)(This))->real)

static HRESULT STDMETHODCALLTYPE proxy_QueryInterface(ID3D11DeviceContext *This, REFIID riid, void **ppv)
{
   if (!ppv)
      return E_POINTER;
   /* The base interfaces resolve to the proxy itself. Anything else -
    * the 11.1+ context interfaces - is refused: a core that used them
    * directly would bypass the map rewrite, and refusal makes it fall
    * back to what it can do through this one. */
   if (     IsEqualGUID(riid, &IID_IUnknown)
         || IsEqualGUID(riid, &IID_ID3D11DeviceChild)
         || IsEqualGUID(riid, &IID_ID3D11DeviceContext))
   {
      InterlockedIncrement(&P(This)->ref);
      *ppv = This;
      return S_OK;
   }
   *ppv = NULL;
   return E_NOINTERFACE;
}

static ULONG STDMETHODCALLTYPE proxy_AddRef(ID3D11DeviceContext *This)
{
   return (ULONG)InterlockedIncrement(&P(This)->ref);
}

static ULONG STDMETHODCALLTYPE proxy_Release(ID3D11DeviceContext *This)
{
   LONG r = InterlockedDecrement(&P(This)->ref);
   if (r == 0)
   {
      if (R(This))
         R(This)->lpVtbl->Release(R(This));
      free(P(This));
   }
   return (ULONG)r;
}

/* Whether the resource has been mapped in this command list; records
 * it if not. Past the table's capacity, a resource is treated as seen,
 * which falls back to the core's own map type. */
static bool proxy_seen(proxy_t *p, ID3D11Resource *res)
{
   unsigned i;
   for (i = 0; i < p->num_mapped; i++)
      if (p->mapped[i] == res)
         return true;
   if (p->num_mapped < PROXY_MAX_MAPPED)
   {
      p->mapped[p->num_mapped++] = res;
      return false;
   }
   return true;
}

static HRESULT STDMETHODCALLTYPE proxy_Map(ID3D11DeviceContext *This,
      ID3D11Resource *pResource, UINT Subresource, D3D11_MAP MapType,
      UINT MapFlags, D3D11_MAPPED_SUBRESOURCE *pMappedResource)
{
   proxy_t *p = P(This);
   if (MapType == D3D11_MAP_WRITE_NO_OVERWRITE && !proxy_seen(p, pResource))
      MapType = D3D11_MAP_WRITE_DISCARD;
   else if (MapType == D3D11_MAP_WRITE_DISCARD)
      proxy_seen(p, pResource);
   return R(This)->lpVtbl->Map(R(This), pResource, Subresource, MapType,
         MapFlags, pMappedResource);
}

static HRESULT STDMETHODCALLTYPE proxy_FinishCommandList(ID3D11DeviceContext *This,
      BOOL RestoreDeferredContextState, ID3D11CommandList **ppCommandList)
{
   HRESULT hr = R(This)->lpVtbl->FinishCommandList(R(This),
         RestoreDeferredContextState, ppCommandList);
   /* A new list: every resource's first map must discard again. */
   P(This)->num_mapped = 0;
   return hr;
}
''')
for ret, name, rest, names in methods:
    if name in special:
        continue
    sig = ', '.join(['ID3D11DeviceContext *This'] + rest)
    call = ', '.join(['R(This)'] + names)
    if ret == 'void':
        body = '   R(This)->lpVtbl->%s(%s);' % (name, call)
    else:
        body = '   return R(This)->lpVtbl->%s(%s);' % (name, call)
    out.append('static %s STDMETHODCALLTYPE proxy_%s(%s)\n{\n%s\n}\n' % (ret, name, sig, body))
out.append('''
ID3D11DeviceContext *d3d11_deferred_proxy_new(ID3D11DeviceContext *deferred)
{
   proxy_t *p;
   if (!deferred || !(p = (proxy_t*)calloc(1, sizeof(*p))))
      return NULL;
   p->real = deferred;
   p->ref  = 1;''')
for ret, name, rest, names in methods:
    out.append('   p->vtbl.%-28s = proxy_%s;' % (name, name))
out.append('''   p->lpVtbl = &p->vtbl;
   deferred->lpVtbl->AddRef(deferred);
   return (ID3D11DeviceContext*)p;
}

ID3D11DeviceContext *d3d11_deferred_proxy_real(ID3D11DeviceContext *proxy)
{
   return proxy ? R(proxy) : NULL;
}
''')
open('gfx/common/d3d11_deferred_proxy.c', 'w').write('\n'.join(out))
print('generated %d methods' % len(methods))
