// GLSL shader autogenerated by cg2glsl.py.
#if defined(VERTEX)
varying     vec4 VARt7;
varying     vec4 VARt6;
varying     vec4 VARt5;
varying     vec4 VARt4;
varying     vec4 VARt3;
varying     vec4 VARt2;
varying     vec4 VARt1;
varying     vec2 _texCoord1;
varying     vec4 _color1;
varying     vec4 _position1;
struct input_dummy {
    vec2 _video_size;
    vec2 _texture_size;
    vec2 _output_dummy_size;
};
struct out_vertex {
    vec4 _position1;
    vec4 _color1;
    vec2 _texCoord1;
    vec4 VARt1;
    vec4 VARt2;
    vec4 VARt3;
    vec4 VARt4;
    vec4 VARt5;
    vec4 VARt6;
    vec4 VARt7;
};
out_vertex _ret_0;
float _TMP1;
uniform mat4 MVPMatrix;
input_dummy _IN1;
vec4 _r0007;
vec4 _v0007;
attribute vec4 VertexCoord;
attribute vec4 COLOR;
attribute vec4 TexCoord;
varying vec4 COL0;
varying vec4 TEX0;
 

         mat4 transpose_(mat4 matrix)
         {
            mat4 ret;
            for (int i = 0; i < 4; i++)
               for (int j = 0; j < 4; j++)
                  ret[i][j] = matrix[j][i];

            return ret;
         }
         
uniform int FrameDirection;
uniform int FrameCount;
#ifdef GL_ES
uniform mediump vec2 OutputSize;
uniform mediump vec2 TextureSize;
uniform mediump vec2 InputSize;
#else
uniform vec2 OutputSize;
uniform vec2 TextureSize;
uniform vec2 InputSize;
#endif
void main()
{
    mat4 MVPMatrix_ = transpose_(MVPMatrix);
    out_vertex _OUT;
    vec2 _ps;
    _v0007 = vec4(float(VertexCoord.x), float(VertexCoord.y), float(VertexCoord.z), float(VertexCoord.w));
    _TMP1 = dot(vec4(float(MVPMatrix_[0].x), float(MVPMatrix_[0].y), float(MVPMatrix_[0].z), float(MVPMatrix_[0].w)), vec4(float(_v0007.x), float(_v0007.y), float(_v0007.z), float(_v0007.w)));
    _r0007.x = float(_TMP1);
    _TMP1 = dot(vec4(float(MVPMatrix_[1].x), float(MVPMatrix_[1].y), float(MVPMatrix_[1].z), float(MVPMatrix_[1].w)), vec4(float(_v0007.x), float(_v0007.y), float(_v0007.z), float(_v0007.w)));
    _r0007.y = float(_TMP1);
    _TMP1 = dot(vec4(float(MVPMatrix_[2].x), float(MVPMatrix_[2].y), float(MVPMatrix_[2].z), float(MVPMatrix_[2].w)), vec4(float(_v0007.x), float(_v0007.y), float(_v0007.z), float(_v0007.w)));
    _r0007.z = float(_TMP1);
    _TMP1 = dot(vec4(float(MVPMatrix_[3].x), float(MVPMatrix_[3].y), float(MVPMatrix_[3].z), float(MVPMatrix_[3].w)), vec4(float(_v0007.x), float(_v0007.y), float(_v0007.z), float(_v0007.w)));
    _r0007.w = float(_TMP1);
    _OUT._position1 = vec4(float(_r0007.x), float(_r0007.y), float(_r0007.z), float(_r0007.w));
    _ps = vec2(1.00000000E+00/TextureSize.x, 1.00000000E+00/TextureSize.y);
    _OUT.VARt1 = TexCoord.xxxy + vec4(float(float(-_ps.x)), 0.00000000E+00, float(float(_ps.x)), float(float((-2.00000000E+00*_ps.y))));
    _OUT.VARt2 = TexCoord.xxxy + vec4(float(float(-_ps.x)), 0.00000000E+00, float(float(_ps.x)), float(float(-_ps.y)));
    _OUT.VARt3 = TexCoord.xxxy + vec4(float(float(-_ps.x)), 0.00000000E+00, float(float(_ps.x)), 0.00000000E+00);
    _OUT.VARt4 = TexCoord.xxxy + vec4(float(float(-_ps.x)), 0.00000000E+00, float(float(_ps.x)), float(float(_ps.y)));
    _OUT.VARt5 = TexCoord.xxxy + vec4(float(float(-_ps.x)), 0.00000000E+00, float(float(_ps.x)), float(float((2.00000000E+00*_ps.y))));
    _OUT.VARt6 = TexCoord.xyyy + vec4(float(float((-2.00000000E+00*_ps.x))), float(float(-_ps.y)), 0.00000000E+00, float(float(_ps.y)));
    _OUT.VARt7 = TexCoord.xyyy + vec4(float(float((2.00000000E+00*_ps.x))), float(float(-_ps.y)), 0.00000000E+00, float(float(_ps.y)));
    _ret_0._position1 = _OUT._position1;
    _ret_0._color1 = COLOR;
    _ret_0._texCoord1 = TexCoord.xy;
    VARt1 = _OUT.VARt1;
    VARt2 = _OUT.VARt2;
    VARt3 = _OUT.VARt3;
    VARt4 = _OUT.VARt4;
    VARt5 = _OUT.VARt5;
    VARt6 = _OUT.VARt6;
    VARt7 = _OUT.VARt7;
    gl_Position = _OUT._position1;
    COL0 = COLOR;
    TEX0.xy = TexCoord.xy;
    return;
    COL0 = _ret_0._color1;
    TEX0.xy = _ret_0._texCoord1;
} 
#elif defined(FRAGMENT)
#ifdef GL_ES
precision mediump float;
#endif
varying     vec4 VARt7;
varying     vec4 VARt6;
varying     vec4 VARt5;
varying     vec4 VARt4;
varying     vec4 VARt3;
varying     vec4 VARt2;
varying     vec4 VARt1;
varying     vec2 _texCoord;
varying     vec4 _color;
struct input_dummy {
    vec2 _video_size;
    vec2 _texture_size;
    vec2 _output_dummy_size;
};
struct out_vertex {
    vec4 _color;
    vec2 _texCoord;
    vec4 VARt1;
    vec4 VARt2;
    vec4 VARt3;
    vec4 VARt4;
    vec4 VARt5;
    vec4 VARt6;
    vec4 VARt7;
};
vec4 _ret_0;
vec3 _TMP60;
vec3 _TMP71;
vec3 _TMP76;
vec3 _TMP75;
float _TMP70;
float _TMP69;
float _TMP68;
float _TMP73;
float _TMP59;
float _TMP58;
float _TMP57;
vec3 _TMP74;
vec3 _TMP56;
vec3 _TMP55;
vec3 _TMP54;
vec3 _TMP53;
vec3 _TMP52;
vec3 _TMP51;
vec3 _TMP50;
vec3 _TMP49;
vec3 _TMP48;
vec3 _TMP47;
vec4 _TMP46;
vec4 _TMP39;
vec4 _TMP38;
vec4 _TMP77;
bvec4 _TMP37;
bvec4 _TMP36;
bvec4 _TMP35;
bvec4 _TMP34;
bvec4 _TMP33;
bvec4 _TMP32;
bvec4 _TMP31;
bvec4 _TMP30;
bvec4 _TMP29;
bvec4 _TMP28;
bvec4 _TMP27;
float _TMP72;
vec4 _TMP20;
vec4 _TMP19;
vec4 _TMP18;
vec4 _TMP17;
vec4 _TMP16;
vec4 _TMP15;
vec4 _TMP14;
vec4 _TMP13;
vec4 _TMP12;
vec4 _TMP11;
vec4 _TMP10;
vec4 _TMP9;
vec4 _TMP8;
vec4 _TMP7;
vec4 _TMP6;
vec4 _TMP5;
vec4 _TMP4;
vec4 _TMP3;
vec4 _TMP2;
vec4 _TMP1;
vec4 _TMP0;
out_vertex _VAR1;
uniform sampler2D Texture;
input_dummy _IN1;
vec2 _x0091;
vec4 _r0135;
vec4 _r0145;
vec4 _r0155;
vec4 _r0165;
vec4 _r0175;
vec4 _r0185;
vec4 _TMP196;
vec4 _a0199;
vec4 _TMP202;
vec4 _a0205;
vec4 _TMP208;
vec4 _a0211;
vec4 _TMP214;
vec4 _a0217;
vec4 _TMP220;
vec4 _a0223;
vec4 _TMP226;
vec4 _a0229;
vec4 _TMP232;
vec4 _a0235;
vec4 _TMP238;
vec4 _a0241;
vec4 _TMP244;
vec4 _a0247;
vec4 _TMP250;
vec4 _a0253;
vec4 _TMP256;
vec4 _a0259;
vec4 _x0263;
vec4 _TMP264;
vec4 _x0273;
vec4 _TMP274;
vec4 _x0283;
vec4 _TMP284;
vec4 _TMP292;
vec4 _a0295;
vec4 _TMP296;
vec4 _a0299;
vec4 _TMP300;
vec4 _a0303;
vec4 _TMP304;
vec4 _a0307;
vec4 _TMP308;
vec4 _a0311;
vec4 _TMP314;
vec4 _a0317;
vec4 _TMP318;
vec4 _a0321;
vec4 _TMP322;
vec4 _a0325;
vec4 _TMP326;
vec4 _a0329;
vec4 _TMP330;
vec4 _a0333;
vec4 _TMP334;
vec4 _a0337;
vec4 _TMP338;
vec4 _a0341;
vec4 _TMP342;
vec4 _a0345;
vec4 _TMP346;
vec4 _a0349;
vec4 _TMP350;
vec4 _a0353;
vec4 _TMP354;
vec4 _a0357;
float _t0379;
float _t0389;
vec3 _df0391;
vec3 _a0393;
vec3 _df0395;
vec3 _a0397;
vec3 _TMP410;
varying vec4 TEX0;
 
uniform int FrameDirection;
uniform int FrameCount;
#ifdef GL_ES
uniform mediump vec2 OutputSize;
uniform mediump vec2 TextureSize;
uniform mediump vec2 InputSize;
#else
uniform vec2 OutputSize;
uniform vec2 TextureSize;
uniform vec2 InputSize;
#endif
void main()
{
    bvec4 _edr;
    bvec4 _edr_left;
    bvec4 _edr_up;
    bvec4 _px;
    bvec4 _interp_restriction_lv1;
    bvec4 _interp_restriction_lv2_left;
    bvec4 _interp_restriction_lv2_up;
    bvec4 _nc;
    bvec4 _nc30;
    bvec4 _nc60;
    bvec4 _nc45;
    vec4 _fx;
    vec4 _fx_left;
    vec4 _fx_up;
    vec3 _res1;
    vec3 _res2;
    vec3 _pix1;
    vec3 _pix2;
    float _blend1;
    float _blend2;
    vec2 _fp;
    vec3 _A11;
    vec3 _B11;
    vec3 _C1;
    vec3 _A2;
    vec3 _B2;
    vec3 _C;
    vec3 _D;
    vec3 _E;
    vec3 _F;
    vec3 _G;
    vec3 _H;
    vec3 _I;
    vec3 _G5;
    vec3 _H5;
    vec3 _I5;
    vec3 _A0;
    vec3 _D0;
    vec3 _G0;
    vec3 _C4;
    vec3 _F4;
    vec3 _I4;
    vec4 _b1;
    vec4 _c3;
    vec4 _e1;
    vec4 _i4;
    vec4 _i5;
    vec4 _h5;
    vec4 _fx45;
    vec4 _fx30;
    vec4 _fx60;
    vec4 _final45;
    vec4 _final30;
    vec4 _final60;
    vec4 _maximo;
    vec3 _res;
    _x0091 = TEX0.xy*TextureSize;
    _fp = fract(_x0091);
    _TMP0 = texture2D(Texture, VARt1.xw);
    _A11 = vec3(float(_TMP0.x), float(_TMP0.y), float(_TMP0.z));
    _TMP1 = texture2D(Texture, VARt1.yw);
    _B11 = vec3(float(_TMP1.x), float(_TMP1.y), float(_TMP1.z));
    _TMP2 = texture2D(Texture, VARt1.zw);
    _C1 = vec3(float(_TMP2.x), float(_TMP2.y), float(_TMP2.z));
    _TMP3 = texture2D(Texture, VARt2.xw);
    _A2 = vec3(float(_TMP3.x), float(_TMP3.y), float(_TMP3.z));
    _TMP4 = texture2D(Texture, VARt2.yw);
    _B2 = vec3(float(_TMP4.x), float(_TMP4.y), float(_TMP4.z));
    _TMP5 = texture2D(Texture, VARt2.zw);
    _C = vec3(float(_TMP5.x), float(_TMP5.y), float(_TMP5.z));
    _TMP6 = texture2D(Texture, VARt3.xw);
    _D = vec3(float(_TMP6.x), float(_TMP6.y), float(_TMP6.z));
    _TMP7 = texture2D(Texture, VARt3.yw);
    _E = vec3(float(_TMP7.x), float(_TMP7.y), float(_TMP7.z));
    _TMP8 = texture2D(Texture, VARt3.zw);
    _F = vec3(float(_TMP8.x), float(_TMP8.y), float(_TMP8.z));
    _TMP9 = texture2D(Texture, VARt4.xw);
    _G = vec3(float(_TMP9.x), float(_TMP9.y), float(_TMP9.z));
    _TMP10 = texture2D(Texture, VARt4.yw);
    _H = vec3(float(_TMP10.x), float(_TMP10.y), float(_TMP10.z));
    _TMP11 = texture2D(Texture, VARt4.zw);
    _I = vec3(float(_TMP11.x), float(_TMP11.y), float(_TMP11.z));
    _TMP12 = texture2D(Texture, VARt5.xw);
    _G5 = vec3(float(_TMP12.x), float(_TMP12.y), float(_TMP12.z));
    _TMP13 = texture2D(Texture, VARt5.yw);
    _H5 = vec3(float(_TMP13.x), float(_TMP13.y), float(_TMP13.z));
    _TMP14 = texture2D(Texture, VARt5.zw);
    _I5 = vec3(float(_TMP14.x), float(_TMP14.y), float(_TMP14.z));
    _TMP15 = texture2D(Texture, VARt6.xy);
    _A0 = vec3(float(_TMP15.x), float(_TMP15.y), float(_TMP15.z));
    _TMP16 = texture2D(Texture, VARt6.xz);
    _D0 = vec3(float(_TMP16.x), float(_TMP16.y), float(_TMP16.z));
    _TMP17 = texture2D(Texture, VARt6.xw);
    _G0 = vec3(float(_TMP17.x), float(_TMP17.y), float(_TMP17.z));
    _TMP18 = texture2D(Texture, VARt7.xy);
    _C4 = vec3(float(_TMP18.x), float(_TMP18.y), float(_TMP18.z));
    _TMP19 = texture2D(Texture, VARt7.xz);
    _F4 = vec3(float(_TMP19.x), float(_TMP19.y), float(_TMP19.z));
    _TMP20 = texture2D(Texture, VARt7.xw);
    _I4 = vec3(float(_TMP20.x), float(_TMP20.y), float(_TMP20.z));
    _TMP72 = dot(vec3(float(_B2.x), float(_B2.y), float(_B2.z)), vec3( 1.43593750E+01, 2.81718750E+01, 5.47265625E+00));
    _r0135.x = float(_TMP72);
    _TMP72 = dot(vec3(float(_D.x), float(_D.y), float(_D.z)), vec3( 1.43593750E+01, 2.81718750E+01, 5.47265625E+00));
    _r0135.y = float(_TMP72);
    _TMP72 = dot(vec3(float(_H.x), float(_H.y), float(_H.z)), vec3( 1.43593750E+01, 2.81718750E+01, 5.47265625E+00));
    _r0135.z = float(_TMP72);
    _TMP72 = dot(vec3(float(_F.x), float(_F.y), float(_F.z)), vec3( 1.43593750E+01, 2.81718750E+01, 5.47265625E+00));
    _r0135.w = float(_TMP72);
    _b1 = vec4(float(_r0135.x), float(_r0135.y), float(_r0135.z), float(_r0135.w));
    _TMP72 = dot(vec3(float(_C.x), float(_C.y), float(_C.z)), vec3( 1.43593750E+01, 2.81718750E+01, 5.47265625E+00));
    _r0145.x = float(_TMP72);
    _TMP72 = dot(vec3(float(_A2.x), float(_A2.y), float(_A2.z)), vec3( 1.43593750E+01, 2.81718750E+01, 5.47265625E+00));
    _r0145.y = float(_TMP72);
    _TMP72 = dot(vec3(float(_G.x), float(_G.y), float(_G.z)), vec3( 1.43593750E+01, 2.81718750E+01, 5.47265625E+00));
    _r0145.z = float(_TMP72);
    _TMP72 = dot(vec3(float(_I.x), float(_I.y), float(_I.z)), vec3( 1.43593750E+01, 2.81718750E+01, 5.47265625E+00));
    _r0145.w = float(_TMP72);
    _c3 = vec4(float(_r0145.x), float(_r0145.y), float(_r0145.z), float(_r0145.w));
    _TMP72 = dot(vec3(float(_E.x), float(_E.y), float(_E.z)), vec3( 1.43593750E+01, 2.81718750E+01, 5.47265625E+00));
    _r0155.x = float(_TMP72);
    _TMP72 = dot(vec3(float(_E.x), float(_E.y), float(_E.z)), vec3( 1.43593750E+01, 2.81718750E+01, 5.47265625E+00));
    _r0155.y = float(_TMP72);
    _TMP72 = dot(vec3(float(_E.x), float(_E.y), float(_E.z)), vec3( 1.43593750E+01, 2.81718750E+01, 5.47265625E+00));
    _r0155.z = float(_TMP72);
    _TMP72 = dot(vec3(float(_E.x), float(_E.y), float(_E.z)), vec3( 1.43593750E+01, 2.81718750E+01, 5.47265625E+00));
    _r0155.w = float(_TMP72);
    _e1 = vec4(float(_r0155.x), float(_r0155.y), float(_r0155.z), float(_r0155.w));
    _TMP72 = dot(vec3(float(_I4.x), float(_I4.y), float(_I4.z)), vec3( 1.43593750E+01, 2.81718750E+01, 5.47265625E+00));
    _r0165.x = float(_TMP72);
    _TMP72 = dot(vec3(float(_C1.x), float(_C1.y), float(_C1.z)), vec3( 1.43593750E+01, 2.81718750E+01, 5.47265625E+00));
    _r0165.y = float(_TMP72);
    _TMP72 = dot(vec3(float(_A0.x), float(_A0.y), float(_A0.z)), vec3( 1.43593750E+01, 2.81718750E+01, 5.47265625E+00));
    _r0165.z = float(_TMP72);
    _TMP72 = dot(vec3(float(_G5.x), float(_G5.y), float(_G5.z)), vec3( 1.43593750E+01, 2.81718750E+01, 5.47265625E+00));
    _r0165.w = float(_TMP72);
    _i4 = vec4(float(_r0165.x), float(_r0165.y), float(_r0165.z), float(_r0165.w));
    _TMP72 = dot(vec3(float(_I5.x), float(_I5.y), float(_I5.z)), vec3( 1.43593750E+01, 2.81718750E+01, 5.47265625E+00));
    _r0175.x = float(_TMP72);
    _TMP72 = dot(vec3(float(_C4.x), float(_C4.y), float(_C4.z)), vec3( 1.43593750E+01, 2.81718750E+01, 5.47265625E+00));
    _r0175.y = float(_TMP72);
    _TMP72 = dot(vec3(float(_A11.x), float(_A11.y), float(_A11.z)), vec3( 1.43593750E+01, 2.81718750E+01, 5.47265625E+00));
    _r0175.z = float(_TMP72);
    _TMP72 = dot(vec3(float(_G0.x), float(_G0.y), float(_G0.z)), vec3( 1.43593750E+01, 2.81718750E+01, 5.47265625E+00));
    _r0175.w = float(_TMP72);
    _i5 = vec4(float(_r0175.x), float(_r0175.y), float(_r0175.z), float(_r0175.w));
    _TMP72 = dot(vec3(float(_H5.x), float(_H5.y), float(_H5.z)), vec3( 1.43593750E+01, 2.81718750E+01, 5.47265625E+00));
    _r0185.x = float(_TMP72);
    _TMP72 = dot(vec3(float(_F4.x), float(_F4.y), float(_F4.z)), vec3( 1.43593750E+01, 2.81718750E+01, 5.47265625E+00));
    _r0185.y = float(_TMP72);
    _TMP72 = dot(vec3(float(_B11.x), float(_B11.y), float(_B11.z)), vec3( 1.43593750E+01, 2.81718750E+01, 5.47265625E+00));
    _r0185.z = float(_TMP72);
    _TMP72 = dot(vec3(float(_D0.x), float(_D0.y), float(_D0.z)), vec3( 1.43593750E+01, 2.81718750E+01, 5.47265625E+00));
    _r0185.w = float(_TMP72);
    _h5 = vec4(float(_r0185.x), float(_r0185.y), float(_r0185.z), float(_r0185.w));
    _fx = vec4( 1.00000000E+00, -1.00000000E+00, -1.00000000E+00, 1.00000000E+00)*_fp.y + vec4( 1.00000000E+00, 1.00000000E+00, -1.00000000E+00, -1.00000000E+00)*_fp.x;
    _fx_left = vec4( 1.00000000E+00, -1.00000000E+00, -1.00000000E+00, 1.00000000E+00)*_fp.y + vec4( 5.00000000E-01, 2.00000000E+00, -5.00000000E-01, -2.00000000E+00)*_fp.x;
    _fx_up = vec4( 1.00000000E+00, -1.00000000E+00, -1.00000000E+00, 1.00000000E+00)*_fp.y + vec4( 2.00000000E+00, 5.00000000E-01, -2.00000000E+00, -5.00000000E-01)*_fp.x;
    _a0199 = _b1.wxyz - _b1;
    _TMP196 = abs(_a0199);
    _TMP27 = bvec4(_TMP196.x < 1.50000000E+01, _TMP196.y < 1.50000000E+01, _TMP196.z < 1.50000000E+01, _TMP196.w < 1.50000000E+01);
    _a0205 = _b1.wxyz - _c3;
    _TMP202 = abs(_a0205);
    _TMP28 = bvec4(_TMP202.x < 1.50000000E+01, _TMP202.y < 1.50000000E+01, _TMP202.z < 1.50000000E+01, _TMP202.w < 1.50000000E+01);
    _a0211 = _b1.zwxy - _b1.yzwx;
    _TMP208 = abs(_a0211);
    _TMP29 = bvec4(_TMP208.x < 1.50000000E+01, _TMP208.y < 1.50000000E+01, _TMP208.z < 1.50000000E+01, _TMP208.w < 1.50000000E+01);
    _a0217 = _b1.zwxy - _c3.zwxy;
    _TMP214 = abs(_a0217);
    _TMP30 = bvec4(_TMP214.x < 1.50000000E+01, _TMP214.y < 1.50000000E+01, _TMP214.z < 1.50000000E+01, _TMP214.w < 1.50000000E+01);
    _a0223 = _e1 - _c3.wxyz;
    _TMP220 = abs(_a0223);
    _TMP31 = bvec4(_TMP220.x < 1.50000000E+01, _TMP220.y < 1.50000000E+01, _TMP220.z < 1.50000000E+01, _TMP220.w < 1.50000000E+01);
    _a0229 = _b1.wxyz - _h5.yzwx;
    _TMP226 = abs(_a0229);
    _TMP32 = bvec4(_TMP226.x < 1.50000000E+01, _TMP226.y < 1.50000000E+01, _TMP226.z < 1.50000000E+01, _TMP226.w < 1.50000000E+01);
    _a0235 = _b1.wxyz - _i4;
    _TMP232 = abs(_a0235);
    _TMP33 = bvec4(_TMP232.x < 1.50000000E+01, _TMP232.y < 1.50000000E+01, _TMP232.z < 1.50000000E+01, _TMP232.w < 1.50000000E+01);
    _a0241 = _b1.zwxy - _h5;
    _TMP238 = abs(_a0241);
    _TMP34 = bvec4(_TMP238.x < 1.50000000E+01, _TMP238.y < 1.50000000E+01, _TMP238.z < 1.50000000E+01, _TMP238.w < 1.50000000E+01);
    _a0247 = _b1.zwxy - _i5;
    _TMP244 = abs(_a0247);
    _TMP35 = bvec4(_TMP244.x < 1.50000000E+01, _TMP244.y < 1.50000000E+01, _TMP244.z < 1.50000000E+01, _TMP244.w < 1.50000000E+01);
    _a0253 = _e1 - _c3.zwxy;
    _TMP250 = abs(_a0253);
    _TMP36 = bvec4(_TMP250.x < 1.50000000E+01, _TMP250.y < 1.50000000E+01, _TMP250.z < 1.50000000E+01, _TMP250.w < 1.50000000E+01);
    _a0259 = _e1 - _c3;
    _TMP256 = abs(_a0259);
    _TMP37 = bvec4(_TMP256.x < 1.50000000E+01, _TMP256.y < 1.50000000E+01, _TMP256.z < 1.50000000E+01, _TMP256.w < 1.50000000E+01);
    _interp_restriction_lv1 = bvec4(_e1.x != _b1.w && _e1.x != _b1.z && (!_TMP27.x && !_TMP28.x || !_TMP29.x && !_TMP30.x || _TMP31.x && (!_TMP32.x && !_TMP33.x || !_TMP34.x && !_TMP35.x) || _TMP36.x || _TMP37.x), _e1.y != _b1.x && _e1.y != _b1.w && (!_TMP27.y && !_TMP28.y || !_TMP29.y && !_TMP30.y || _TMP31.y && (!_TMP32.y && !_TMP33.y || !_TMP34.y && !_TMP35.y) || _TMP36.y || _TMP37.y), _e1.z != _b1.y && _e1.z != _b1.x && (!_TMP27.z && !_TMP28.z || !_TMP29.z && !_TMP30.z || _TMP31.z && (!_TMP32.z && !_TMP33.z || !_TMP34.z && !_TMP35.z) || _TMP36.z || _TMP37.z), _e1.w != _b1.z && _e1.w != _b1.y && (!_TMP27.w && !_TMP28.w || !_TMP29.w && !_TMP30.w || _TMP31.w && (!_TMP32.w && !_TMP33.w || !_TMP34.w && !_TMP35.w) || _TMP36.w || _TMP37.w));
    _interp_restriction_lv2_left = bvec4(_e1.x != _c3.z && _b1.y != _c3.z, _e1.y != _c3.w && _b1.z != _c3.w, _e1.z != _c3.x && _b1.w != _c3.x, _e1.w != _c3.y && _b1.x != _c3.y);
    _interp_restriction_lv2_up = bvec4(_e1.x != _c3.x && _b1.x != _c3.x, _e1.y != _c3.y && _b1.y != _c3.y, _e1.z != _c3.z && _b1.z != _c3.z, _e1.w != _c3.w && _b1.w != _c3.w);
    _x0263 = (_fx - vec4( 1.10000002E+00, 9.99999940E-02, -8.99999976E-01, 9.99999940E-02))/vec4( 7.99999952E-01, 7.99999952E-01, 7.99999952E-01, 7.99999952E-01);
    _TMP77 = min(vec4( 1.00000000E+00, 1.00000000E+00, 1.00000000E+00, 1.00000000E+00), _x0263);
    _TMP264 = max(vec4( 0.00000000E+00, 0.00000000E+00, 0.00000000E+00, 0.00000000E+00), _TMP77);
    _fx45 = _TMP264*_TMP264*(3.00000000E+00 - 2.00000000E+00*_TMP264);
    _x0273 = (_fx_left - vec4( 6.00000024E-01, 6.00000024E-01, -8.99999976E-01, -4.00000006E-01))/vec4( 7.99999952E-01, 7.99999952E-01, 7.99999952E-01, 8.00000012E-01);
    _TMP77 = min(vec4( 1.00000000E+00, 1.00000000E+00, 1.00000000E+00, 1.00000000E+00), _x0273);
    _TMP274 = max(vec4( 0.00000000E+00, 0.00000000E+00, 0.00000000E+00, 0.00000000E+00), _TMP77);
    _fx30 = _TMP274*_TMP274*(3.00000000E+00 - 2.00000000E+00*_TMP274);
    _x0283 = (_fx_up - vec4( 1.60000002E+00, -4.00000006E-01, -1.39999998E+00, 9.99999940E-02))/vec4( 8.00000072E-01, 8.00000012E-01, 7.99999952E-01, 7.99999952E-01);
    _TMP77 = min(vec4( 1.00000000E+00, 1.00000000E+00, 1.00000000E+00, 1.00000000E+00), _x0283);
    _TMP284 = max(vec4( 0.00000000E+00, 0.00000000E+00, 0.00000000E+00, 0.00000000E+00), _TMP77);
    _fx60 = _TMP284*_TMP284*(3.00000000E+00 - 2.00000000E+00*_TMP284);
    _a0295 = _e1 - _c3;
    _TMP292 = abs(_a0295);
    _a0299 = _e1 - _c3.zwxy;
    _TMP296 = abs(_a0299);
    _a0303 = _c3.wxyz - _h5;
    _TMP300 = abs(_a0303);
    _a0307 = _c3.wxyz - _h5.yzwx;
    _TMP304 = abs(_a0307);
    _a0311 = _b1.zwxy - _b1.wxyz;
    _TMP308 = abs(_a0311);
    _TMP38 = _TMP292 + _TMP296 + _TMP300 + _TMP304 + 4.00000000E+00*_TMP308;
    _a0317 = _b1.zwxy - _b1.yzwx;
    _TMP314 = abs(_a0317);
    _a0321 = _b1.zwxy - _i5;
    _TMP318 = abs(_a0321);
    _a0325 = _b1.wxyz - _i4;
    _TMP322 = abs(_a0325);
    _a0329 = _b1.wxyz - _b1;
    _TMP326 = abs(_a0329);
    _a0333 = _e1 - _c3.wxyz;
    _TMP330 = abs(_a0333);
    _TMP39 = _TMP314 + _TMP318 + _TMP322 + _TMP326 + 4.00000000E+00*_TMP330;
    _edr = bvec4(_TMP38.x < _TMP39.x && _interp_restriction_lv1.x, _TMP38.y < _TMP39.y && _interp_restriction_lv1.y, _TMP38.z < _TMP39.z && _interp_restriction_lv1.z, _TMP38.w < _TMP39.w && _interp_restriction_lv1.w);
    _a0337 = _b1.wxyz - _c3.zwxy;
    _TMP334 = abs(_a0337);
    _a0341 = _b1.zwxy - _c3;
    _TMP338 = abs(_a0341);
    _edr_left = bvec4((2.00000000E+00*_TMP334).x <= _TMP338.x && _interp_restriction_lv2_left.x, (2.00000000E+00*_TMP334).y <= _TMP338.y && _interp_restriction_lv2_left.y, (2.00000000E+00*_TMP334).z <= _TMP338.z && _interp_restriction_lv2_left.z, (2.00000000E+00*_TMP334).w <= _TMP338.w && _interp_restriction_lv2_left.w);
    _a0345 = _b1.wxyz - _c3.zwxy;
    _TMP342 = abs(_a0345);
    _a0349 = _b1.zwxy - _c3;
    _TMP346 = abs(_a0349);
    _edr_up = bvec4(_TMP342.x >= (2.00000000E+00*_TMP346).x && _interp_restriction_lv2_up.x, _TMP342.y >= (2.00000000E+00*_TMP346).y && _interp_restriction_lv2_up.y, _TMP342.z >= (2.00000000E+00*_TMP346).z && _interp_restriction_lv2_up.z, _TMP342.w >= (2.00000000E+00*_TMP346).w && _interp_restriction_lv2_up.w);
    _nc45 = bvec4(_edr.x && bool(_fx45.x), _edr.y && bool(_fx45.y), _edr.z && bool(_fx45.z), _edr.w && bool(_fx45.w));
    _nc30 = bvec4(_edr.x && _edr_left.x && bool(_fx30.x), _edr.y && _edr_left.y && bool(_fx30.y), _edr.z && _edr_left.z && bool(_fx30.z), _edr.w && _edr_left.w && bool(_fx30.w));
    _nc60 = bvec4(_edr.x && _edr_up.x && bool(_fx60.x), _edr.y && _edr_up.y && bool(_fx60.y), _edr.z && _edr_up.z && bool(_fx60.z), _edr.w && _edr_up.w && bool(_fx60.w));
    _a0353 = _e1 - _b1.wxyz;
    _TMP350 = abs(_a0353);
    _a0357 = _e1 - _b1.zwxy;
    _TMP354 = abs(_a0357);
    _px = bvec4(_TMP350.x <= _TMP354.x, _TMP350.y <= _TMP354.y, _TMP350.z <= _TMP354.z, _TMP350.w <= _TMP354.w);
    _nc = bvec4(_nc30.x || _nc60.x || _nc45.x, _nc30.y || _nc60.y || _nc45.y, _nc30.z || _nc60.z || _nc45.z, _nc30.w || _nc60.w || _nc45.w);
    _final45 = vec4(float(_nc45.x), float(_nc45.y), float(_nc45.z), float(_nc45.w))*_fx45;
    _final30 = vec4(float(_nc30.x), float(_nc30.y), float(_nc30.z), float(_nc30.w))*_fx30;
    _final60 = vec4(float(_nc60.x), float(_nc60.y), float(_nc60.z), float(_nc60.w))*_fx60;
    _TMP46 = max(_final30, _final60);
    _maximo = max(_TMP46, _final45);
    if (_nc.x) { 
        if (_px.x) { 
            _TMP47 = _F;
        } else {
            _TMP47 = _H;
        } 
        _pix1 = _TMP47;
        _blend1 = _maximo.x;
    } else {
        if (_nc.y) { 
            if (_px.y) { 
                _TMP48 = _B2;
            } else {
                _TMP48 = _F;
            } 
            _pix1 = _TMP48;
            _blend1 = _maximo.y;
        } else {
            if (_nc.z) { 
                if (_px.z) { 
                    _TMP49 = _D;
                } else {
                    _TMP49 = _B2;
                } 
                _pix1 = _TMP49;
                _blend1 = _maximo.z;
            } else {
                if (_nc.w) { 
                    if (_px.w) { 
                        _TMP50 = _H;
                    } else {
                        _TMP50 = _D;
                    } 
                    _pix1 = _TMP50;
                    _blend1 = _maximo.w;
                } 
            } 
        } 
    } 
    if (_nc.w) { 
        if (_px.w) { 
            _TMP51 = _H;
        } else {
            _TMP51 = _D;
        } 
        _pix2 = _TMP51;
        _blend2 = _maximo.w;
    } else {
        if (_nc.z) { 
            if (_px.z) { 
                _TMP52 = _D;
            } else {
                _TMP52 = _B2;
            } 
            _pix2 = _TMP52;
            _blend2 = _maximo.z;
        } else {
            if (_nc.y) { 
                if (_px.y) { 
                    _TMP53 = _B2;
                } else {
                    _TMP53 = _F;
                } 
                _pix2 = _TMP53;
                _blend2 = _maximo.y;
            } else {
                if (_nc.x) { 
                    if (_px.x) { 
                        _TMP54 = _F;
                    } else {
                        _TMP54 = _H;
                    } 
                    _pix2 = _TMP54;
                    _blend2 = _maximo.x;
                } 
            } 
        } 
    } 
    _TMP73 = pow(float(_E.x), 2.40039062E+00);
    _TMP68 = float(_TMP73);
    _TMP73 = pow(float(_E.y), 2.40039062E+00);
    _TMP69 = float(_TMP73);
    _TMP73 = pow(float(_E.z), 2.40039062E+00);
    _TMP70 = float(_TMP73);
    _E = vec3(_TMP68, _TMP69, _TMP70);
    _TMP73 = pow(float(_pix1.x), 2.40039062E+00);
    _TMP68 = float(_TMP73);
    _TMP73 = pow(float(_pix1.y), 2.40039062E+00);
    _TMP69 = float(_TMP73);
    _TMP73 = pow(float(_pix1.z), 2.40039062E+00);
    _TMP70 = float(_TMP73);
    _TMP55 = vec3(_TMP68, _TMP69, _TMP70);
    _t0379 = float(_blend1);
    _res1 = _E + _t0379*(_TMP55 - _E);
    _TMP73 = pow(float(_pix2.x), 2.40039062E+00);
    _TMP68 = float(_TMP73);
    _TMP73 = pow(float(_pix2.y), 2.40039062E+00);
    _TMP69 = float(_TMP73);
    _TMP73 = pow(float(_pix2.z), 2.40039062E+00);
    _TMP70 = float(_TMP73);
    _TMP56 = vec3(_TMP68, _TMP69, _TMP70);
    _t0389 = float(_blend2);
    _res2 = _E + _t0389*(_TMP56 - _E);
    _a0393 = _E - _res1;
    _TMP74 = abs(vec3(float(_a0393.x), float(_a0393.y), float(_a0393.z)));
    _df0391 = vec3(float(_TMP74.x), float(_TMP74.y), float(_TMP74.z));
    _TMP57 = _df0391.x + _df0391.y + _df0391.z;
    _a0397 = _E - _res2;
    _TMP74 = abs(vec3(float(_a0397.x), float(_a0397.y), float(_a0397.z)));
    _df0395 = vec3(float(_TMP74.x), float(_TMP74.y), float(_TMP74.z));
    _TMP58 = _df0395.x + _df0395.y + _df0395.z;
    _TMP59 = float((_TMP58 >= _TMP57));
    _res = _res1 + _TMP59*(_res2 - _res1);
    _TMP73 = pow(float(_res.x), 4.54589844E-01);
    _TMP68 = float(_TMP73);
    _TMP73 = pow(float(_res.y), 4.54589844E-01);
    _TMP69 = float(_TMP73);
    _TMP73 = pow(float(_res.z), 4.54589844E-01);
    _TMP70 = float(_TMP73);
    _TMP60 = vec3(_TMP68, _TMP69, _TMP70);
    _TMP75 = min(vec3( 1.00000000E+00, 1.00000000E+00, 1.00000000E+00), vec3(float(_TMP60.x), float(_TMP60.y), float(_TMP60.z)));
    _TMP71 = vec3(float(_TMP75.x), float(_TMP75.y), float(_TMP75.z));
    _TMP76 = max(vec3( 0.00000000E+00, 0.00000000E+00, 0.00000000E+00), vec3(float(_TMP71.x), float(_TMP71.y), float(_TMP71.z)));
    _TMP410 = vec3(float(_TMP76.x), float(_TMP76.y), float(_TMP76.z));
    _ret_0 = vec4(float(_TMP410.x), float(_TMP410.y), float(_TMP410.z), 1.00000000E+00);
    gl_FragColor = _ret_0;
    return;
} 
#endif
