name: CI iOS (13)

on:
  push:
    branches: [master]
  pull_request:

permissions:
  contents: read

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v6

    - name: Compile RA
      run: |
        set -o pipefail
        xcodebuild -workspace pkg/apple/RetroArch.xcworkspace -destination generic/platform=iOS -config Release \
        -scheme "RetroArch iOS Release" -xcconfig pkg/apple/GitHubCI.xcconfig \
        CODE_SIGNING_ALLOWED=NO \ CODE_SIGNING_REQUIRED=NO \ CODE_SIGN_IDENTITY="" \ PROVISIONING_PROFILE_SPECIFIER="" \
        -derivedDataPath build
