name: CI Wii

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

permissions:
  contents: read

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: git.libretro.com:5050/libretro-infrastructure/libretro-build-devkitpro:latest
      options: --user root

    steps:
    - uses: taiki-e/checkout-action@v1

    - name: Compile Salamander
      run: |
        make -f Makefile.wii.salamander -j$(getconf _NPROCESSORS_ONLN) clean
        make -f Makefile.wii.salamander -j$(getconf _NPROCESSORS_ONLN) EXTERNAL_LIBOGC=1 GX_PTHREAD_LEGACY=0

    - name: Compile RA
      run: |
        make -f Makefile.wii -j$(getconf _NPROCESSORS_ONLN) clean
        make -f Makefile.wii -j$(getconf _NPROCESSORS_ONLN) EXTERNAL_LIBOGC=1 GX_PTHREAD_LEGACY=0 HAVE_STATIC_DUMMY=1
    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

