name: CI Windows x64 (MXE)

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

permissions:
  contents: read

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: git.libretro.com:5050/libretro-infrastructure/libretro-build-mxe-win64-cross:gcc10
      options: --user root

    steps:
    - uses: taiki-e/checkout-action@v1

    - name: Compile RA
      run: |
        export MOC=/usr/lib/mxe/usr/x86_64-w64-mingw32.shared/qt5/bin/moc
        ./configure --host=x86_64-w64-mingw32.shared
        make clean
        make -j$(getconf _NPROCESSORS_ONLN)

    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
