<?xml version="1.0" encoding="UTF-8"?>
<!-- XML/GLSL shader autogenerated by cg2xml.py -->
<shader language="GLSL" style="GLES2">
    <vertex><![CDATA[
varying     float _frame_rotation;
varying     float _frame_direction;
varying     float _frame_count;
varying     vec2 _output_dummy_size;
varying     vec4 _t6;
varying     vec4 _t5;
varying     vec4 _t4;
varying     vec4 _t3;
varying     vec4 _t2;
varying     vec4 _t1;
varying     vec4 _texCoord;
varying     vec4 _position1;
struct out_vertex {
    vec4 _position1;
    vec4 _texCoord;
    vec4 _t1;
    vec4 _t2;
    vec4 _t3;
    vec4 _t4;
    vec4 _t5;
    vec4 _t6;
};
struct input_dummy {
    vec2 _video_size;
    vec2 _texture_size;
    vec2 _output_dummy_size;
    float _frame_count;
    float _frame_direction;
    float _frame_rotation;
};
out_vertex _ret_0;
uniform mat4 rubyMVPMatrix;
vec4 _r0030;
attribute vec4 rubyVertexCoord;
attribute vec4 rubyTexCoord;
varying vec4 TEX0;
varying vec4 TEX1;
varying vec4 TEX2;
varying vec4 TEX3;
varying vec4 TEX4;
varying vec4 TEX5;
varying vec4 TEX6;
 

         mat4 transpose_(mat4 matrix)
         {
            mat4 ret;
            for (int i = 0; i < 4; i++)
               for (int j = 0; j < 4; j++)
                  ret[i][j] = matrix[j][i];

            return ret;
         }
         
uniform mediump vec2 rubyOutputSize;
uniform mediump vec2 rubyTextureSize;
uniform mediump vec2 rubyInputSize;
void main()
{
    mat4 rubyMVPMatrix_ = transpose_(rubyMVPMatrix);
    out_vertex _TMP28;
    _r0030.x = dot(rubyMVPMatrix_[0], rubyVertexCoord);
    _r0030.y = dot(rubyMVPMatrix_[1], rubyVertexCoord);
    _r0030.z = dot(rubyMVPMatrix_[2], rubyVertexCoord);
    _r0030.w = dot(rubyMVPMatrix_[3], rubyVertexCoord);
    _TMP28._texCoord = vec4(rubyTexCoord.x, rubyTexCoord.y, 0.00000000E+00, 0.00000000E+00);
    _TMP28._t1 = vec4(rubyTexCoord.x, rubyTexCoord.y, rubyTexCoord.x, rubyTexCoord.y) + vec4( -8.15529958E-04, -1.01451250E-03, -2.10035988E-03, -1.83949989E-04);
    _TMP28._t2 = vec4(rubyTexCoord.x, rubyTexCoord.y, rubyTexCoord.x, rubyTexCoord.y) + vec4( -1.73978484E-03, 1.14284246E-03, -5.08362486E-04, 1.55178993E-03);
    _TMP28._t3 = vec4(rubyTexCoord.x, rubyTexCoord.y, rubyTexCoord.x, rubyTexCoord.y) + vec4( 2.40584998E-03, -4.87457495E-04, 1.18358503E-03, -1.20006502E-03);
    _TMP28._t4 = vec4(rubyTexCoord.x, rubyTexCoord.y, rubyTexCoord.x, rubyTexCoord.y) + vec4( 1.29864004E-03, 1.91755500E-03, 4.63652483E-04, -2.23281002E-03);
    _TMP28._t5 = vec4(rubyTexCoord.x, rubyTexCoord.y, rubyTexCoord.x, rubyTexCoord.y) + vec4( 1.26857741E-03, 1.61062489E-04, 2.24104989E-03, 1.03114499E-03);
    _TMP28._t6 = vec4(rubyTexCoord.x, rubyTexCoord.y, rubyTexCoord.x, rubyTexCoord.y) + vec4( -8.04850017E-04, -2.33153743E-03, -1.97889749E-03, -1.49426248E-03);
    _position1 = _r0030;
    _texCoord = _TMP28._texCoord;
    _t1 = _TMP28._t1;
    _t2 = _TMP28._t2;
    _t3 = _TMP28._t3;
    _t4 = _TMP28._t4;
    _t5 = _TMP28._t5;
    _t6 = _TMP28._t6;
    gl_Position = _r0030;
    TEX0 = _TMP28._texCoord;
    TEX1 = _TMP28._t1;
    TEX2 = _TMP28._t2;
    TEX3 = _TMP28._t3;
    TEX4 = _TMP28._t4;
    TEX5 = _TMP28._t5;
    TEX6 = _TMP28._t6;
    return;
    TEX0 = _texCoord;
    TEX1 = _t1;
    TEX2 = _t2;
    TEX3 = _t3;
    TEX4 = _t4;
    TEX5 = _t5;
    TEX6 = _t6;
} 
 ]]></vertex>
    <fragment><![CDATA[
#ifdef GL_ES
precision mediump float;
#endif
varying     float _frame_rotation;
varying     float _frame_direction;
varying     float _frame_count;
varying     vec2 _output_dummy_size;
varying     vec4 _t6;
varying     vec4 _t5;
varying     vec4 _t4;
varying     vec4 _t3;
varying     vec4 _t2;
varying     vec4 _t1;
varying     vec4 _texCoord;
struct out_vertex {
    vec4 _texCoord;
    vec4 _t1;
    vec4 _t2;
    vec4 _t3;
    vec4 _t4;
    vec4 _t5;
    vec4 _t6;
};
struct input_dummy {
    vec2 _video_size;
    vec2 _texture_size;
    vec2 _output_dummy_size;
    float _frame_count;
    float _frame_direction;
    float _frame_rotation;
};
vec4 _ret_0;
vec4 _TMP11;
vec4 _TMP10;
vec4 _TMP9;
vec4 _TMP8;
vec4 _TMP7;
vec4 _TMP6;
vec4 _TMP5;
vec4 _TMP4;
vec4 _TMP3;
vec4 _TMP2;
vec4 _TMP1;
vec4 _TMP0;
uniform sampler2D rubyTexture;
varying vec4 TEX0;
varying vec4 TEX1;
varying vec4 TEX2;
varying vec4 TEX3;
varying vec4 TEX4;
varying vec4 TEX5;
varying vec4 TEX6;
 
uniform mediump vec2 rubyOutputSize;
uniform mediump vec2 rubyTextureSize;
uniform mediump vec2 rubyInputSize;
void main()
{
    vec4 _color;
    _color = texture2D(rubyTexture, TEX0.xy);
    _TMP0 = texture2D(rubyTexture, TEX1.xy);
    _color = _color + _TMP0;
    _TMP1 = texture2D(rubyTexture, TEX1.zw);
    _color = _color + _TMP1;
    _TMP2 = texture2D(rubyTexture, TEX2.xy);
    _color = _color + _TMP2;
    _TMP3 = texture2D(rubyTexture, TEX2.zw);
    _color = _color + _TMP3;
    _TMP4 = texture2D(rubyTexture, TEX3.xy);
    _color = _color + _TMP4;
    _TMP5 = texture2D(rubyTexture, TEX3.zw);
    _color = _color + _TMP5;
    _TMP6 = texture2D(rubyTexture, TEX4.xy);
    _color = _color + _TMP6;
    _TMP7 = texture2D(rubyTexture, TEX4.zw);
    _color = _color + _TMP7;
    _TMP8 = texture2D(rubyTexture, TEX5.xy);
    _color = _color + _TMP8;
    _TMP9 = texture2D(rubyTexture, TEX5.zw);
    _color = _color + _TMP9;
    _TMP10 = texture2D(rubyTexture, TEX6.xy);
    _color = _color + _TMP10;
    _TMP11 = texture2D(rubyTexture, TEX6.zw);
    _color = _color + _TMP11;
    _ret_0 = _color/1.30000000E+01;
    gl_FragColor = _ret_0;
    return;
} 
 ]]></fragment>
</shader>
