const libretroCores = {
	"2048": "2048",
	"anarch": "Anarch",
	"ardens": "Arduboy (Ardens)",
	"arduous": "Arduboy (Arduous)",
	"bk": "Elektronika - BK-0010/BK-0011 (BK)",
	"chailove": "ChaiLove",
	"craft": "Minecraft (Craft)",
	"DoubleCherryGB": "Nintendo - Game Boy / Color (DoubleCherryGB)",
	"ecwolf": "Wolfenstein 3D (ECWolf)",
	"fbalpha2012": "Arcade (FB Alpha 2012)",
	"fbalpha2012_cps1": "Arcade (FB Alpha 2012 CPS1)",
	"fbalpha2012_cps2": "Arcade (FB Alpha 2012 CPS2)",
	"fbalpha2012_neogeo": "Arcade (FB Alpha 2012 NeoGeo)",
	"fceumm": "Nintendo - NES / Famicom (FCEUmm)",
	"freechaf": "Fairchild ChannelF (FreeChaF)",
	"galaksija": "Galaksija",
	"gambatte": "Nintendo - Game Boy / Color (Gambatte)",
	"gme": "Game Music Emu",
	"gearboy": "Nintendo - Game Boy / Color (GearBoy)",
	"gearcoleco": "Coleco - ColecoVision (GearColeco)",
	"gearsystem": "Sega - MS/GG/SG-1000 (GearSystem)",
	"genesis_plus_gx": "Sega - MS/GG/MD/CD (Genesis Plus GX)",
	"genesis_plus_gx_wide": "Sega - MS/GG/MD/CD (Genesis Plus GX Wide)",
	"gong": "Gong",
	"gw": "Handheld Electronic (GW)",
	"handy": "Atari - Lynx (Handy)",
	"jaxe": "CHIP-8/S-CHIP/XO-CHIP (JAXE)",
	"jumpnbump": "Jump 'n Bump",
	"lowresnx": "LowResNX",
	"lutro": "Lua Engine (Lutro)",
	"m2000": "Philips - P2000T (M2000)",
	"mame2000": "Arcade - MAME 2000",
	"mame2003": "Arcade - MAME 2003",
	"mame2003_plus": "Arcade - MAME 2003-Plus",
	"mednafen_lynx": "Atari - Lynx (Beetle Lynx)",
	"mednafen_ngp": "SNK - Neo Geo Pocket / Color (Beetle Neo Geo Pop)",
	"mednafen_pce_fast": "NEC - PC Engine / CD (Beetle PC Engine Fast)",
	"mednafen_vb": "Nintendo - Virtual Boy (Beetle VB)",
	"mednafen_wswan": "Bandai - WonderSwan/Color (Beetle WonderSwan)",
	"mgba": "Nintendo - Game Boy Advance (mGBA)",
	"minivmac": "Mac II (MiniVmac)",
	"mu": "Palm OS(Mu)",
	"mrboom": "Bomberman (Mr.Boom)",
	"neocd": "SNK - Neo Geo CD (NeoCD)",
	"nestopia": "Nintendo - NES / Famicom (Nestopia)",
	"numero": "Texas Instruments TI-83 (Numero)",
	"nxengine": "Cave Story (NX Engine)",
	"o2em": "Magnavox - Odyssey2 / Philips Videopac+ (O2EM)",
	"opera": "The 3DO Company - 3DO (Opera)",
	"pcsx_rearmed": "Sony - PlayStation (PCSX ReARMed)",
	"picodrive": "Sega - MS/GG/MD/CD/32X (PicoDrive)",
	"pocketcdg": "PocketCDG",
	"prboom": "Doom (PrBoom)",
	"quasi88": "NEC - PC-8000 / PC-8800 series (QUASI88)",
	"quicknes": "Nintendo - NES / Famicom (QuickNES)",
	"retro8": "PICO-8 (Retro8)",
	"scummvm": "ScummVM",
	"snes9x2002": "Nintendo - SNES / SFC (Snes9x 2002)",
	"snes9x2005": "Nintendo - SNES / SFC (Snes9x 2005)",
	"snes9x2010": "Nintendo - SNES / SFC (Snes9x 2010)",
	"snes9x": "Nintendo - SNES / SFC (Snes9x)",
	"squirreljme": "Java ME (SquirrelJME)",
	"tamalibretro": "Bandai - Tamagothci P1 (TamaLIBretro)",
	"tgbdual": "Nintendo - Game Boy / Color (TGB Dual)",
	"theodore": "Theodore (Thomson TO8/TO9)",
	"tic80": "TIC-80",
	"tyrquake": "Quake (TyrQuake)",
	"uw8": "MicroW8 (UW8)",
	"uzem": "Uzebox (Uzem)",
	"vaporspec": "Vaporspec",
	"vba_next": "Nintendo - Game Boy Advance (VBA Next)",
	"vecx": "GCE - Vectrex (Vecx)",
	"vice_x64": "Commodore - C64 (VICE x64, fast)",
	"vice_x64sc": "Commodore - C64 (VICE x64sc, accurate)",
	"vice_x128": "Commodore - C128 (VICE x128)",
	"vice_xcbm2": "Commodore - CBM-II 6x0/7x0 (VICE xcbm2)",
	"vice_xcbm5x0": "Commodore - CBM-II 5x0 (xcbm5x0)",
	"vice_xpet": "Commodore - PET (VICE xpet)",
	"vice_xplus4": "Commodore - PLUS/4 (VICE xplus4)",
	"vice_xscpu64": "Commodore - C64 SuperCPU (VICE xscpu4)",
	"vice_xvic": "Commodore - VIC-20 (VICE xvic)",
	"virtualxt": "VirtualXT",
	"vitaquake2": "Quake II (vitaQuake 2)",
	"vitaquake2-rogue": "Quake II - Ground Zero (vitaQuake2 (rogue))",
	"vitaquake2-xatrix": "Quake II - The Reckoning (vitaQuake2 (xatrix))",
	"vitaquake2-zaero": "Quake II - Zaero (vitaQuake2 (zaero))",
	"wasm4": "WASM4",
	"x1": "Sharp X1 (X Millenium)",
	"xrick": "Rick Dangerous (XRick)"
};
