const libretroCores = {
	"2048": "2048",
	"DoubleCherryGB": "Nintendo - Game Boy / Color (DoubleCherryGB)",
	"anarch": "Anarch",
	"ardens": "Arduboy (Ardens)",
	"arduous": "Arduboy (Arduous)",
	"bk": "Elektronika - BK-0010/BK-0011(M)",
	"chailove": "ChaiLove",
	"clownmdemu": "Sega - MD/CD (ClownMDEmu)",
	"craft": "Minecraft (Craft)",
	"dice": "Arcade (DICE)",
	"ecwolf": "Wolfenstein 3D (ECWolf)",
	"fbalpha2012_cps1": "Arcade (FB Alpha 2012 CPS-1)",
	"fbalpha2012_cps2": "Arcade (FB Alpha 2012 CPS-2)",
	"fbalpha2012": "Arcade (FB Alpha 2012)",
	"fbalpha2012_neogeo": "Arcade (FB Alpha 2012 Neo Geo)",
	"fbneo": "Arcade (FinalBurn Neo)",
	"fceumm": "Nintendo - NES / Famicom (FCEUmm)",
	"freechaf": "Fairchild - ChannelF (FreeChaF)",
	"galaksija": "Elektronika Inženjering - Galaksija (Galaksija)",
	"gam4980": "GAM4980",
	"gambatte": "Nintendo - Game Boy / Color (Gambatte)",
	"gearboy": "Nintendo - Game Boy / Color (Gearboy)",
	"gearcoleco": "Coleco - ColecoVision (Gearcoleco)",
	"geargrafx": "NEC - PC Engine / SuperGrafx / CD (Geargrafx)",
	"gearsystem": "Sega - MS/GG/SG-1000 (Gearsystem)",
	"genesis_plus_gx": "Sega - MS/GG/MD/CD (Genesis Plus GX)",
	"genesis_plus_gx_wide": "Sega - MS/GG/MD/CD (Genesis Plus GX Wide)",
	"gme": "Game Music Emu",
	"gong": "Gong",
	"gw": "Handheld Electronic (GW)",
	"handy": "Atari - Lynx (Handy)",
	"jaxe": "CHIP-8/S-CHIP/XO-CHIP (JAXE)",
	"jumpnbump": "Jump 'n Bump",
	"lowresnx": "LowRes NX",
	"lutro": "Lua Engine (Lutro)",
	"m2000": "Philips - P2000T (M2000)",
	"mame2000": "Arcade (MAME 2000)",
	"mame2003": "Arcade (MAME 2003)",
	"mame2003_plus": "Arcade (MAME 2003-Plus)",
	"mednafen_lynx": "Atari - Lynx (Beetle Lynx)",
	"mednafen_ngp": "SNK - Neo Geo Pocket / Color (Beetle NeoPop)",
	"mednafen_pce_fast": "NEC - PC Engine / CD (Beetle PCE FAST)",
	"mednafen_vb": "Nintendo - Virtual Boy (Beetle VB)",
	"mednafen_wswan": "Bandai - WonderSwan/Color (Beetle Wonderswan)",
	"mgba": "Nintendo - Game Boy Advance (mGBA)",
	"minivmac": "Mac II (minivmac)",
	"mrboom": "Mr.Boom (Bomberman)",
	"mu": "Palm OS (Mu)",
	"neocd": "SNK - Neo Geo CD (NeoCD)",
	"nestopia": "Nintendo - NES / Famicom (Nestopia)",
	"numero": "Texas Instruments TI-83 (Numero)",
	"nxengine": "Cave Story (NXEngine)",
	"o2em": "Magnavox - Odyssey2 / Philips Videopac+ (O2EM)",
	"opera": "The 3DO Company - 3DO (Opera)",
	"pcsx_rearmed": "Sony - PlayStation (PCSX ReARMed)",
	"picodrive": "Sega - MS/GG/MD/CD/32X (PicoDrive)",
	"pocketcdg": "PocketCDG",
	"prboom": "Doom (PrBoom)",
	"quasi88": "NEC - PC-8000 / PC-8800 series (QUASI88)",
	"quicknes": "Nintendo - NES / Famicom (QuickNES)",
	"retro8": "PICO-8 (Retro8)",
	"scummvm": "ScummVM",
	"snes9x2002": "Nintendo - SNES / SFC (Snes9x 2002)",
	"snes9x2005": "Nintendo - SNES / SFC (Snes9x 2005)",
	"snes9x2010": "Nintendo - SNES / SFC (Snes9x 2010)",
	"snes9x": "Nintendo - SNES / SFC (Snes9x)",
	"tamalibretro": "Bandai - Tamagotchi P1 (TamaLIBretro)",
	"tgbdual": "Nintendo - Game Boy / Color (TGB Dual)",
	"theodore": "Thomson - MO/TO (Theodore)",
	"tic80": "TIC-80",
	"tyrquake": "Quake (TyrQuake)",
	"uw8": "MicroW8",
	"uzem": "Uzebox (Uzem)",
	"vaporspec": "VaporSpec",
	"vba_next": "Nintendo - Game Boy Advance (VBA Next)",
	"vecx": "GCE - Vectrex (vecx)",
	"vice_x128": "Commodore - C128 (VICE x128)",
	"vice_x64": "Commodore - C64 (VICE x64, fast)",
	"vice_x64sc": "Commodore - C64 (VICE x64sc, accurate)",
	"vice_xpet": "Commodore - PET (VICE xpet)",
	"vice_xplus4": "Commodore - PLUS/4 (VICE xplus4)",
	"vice_xscpu64": "Commodore - C64 SuperCPU (VICE xscpu64)",
	"vice_xvic": "Commodore - VIC-20 (VICE xvic)",
	"vitaquake2-rogue": "Quake II - Ground Zero (vitaQuake 2 [Rogue])",
	"vitaquake2-xatrix": "Quake II - The Reckoning (vitaQuake 2 [Xatrix])",
	"vitaquake2-zaero": "Quake II - Zaero (vitaQuake 2 [Zaero])",
	"vitaquake2": "Quake II (vitaQuake 2)",
	"wasm4": "WASM-4",
	"x1": "Sharp X1 (X Millennium)",
	"xrick": "Rick Dangerous (XRick)"
};
